### ISSUE TITLE
Windows Binary Packages (Updates?) and how to compile under Windows

### ISSUE THREAD

**Issue by GoogleCodeExporter** [EionRobb/skype4pidgin#241]
```
Just wondering when there will be updates to the binary packges for Windows?

Also: How do I best compile the plugin under Windows. Under Linux it is 
relatively easy but how do I do it under Windows, also regarding dependencies. 
As compiler I guess mingw should be sufficient?

Also I believe the README regarding compiling is a bit out of date in general.
```

Original issue reported on code.google.com by `andreas....@gmail.com` on 8 Jan 2015 at 9:56

**Comment by zaneperry** [comment]
Is there a way to upload the builds to github instead of zippyshare?

**Comment by EionRobb** [comment]
@zaneperry I'll organise an official release via GitHub, but for now I'll keep an installer on the main site http://eion.robbmob.com/pidgin-skypeweb-installer.exe

**Comment by zaneperry** [comment]
Sweet!  Thanks!

**Comment by EionRobb** [comment]
The readme page says how to download nowadays :)
