### ISSUE TITLE
skypeweb: avatars not automatically fetched

### ISSUE THREAD

**Issue by GoogleCodeExporter** [EionRobb/skype4pidgin#244]
```
What steps will reproduce the problem?
1. Login to skypeweb
2. No avatars of the Skype contacts are displayed

What is the expected output? What do you see instead?
Avatars of the contacts are displayed. 

Please provide any additional information below.
The avatar of a Sype contact is shown after manually clicking on menu: Get info
```

Original issue reported on code.google.com by `mbercht...@gmail.com` on 15 Jan 2015 at 8:18

**Comment by TomTheDragon** [comment]
I also got this problem, this avatar download never seems to work for me. I tried it on 2 different windows and 3 different linux machines with no success.

**Comment by EionRobb** [comment]
@TomTheDragon You can force-download the icon through right-clicking on the buddy and choosing Get Info as a workaround for now until I work out why it's not automatically downloading

**Comment by TomTheDragon** [comment]
The forced method is working on pidgin but there seems to be no luck on other libpurple based messengers (for example: spectrum) who dont have this function.

**Comment by rigid** [comment]
maybe the forced method could be used by default as a workaround?

**Comment by Yann-R** [comment]
Forcing the reload (by using Get info action) is also a possible workaround for Adium (that uses a plugin wrapping a ported version of a ported version of your SkypeWeb).

But it's worth mentioning that sI have to force this reload for some Skype contacts (and not all) each time I reconnect using SkypeWeb for Adium.
Is this the case with other clients?
Is there any idea how to solve it?

**Comment by EionRobb** [comment]
There's been some changes with how avatars are fetched in some commits over the past few days.  If this is still a problem for people, please reopen
