### ISSUE TITLE
What is the difference between the "Skype" and "Skype (D-Bus)" accounts?

### ISSUE THREAD

**Issue by IslandUsurper** [EionRobb/skype4pidgin#254]
Why should I use one or the other? As near as I can tell, they function the same, so I'm wondering why there's an option when I create an account.

**Comment by EionRobb** [comment]
One uses D-Bus, the other doesn't ;)
The D-Bus version is for non-X11 libpurple clients, such as Finch.

Ideally though, you should use the skypeweb plugin instead :)

**Comment by langpavel** [comment]
So, what is the best choice today?

**Comment by EionRobb** [comment]
@langpavel the best choice is neither X11 nor Dbus - those protocols don't work any more and only the skypeweb plugin will work
