### ISSUE TITLE
'Known as' bug in skypeweb

### ISSUE THREAD

**Issue by xvitaly** [EionRobb/skype4pidgin#256]
After starting chat with any Skype contact plugin writes in chat window and log file this:
```
(3:39:04 PM) $buddy_skype_login is now known as $yyyyyyyyyy.
(3:39:04 PM) $buddy_skype_login is now known as $yyyyyyyyyy.
(3:39:06 PM) $buddy_skype_login is now known as $yyyyyyyyyy.
(3:39:06 PM) $buddy_skype_login is now known as $yyyyyyyyyy.
```
$yyyyyyyyyy - Skype nickname. After 3-5 minutes it stops.

**Comment by xvitaly** [comment]
Occurs only while connected via Socks proxy. It disconnects and reconnects from Skype every second.

**Comment by EionRobb** [comment]
Shouldn't be happening any more.  Are you still getting this?
