### ISSUE TITLE
Blocked Contacts Appear In Pidgin

### ISSUE THREAD

**Issue by eborenst** [EionRobb/skype4pidgin#257]
I just switched from the old plugin to the March 19th Skypeweb build. I've found that people (or, specifically, one person) I have blocked in the Skype client are appearing in Pidgin's buddy list. If I remove them from Pidgin's list, they just re-appear the next time I restart Pidgin. They do not show up in the Skype client, except on the list of "Blocked Contacts" in the options window. Presumably they should not be showing up in Pidgin either.

One other data point - the person that continues to show up was only blocked recently (in the past week or so, though I don't recall exactly). Is it possible that it's just because it was a recent conversation?

**Comment by vitalyster** [comment]
I have the same problem with contacts blocked for years

**Comment by EionRobb** [comment]
I believe this has been fixed now on the server-side after they added support for blocking/unblocking clients?  Can you have another try and let me know if it's still happening?

**Comment by eborenst** [comment]
Will do.

**Comment by vitalyster** [comment]
Still seeing blocked contacts

**Comment by eborenst** [comment]
As Vitalyster said, I'm also still seeing blocked contacts

**Comment by Xylemon** [comment]
I  too see people I have removed (or blocked) on the Skype client list show up in my contact list. It's very odd.

**Comment by Xylemon** [comment]
This seems to be fixed now, at least I don't see those old nasty spam accounts I blocked or removed friends.

**Comment by vitalyster** [comment]
Does not fixed for me

**Comment by EionRobb** [comment]
Are blocked contacts still showing now?  You might have to re-block them in Pidgin if they were blocked before this code change was made.

**Comment by vitalyster** [comment]
I still seeing blocked contacts even if delete purple account and create again

**Comment by EionRobb** [comment]
Can you try unblocking and re-blocking the contact again?

**Comment by vitalyster** [comment]
I have new blocked contacts (made in microsoft clients last two days) and they all are showing here.

**Comment by EionRobb** [comment]
@vitalyster are you able to pastebin the response from the /users/self/contacts request in the debug log, which should show blocked:true for the buddies that have been marked as blocked?

**Comment by vitalyster** [comment]
I see `GET /users/[myname]/profile` request, and response contains users array with:
```
{"skypename":"femme.sexy.webcam","fullname":null,"authorized":false,"blocked":true,"display_name":null,"pstn_number":null,"phone1":null,"phone1_label":null,"phone2":null,"phone2_label":null,"phone3":null,"phone3_label":null}
```
Then I see `POST /users/self/contacts/profiles` with received users as data array , which includes these blocked contacts (`&contacts[]=femme.sexy.webcam`), so I think plugin ignores that "blocked" field

**Comment by EionRobb** [comment]
I'm just gonna close this issue since it's really old now.  If it's still happening, please reopen
