### ISSUE TITLE
skypeweb: No data in response

### ISSUE THREAD

**Issue by vitalyster** [EionRobb/skype4pidgin#258]
As I understand, skypeweb should poll "/v1/users/ME/endpoints/SELF/subscriptions/0/poll" url with some period, and it works first day or so and I see messages in client. After long period of time (about day) all poll requests instantly returns with "no data in response" (2-3 times in a second!). Restart skypeweb solves this problem. But how not to enter into this broken state?

**Comment by vitalyster** [comment]
Looks like problem gone with b69203be7308

**Comment by vitalyster** [comment]
Problem still present

**Comment by EionRobb** [comment]
Do you also use gnutls instead of libnss, @vitalyster?

**Comment by vitalyster** [comment]
No, I'm using nss

**Comment by vitalyster** [comment]
Let's watching #287
