### ISSUE TITLE
Can't build the source

### ISSUE THREAD

**Issue by meanbunny** [EionRobb/skype4pidgin#259]
When attempting to build the source using the instructions on the main page. I receive the following error.

make libpurple.so
make: *** No rule to make target 'libpurple.so'.  Stop.

EDIT
Can we update the instructions to be a little more specific? 

What I had to do in order to get this to work is the following.

1.) git clone git@github.com:EionRobb/skype4pidgin.git
2.) Copy everything inside of skype4pidgin folder to ${PIDGIN_SOURCE}/libpurple/plugins/
3.) Then re-build pidgin and re-install
4.) ./configure --disable-screensaver --disable-gtkspell --disable-gstreamer --disable-vv --disable-idn --disable-meanwhile --disable-avahi --disable-nm --disable-perl --disable-tcl
5.) make ; sudo make install ;

After this I was able to get add the Skype account to my approved list of apps that use the Skype API.

**Comment by meanbunny** [comment]
Nvm I didn't follow the instructions right. Trying again

**Comment by EionRobb** [comment]
Try compiling the new skypeweb folder instead.  It doesn't need to be built in-tree.  And you should have used `make libskype.so` instead of trying to build libpurple :)
