### ISSUE TITLE
Simultanious Logins Should Be Possible

### ISSUE THREAD

**Issue by Synthetisoft** [EionRobb/skype4pidgin#261]
In Pidgin if you try to use two Skype logins at the same time it says you can't but in reality you can run two copies of skype at the same time so shouldn't this plugin be able to take advantage of that? In Windows to run a second copy of skype you just run: "C:\Program Files (x86)\Skype\Phone\Skype.exe" /secondary

Can you make the plugin take advantage of two skype instances?

**Comment by EionRobb** [comment]
The old desktop Api didn't have a reliable way of specifying which instance
of skype to connect to. You're better off using the skypeweb plugin that
does not need skype running at all
