### ISSUE TITLE
Chats are immediately marked as read on the server - please make it more lazy.

### ISSUE THREAD

**Issue by kiilerix** [EionRobb/skype4pidgin#265]
The HTTP approach seems like a life saver - thanks!

It might not replace skype 100% but it does 99% of what Skype does and it does it so much better. I can always bite the bullet and launch Skype if I need it. Skype is usually fine with running multiple clients side by side.

One thing: Chats that are open in Pidgin will immediately be marked as read. Running multiple clients side by side do thus not really work.

Please try to change it so chats only are marked as read on the server when the tab gets focus.

**Comment by vitalyster** [comment]
+1

**Comment by EionRobb** [comment]
Want to give that one a go and let me know?

**Comment by vitalyster** [comment]
I'm using skypeweb from spectrum2 and now messages never marked as seen. What should I send from spectrum side to set "focus" on conversation?

**Comment by EionRobb** [comment]
@vitalyster if you can trigger the conversation-updated signal on the conversation to update the unread status then the plugin should pick up on it

**Comment by vitalyster** [comment]
I'm see it when libskypeweb.so loading:
` signals:Something tried to register a callback for the 'conversation-updated' signal, but we do not have any signals registered with the given handle`

**Comment by vitalyster** [comment]
Fixed with #275, but now problem is:
https://github.com/EionRobb/skype4pidgin/blob/master/skypeweb/skypeweb_messages.c#L280
`conv` always `NULL` there, and when signal is received there is no `last_skypeweb_id`
