### ISSUE TITLE
Chat doesn't have any message

### ISSUE THREAD

**Issue by SG5** [EionRobb/skype4pidgin#266]
Plugin successful send\receive message from contacts and load chat rooms
But after join chat, pidgin doesn't show any message

**Comment by EionRobb** [comment]
The plugin will try to download as much history from the room that it can, but not all rooms have history stored on the server unfortunately.

If you can get a debug log from pidgin as you connect to the room, we can try and work out whether it's possible to get the messages out of the server or not

**Comment by SG5** [comment]
There is debug log after message send - https://gist.github.com/SG5/6631d3835613f8a8061b
Other skype users don't see my message
This chat room has 17 users. I've tested plugin at another account on chat with 3 users and all work fine.

**Comment by EionRobb** [comment]
Can you update, rebuild the plugin with the latest version and try again?

**Comment by SG5** [comment]
I couldn't build plugin for windows from source. My tests was on plugin from #241. Could you provide new binary?

**Comment by EionRobb** [comment]
You can download a new windows version from http://eion.robbmob.com/libskypeweb-debug.dll

I just re-read your messages now and it's talking about P2P chats, which unfortunately don't work with the new plugin.  You can try it out though to see if you have any luck.

Otherwise, you'll need to recreate it as a new chat room, using the /fork command on the old room in a desktop Skype client

**Comment by EionRobb** [comment]
I'm just gonna close this issue since it's really old now.  If it's still happening, please reopen

**Comment by daks-ua** [comment]
Yes, the same issue here. I'm using skypeweb plugin. All new-technology chats (cloud chats) work fine, but all old chats (p2p) are broken, i.e. I can see them in 'Join chat' —> 'Room list' and can add to the roster, I can see all participants in these chats, but I don't see any messages from them. Other guys can't see mine as well.
So it works partially and I believe it is possible to get it fully working.
P.s.: Gentoo x86_64, pidgin-2.10.12, pidgin-skypeweb plugin from master (commit c1d307a4923f178c831880d56da2c9b340db3372, Feb 18, 2016)

**Comment by EionRobb** [comment]
Sorry, @daks-ua there's no P2P component to the plugin so it's unlikely that it will ever work.  The only workaround is to run the /fork command on the old P2P group chat to recreate it as a cloud-backed thread.
