### ISSUE TITLE
Plugin loses messages

### ISSUE THREAD

**Issue by Onkovat** [EionRobb/skype4pidgin#267]
I noticed that the plugin is missing messages. I heared the sound coming from skype but no message shows up on pidgin.

I suspect this happens when the writer is too fast.

Do you only check for the last message on a certain timeframe? Maybe you should check the last 10 messages and filter for duplicates then.

Skype 7.4.0.102
Pidgin 2.10.11
The plugin doesnt show up in plugin list for me for some reason so i cant tell the version.

**Comment by EionRobb** [comment]
Hmm... this could happen if we receive more than one message per second.  I'll see what I can do about it

**Comment by Onkovat** [comment]
Yes, thats exactly the impression i had. Im wondering why that didnt
came up earlier since what happens if someone is posting a longer text
that includes linebreaks? Skype will send it as several messages and the
plugin might only receive the last line.

Maybe poll so many messages until you find the last one that was logged
in skype or the message that a new conversation started.

But i dont know how you handle polling with skype at all.

Hope you can solve it since after i read the skype logs i found that the
text had a different meaning than i thought. :P

Am 09.05.2015 um 12:54 schrieb Eion Robb:

**Comment by EionRobb** [comment]
Hmm... I just sent myself several messages within a second without issue.

Are you able to get a debug log (Help->Debug Windows, from the Pidgin Buddly List) of the problem so we can confirm what's happening?

**Comment by EionRobb** [comment]
Oh, I should also check whether you're using the old Skype plugin (that needs skype running) or the newer skypeweb plugin (that works without skype, but no voice/video yet)

**Comment by Onkovat** [comment]
I could not check the plugin version since the plugin doesnt show up in
my pidgin plugin list for some reason. But i need skype running in order
to work.

How to exchange the plugins?

Am 09.05.2015 um 13:03 schrieb Eion Robb:

**Comment by EionRobb** [comment]
Have a read of https://github.com/EionRobb/skype4pidgin/blob/master/skypeweb/README.md and see how you get on

**Comment by Onkovat** [comment]
Thats the plugin dll i used till now. Ill now trying out the other
plugin. Would be interesting not having to run skype all the time.

Am 09.05.2015 um 14:05 schrieb Eion Robb:

**Comment by Onkovat** [comment]
I dont know why but with the new plugin skype accounts arent recognized.

I put libskypeweb-debug.dll into L:\Pidgin\App\Pidgin\plugins and
renamed libskype.dll to libskype.dll.old.

Then i put libjson-glib-1.0.dll into L:\Pidgin\App\Pidgin.

Im using the portable version.

My skype account shows up as "unknown" after i restarted pidgin.

Doesnt it work with portable versions or did i put one of the files in
the wrong place?

Am 09.05.2015 um 14:05 schrieb Eion Robb:

**Comment by Onkovat** [comment]
I now changed it back temporarely in order to be able to use skype on
pidgin.
If you know what the problem was with the newer version let me know...

Am 09.05.2015 um 14:05 schrieb Eion Robb:

**Comment by EionRobb** [comment]
The SkypeWeb plugin doesn't replace the account, rather, it creates a new option.  If you edit the account and choose "Skype (HTTP)" from the dropdown list, it should start using the new plugin.

**Comment by Onkovat** [comment]
I did it that way now. It didnt log in automatically so i restarted. But
now it claims "Failed getting Skype Token". I closed skype before
restarting. And it works with the old plugin and skype running.

What could be the problem? Ah, i know... http... you most probably use
those ports that block webserver ports for some reason. I disabled it
because i dont see why skype should have to block those ports without
being a webserver.

Ill try enabling them and see what happens.

Can the ports be changed?
....

Guess that wasnt the problem. Changed the option in skype and restarted
and closed skype. Still the same error in pidgin.


Am 10.05.2015 um 02:20 schrieb Eion Robb:

**Comment by EionRobb** [comment]
No, it doesn't use the port 80/443 in the Skype executable.  I would hazard a guess that you have a Live/MSN login, which doesn't yet work with the plugin.  If you can try logging in with your Skype username/password instead (if you know it) it should work for you.

**Comment by Onkovat** [comment]
Might be. I had one skype account and one msn account that i changed to
skype. First i only could use one but at some point it worked that i had
both accounts buddies in my pidgin. With the old extension.

I will go to the old extension for now. Is there a way to fix the
missing messages? Or maybe i dont have the newest version of the old
plugin? Is it still available?

Am 11.05.2015 um 07:00 schrieb Eion Robb:

**Comment by Onkovat** [comment]
I guess i told you something wrong. I had two yahoo accounts. The one
for skype is unique and has the username sebastian.jurk. I guess thats a
real skype account?

Am 11.05.2015 um 07:00 schrieb Eion Robb:

**Comment by EionRobb** [comment]
Live/MSN logins are working now

**Comment by szr8** [comment]
@EionRobb, When I try logging in with my MSN/Live account, the connect fails with "Failed getting Magic T value" shown at the bottom of the contact list. I am not sure what I might be doing incorrectly.

**Comment by EionRobb** [comment]
@szr8 please open a new issue
