### ISSUE TITLE
[Skypeweb] Duplicate sent messages 

### ISSUE THREAD

**Issue by hetdegon** [EionRobb/skype4pidgin#268]
Since commit bcd715535ce0d2a3f0dd316123ed978ac4378189 (the latest as of now), sending a message appears duplicated in the pidgin window:
![snapshot1](https://cloud.githubusercontent.com/assets/323651/7545202/1f779b5e-f5d4-11e4-9fa9-2a9a6ba26a14.png)
Although the message only gets sent once to the other person as normal, it seems to be a merely aesthetic issue.
The delay for the "echo" is mostly instantaneous, but it's possible to receive a message from the other person before the echo appears, and judging from order in the skype client, it seems to appear exactly when the other person receives the message.

System is Ubuntu 15.04 64bit, pidgin 2.10.9 and skypeweb plugin built from commit bcd715535ce0d2a3f0dd316123ed978ac4378189.

**Comment by EionRobb** [comment]
Sorry bout that.  Should be fixed in that commit if you want to give it a go?

**Comment by hetdegon** [comment]
It does work normally again. Thank you for the quick fix!
