### ISSUE TITLE
Crashes pidgin when connecting

### ISSUE THREAD

**Issue by fr500** [EionRobb/skype4pidgin#271]
https://dl.dropboxusercontent.com/u/149537/Screenshot%202015-05-27%2022.37.54.png

**Comment by TomTheDragon** [comment]
I have the same Problem on Windows 8.0 x64.
It was running fine all the time but i do get the same error for some days now.

**Comment by EionRobb** [comment]
If you can attach a backtrace of the error that would help narrow down where the crash is happening.  I'm not sure where PortablePidgin stores it, but standard Pidgin keeps them at %appdata%\.purple\Pidgin.RPT

Running it with the --debug flag would also be helpful.

**Comment by TomTheDragon** [comment]
Ok i tested it on LinuxMint 17.1 and it also crashes right after to plugin gets loaded but this time without an error. The log is also really big (~100-200kb).
However this part in the end always seems to be the same:

(04:46:14) dns: Got response for 'api.asm.skype.com'
(04:46:14) dnsquery: IP resolved for api.asm.skype.com
(04:46:14) proxy: Attempting connection to 137.116.225.139
(04:46:14) proxy: Connecting to api.asm.skype.com:443 with no proxy
(04:46:14) proxy: Connection in progress
(04:46:14) proxy: Connecting to api.asm.skype.com:443.
(04:46:14) proxy: Connected to api.asm.skype.com:443.
(04:46:14) nss: subject=CN=api.asm.skype.com issuer=CN=MSIT Machine Auth CA 2,DC=redmond,DC=corp,DC=microsoft,DC=com
(04:46:14) nss: subject=CN=MSIT Machine Auth CA 2,DC=redmond,DC=corp,DC=microsoft,DC=com issuer=CN=Microsoft Internet Authority
(04:46:14) nss: subject=CN=Microsoft Internet Authority issuer=CN=Baltimore CyberTrust Root,OU=CyberTrust,O=Baltimore,C=IE
(04:46:14) nss: partial certificate chain
(04:46:14) certificate/x509/tls_cached: Starting verify for api.asm.skype.com
(04:46:14) certificate/x509/tls_cached: Checking for cached cert...
(04:46:14) certificate/x509/tls_cached: ...Found cached cert
(04:46:14) nss/x509: Loading certificate from /home/tom/.purple/certificates/x509/tls_peers/api.asm.skype.com
(04:46:14) certificate/x509/tls_cached: Peer cert matched cached
(04:46:14) nss/x509: Exporting certificate to /home/tom/.purple/certificates/x509/tls_peers/api.asm.skype.com
(04:46:14) util: Writing file /home/tom/.purple/certificates/x509/tls_peers/api.asm.skype.com
(04:46:14) nss: Trusting CN=api.asm.skype.com
(04:46:14) certificate: Successfully verified certificate for api.asm.skype.com
(04:46:14) util: request constructed
(04:46:14) util: Response headers: 'HTTP/1.1 404 Not Found
Content-Type: text/html
Server: Microsoft-IIS/8.5
X-Powered-By: ASP.NET
Date: Mon, 01 Jun 2015 02:46:13 GMT
Connection: close
Content-Length: 1245

'
(04:46:14) util: parsed 1245
(04:46:14) imgstore: retrieved image id 1
*** Error in `pidgin': double free or corruption (!prev): 0x00007f350ae70800 ***
dns[3051]: Oops, father has gone, wait for me, wait...!
dns[3048]: Oops, father has gone, wait for me, wait...!
dns[3045]: Oops, father has gone, wait for me, wait...!
dns[3005]: Oops, father has gone, wait for me, wait...!

**Comment by EionRobb** [comment]
Looks like a crash in skypeweb_got_imagemessage() when there's no image to download from the server for an embedded image message thing.  But it should be picking up that there was an error :|

I'll keep digging

**Comment by TomTheDragon** [comment]
Hm.. ok i did find out that it still seems to work fine when i use the plugin on Spectrum, on my debian server.
But i still think that the main problem must be something else, because it did work on any OS when i use a different skype account with much smaller buddy list.
I am not sure but.. could there be any type of limit how much buddy information it can download/process at once?

**Comment by EionRobb** [comment]
Can you try with latest commit?  Fixed a couple of crashes when receiving messages/message history

**Comment by TomTheDragon** [comment]
I did try it and it seems to run fine this time on Linux Mint but it still crashes on Windows.
This time with this error massage:
Json:ERROR:json-scanner.c:895:json_scanner_get_unichar: assertion failed: (g_unichar_validate (uchar))

**Comment by EionRobb** [comment]
@TomTheDragon sorry for taking forever to reply, is it still crashing with the latest version for you?  If it is, can you get a backtrace?

**Comment by TomTheDragon** [comment]
OK i tested two accounts on two different machines (Win8.1 and Mint17.1) and everything did run fine on Mint, but i still had problems one my main account on Windows.
It crashed again with this error:
Json:ERROR:json-scanner.c:895:json_scanner_get_unichar: assertion failed: (g_unichar_validate (uchar))

**Comment by EionRobb** [comment]
Still getting crashes with the latest version?
I'll need a gdb backtrace to be able to track down the crash.
https://developer.pidgin.im/wiki/GetABacktrace

**Comment by TomTheDragon** [comment]
I still get the same error when i use my main account on the windows version of pidgin.
I also have a debug file here, i hope it helps https://dl.dropboxusercontent.com/u/5332116/bla/pidgin.RPT

**Comment by TomTheDragon** [comment]
The situation is still the same with the newest build :/
I also checked my gdb file but there was no newer entry inside, i also did try to delete the file but he did not add anything new to it.
It crashes always on different points if i look at the console, the only thing which seems to be the same every time, are this lines:

(22:09:26) skypeweb: Got response: HTTP/1.1 200 OK
Server: nginx/1.4.2
Date: Mon, 13 Jul 2015 20:09:22 GMT
Content-Type: application/json; ver=1.0; charset=utf-8
Connection: close
X-Stratus-Processing-Time: 0.2511
X-Stratus-Request-Id: abcd1234.5715cdf5
Pragma: no-cache
Cache-Control: no-store, no-cache, must-revalidate
Expires: Thu, 01 Jan 1970 00:00:01 +0000
Access-Control-Allow-Origin: https://web.skype.com
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: X-Stratus-Request-Id, X-Stratus-Processing-Time,X-Processing-Time
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Strict-Transport-Security: max-age=7776000
X-Processing-Time: 0.256
X-Stratus-Endpoint: /users/:username/contacts
X-Content-Type-Options: nosniff


**
Json:ERROR:json-scanner.c:895:json_scanner_get_unichar: assertion failed: (g_unichar_validate (uchar))

**Comment by EionRobb** [comment]
@TomTheDragon am I able to chat directly to you on Skype about it?  I'm wanting to try a few  debugging things with you and it might be quicker to IM

**Comment by TomTheDragon** [comment]
Sure why not? ;)
Just add me under this name: TomTheDragon87

**Comment by EionRobb** [comment]
So after testing with another users it appears to be a bug in the json-glib with certain unicode characters.  Can you try with an updated version of libjson-glib.dll that I built for the new Facebook plugin, from https://github.com/jgeboski/purple-facebook/releases/download/downloads/libjson-glib-1.0.dll and see if that works?

**Comment by TomTheDragon** [comment]
OK i tried the new libjson-glib.dll and it just did crash again.. but i did get it to work again after a second try :)
I just hope this will run as stable as it did some months ago.

**Comment by TomTheDragon** [comment]
The error is back again.. this time it crashes with this massage in the console:
____________________________________________________
(12:45:34) dnsquery: Performing DNS lookup for db3-client-s.gateway.messenger.live.com
(12:45:34) g_log: xmlnode_get_attrib: assertion `node != NULL' failed
(12:45:34) g_log: purple_url_parse: assertion `url != NULL' failed
____________________________________________________

And this is from the RPT file:
____________________________________________________
Error occured on Wednesday, July 29, 2015 at 12:45:34.

Windows Version 6.2 Build 9200 

D:\Pidgin\pidgin.exe caused an Access Violation at location 6862f359 in module D:\Pidgin\Gtk\bin\libglib-2.0-0.dll Reading from location ff0a0000.

Registers:
eax=00000000 ebx=00000000 ecx=ffffffff edx=04d5e100 esi=00000006 edi=ff0a0000
eip=6862f359 esp=0028d820 ebp=0028db98 iopl=0         nv up ei pl zr na po nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010246

Call stack:
         D:\Pidgin\Gtk\bin\libglib-2.0-0.dll [2.28.8.0]
6862F359 D:\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_win32_locale_filename_from_utf8
68630053 D:\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_win32_locale_filename_from_utf8
68627DD4 D:\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_vasprintf
6860749A D:\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_strdup_vprintf
686074B8 D:\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_strdup_printf
02373ED1 D:\Pidgin\plugins\libskypeweb.dll
         D:\Pidgin\libpurple.dll [2.10.11.0]
         Using Debug Symbols from: D:\Pidgin\pidgin-2.10.11-dbgsym\libpurple.dll.dbgsym
607AE99F D:\Pidgin\libpurple.dll  purple_conversation_get_im_data
         D:\Pidgin\Gtk\bin\libglib-2.0-0.dll [2.28.8.0]
686098D8 D:\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_str_equal
023764CF D:\Pidgin\plugins\libskypeweb.dll
02376C6F D:\Pidgin\plugins\libskypeweb.dll
6890C45F D:\Pidgin\libjson-glib-1.0.dll  json_parser_get_root  c:/cygwin/home/Eion/win32-dev/json-glib-0.14.2/json-glib/json-parser.c:1080
023720F5 D:\Pidgin\plugins\libskypeweb.dll
____________________________________________________

**Comment by TomTheDragon** [comment]
OK i could fix it myself, i just updated the GTK+ 2 bundle with the newest one (v2.24). The version that comes with the current version of Pidgin (v2.16) seems to be too old.

Here for everyone who is having the same problem --> http://ftp.gnome.org/pub/gnome/binaries/win32/gtk+/2.24/gtk+-bundle_2.24.10-20120208_win32.zip

**Comment by EionRobb** [comment]
I'm just gonna close this issue since it's really old now.  If it's still happening, please reopen
