### ISSUE TITLE
Skype icons

### ISSUE THREAD

**Issue by Hernou** [EionRobb/skype4pidgin#272]
I find this file with the skype icon in svg : http://www.filedropper.com/skype2013
So I do icons in 16, 22 and 48 px...
Maybe can you use it to update your skype icons :-)

![skype](https://cloud.githubusercontent.com/assets/6020558/7873118/96cd992c-059e-11e5-8240-2b6e7fd9239e.png) 
![skype](https://cloud.githubusercontent.com/assets/6020558/7873122/9cd29c28-059e-11e5-83f3-3bb8e70f601e.png) 
![skype](https://cloud.githubusercontent.com/assets/6020558/7873125/a1b3fb7e-059e-11e5-88be-02c9d2e0c66d.png)

**Comment by EionRobb** [comment]
Unfortunately that's not in the Tango icon style guidelines that Pidgin uses

**Comment by Hernou** [comment]
ha okok :-)
