### ISSUE TITLE
Skypeweb: Possiblity of Audio Calling?

### ISSUE THREAD

**Issue by Xylemon** [EionRobb/skype4pidgin#273]
While this program is still in it's early phases, and other stuff has to be done I'm sure, will there be the possibility of audio calling in the future?

**Comment by EionRobb** [comment]
There is a possibility, yes :)  Can only implement what Skype for Web implements and they've talked about an ORTP for voice/video in the future, but who knows when

**Comment by EionRobb** [comment]
Keep it going in #349
