### ISSUE TITLE
SkypeWeb: Can't compile

### ISSUE THREAD

**Issue by Xylemon** [EionRobb/skype4pidgin#279]
Using the latest git, I can no longer compile:

kypeweb_connection.c: In function 'skypeweb_post_or_get_ssl_connect_cb':
skypeweb_connection.c:390:9: warning: variable 'len' set but not used [-Wunused-but-set-variable]
  gssize len;
         ^
skypeweb_contacts.c: In function 'skypeweb_got_vm_download_info':
skypeweb_contacts.c:180:15: warning: variable 'url' set but not used [-Wunused-but-set-variable]
  const gchar *url, *assetId, *status;
               ^
skypeweb_login.c: In function 'skypeweb_login_got_pie':
skypeweb_login.c:70:2: warning: null argument where non-null required (argument 1) [-Wnonnull]
  gettimeofday(NULL, &tz);
  ^
skypeweb_messages.c: In function 'process_message_resource':
skypeweb_messages.c:107:13: warning: assignment from incompatible pointer type
    chatconv = purple_serv_got_joined_chat(sa->pc, g_str_hash(chatname), chatname);
             ^
skypeweb_messages.c:116:3: error: 'conv' undeclared (first use in this function)
   conv = PURPLE_CONVERSATION(chatconv);
   ^
skypeweb_messages.c:116:3: note: each undeclared identifier is reported only once for each function it appears in
skypeweb_messages.c:190:59: error: macro "purple_chat_user_set_flags" passed 3 arguments, but takes just 2
     purple_chat_user_set_flags(chatconv, &user[2], cbflags);
                                                           ^
skypeweb_messages.c:190:5: error: 'purple_chat_user_set_flags' undeclared (first use in this function)
     purple_chat_user_set_flags(chatconv, &user[2], cbflags);
     ^
skypeweb_messages.c:181:25: warning: variable 'cbflags' set but not used [-Wunused-but-set-variable]
     PurpleChatUserFlags cbflags = PURPLE_CHAT_USER_NONE;
                         ^
skypeweb_messages.c:215:26: warning: unused variable 'imconv' [-Wunused-variable]
    PurpleIMConversation *imconv;
                          ^
skypeweb_messages.c:262:17: warning: unused variable 'sid' [-Wunused-variable]
    const gchar *sid = purple_xmlnode_get_attrib(blob, "sid");
                 ^
skypeweb_messages.c:68:15: warning: variable 'skypeeditedid' set but not used [-Wunused-but-set-variable]
  const gchar *skypeeditedid = NULL;
               ^
skypeweb_messages.c: In function 'process_conversation_resource':
skypeweb_messages.c:317:14: warning: variable 'threadProperties' set but not used [-Wunused-but-set-variable]
  JsonObject *threadProperties;
              ^
skypeweb_messages.c:316:15: warning: unused variable 'id' [-Wunused-variable]
  const gchar *id = json_object_get_string_member(resource, "id");
               ^
skypeweb_messages.c: In function 'skypeweb_get_conversation_history_since':
skypeweb_messages.c:560:2: warning: format '%d' expects argument of type 'int', but argument 3 has type 'time_t' [-Wformat=]
  url = g_strdup_printf("/v1/users/ME/conversations/%s/messages?startTime=%d000&pageSize=30&view=msnp24Equivalent&targetType=Passport|Skype|Lync|Thread", purple_url_encode(convname), since);
  ^
skypeweb_messages.c: In function 'skypeweb_get_all_conversations_since':
skypeweb_messages.c:606:2: warning: format '%d' expects argument of type 'int', but argument 2 has type 'time_t' [-Wformat=]
  url = g_strdup_printf("/v1/users/ME/conversations?startTime=%d000&pageSize=100&view=msnp24Equivalent&targetType=Passport|Skype|Lync|Thread", since);
  ^
skypeweb_messages.c: In function 'skypeweb_chat_send':
skypeweb_messages.c:979:11: warning: assignment from incompatible pointer type
  chatconv = purple_conversations_find_chat(pc, id);
           ^
skypeweb_messages.c: In function 'skypeweb_chat_invite':
skypeweb_messages.c:1014:11: warning: assignment from incompatible pointer type
  chatconv = purple_conversations_find_chat(pc, id);
           ^
skypeweb_messages.c: In function 'skypeweb_chat_kick':
skypeweb_messages.c:1038:11: warning: assignment from incompatible pointer type
  chatconv = purple_conversations_find_chat(pc, id);
           ^
libskypeweb.c: In function 'skypeweb_join_chat':
libskypeweb.c:216:11: warning: assignment from incompatible pointer type
  chatconv = purple_serv_got_joined_chat(pc, g_str_hash(chatname), chatname);
           ^
libskypeweb.c: In function 'skypeweb_cmd_leave':
libskypeweb.c:388:2: warning: implicit declaration of function 'purple_chat_conversation_get_id' [-Wimplicit-function-declaration]
  id = purple_chat_conversation_get_id(PURPLE_CHAT_CONVERSATION(conv));
  ^
make: *** [libskypeweb.so] Error 1

**Comment by v01k** [comment]
+1 for build fail

> libskypeweb.c: In function ‘skypeweb_cmd_leave’:
> libskypeweb.c:388:2: warning: implicit declaration of function ‘purple_chat_conversation_get_id’ [-Wimplicit-function-declaration]
>   id = purple_chat_conversation_get_id(PURPLE_CHAT_CONVERSATION(conv));
>   ^
> Makefile:42: recipe for target 'libskypeweb.so' failed
> make: *** [libskypeweb.so] Error 1

Trunk from googlecode builds without errors.

**Comment by xvitaly** [comment]
Сheckout your working copy to revision 2638847239df3d670e6369fad3ffca069bae1c9e:
```
git checkout 2638847239df3d670e6369fad3ffca069bae1c9e
```

**Comment by phpony** [comment]
Thanks! This revision compiles without errors.

**Comment by EionRobb** [comment]
Latest commit should work for you too :)
