### ISSUE TITLE
(SkypeWeb) Redundant Contact Request Notifications, Related Crash

### ISSUE THREAD

**Issue by redyoshi49q** [EionRobb/skype4pidgin#284]
My version of the SkypeWeb plugin is old, but I'm not entirely sure how old (I'm not aware of the presence of any versioning information).  It's possible that this issue has already been fixed in a newer version.

While both Skype and Pidgin/the SkypeWeb plugin were running, I received a contact request from someone on Skype.  At the time, I was asleep, and I didn't see the contact request until 10 hours later.  When I did notice it, Pidgin's Buddy List window showed slightly more than 200 redundant copies of this notification.  As I was rapidly clicking the "Deny" button on these notifications, Pidgin crashed.

Below is the stacktrace.  Unfortunately, it doesn't show any of the functions related to SkypeWeb; it only shows GTK library calls (I presume the stacktrace was truncated?).  I'm running Pidgin 2.10.11 and Windows 7.

	Error occured on Saturday, June 20, 2015 at 16:59:17.

	Windows Version 6.1 Build 7601 Service Pack 1

	C:\Program Files (x86)\Pidgin\pidgin.exe caused an Access Violation at location 058aee70 Writing to location 058aee70.

	Registers:
	eax=058aee70 ebx=0d09b000 ecx=0d09b000 edx=00000000 esi=0a3f6930 edi=0d09b0f0
	eip=058aee70 esp=0028e31c ebp=0028e408 iopl=0         nv up ei pl nz na pe nc
	cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010202

	Call stack:

			 C:\Program Files (x86)\Pidgin\libpurple.dll [2.10.11.0]
			 Using Debug Symbols from: C:\Program Files (x86)\Pidgin\pidgin-2.10.11-dbgsym\libpurple.dll.dbgsym
	01DE15B0 C:\Program Files (x86)\Pidgin\libpurple.dll
			 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll [2.28.8.0]
	63A54857 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_handler_disconnect
	63A5B7DF C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit_valist
	63A5B962 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit
			 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
	02553819 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_button_clicked
	02554F70 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_button_new
			 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll [2.28.8.0]
	63A452C2 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_closure_invoke
	63A54237 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_handler_disconnect
	63A5B7DF C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit_valist
	63A5B962 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit
			 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
	02553889 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_button_released
	02553A08 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_button_new
	0260A262 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_marshal_BOOLEAN__VOID
			 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll [2.28.8.0]
	63A452C2 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_closure_invoke
	63A54512 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_handler_disconnect
	63A5B614 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit_valist
	63A5B962 C:\Program Files (x86)\Pidgin\Gtk\bin\libgobject-2.0-0.dll  g_signal_emit
			 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
	02714553 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_widget_class_list_style_properties
	02602C9A C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_propagate_event
	02603C49 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_main_do_event
			 C:\Program Files (x86)\Pidgin\Gtk\bin\libgdk-win32-2.0-0.dll [2.16.6.0]
	6C36CA7F C:\Program Files (x86)\Pidgin\Gtk\bin\libgdk-win32-2.0-0.dll  gdk_event_get_graphics_expose
			 C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll [2.28.8.0]
	685EB167 C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_main_context_dispatch
	685EB90D C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_main_context_dispatch
	685EBD9D C:\Program Files (x86)\Pidgin\Gtk\bin\libglib-2.0-0.dll  g_main_loop_run
			 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll [2.16.6.0]
	02604260 C:\Program Files (x86)\Pidgin\Gtk\bin\libgtk-win32-2.0-0.dll  gtk_main

**Comment by EionRobb** [comment]
That's a bit of a strange crash log.

Fortunately the duplicate contact request bug has been fixed already :)

**Comment by EionRobb** [comment]
Still getting problems with the latest dlls?

**Comment by redyoshi49q** [comment]
Slow yoshi is slow.  I just now restarted Pidgin after having replaced the old version of the SkypeWeb plugin .dll with the new one (backing up the old one, just in case).  I'll let you know if the problem happens again, though I wouldn't expect it to if there's a live fix for the duplicate contact request bug.

Thanks for the quick response.

**Comment by EionRobb** [comment]
Alrighty, I'll close this issue now, but if the same crash is happening feel free to reopen it :)
and of course, if you get some new crashes please open a new issue for them too :)
