### ISSUE TITLE
Skypweb:   Images don't apear.

### ISSUE THREAD

**Issue by Thaodan** [EionRobb/skype4pidgin#285]
I  got the problem that images that I should get won't appear in my chat, even don't as url as skype linux.

I'm using telepathy-haze with kde telepathy.

**Comment by EionRobb** [comment]
Yeah, this is because of
https://github.com/EionRobb/skype4pidgin/commit/dbcb241de04b0ef8565b1b9cd8153ad52fd2fd12
Where I disabled the downloading of images because it was causing crashes.

Patches welcome :)

**Comment by Thaodan** [comment]
what about  just disaplaying the url to raw url?  so that clients like ktp can display them?

**Comment by EionRobb** [comment]
The url given from the server needs to have login details from the plugin to be able to view and can't be clicked on

**Comment by Thaodan** [comment]
hm sad to hear, that there's no workaround.

**Comment by Thaodan** [comment]
Maybe just display a link like Desktop Skype so that you don't miss images:
Sie haben ein neues Bild empfangen. Ansehen auf: https://api.asm.skype.com/s/i?0-neu-d4-1e623fdf618ef********************

**Comment by EionRobb** [comment]
I've added them back in again as of a commit or two ago.  Can you give it a try?

**Comment by Thaodan** [comment]
I'll do,do this work with telepathy?

**Comment by EionRobb** [comment]
I don't know if telepathy displays inline images, sorry.  Please let me know if it does :)

**Comment by Thaodan** [comment]
don't works, maybe ad a workaround and ad the url like the skype server does for skype for linux?
Ping me of you want logs.

**Comment by utack** [comment]
Currently a "embedded" image received or sent (from Android) makes pidgin crash when it tries to display the message.
Is this expected/known or just on my machine?

**Comment by EionRobb** [comment]
@utack can you open a new issue and attach a backtrace of the crash?

**Comment by EionRobb** [comment]
I'm just gonna close this issue since it's really old now.  If it's still happening, please reopen
