### ISSUE TITLE
crashing after being added to group chat

### ISSUE THREAD

**Issue by dejl** [EionRobb/skype4pidgin#288]
after being added to a group chat:

** (process:19667): CRITICAL **: file signals.c: line 267 (signal_connect_common): should not be reached

** (process:19667): CRITICAL **: purple_conversation_get_chat_data: assertion 'conv != NULL' failed

(process:19667): Json-CRITICAL **: json_object_get_string_member: assertion 'node != NULL' failed

** (process:19667): CRITICAL **: purple_conversation_get_chat_data: assertion 'conv != NULL' failed

(process:19667): Json-CRITICAL **: json_object_get_string_member: assertion 'node != NULL' failed

(process:19667): GLib-CRITICAL **: g_source_remove: assertion 'tag > 0' failed

**Comment by EionRobb** [comment]
You don't happen to have a corresponding debug log or crash backtrace (or
both)?

**Comment by dejl** [comment]
sorry, forgot to post that.

http://sprunge.us/MTjh

**Comment by dejl** [comment]
It seems to stop crashing after a while

**Comment by EionRobb** [comment]
I can't quite see where that's going wrong.

Do you have a full backtrace (with line numbers)?  Probably a debug log (from libpurple's --debug output) would be ideal

**Comment by EionRobb** [comment]
Sorry, can't do much at the moment without that backtrace :(
If you manage to get it to crash again a GDB backtrace with a corresponding --debug log would help track down what's going on.  Please re-open and attach once you get them.
