### ISSUE TITLE
Can't login ssl hand shake failed

### ISSUE THREAD

**Issue by Thaodan** [EionRobb/skype4pidgin#289]
I try to login but it didn't succeed cause of this error:
´´´
06.07.2015 21:46:49.573019 - [purple/skypeweb] sending headers:
GET /logout HTTP/1.0
Host: login.skype.com
Connection: close
Accept: */*
Cookie: 
Accept-Encoding: gzip
Accept-Language: de-DE.UTF-8, de-DE, de.UTF-8, de, C
06.07.2015 21:46:49.573054 - [purple/dnsquery] Performing DNS lookup for login.skype.com
06.07.2015 21:46:49.573065 - [purple/skypeweb] destroying 0 waiting connections
06.07.2015 21:46:49.573067 - [purple/skypeweb] destroying 1 incomplete connections
06.07.2015 21:46:49.573088 - [purple/connection] Destroying connection 0x234e280
06.07.2015 21:46:49.572904 - [GLib] g_source_remove: assertion 'tag > 0' failed
06.07.2015 21:46:49.572917 - [GLib] g_source_remove: assertion 'tag > 0' failed
06.07.2015 21:46:49.572923 - [GLib] g_source_remove: assertion 'tag > 0' failed
06.07.2015 21:46:49.573122 - [haze/haze] haze_connection_dispose: disposing of (HazeConnection *)0x2333150
06.07.2015 21:46:49.573127 - [haze/haze] close_all: closing im channels
06.07.2015 21:46:49.573184 - [haze/haze] haze_connection_finalize: deleting account Thaodann
06.07.2015 21:46:49.573209 - [purple/account] Destroying account 0x23325f0
06.07.2015 21:46:49.574996 - [haze/haze] haze_protocol_translate_parameters: setting parameter account (telepathy name account)
06.07.2015 21:46:49.575000 - [haze/haze] haze_protocol_translate_parameters: setting parameter  (telepathy name )
06.07.2015 21:46:49.575011 - [haze/haze] haze_connection_init: Initializing (HazeConnection *)0x2333450
06.07.2015 21:46:49.575078 - [haze/haze] haze_connection_constructor: Post-construction: (HazeConnection *)0x2333450
06.07.2015 21:46:49.748589 - [purple/account] Connecting to account Thaodann.
06.07.2015 21:46:49.748600 - [purple/connection] Connecting. gc = 0x23f80e0
06.07.2015 21:46:49.748606 - [purple/util] requesting to fetch a URL
06.07.2015 21:46:49.748657 - [purple/dnsquery] Performing DNS lookup for login.skype.com
06.07.2015 21:46:49.748672 - [purple/account] Connecting to account Thaodann.
06.07.2015 21:46:49.748785 - [purple/dns] Wait for DNS child 15590 failed: No child processes
06.07.2015 21:46:49.748805 - [purple/dns] Wait for DNS child 15589 failed: No child processes
06.07.2015 21:46:49.750874 - [purple/dns] Created new DNS child 24282, there are now 1 children.
06.07.2015 21:46:49.750982 - [purple/dns] Successfully sent DNS request to child 24282
06.07.2015 21:46:49.781524 - [purple/dns] Got response for 'login.skype.com'
06.07.2015 21:46:49.781534 - [purple/dnsquery] IP resolved for login.skype.com
06.07.2015 21:46:49.781539 - [purple/proxy] Attempting connection to 91.190.216.77
06.07.2015 21:46:49.781548 - [purple/proxy] Connecting to login.skype.com:443 with no proxy
06.07.2015 21:46:49.781593 - [purple/proxy] Connection in progress
06.07.2015 21:46:49.821652 - [purple/proxy] Connecting to login.skype.com:443.
06.07.2015 21:46:49.821660 - [purple/proxy] Connected to login.skype.com:443.
06.07.2015 21:46:54.578155 - [purple/util] Writing file accounts.xml to directory /tmp/haze-T9a9ad
06.07.2015 21:46:54.578169 - [purple/util] Writing file /tmp/haze-T9a9ad/accounts.xml
06.07.2015 21:52:30.192334 - [purple/nss] Handshake failed  (-5938)
06.07.2015 21:52:30.192413 - [purple/connection] Connection error on 0x23f80e0 (reason: 0 description: Unable to connect to login.skype.com: SSL Handshake Failed)
06.07.2015 21:52:30.192480 - [haze/haze] close_all: closing im channels
06.07.2015 21:52:30.193517 - [purple/account] Disconnecting account Thaodann (0x2521380)
06.07.2015 21:52:30.193557 - [purple/connection] Disconnecting connection 0x23f80e0
06.07.2015 21:52:30.193653 - [purple/skypeweb] getting url /logout
```

I'm using telepathy-haze with ktp on Arch Linux.

**Comment by EionRobb** [comment]
Can you open https://login.skype.com/ in your browser?
There's normally a bit more info than that, but it sounds like your NSS is configured to use SSL/TLS versions that the server doesn't support.
In Pidgin there's an NSS config plugin that lets you configure what versions of SSL/TLS to enable in NSS.  I'm not sure how you'd do that in telepathy.

**Comment by vitalyster** [comment]
In last two days I'm constantly receive  `nss:Handshake failed  (-12193)`, which is `SSL_ERROR_DECODE_ERROR_ALERT` NSS error. What may be a problem?

**Comment by Thaodan** [comment]
@EionRobb  yes I can open ir, its defenetly a problem caused by the latest nss update here on arch 3.19.2

**Comment by vitalyster** [comment]
My NSS error -12193 fixed with upgrading NSS/NSPR to 3.19.2/4.10.8. As skypeweb checks now libpurple version, it maybe should check NSS/NSPR version too.
