### ISSUE TITLE
Ubuntu 15.04, failing at Make command

### ISSUE THREAD

**Issue by leannecrow** [EionRobb/skype4pidgin#291]
Hey, I'm trying to configure Pidgin with it but it's failing to do. I can't find glib.20 package in the Synaptic Manager. 

~/skype4pidgin/skypeweb$ make
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glib-2.0' found
Package json-glib-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `json-glib-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'json-glib-1.0' found
Package purple was not found in the pkg-config search path.
Perhaps you should add the directory containing `purple.pc'
to the PKG_CONFIG_PATH environment variable
No package 'purple' found
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glib-2.0' found
Package json-glib-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `json-glib-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'json-glib-1.0' found
Package purple was not found in the pkg-config search path.
Perhaps you should add the directory containing `purple.pc'
to the PKG_CONFIG_PATH environment variable
No package 'purple' found
gcc -Wall -I. -g -O2 -fPIC -pipe skypeweb_connection.c skypeweb_contacts.c skypeweb_login.c skypeweb_messages.c skypeweb_util.c libskypeweb.c  -o libskypeweb.so   -shared
In file included from skypeweb_connection.h:22:0,
                 from skypeweb_connection.c:19:
libskypeweb.h:25:18: fatal error: glib.h: No such file or directory
 #include <glib.h>
                  ^
compilation terminated.
In file included from skypeweb_contacts.h:22:0,
                 from skypeweb_contacts.c:20:
libskypeweb.h:25:18: fatal error: glib.h: No such file or directory
 #include <glib.h>
                  ^
compilation terminated.
In file included from skypeweb_login.h:22:0,
                 from skypeweb_login.c:19:
libskypeweb.h:25:18: fatal error: glib.h: No such file or directory
 #include <glib.h>
                  ^
compilation terminated.
In file included from skypeweb_messages.h:22:0,
                 from skypeweb_messages.c:19:
libskypeweb.h:25:18: fatal error: glib.h: No such file or directory
 #include <glib.h>
                  ^
compilation terminated.
In file included from skypeweb_util.h:19:0,
                 from skypeweb_util.c:19:
libskypeweb.h:25:18: fatal error: glib.h: No such file or directory
 #include <glib.h>
                  ^
compilation terminated.
In file included from libskypeweb.c:19:0:
libskypeweb.h:25:18: fatal error: glib.h: No such file or directory
 #include <glib.h>
                  ^
compilation terminated.
Makefile:42: recipe for target 'libskypeweb.so' failed
make: *** [libskypeweb.so] Error 1

**Comment by krokodilerian** [comment]
@leannecrow , you seem to need the libglib2.0-dev, libjson-glib-dev and libpurple-dev packagess.

**Comment by leannecrow** [comment]
Ok, I installed those and it probably installed. But when I go to add accounts, I don't see Skype.

**Comment by krokodilerian** [comment]
Did you do
make install
afterwards ? Then after you restart pidgin, you should see it.

**Comment by leannecrow** [comment]
Had to restart, fixed.
