### ISSUE TITLE
Custom font in Pidgin not working right

### ISSUE THREAD

**Issue by Silent-Hunter** [EionRobb/skype4pidgin#292]
When I have the default font for chats in Pidgin set to Monospace, my friends see this:

<font face="Monospace">Sample text.</font>

Skype doesn't support custom fonts, shouldn't the plugin not send them?

**Comment by EionRobb** [comment]
It seems to depend on which Skype client you're seeing it on as to whether it works or not :)

What client are you having problems sending messages to?

**Comment by Silent-Hunter** [comment]
It's the web.skype.com one. A friend said he could see those tags around it. And then I looked in web.skype.com and I could see it too.

-----Original Message-----

**Comment by EionRobb** [comment]
The web client isn't correctly formatting html at the moment. It should be
showing fine on other clients though

**Comment by Silent-Hunter** [comment]
But do other clients even accept formatted text? Why send the formatting at all?

-----Original Message-----

**Comment by EionRobb** [comment]
Yes they do accept formatting
