### ISSUE TITLE
Today I can't suddenly log in

### ISSUE THREAD

**Issue by freed00m** [EionRobb/skype4pidgin#293]
"SkypeWeb Plugin for Pidgin"
Failed getting Registration Token

I am able to use web.skype and linux client skype

The plugin was working, but stopped, no setting has been changed in Pidgin 2.10.9 (libpurple 2.10.9).

---

Processor : 4x AMD A8-4500M APU integrated GPU
Operating System : Linux Mint 17.1 Rebecca (MATE)
OpenGL : AMD Radeon HD 7640G
X11 Vendor : The X.Org Foundation v1.15.1
Kernel : Linux 3.13.0.57 (x86_64)

**Comment by hetdegon** [comment]
Happens to me as well, even after updating to f1331dbdac0dd65ef3c747031199823e669f364a .
OS: Ubuntu 15.04 64 bit.
Pidgin: 2.10.9
Skypeweb: Git f1331dbdac0dd65ef3c747031199823e669f364a self-built.

**Comment by SebiPanther** [comment]
I have the same Problem. After the Problem appeared i've update to the newest version of the Plugin. But i doesn't solve the problem  - this is the output from "pidgin --debug":
>>
(11:11:37) account: Connecting to account SebiPanther.
(11:11:37) connection: Connecting. gc = 0x7f2ddec125d0
(11:11:37) util: requesting to fetch a URL
(11:11:37) dnsquery: Performing DNS lookup for login.skype.com
(11:11:38) dns: Created new DNS child 9642, there are now 1 children.
(11:11:38) dns: Successfully sent DNS request to child 9642
(11:11:38) dns: Got response for 'login.skype.com'
(11:11:38) dnsquery: IP resolved for login.skype.com
(11:11:38) proxy: Attempting connection to 91.190.216.77
(11:11:38) proxy: Connecting to login.skype.com:443 with no proxy
(11:11:38) proxy: Connection in progress
(11:11:38) proxy: Connecting to login.skype.com:443.
(11:11:38) proxy: Connected to login.skype.com:443.
(11:11:38) nss: subject=CN=login.skype.com,O=Skype,L=Dublin,C=IE issuer=CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US
(11:11:38) nss: subject=CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US issuer=CN=Baltimore CyberTrust Root,OU=CyberTrust,O=Baltimore,C=IE
(11:11:38) nss: partial certificate chain
(11:11:38) certificate/x509/tls_cached: Starting verify for login.skype.com
(11:11:38) certificate/x509/tls_cached: Checking for cached cert...
(11:11:38) certificate/x509/tls_cached: ...Found cached cert
(11:11:38) nss/x509: Loading certificate from /home/sebi/.purple/certificates/x509/tls_peers/login.skype.com
(11:11:38) certificate/x509/tls_cached: Peer cert matched cached
(11:11:38) nss/x509: Exporting certificate to /home/sebi/.purple/certificates/x509/tls_peers/login.skype.com
(11:11:38) util: Writing file /home/sebi/.purple/certificates/x509/tls_peers/login.skype.com
(11:11:38) nss: Trusting CN=login.skype.com,O=Skype,L=Dublin,C=IE
(11:11:38) certificate: Successfully verified certificate for login.skype.com
(11:11:38) util: request constructed
(11:11:38) util: Response headers: 'HTTP/1.1 200 OK
Server: nginx
Date: Sun, 12 Jul 2015 09:11:38 GMT
Content-Type: text/html; ver=1.0; charset=utf-8;
Connection: close
Set-Cookie: SC=CC=:CCY=:LC=en:LIM=:TM=1436692298:TS=1436692298:TZ=:VAT=:VER=; expires=Mon, 11-Jul-2016 09:11:38 GMT; Max-Age=31536000; path=/; domain=.skype.com
Set-Cookie: frmrgtpe=1-1; path=/; domain=.skype.com
X-Stratus-Processing-Time: 0.0291
X-Skype-Request-Id: afaaea4a
X-Stratus-Request-Id: afaaea4a
Pragma: no-cache
Cache-Control: no-store, no-cache, must-revalidate
Expires: Thu, 01 Jan 1970 00:00:01 +0000
P3P: CP="CAO PSA OUR"
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
X-Processing-Time: 0.031
Strict-Transport-Security: max-age=31536000; includeSubDomains

'
(11:11:38) util: requesting to fetch a URL
(11:11:38) dnsquery: Performing DNS lookup for login.skype.com
(11:11:38) dns: Successfully sent DNS request to child 9642
(11:11:38) dns: Got response for 'login.skype.com'
(11:11:38) dnsquery: IP resolved for login.skype.com
(11:11:38) proxy: Attempting connection to 91.190.216.77
(11:11:38) proxy: Connecting to login.skype.com:443 with no proxy
(11:11:38) proxy: Connection in progress
(11:11:38) proxy: Connecting to login.skype.com:443.
(11:11:38) proxy: Connected to login.skype.com:443.
(11:11:38) nss: subject=CN=login.skype.com,O=Skype,L=Dublin,C=IE issuer=CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US
(11:11:38) nss: partial certificate chain
(11:11:38) certificate/x509/tls_cached: Starting verify for login.skype.com
(11:11:38) certificate/x509/tls_cached: Checking for cached cert...
(11:11:38) certificate/x509/tls_cached: ...Found cached cert
(11:11:38) nss/x509: Loading certificate from /home/sebi/.purple/certificates/x509/tls_peers/login.skype.com
(11:11:38) certificate/x509/tls_cached: Peer cert matched cached
(11:11:38) nss/x509: Exporting certificate to /home/sebi/.purple/certificates/x509/tls_peers/login.skype.com
(11:11:38) util: Writing file /home/sebi/.purple/certificates/x509/tls_peers/login.skype.com
(11:11:38) nss: Trusting CN=login.skype.com,O=Skype,L=Dublin,C=IE
(11:11:38) certificate: Successfully verified certificate for login.skype.com
(11:11:38) util: request constructed
(11:11:38) util: Response headers: 'HTTP/1.1 200 OK
Server: nginx
Date: Sun, 12 Jul 2015 09:11:38 GMT
Content-Type: text/html; ver=1.0; charset=utf-8;
Content-Length: 4133
Connection: keep-alive
Set-Cookie: SC=CC=:CCY=:LC=en:LIM=:TM=1436692298:TS=1436692298:TZ=:VAT=:VER=; expires=Mon, 11-Jul-2016 09:11:38 GMT; Max-Age=31536000; path=/; domain=.skype.com
Set-Cookie: login-bt=578134; expires=Mon, 13-Jul-2015 09:12:38 GMT; Max-Age=86460; path=/; secure; httponly
Set-Cookie: refresh-token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJpYXQiOjE0MzY2OTIyOTgsImV4cCI6MTQzNjc3ODY5OCwic2t5cGVpZCI6InNlYmlwYW50aGVyIiwic2NwIjoxLCJjc2kiOiIyIn0.PTAekoRSdaH7RYKNY4zIDwEBvtpZ8ZCQ3Z7TLOKHSfxkkdDngtl0SBlIXBd9dlHkvmkpj0mL1oNgHMqbtKLsTs4v9zCFMO8kujqCeOmsvxHBkE5DD0zokymlDXQtvRXJTLYFSkGjTIHd_w-D5j4cQz2efp2NtAYIIEObK11nyEETQGGnirwiC5TRYwd54iR1E4oI0BdwZUwvfRNR; path=/; secure; httponly
Set-Cookie: skplet=1436778698; path=/; domain=.skype.com
Set-Cookie: login-ibb=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; domain=.skype.com; secure
Set-Cookie: lastLogin=SK; expires=Tue, 11-Aug-2015 09:11:38 GMT; Max-Age=2592000; path=/
Set-Cookie: skype-session=f05908d18162043014cf0233d7cbbce7de732782; path=/; domain=.skype.com; secure; httponly
Set-Cookie: skype-session-token=12d1a96e0ede27b057347db04154fc08835b1794; path=/; domain=.skype.com
X-Stratus-Processing-Time: 0.1254
X-Skype-Request-Id: 46aa0ac3
X-Stratus-Request-Id: 46aa0ac3
Pragma: no-cache
Cache-Control: no-store, no-cache, must-revalidate
Expires: Thu, 01 Jan 1970 00:00:01 +0000
P3P: CP="CAO PSA OUR"
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
X-Processing-Time: 0.134
Strict-Transport-Security: max-age=31536000; includeSubDomains

'
(11:11:38) util: parsed 4133
(11:11:38) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file /usr/share/pixmaps/pidgin/protocols/16/skype.png: Failed to open file '/usr/share/pixmaps/pidgin/protocols/16/skype.png': No such file or directory
(11:11:38) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file /usr/share/pixmaps/pidgin/protocols/22/skype.png: Failed to open file '/usr/share/pixmaps/pidgin/protocols/22/skype.png': No such file or directory
(11:11:38) util: requesting to fetch a URL
(11:11:38) dnsquery: Performing DNS lookup for client-s.gateway.messenger.live.com
(11:11:38) dns: Successfully sent DNS request to child 9642
(11:11:38) dns: Got response for 'client-s.gateway.messenger.live.com'
(11:11:38) dnsquery: IP resolved for client-s.gateway.messenger.live.com
(11:11:38) proxy: Attempting connection to 157.56.123.78
(11:11:38) proxy: Connecting to client-s.gateway.messenger.live.com:443 with no proxy
(11:11:38) proxy: Connection in progress
(11:11:38) proxy: Connecting to client-s.gateway.messenger.live.com:443.
(11:11:38) proxy: Connected to client-s.gateway.messenger.live.com:443.
(11:11:39) nss: Handshake failed  (-5961)
(11:11:39) g_log: skypeweb_string_get_chunk: assertion 'haystack && start && end' failed
(11:11:39) g_log: skypeweb_string_get_chunk: assertion 'haystack && start && end' failed
(11:11:39) g_log: skypeweb_string_get_chunk: assertion 'haystack && start && end' failed
(11:11:39) connection: Connection error on 0x7f2ddec125d0 (reason: 2 description: Failed getting Registration Token)
(11:11:39) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file /usr/share/pixmaps/pidgin/protocols/16/skype.png: Failed to open file '/usr/share/pixmaps/pidgin/protocols/16/skype.png': No such file or directory
(11:11:39) account: Disconnecting account SebiPanther (0x7f2dddb775c0)
(11:11:39) connection: Disconnecting connection 0x7f2ddec125d0
(11:11:39) GLib: g_source_remove: assertion 'tag > 0' failed
(11:11:39) GLib: g_source_remove: assertion 'tag > 0' failed
(11:11:39) GLib: g_source_remove: assertion 'tag > 0' failed
(11:11:39) skypeweb: getting url /logout
(11:11:39) skypeweb: sending headers:
GET /logout HTTP/1.0
Host: login.skype.com
Connection: close
Accept: */*
Cookie: skplet=1436778698;skype-session-token=12d1a96e0ede27b057347db04154fc08835b1794;login-bt=578134;lastLogin=SK;login-ibb=deleted;skype-session=f05908d18162043014cf0233d7cbbce7de732782;SC=CC=:CCY=:LC=en:LIM=:TM=1436692298:TS=1436692298:TZ=:VAT=:VER=;refresh-token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJpYXQiOjE0MzY2OTIyOTgsImV4cCI6MTQzNjc3ODY5OCwic2t5cGVpZCI6InNlYmlwYW50aGVyIiwic2NwIjoxLCJjc2kiOiIyIn0.PTAekoRSdaH7RYKNY4zIDwEBvtpZ8ZCQ3Z7TLOKHSfxkkdDngtl0SBlIXBd9dlHkvmkpj0mL1oNgHMqbtKLsTs4v9zCFMO8kujqCeOmsvxHBkE5DD0zokymlDXQtvRXJTLYFSkGjTIHd_w-D5j4cQz2efp2NtAYIIEObK11nyEETQGGnirwiC5TRYwd54iR1E4oI0BdwZUwvfRNR;
Accept-Encoding: gzip
Accept-Language: de-DE, de, C
<<

**Comment by freed00m** [comment]
I pulled minute ago and this is usually my output. 

```
~# sudo make

i686-pc-linux-gnu-gcc -I/usr/include/libpurple -DPURPLE_PLUGINS -DENABLE_NLS -Wall -pthread `pkg-config --cflags glib-2.0` -I/usr/include -I. -g -march=athlon-xp -pipe libskype.c -o libskype.so -shared -fPIC -DPIC
/bin/sh: 1: i686-pc-linux-gnu-gcc: not found
make: *** [libskype.so] Error 127
```

I am ignoring this because it worked before with the same output.

Plugin is still broken.! Git pull is up to date.


```
(11:31:40) jabber: Unhandled IQ with id purplebe0e2250
(11:31:42) util: Writing file prefs.xml to directory /home/frdm/.purple
(11:31:42) util: Writing file /home/frdm/.purple/prefs.xml
(11:31:42) util: Writing file accounts.xml to directory /home/frdm/.purple
(11:31:42) util: Writing file /home/frdm/.purple/accounts.xml
(11:31:42) util: Writing file blist.xml to directory /home/frdm/.purple
(11:31:42) util: Writing file /home/frdm/.purple/blist.xml
(11:31:47) jabber: jabber_actions: have pep: YES
(11:31:47) account: Connecting to account q...q...q.
(11:31:47) connection: Connecting. gc = 0x7f4a65b68370
(11:31:47) util: requesting to fetch a URL
(11:31:47) dnsquery: Performing DNS lookup for login.skype.com
(11:31:47) dns: Successfully sent DNS request to child 7620
(11:31:47) dns: Got response for 'login.skype.com'
(11:31:47) dnsquery: IP resolved for login.skype.com
(11:31:47) proxy: Attempting connection to 91.190.216.77
(11:31:47) proxy: Connecting to login.skype.com:443 with no proxy
(11:31:47) proxy: Connection in progress
(11:31:47) proxy: Connecting to login.skype.com:443.
(11:31:47) proxy: Connected to login.skype.com:443.
(11:31:47) nss: subject=CN=login.skype.com,O=Skype,L=Dublin,C=IE issuer=CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US
(11:31:47) nss: subject=CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US issuer=CN=Baltimore CyberTrust Root,OU=CyberTrust,O=Baltimore,C=IE
(11:31:47) nss: partial certificate chain
(11:31:47) certificate/x509/tls_cached: Starting verify for login.skype.com
(11:31:47) certificate/x509/tls_cached: Checking for cached cert...
(11:31:47) certificate/x509/tls_cached: ...Found cached cert
(11:31:47) nss/x509: Loading certificate from /home/frdm/.purple/certificates/x509/tls_peers/login.skype.com
(11:31:47) certificate/x509/tls_cached: Peer cert matched cached
(11:31:47) nss/x509: Exporting certificate to /home/frdm/.purple/certificates/x509/tls_peers/login.skype.com
(11:31:47) util: Writing file /home/frdm/.purple/certificates/x509/tls_peers/login.skype.com
(11:31:47) nss: Trusting CN=login.skype.com,O=Skype,L=Dublin,C=IE
(11:31:47) certificate: Successfully verified certificate for login.skype.com
(11:31:47) util: request constructed
(11:31:48) util: Response headers: 'HTTP/1.1 200 OK
Server: nginx
Date: Sun, 12 Jul 2015 09:31:47 GMT
Content-Type: text/html; ver=1.0; charset=utf-8;
Connection: close
Set-Cookie: SC=CC=:CCY=:LC=en:LIM=:TM=1436693507:TS=1436693507:TZ=:VAT=:VER=; expires=Mon, 11-Jul-2016 09:31:47 GMT; Max-Age=31536000; path=/; domain=.skype.com
Set-Cookie: frmrgtpe=1-1; path=/; domain=.skype.com
X-Stratus-Processing-Time: 0.0353
X-Skype-Request-Id: d0fa5525
X-Stratus-Request-Id: d0fa5525
Pragma: no-cache
Cache-Control: no-store, no-cache, must-revalidate
Expires: Thu, 01 Jan 1970 00:00:01 +0000
P3P: CP="CAO PSA OUR"
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
X-Processing-Time: 0.038
Strict-Transport-Security: max-age=31536000; includeSubDomains

'
(11:31:48) util: requesting to fetch a URL
(11:31:48) dnsquery: Performing DNS lookup for login.skype.com
(11:31:48) dns: Successfully sent DNS request to child 7620
(11:31:48) dns: Got response for 'login.skype.com'
(11:31:48) dnsquery: IP resolved for login.skype.com
(11:31:48) proxy: Attempting connection to 91.190.216.77
(11:31:48) proxy: Connecting to login.skype.com:443 with no proxy
(11:31:48) proxy: Connection in progress
(11:31:48) proxy: Connecting to login.skype.com:443.
(11:31:48) proxy: Connected to login.skype.com:443.
(11:31:48) nss: subject=CN=login.skype.com,O=Skype,L=Dublin,C=IE issuer=CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US
(11:31:48) nss: partial certificate chain
(11:31:48) certificate/x509/tls_cached: Starting verify for login.skype.com
(11:31:48) certificate/x509/tls_cached: Checking for cached cert...
(11:31:48) certificate/x509/tls_cached: ...Found cached cert
(11:31:48) nss/x509: Loading certificate from /home/frdm/.purple/certificates/x509/tls_peers/login.skype.com
(11:31:48) certificate/x509/tls_cached: Peer cert matched cached
(11:31:48) nss/x509: Exporting certificate to /home/frdm/.purple/certificates/x509/tls_peers/login.skype.com
(11:31:48) util: Writing file /home/frdm/.purple/certificates/x509/tls_peers/login.skype.com
(11:31:48) nss: Trusting CN=login.skype.com,O=Skype,L=Dublin,C=IE
(11:31:48) certificate: Successfully verified certificate for login.skype.com
(11:31:48) util: request constructed
(11:31:48) util: Response headers: 'HTTP/1.1 200 OK
Server: nginx
Date: Sun, 12 Jul 2015 09:31:48 GMT
Content-Type: text/html; ver=1.0; charset=utf-8;
Content-Length: 4130
Connection: keep-alive
Set-Cookie: SC=CC=:CCY=:LC=en:LIM=:TM=1436693508:TS=1436693508:TZ=:VAT=:VER=; expires=Mon, 11-Jul-2016 09:31:48 GMT; Max-Age=31536000; path=/; domain=.skype.com
Set-Cookie: login-bt=578134; expires=Mon, 13-Jul-2015 09:32:48 GMT; Max-Age=86460; path=/; secure; httponly
Set-Cookie: refresh-token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJpYXQiOjE0MzY2OTM1MDgsImV4cCI6MTQzNjc3OTkwOCwic2t5cGVpZCI6InEuLi5xLi4ucSIsInNjcCI6MSwiY3NpIjoiMSJ9.CVMHSqGMKYHCw8XDwS8QY_pQsrZvfS1QdZqsl_gR_wsEENsePSeSBXZQeIJjlbX-rKmFt730SBrz81CUDe_-3T4LQOX4ElaQ7o4a2W0WmMO7Q0RtLQ0SIuKZAxzPZMtI70lM6weTirDjEolBCbByWbvt3VbqZYzEAw_v__0BSgyDtwH_a-ps38DefEpzpP98y50Ctp6TQsKUyitr; path=/; secure; httponly
Set-Cookie: skplet=1436779908; path=/; domain=.skype.com
Set-Cookie: login-ibb=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; domain=.skype.com; secure
Set-Cookie: lastLogin=SK; expires=Tue, 11-Aug-2015 09:31:48 GMT; Max-Age=2592000; path=/
Set-Cookie: skype-session=f742c522acea36ea0547126f1c28d62c5a09dd8d; path=/; domain=.skype.com; secure; httponly
Set-Cookie: skype-session-token=32585ff1bf7ffbc9849df8ea6f00198ce4baafbd; path=/; domain=.skype.com
X-Stratus-Processing-Time: 0.1999
X-Skype-Request-Id: c6177cc5
X-Stratus-Request-Id: c6177cc5
Pragma: no-cache
Cache-Control: no-store, no-cache, must-revalidate
Expires: Thu, 01 Jan 1970 00:00:01 +0000
P3P: CP="CAO PSA OUR"
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
X-Processing-Time: 0.209
Strict-Transport-Security: max-age=31536000; includeSubDomains

'
(11:31:48) util: parsed 4130
(11:31:48) jabber: jabber_actions: have pep: YES
(11:31:48) util: requesting to fetch a URL
(11:31:48) dnsquery: Performing DNS lookup for client-s.gateway.messenger.live.com
(11:31:48) dns: Successfully sent DNS request to child 7620
(11:31:49) dns: Got response for 'client-s.gateway.messenger.live.com'
(11:31:49) dnsquery: IP resolved for client-s.gateway.messenger.live.com
(11:31:49) proxy: Attempting connection to 157.56.123.78
(11:31:49) proxy: Connecting to client-s.gateway.messenger.live.com:443 with no proxy
(11:31:49) proxy: Connection in progress
(11:31:49) proxy: Connecting to client-s.gateway.messenger.live.com:443.
(11:31:49) proxy: Connected to client-s.gateway.messenger.live.com:443.
(11:31:49) nss: Handshake failed  (-5961)
(11:31:49) g_log: skypeweb_string_get_chunk: assertion 'haystack && start && end' failed
(11:31:49) g_log: skypeweb_string_get_chunk: assertion 'haystack && start && end' failed
(11:31:49) g_log: skypeweb_string_get_chunk: assertion 'haystack && start && end' failed
(11:31:49) connection: Connection error on 0x7f4a65b68370 (reason: 2 description: Failed getting Registration Token)
(11:31:49) jabber: jabber_actions: have pep: YES
(11:31:49) account: Disconnecting account q...q...q (0x7f4a65316690)
(11:31:49) connection: Disconnecting connection 0x7f4a65b68370
(11:31:49) GLib: g_source_remove: assertion 'tag > 0' failed
(11:31:49) GLib: g_source_remove: assertion 'tag > 0' failed
(11:31:49) GLib: g_source_remove: assertion 'tag > 0' failed
(11:31:49) skypeweb: getting url /logout
(11:31:49) skypeweb: sending headers:
GET /logout HTTP/1.0
Host: login.skype.com
Connection: close
Accept: */*
Cookie: skplet=1436779908;skype-session-token=32585ff1bf7ffbc9849df8ea6f00198ce4baafbd;login-bt=578134;lastLogin=SK;login-ibb=deleted;skype-session=f742c522acea36ea0547126f1c28d62c5a09dd8d;SC=CC=:CCY=:LC=en:LIM=:TM=1436693508:TS=1436693508:TZ=:VAT=:VER=;refresh-token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJpYXQiOjE0MzY2OTM1MDgsImV4cCI6MTQzNjc3OTkwOCwic2t5cGVpZCI6InEuLi5xLi4ucSIsInNjcCI6MSwiY3NpIjoiMSJ9.CVMHSqGMKYHCw8XDwS8QY_pQsrZvfS1QdZqsl_gR_wsEENsePSeSBXZQeIJjlbX-rKmFt730SBrz81CUDe_-3T4LQOX4ElaQ7o4a2W0WmMO7Q0RtLQ0SIuKZAxzPZMtI70lM6weTirDjEolBCbByWbvt3VbqZYzEAw_v__0BSgyDtwH_a-ps38DefEpzpP98y50Ctp6TQsKUyitr;
Accept-Encoding: gzip
Accept-Language: en-GB.UTF-8, en-GB, en.UTF-8, en, C


(11:31:49) dnsquery: Performing DNS lookup for login.skype.com
(11:31:49) skypeweb: destroying 0 waiting connections
(11:31:49) skypeweb: destroying 1 incomplete connections
(11:31:49) jabber: jabber_actions: have pep: YES
(11:31:49) connection: Destroying connection 0x7f4a65b68370
(11:31:52) util: Writing file accounts.xml to directory /home/frdm/.purple
(11:31:52) util: Writing file /home/frdm/.purple/accounts.xml
(11:31:55) imgstore: retrieved image id 1
(11:31:55) imgstore: retrieved image id 2
(11:31:55) imgstore: retrieved image id 3
(11:31:55) imgstore: retrieved image id 4
(11:31:55) account: Disconnecting account freed00m@dukgo.com/DukcDuckGo (0x7f4a65312c00)
(11:31:55) connection: Disconnecting connection 0x7f4a65b71f50
(11:31:55) connection: Deactivating keepalive.
(11:31:55) jabber: Sending (ssl) (freed00m@dukgo.com/DukcDuckGo): </stream:stream>
(11:31:55) connection: Destroying connection 0x7f4a65b71f50
(11:31:55) certificate: CertificateVerifier tls_cached unregistered
(11:31:55) certificate: CertificateVerifier singleuse unregistered
(11:31:55) certificate: CertificatePool tls_peers unregistered
(11:31:55) certificate: CertificatePool ca unregistered
(11:31:55) main: Unloading normal plugins
(11:31:55) plugins: Unloading plugin Pidgin GTK+ Theme Control
(11:31:55) plugins: Unloading plugin Off-the-Record Messaging
(11:31:55) plugins: Unloading plugin History
(11:31:55) plugins: Unloading plugin SSL
(11:31:55) plugins: Unloading plugin NSS
(11:31:55) certificate: CertificateScheme x509 unregistered
(11:31:55) plugins: Unloading plugin Autoaccept
(11:31:55) util: Writing file blist.xml to directory /home/frdm/.purple
(11:31:55) util: Writing file /home/frdm/.purple/blist.xml
(11:31:55) blist: Destroying
(11:31:55) accels: accel changed, scheduling save.
(11:31:55) accels: accel changed, scheduling save.
(11:31:55) accels: accel changed, scheduling save.
(11:31:55) accels: accel changed, scheduling save.
(11:31:55) accels: accel changed, scheduling save.
(11:31:55) accels: accel changed, scheduling save.
(11:31:55) accels: accel changed, scheduling save.
(11:31:55) accels: accel changed, scheduling save.
(11:31:55) accels: accel changed, scheduling save.
(11:31:55) accels: accel changed, scheduling save.
(11:31:55) accels: accel changed, scheduling save.
(11:31:55) accels: accel changed, scheduling save.
(11:31:55) accels: accel changed, scheduling save.
(11:31:55) util: Writing file status.xml to directory /home/frdm/.purple
(11:31:55) util: Writing file /home/frdm/.purple/status.xml
(11:31:55) account: Destroying account 0x7f4a65318430
(11:31:55) account: Destroying account 0x7f4a65312c00
(11:31:55) account: Destroying account 0x7f4a65316690
(11:31:55) main: Unloading all plugins
(11:31:55) plugins: Unloading plugin Skype
(11:31:55) plugins: Unloading plugin SIMPLE
(11:31:55) plugins: Unloading plugin MXit
(11:31:55) plugins: Unloading plugin Skype (D-Bus)
(11:31:55) plugins: Unloading plugin XMPP
(11:31:55) jabber: destroying hash tables for data objects
(11:31:55) plugins: Unloading plugin GroupWise
(11:31:55) plugins: Unloading plugin IRC
(11:31:55) plugins: Unloading plugin Bonjour
(11:31:55) plugins: Unloading plugin Skype (HTTP)
(11:31:55) plugins: Unloading plugin Yahoo JAPAN
(11:31:55) plugins: Unloading plugin Gadu-Gadu
(11:31:55) plugins: Unloading plugin Zephyr
(11:31:55) plugins: Unloading plugin MySpaceIM
(11:31:55) plugins: Unloading plugin ICQ
(11:31:55) plugins: Unloading plugin MSN
(11:31:55) plugins: Unloading plugin Yahoo
(11:31:55) plugins: Unloading plugin Perl Plugin Loader
(11:31:55) plugins: Unloading plugin AIM
(11:31:55) plugins: Unloading plugin Tcl Plugin Loader
(11:31:55) plugins: Unloading plugin Sametime
(11:31:55) Session Management: Handling closed ICE connection... 
(11:31:55) done.
(11:31:55) Session Management: Connection closed.
(11:31:55) gtkblist: removed visibility manager: 0
(11:31:55) docklet: detached
(11:31:55) docklet: GTK+ destroyed
```

**Comment by EionRobb** [comment]
So it looks like people are getting
(11:11:39) nss: Handshake failed (-5961)
In their error logs when logging in, which is saying that the TCP connection is being closed.

Can I check that everyone experiencing this is using Pidgin 2.10.11 and not an older version?  If you're using 2.10.11, can you check the NSS Preferences plugin (in Tools->Plugins) what the min and max version of TLS/SSL is set to?

**Comment by EionRobb** [comment]
So it looks like its when using older versions of libpurple, NSS is trying to connect with TLS1.0 and the server is rejecting.

Make sure you update libpurple to 2.10.11 (and verify that it's that in Help->About) and try again. :)

**Comment by hetdegon** [comment]
Updating to 2.10.11 fixed it for me.

**Comment by freed00m** [comment]
YES, updating to 2.10.11 fixed the issue.

Anyone having trouble please update from this repo
http://www.ubuntuupdates.org/ppa/pidgin

Should be mentioned in readme.

**Comment by EionRobb** [comment]
Ok, I've made the plugin check to make sure you're using libpurple 2.10.11 if it can't login.  Hopefully that helps for other people with the same issue.

**Comment by SebiPanther** [comment]
It works again! \o/
I've just installed the last Versions (Pidgin 2.10.11 (libpurple 2.10.11)) and enabled the NSS preferences Plugin without changing the configuration of it.
Thanks <3

**Comment by event** [comment]
Hi,
It looks like the issue is back again :(
Pidgin version 2.10.11. Skype4Web pulled this morning

Here is the log:
(12:00:22) util: parsed 3488
(12:00:22) util: requesting to fetch a URL
(12:00:22) dnsquery: Performing DNS lookup for client-s.gateway.messenger.live.com
(12:00:22) dns: Successfully sent DNS request to child 15727
(12:00:27) dns: Got response for 'client-s.gateway.messenger.live.com'
(12:00:27) dnsquery: IP resolved for client-s.gateway.messenger.live.com
(12:00:27) proxy: Attempting connection to 157.56.123.78
(12:00:27) proxy: Connecting to client-s.gateway.messenger.live.com:443 with no proxy
(12:00:27) proxy: Connection in progress
(12:00:27) proxy: Connecting to client-s.gateway.messenger.live.com:443.
(12:00:27) proxy: Connected to client-s.gateway.messenger.live.com:443.
dns[15727]: nobody needs me... =(
(12:01:31) nss: Handshake failed  (-5961)
(12:01:31) g_log: skypeweb_string_get_chunk: assertion 'haystack && start && end' failed
(12:01:31) g_log: skypeweb_string_get_chunk: assertion 'haystack && start && end' failed
(12:01:31) g_log: skypeweb_string_get_chunk: assertion 'haystack && start && end' failed
(12:01:31) g_log: skypeweb_string_get_chunk: assertion 'haystack && start && end' failed
(12:01:31) connection: Connection error on 0x2066470 (reason: 2 description: Failed getting Registration Token)
(12:01:31) account: Disconnecting account event84 (0x19bf9b0)
(12:01:31) connection: Disconnecting connection 0x2066470
(12:01:31) GLib: g_source_remove: assertion 'tag > 0' failed
(12:01:31) GLib: g_source_remove: assertion 'tag > 0' failed
(12:01:31) GLib: g_source_remove: assertion 'tag > 0' failed
(12:01:31) skypeweb: getting url /logout
(12:01:31) skypeweb: sending headers:
GET /logout HTTP/1.0
Host: login.skype.com
Connection: close
Accept: */*
Cookie: kmsi=deleted;lastLogin=SK;login-bt=578134;SC=CC=:CCY=:LC=en:LIM=:TM=1453118422:TS=1453118422:TZ=:VAT=:VER=;refresh-token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjIifQ.eyJpYXQiOjE0NTMxMTg0MjIsImV4cCI6MTQ1NTcxMDQyMiwic2t5cGVpZCI6ImV2ZW50ODQiLCJzY3AiOjEsImNzaSI6IjAiLCJhYXQiOjE0NTMxMTg0MjJ9.bI3HEglK0-jEd282MSgA4GshQVlM0Z8NuQ4h8ZIeIRAzqn-aE5gLue8IMH7bifthq2f6wYHUewGx7or96FFRAVhyipjNTbv11rGP-doUu6jvdSdC_3ztME-VPVnjx9A4jwxQ8BbMDi7V5Y2pMZusHxZzG5o5Zzk4blF0iyd4GGit-muK7WbvpZYLc_eHvGXBeZbHTWId-1y0ORfY;skplet=1455710422;
Accept-Encoding: gzip
Accept-Language: en-IE, en, en, C
