### ISSUE TITLE
Cannot join to Skype group.

### ISSUE THREAD

**Issue by pcroland** [EionRobb/skype4pidgin#298]
I did "/get name" command in Skype and get this output:
#pcroland.tk/$live:salamondavid_1;571b01cfad580ed6
I wasn't able to join to the group in pidgin with this output and the group is not on the grouplist.
Windows 8.1
Skype 7.6.0.105
Pidgin 2.10.11

**Comment by EionRobb** [comment]
That looks like a legacy p2p group chat that the new skypeweb plugin is unable to connect to. It's apparently possible to recreate it as a cloud-backed thread using the /fork command from the Skype client, which starts a new chat and invites all the buddies into it.

**Comment by pcroland** [comment]
Thanks! "/fork" did the work :D
