### ISSUE TITLE
Messages from (and to) msn/live accounts not getting through.

### ISSUE THREAD

**Issue by szr8** [EionRobb/skype4pidgin#299]
The debug log below shows that an incoming message from MSN/Live user (using old MSN account via Butterfly Messenger) to Pidgin/Skypeweb (using legacy live/msn login of merged account) is attempting to come through but doesn't seem to be processed correctly (assuming going by the "g_log: process_message_resource: assertion `from' failed" line.)

Debug log: https://gist.github.com/szr8/1267c3c8dd00b249ee0c

I also do no appear to be able to send messages the other way (from Pidgin/Skypeweb -> MSN/Live user), which is likely due to the same reasons.

**Comment by EionRobb** [comment]
Fascinating :)
I haven't got any msn-only users on my buddy list to test this with. I don't know if web.skype.com handles them either, but it would be good to make this work. 

Does the msn user show on the buddy list?

**Comment by szr8** [comment]
Yes, the MSN user shows in the list in both the official client and via web.skype.com and yes messaging works via web.skype.com. It looks like messages from MSN are hitting the skypeweb plugin as my debug log shows, but it doesn't seem to know what to do with them.

There is also https://messenger.live.com/ which is a separate and different applet from https://web.skype.com, and it too works with both MSN and Skype users and seems to actually work better. This might be something to look at perhaps though I don't know if it will remain in the long run or not.

**Comment by EionRobb** [comment]
Ok, just commited some changes to make things maybe possibly work with MSN contacts.  Maybe.

Needless to say, it needs testing!  (windows dll for testing at http://eion.robbmob.com/libskypeweb-debug.dll )  I don't have any MSN-only contacts any more, so it's a bit of a guess from me about the changes.

Feedback welcome :)

**Comment by EionRobb** [comment]
Oops, found lots of memory corruption things in the MSN commits, but have committed a few more changes to fix

**Comment by EionRobb** [comment]
MSN stuff should be all good and has been working for a while now.  Feel free to create new issues if you're having trouble still
