### ISSUE TITLE
Skypeweb crash when someone sends an image to the user (again)

### ISSUE THREAD

**Issue by hetdegon** [EionRobb/skype4pidgin#301]
Since you said to open a new issue in #252 ...it crashes again since image fetching was re-enabled . Same situation and behavior as that issue, just with pidgin 2.10.11 and latest skypeweb version.
At times the images just start a transfer on the regular Skype client, at times they upload it to that server. Even two images with the same format sent consecutively from the same device can or can not trigger the skype "feature".

**Comment by EionRobb** [comment]
Can you supply a new backtrace and new debug log, since it's going to be a slightly different crash to before :)

**Comment by hetdegon** [comment]
As soon as I am unable to reproduce, for sure. Today I logged in and found out someone triggered the "upload to skype server" thing while I was out, and the image actually showed inline. It was a different person, so not sure if it's something dependent on their skype client version. Will try to force it to happen ASAP.

**Comment by hetdegon** [comment]
I got a few cases of surprise crash again, but it appears to have some quantum effect that prevents it from crashing when under observation or when debug mode is enabled, and the "shared image" feature only seems to kick in whenever it feels like it. 
Having a person sending photos from the mobile version of Skype while debug mode is enabled won't trigger the crash or the "shared image" feature, but the same person sending a photo from the same phone hours later does trigger it. Photos were about the same file size and format, both of our status didn't change, there were no reboots or updates in either side. Similarly, asking a person that caused the crash to resend the same image that triggered the feature and crash a second time doesn't seem to trigger it again, and starts a normal file transfer in the official Skype client. It seems completely random.
Because of that, I'll close this issue until I can trigger it reliably, because at this rate it can take months. Sorry for the inconvenience.
