### ISSUE TITLE
Messenger contacts not added to Pidgin

### ISSUE THREAD

**Issue by duairc** [EionRobb/skype4pidgin#302]
Hey,

I'm using the skypeweb plugin. When I add my merged Skype/MSN Messenger account, my Skype contacts get added to Pidgin, but not my Messenger ones. If I decouple my Skype and MSN accounts and add my MSN account to the skypeweb Pidgin plugin, it logs in successfully, but no contacts are added.

I'm not sure if this is the expected behaviour or not, but given that the MSN plugin that comes with Pidgin no longer works, it would be nice if skypeweb could replace that.

**Comment by EionRobb** [comment]
See #299
