### ISSUE TITLE
Checkbox in Advanced settings, no description

### ISSUE THREAD

**Issue by freed00m** [EionRobb/skype4pidgin#305]
I have no Idea if it does anything?  Web skype
Does it?

![selection_006](https://cloud.githubusercontent.com/assets/9461698/8772227/96f7788c-2eca-11e5-8ae6-e6945eb55615.png)

I didn't run it with debug flag.

**Comment by EionRobb** [comment]
That's normal, a protocol needs to have at least one option to prevent a crash-on-quit problem :)

**Comment by maritz** [comment]
I'm getting 2 other options there as well about "typing" status.

But regardless: Wouldn't it be better to have some kind of placebo text there? Like 

    (advanced only) check validity of text message format on plumbus files for XTTR:D protocol

That way people will most likely ignore the checkbox, and if someone wants to know what it actually is, they will get a google result pointing to the github commit explaining wtf is going on.

Just a suggestion, obviously if you really want to know (like I did) you can still find this issue.
