### ISSUE TITLE
compilation on x86_64

### ISSUE THREAD

**Issue by drzraf** [EionRobb/skype4pidgin#306]
skypeweb/CMakeFiles/skypeweb.dir/flags.make is missing
```-I/usr/lib/x86_64-linux-gnu/glib-2.0/include/```

And /skypeweb/Makefile.eion may have to specify:
```LINUX64_COMPILER = x86_64-linux-gnu-gcc```

But the former is an autogenerated file (don't know how)
At least it was the changes I needed to compile on Debian Jessie amd64

**Comment by EionRobb** [comment]
Can you send through a PR?  The cmake files were submitted by someone else, and I don't know anything about it :)

**Comment by vitalyster** [comment]
Can you post full cmake configuring log? It should detect compiler without changes.

**Comment by EionRobb** [comment]
I'm just gonna close this issue since it's really old now.  If it's still happening, please reopen
