### ISSUE TITLE
Failed getting MSPRequ cookie

### ISSUE THREAD

**Issue by nahuelange** [EionRobb/skype4pidgin#307]
After installing it and using it with spectrum, when I configure my account I have this error:
«Failed getting MSPRequ cookie»

Any idea of the origin of the problem? Is it a bug or is it unproperly configured?

**Comment by nahuelange** [comment]
FYI I'm using the «master» branch

**Comment by nahuelange** [comment]
It seems to be an SSL problems with libpurple... but I have no idea why…

In the logs I have this:

30841: 2015-07-22 15:14:37,194 INFO  libpurple: proxy:Attempting connection to 91.190.216.77
30841: 2015-07-22 15:14:37,194 INFO  libpurple: proxy:Connecting to login.skype.com:443 with no proxy
30841: 2015-07-22 15:14:37,195 INFO  libpurple: proxy:Connection in progress
30841: 2015-07-22 15:14:37,209 INFO  libpurple: proxy:Connecting to login.skype.com:443.
30841: 2015-07-22 15:14:37,210 INFO  libpurple: proxy:Connected to login.skype.com:443.
30841: 2015-07-22 15:14:37,247 INFO  libpurple: nss:SSL version 3.2 using 128-bit RC4 with 128-bit MD5 MAC
Server Auth: 2048-bit RSA, Key Exchange: 2048-bit RSA, Compression: NULL
Cipher Suite Name: SSL_RSA_WITH_RC4_128_MD5
30841: 2015-07-22 15:14:37,247 INFO  libpurple: nss:subject=CN=login.skype.com,O=Skype,L=Dublin,C=IE issuer=CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US
30841: 2015-07-22 15:14:37,247 INFO  libpurple: nss:subject=CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US issuer=CN=Baltimore CyberTrust Root,OU=CyberTrust,O=Baltimore,C=IE
30841: 2015-07-22 15:14:37,247 INFO  libpurple: nss:partial certificate chain
30841: 2015-07-22 15:14:37,247 INFO  libpurple: certificate/x509/tls_cached:Starting verify for login.skype.com
30841: 2015-07-22 15:14:37,247 INFO  libpurple: certificate/x509/tls_cached:Checking for cached cert...
30841: 2015-07-22 15:14:37,248 INFO  libpurple: certificate/x509/tls_cached:...Not in cache
30841: 2015-07-22 15:14:37,248 INFO  libpurple: certificate/x509/ca:Couldn't open location './ca-certs'
30841: 2015-07-22 15:14:37,248 INFO  libpurple: certificate/x509/ca:Lazy init completed.
30841: 2015-07-22 15:14:37,252 INFO  libpurple: nss:CERT 1. CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US [Certificate Authority]:
30841: 2015-07-22 15:14:37,252 INFO  libpurple: nss:  ERROR -8179: SEC_ERROR_UNKNOWN_ISSUER
30841: 2015-07-22 15:14:37,252 INFO  libpurple: certificate:Failed to verify certificate for login.skype.com
30841: 2015-07-22 15:14:37,252 ERROR backend: g_log skypeweb_string_get_chunk: assertion `haystack && start && end' failed
30841: 2015-07-22 15:14:37,252 INFO  libpurple: connection:Connection error on 0x83b42b8 (reason: 2 description: Failed getting MSPRequ cookie)

**Comment by EionRobb** [comment]
That looks like you don't have the Microsoft CA in your certs?

**Comment by nahuelange** [comment]
But…I have the ca-certificates installed… and going to the login.skype.com URL doesn't throw any problem with other softwares

**Comment by EionRobb** [comment]
Do you have them in your pidgin ca-certs?  Looks like it's having trouble loading them "Couldn't open location './ca-certs'"

**Comment by nahuelange** [comment]
Yes, I think…

/usr/share/purple/ca-certs# ls -al
total 32
drwxr-xr-x 2 root root 4096 juil. 23 11:18 .
drwxr-xr-x 3 root root 4096 juil. 23 09:28 ..
-rw-r--r-- 1 root root 1505 oct.  19  2014 AOL_Member_CA.pem
-rw-r--r-- 1 root root 2256 oct.  19  2014 DigiCertHighAssuranceCA-3.pem
-rw-r--r-- 1 root root 1818 oct.  19  2014 Microsoft_Internet_Authority_2010.pem
-rw-r--r-- 1 root root 2167 oct.  19  2014 Microsoft_Secure_Server_Authority_2010.pem
-rw-r--r-- 1 root root 2136 oct.  19  2014 VeriSign_Class3_Extended_Validation_CA.pem
-rw-r--r-- 1 root root 1277 oct.  19  2014 VeriSign_International_Server_Class_3_CA.pem

**Comment by EionRobb** [comment]
There should be a Baltimore_CyberTrust_Root.pem too?  Are you not using the default certs that come with Pidgin?

**Comment by nahuelange** [comment]
Hmmm I found how a workaround :
ln -s /usr/share/ca-certificates/ /var/lib/spectrum2/skype.mydomain.org/certificates/x509/ca-certs/

why? i don't know :-)

**Comment by EionRobb** [comment]
That lets spectrum2 use your systems ca-certs :)
Glad you figured it out :)

**Comment by Macadoshis** [comment]
Seems like ```Failed getting MSPRequ cookie``` is a generic error message for multiple issues.

See yet unresolved #389 issue, displaying ```Failed getting MSPRequ cookie``` after getting a HTTP 400 response from login.live.com:443.
Not sure it's only related to a SSL problem.

**Comment by rugabunda** [comment]
I had this problem with a router ad blocker, i had disabled blocking and it persisted, until I had cleared dns cache in acrylic.
