### ISSUE TITLE
SkypeWeb disconnects silently after 24 hours

### ISSUE THREAD

**Issue by Waterkonijn** [EionRobb/skype4pidgin#308]
Hello,
This is my first post so I don't quite know the environment just yet, and I apologise for this.

I have had this issue with Skypeweb from the start that it does exactly as the title says and it disconnects after exactly 24 hours without error, warning or even showing that it has disconnected.

I was wondering if there is a fix for this or at least a  workaround.

**Comment by vitalyster** [comment]
Looks like The Main Bug #287 :)

**Comment by EionRobb** [comment]
Yeah, sounds like #287 :)
