### ISSUE TITLE
libskype.c:1:0: error: CPU you selected does not support x86-64 instruction set

### ISSUE THREAD

**Issue by jusa213** [EionRobb/skype4pidgin#311]
Hello

Thanks for the nice plugin.
I get an error while trying to compile it on debian 8. I try to compile it on debian 64bit and of course a cpu that is 64bit. If this is the same issue like #306 then sorry for the double post.

here is what I get:
-----
make
i686-pc-linux-gnu-gcc -I/usr/include/libpurple -DPURPLE_PLUGINS -DENABLE_NLS -Wall -pthread `pkg-config --cflags glib-2.0` -I/usr/include -I. -g -march=athlon-xp -pipe libskype.c -o libskype.so -shared -fPIC -DPIC
/bin/sh: 1: i686-pc-linux-gnu-gcc: not found
Makefile:68: recipe for target 'libskype.so' failed
make: *** [libskype.so] Error 127

So I made some symlinks: 
ln -s g++ i686-pc-linux-gnu-g++
ln -s gcc i686-pc-linux-gnu-gcc
ln -s c++ i686-pc-linux-gnu-c++
ln -s cpp i686-pc-linux-gnu-cpp

But then I get the following error:
------
make
i686-pc-linux-gnu-gcc -I/usr/include/libpurple -DPURPLE_PLUGINS -DENABLE_NLS -Wall -pthread `pkg-config --cflags glib-2.0` -I/usr/include -I. -g -march=athlon-xp -pipe libskype.c -o libskype.so -shared -fPIC -DPIC
libskype.c:1:0: error: CPU you selected does not support x86-64 instruction set
 /*
 ^
libskype.c:1:0: error: CPU you selected does not support x86-64 instruction set
Makefile:68: recipe for target 'libskype.so' failed
make: *** [libskype.so] Error 1

Any idea about that?

**Comment by vitalyster** [comment]
1) you are building old skype plugin, the new one located in skypeweb/ directory
2) Makefile provided with old plugin assumed you have both 32 and 64 bit compilers, you should **not** link 32-bit stuff to 64-bit compiler, you need to install 32 bit compiler or comment out compilation of 32-bit plugin (in fact you need to go 1)

**Comment by jusa213** [comment]
@vitalyster, thanks for the explanation. Compiling inside skypeweb dir did work. I tink this ticket can be closed.
