### ISSUE TITLE
Skypweb: Support Message Sync aka revice message sent from user

### ISSUE THREAD

**Issue by Thaodan** [EionRobb/skype4pidgin#312]
Usally Skype sends messages that were send from other clients of the user (xmpp calls them resources) to all clients that they're in sync. 
Currently Skypweb don't supports this or receives these messages.

**Comment by EionRobb** [comment]
Can you provide an example?  Self-sent messages are working here...

**Comment by Thaodan** [comment]
at least with telepathy-haze it don works

**Comment by EionRobb** [comment]
Either this bug has magically gone away on it's own or it's not something the plugin can solve.  Either way :(
