### ISSUE TITLE
Skypweb: Add native telepathy support

### ISSUE THREAD

**Issue by Thaodan** [EionRobb/skype4pidgin#314]
It would be nice if telepathy would be native support as telepathy-haze is broken in many ways and especially for future video/voice support it would be much easier to implement.

**Comment by TemeV** [comment]
If there was a "libskypeweb" that is not depending on libpurple, this would be easily doable. Now it seems that the code is heavily depending on purple. Is it possible to separate the "skype parts" and "purple parts" to make the "skype parts" reusable for other projects?

**Comment by EionRobb** [comment]
Unfortunately this falls well outside of the scope of this plugin.  Rewriting this plugin from scratch is not something I'm prepared to do.  I'm happy to provide advise about the protocol (and of course, you're welcome to use portions of the code as long as you keep your telepathy module GPL)

**Comment by Thaodan** [comment]
Could you at least write a wrapper? In which ways puple helped you to write  the plugin?
As far as I see the plugin is mostly talking to the website to pull and get data or not?

**Comment by EionRobb** [comment]
Haze is the wrapper :)

**Comment by Thaodan** [comment]
A wrapper around your skype functionality so that there's a real libskype. 
Haze is crap and broken, especially in this case:
https://github.com/EionRobb/skype4pidgin/issues/312
https://github.com/EionRobb/skype4pidgin/issues/300

etc.

**Comment by Omar007** [comment]
@EionRobb I have some questions regarding the communication between the plugin and the Skype website as I may try and pick this up.
Do you have some documentation of the different endpoints that are currently available or do I have to extract the information from the code? Is the UWCA anywhere close to it?
From what I gathered, Skype does not (yet) implement WebRTC and still uses a browser plugin and as such we would not be able to implement any form of voice/video for the time being right? (short of trying to reverse engineer the plugin or something, which I'm not going to do if you don't mind ;P )
