### ISSUE TITLE
SkypeWeb: posible bug in skypeweb_gunzip()

### ISSUE THREAD

**Issue by pchome** [EionRobb/skype4pidgin#321]
https://github.com/EionRobb/skype4pidgin/blob/master/skypeweb/skypeweb_connection.c#L72
Something strange here.

Is there missed `gzip_err =` before `inflateInit2(&zstr, -MAX_WBITS);` , or wrong code after `if (gzip_err == Z_DATA_ERROR)`?
Because  `if (gzip_err != Z_OK)` unneeded if  `Z_DATA_ERROR` is set.

**Comment by EionRobb** [comment]
Wow, nice find.  I've been reusing that code for.... 8 years and never noticed that before :)

**Comment by EionRobb** [comment]
Thanks for that :)
