### ISSUE TITLE
Re: Did this plugin make your life happier? Send me $1 to say thanks!

### ISSUE THREAD

**Issue by Lord-Evil** [EionRobb/skype4pidgin#322]
Will send more if you can help me create stand-alone client/library. Ideal target is to create OOP interface for D(that's not that hard, already made one for XMPP libstrophe).

**Comment by EionRobb** [comment]
Unfortunately I don't know anything about D.

If you're wanting something standalone, you could try using either spectrum2 (which is an XMPP transport using libpurple) or catbref/bitlbee (both IRC servers) that can use libpurple as a backend.

**Comment by Lord-Evil** [comment]
It's not hard to bind C libs in D, just use "dstep". But I've found it hard to bind to libpurple it self. I came to conclusion that I need some kind of HTTP interface for libpurple. Well, spectrum2 looks promising. Thanks for the advice!
