### ISSUE TITLE
Skypeweb bug: no nickname auto resolving

### ISSUE THREAD

**Issue by xvitaly** [EionRobb/skype4pidgin#326]
Nicknames not automatically resolving after last skypeweb updates. Only Skype logins as nicknames in Pidgin buddy list. Tested on fresh Pidgin installation.

**Comment by xvitaly** [comment]
Downgraded to commit Jul 23, 2015 and now works fine.

**Comment by pchome** [comment]
https://github.com/EionRobb/skype4pidgin/blob/master/skypeweb/skypeweb_connection.c#L586
it looks like `SKYPEWEB_NEW_CONTACTS_HOST` missed here
I changed it to: `if (g_str_equal(host, SKYPEWEB_NEW_CONTACTS_HOST) || g_str_equal(host, SKYPEWEB_CONTACTS_HOST) || g_str_equal(host, SKYPEWEB_VIDEOMAIL_HOST)) {`
and it works for me

**Comment by EionRobb** [comment]
Sorry about that, should be fixed now
