### ISSUE TITLE
SkypeWeb: chat: unhandled event "Control/Typing"

### ISSUE THREAD

**Issue by pchome** [EionRobb/skype4pidgin#328]
Debug output: __*Unhandled thread message resource messagetype 'Control/Typing'*__

**Comment by EionRobb** [comment]
Multi-user chats don't support typing notifications in libpurple/Pidgin.... not quite sure how to handle them yet

**Comment by pchome** [comment]
> not quite sure how to handle them yet

me too, I'm not so familiar with libpurple and simply copy/pasted corresponding part of code from IM block to check if it works
and it didn't :)

but I found this while digging: `PURPLE_CBFLAGS_TYPING        = 0x0010, /**< Currently typing             */`
maybe this flag must be set when "Control/Typing" event received (and reset when message received from this user) ?

**Comment by pchome** [comment]
So, the best thing I can get from purple API for notifications in chat is "system messages".
But there is no way to remove messages from conversation (maybe full destruction and restoration of only selected messages, but it's too evil method for notification :) ). Message changing/editing/removing API would be great for notifications like this.

Also **Skype for Web** server do not reporting "Typed" ("ClearTyping"?) events for chat, so something like timeout needed to report in chat that nobody typing now.

This example prints _"buddy typing ..."_ message into conversation:
```patch
diff --git a/skypeweb/skypeweb_messages.c b/skypeweb/skypeweb_messages.c
index f3652e2..1c9ad6d 100644
--- a/skypeweb/skypeweb_messages.c
+++ b/skypeweb/skypeweb_messages.c
@@ -122,7 +122,25 @@ process_message_resource(SkypeWebAccount *sa, JsonObject *resource)
 		}
 		conv = PURPLE_CONVERSATION(chatconv);
 		
-		if ((g_str_equal(messagetype, "RichText") || g_str_equal(messagetype, "Text")) && content && *content) {
+		if (g_str_equal(messagetype, "Control/Typing")) {
+			// typing notification text, not personalized because of multiple "typing" events
+			const gchar *message = g_strdup_printf("%s ...", _("buddy typing"));
+			const gchar *last_message = NULL;
+
+			from = skypeweb_contact_url_to_name(from);
+			g_return_if_fail(from);
+
+			// get last message (first in GList)
+			if (g_list_length(conv->message_history)) {
+				PurpleConvMessage *last = g_list_nth_data(g_list_first(conv->message_history),0);
+				last_message = g_strdup(last->what);
+			}
+
+			// add typing notification to chat
+			if (last_message && !g_str_equal(last_message, message)) {
+				purple_conversation_write(conv, NULL, message, PURPLE_MESSAGE_NO_LOG | PURPLE_MESSAGE_NOTIFY | PURPLE_MESSAGE_ACTIVE_ONLY , composetimestamp);
+			}
+		} else if ((g_str_equal(messagetype, "RichText") || g_str_equal(messagetype, "Text")) && content && *content) {
 			gchar *html;
 			gint skypeemoteoffset = 0;
 			

```

P.S. I not really sure, but closed chat windows are forced to be opened by that events, while they shouldn't. Maybe something wrong in my Pidgin configuration or maybe it's SkypeWeb plugin's default behaviour when event was received,  I don't figured out yet.

**Comment by EionRobb** [comment]
I've been thinking about this a bit... how about we set the 'voice' flag on the chatbuddy, so they'll have an icon next to their name while they're typing?  We could set the typing cbflag flag too.

**Comment by pchome** [comment]
I saw somewhere in the code 'voice' flag is set for all but creator. 
https://github.com/EionRobb/skype4pidgin/blob/f990671c7cf7de24c19a0b3a4f7988a28f7eca29/skypeweb/skypeweb_messages.c#L601 - this,
https://github.com/EionRobb/skype4pidgin/blob/f990671c7cf7de24c19a0b3a4f7988a28f7eca29/skypeweb/skypeweb_messages.c#L193 - and this parts

Can users write into chat when 'voice' flag don't set ?

**Comment by pchome** [comment]
ok , I added 
```
PurpleConvChatBuddyFlags cbflags = purple_conv_chat_user_get_flags(chatconv, from);
purple_conv_chat_user_set_flags(chatconv, from, cbflags | PURPLE_CHAT_USER_VOICE);
purple_conversation_update(conv, PURPLE_CONV_UPDATE_TYPING);
```
to "Control/Typing" block and `, cbflags ^ PURPLE_CHAT_USER_VOICE)` to "RichText" block
and it works fine :)
'voice' icon added while typing and removed when message reseived

**Comment by pchome** [comment]
I think you can implement both variants disabled by default and controlled via options in  account settings dialog (you already have empty one [here](https://github.com/EionRobb/skype4pidgin/blob/f990671c7cf7de24c19a0b3a4f7988a28f7eca29/skypeweb/libskypeweb.c#L698) :wink: ).
