### ISSUE TITLE
skypeweb: building for older libpurple

### ISSUE THREAD

**Issue by 07151129** [EionRobb/skype4pidgin#330]
I'm trying to build the plugin for Adium (it uses libpurple 2.10.9), but I am not sure how to build it after changes introduced in https://github.com/EionRobb/skype4pidgin/commit/544f7a4af29f307abe40e8d217ea0adc3f60440a and further; before, `purple_init_skypeweb_plugin` symbol was defined, which was then used for plugin initialization in Adium. Now, it isn't there anymore, and so the plugin does not get initialised.

**Comment by EionRobb** [comment]
Ah. I had forgotten that adium uses static compiled plugins within the adium plugin system. Dropping the PURPLE_INIT_PLUGIN macro won't help there. 

Maybe we can add back in a static version of the purple plugin init function for adium to use. I wonder if it should be looking specific to adium though or if it should be looking for the static prpls #define

**Comment by tripplet** [comment]
Hi, It would be nice if this is working again, currently I'm not able to progress further on the adium development.

**Comment by EionRobb** [comment]
@tripplet sorry to hear that :( 
I'm afk for the next couple of days, but if you have a patch or PR that helps, I'd be happy to commit it

Would it be enough to have two definitions of the init function if one was unique or does the purple-init-plugin function need to be renamed too to prevent function name collision?

**Comment by tripplet** [comment]
@EionRobb No rush, I'm just not so familiar with the libpurple interface and code.
I copied my existing code from the old AdiumSteam project, which uses the call "purple_init_steam_plugin();"
For reference:
The last version working with in the adium plugin is c0408decd68be6796f621eac6169b826bed613b9

**Comment by EionRobb** [comment]
Latest commit should provide a  purple_init_skypeweb_plugin()  function that you could use for an Adium plugin, hopefully? :)

**Comment by 07151129** [comment]
Thanks for the update! It is working correctly now.

**Comment by rodneyrod** [comment]
Has anyone put out any binary releases of this?
I'm having trouble compiling Adium on my setup and this is preventing me from getting the plugin compiled and working.
