### ISSUE TITLE
Not a valid Win32 application?

### ISSUE THREAD

**Issue by Traediras** [EionRobb/skype4pidgin#331]
Running Pidgin Portable, loaded the libskypeweb-debug.dll into the plugins directory, and I get thrown this error when I go to activate the plugin.

>(09:50:19) plugins: probing D:\PortableApps\PidginPortable\App\Pidgin\plugins\libskypeweb-debug.dll
>(09:50:19) plugins: D:\PortableApps\PidginPortable\App\Pidgin\plugins\libskypeweb-debug.dll is not loadable: `D:\PortableApps\PidginPortable\App\Pidgin\plugins\libskypeweb-debug.dll': %1 is not a valid Win32 application.

**Comment by EionRobb** [comment]
That's very odd. It's not been marked as unsafe or blocked by Windows? Or
could it be that libjsonglib isn't in the right place? (although that would
normally give a different error)
Where did you download the dll from? Does
http://eion.robbmob.com/libskypeweb.dll work instead?

**Comment by Traediras** [comment]
Thankyou, that second .dll works.

**Comment by EionRobb** [comment]
Yeah, that's double weird. It should be the same (the debug one just has
some additional debug stuff in it)
