### ISSUE TITLE
skypeweb: no longer showing other users nicknames

### ISSUE THREAD

**Issue by omegadragon** [EionRobb/skype4pidgin#335]
im not sure what the revision was on the Version (0.1 for Windows pidgin) i had but it worked partially,  but only for the ones in the friends(contacts) list.  
it was the one out around july 7th give or take

as a example the old version would say omega but the  current plugin says omegadragon instead now.

in group chat it never really worked(friends only) but the actual skype clients(web/desktop) can pull the names for everyone in the group chat. :)

Thank you for making this plugin and for your time!
And if im being confusing let me know ill try to explain it better :)

**Comment by EionRobb** [comment]
Can you get a debug log as you connect?

**Comment by omegadragon** [comment]
Current version:
https://drive.google.com/file/d/0B0AcMZg-cGb1WmVTVXpLNVNJUmM/view?usp=sharing
Old version:
https://drive.google.com/file/d/0B0AcMZg-cGb1bjlWeWdoNF95VWc/view?usp=sharing
the group chat im in ranges from sfw to nsfw so friendly warning

**Comment by EionRobb** [comment]
The newer plugin gets contacts in a different way (to get the MSN contacts too) but it doesn't look like its doing the right request, in your case.

It's doing a request to https://contacts.skype.com/contacts/v1/users/Doom12321/contacts to get your contacts but not getting a response from the server.   I'm wondering if it shouldn't be going to that address (eg, its case-sensitive and needs to be doom12321 instead).  Can you try changing your username in Pidgin to be all lowercase and see if that helps (after an account reconnect)?

**Comment by omegadragon** [comment]
it does fix it XD i should of thought of that lol.

out of curiosity i tested with the skype client and it changed an account i made with a few capitols to all lower case :) if this is helpful.

also is group chat non friend nicknames supposed to show as well? if not im willing to help test it if you need the help. :)

**Comment by EionRobb** [comment]
I believe I fixed the original issue here a long while ago, so closing this issue :)

**Comment by WibbletheDuck** [comment]
Was just trying to set bitlbee up with this plugin, and found that group chats do not have nicknames.  It's not clear from this thread whether they ever did, so I'm not sure if this is a bug report or feature request.

I note they also don't show up in groups when using tripplet's Adium plugin, if that helps with bug hunting.

**Comment by dequis** [comment]
@WibbletheDuck open a new ticket
