### ISSUE TITLE
Unable to make

### ISSUE THREAD

**Issue by lordninjamelon** [EionRobb/skype4pidgin#338]
I'm Linux Mint 17.2 Cinnamon 64-bit. I installed libglib2.0-dev, libjson-glib-dev, libpurple-dev but I am unable to make the program. 

***
 ~/skype4pidgin $ make
i686-pc-linux-gnu-gcc -I/usr/include/libpurple -DPURPLE_PLUGINS -DENABLE_NLS -Wall -pthread `pkg-config --cflags glib-2.0` -I/usr/include -I. -g -march=athlon-xp -pipe libskype.c -o libskype.so -shared -fPIC -DPIC
/bin/sh: 1: i686-pc-linux-gnu-gcc: not found
make: *** [libskype.so] Error 127
***

**Comment by EionRobb** [comment]
Whoops, you're trying to build the wrong plugin.  You want to go into the skypeweb subfolder before doing the make

**Comment by EionRobb** [comment]
Ah yep, just double-checked we've got the right info at https://github.com/EionRobb/skype4pidgin/tree/master/skypeweb#compiling the key bit is the "cd skype4pidgin/skypeweb" :)
