### ISSUE TITLE
No longer connection over Spectrum2 (cookie/token problem)

### ISSUE THREAD

**Issue by TomTheDragon** [EionRobb/skype4pidgin#339]
I just updated the skypeweb plugin on my spectrum skype transport but i now just get errors like this:

Standard Skype account: Failed getting Skype Token
Merged MSN account: Failed getting MSPRequ cookie

Is there maybe a simple fix for this problem?

**Comment by EionRobb** [comment]
Can you get a debug log?  Did it come right after a time (eg, could be server downtime?)

**Comment by TomTheDragon** [comment]
Hm.. i got it to work again, by copying the certificates from my desktop installation, over to the spectrum folder on my server. But i think this will be only a temporary solution.

**Comment by rugabunda** [comment]
I had this problem with a router ad blocker with pixelsrv-tls, i had disabled blocking and it persisted, until I had cleared windows dns cache in acrylic.
