### ISSUE TITLE
Pidgin crashes at fresh launch.

### ISSUE THREAD

**Issue by Toqozz** [EionRobb/skype4pidgin#340]
STR:

- boot pc
- start pidgin
- pidgin launches skype
- pidgin tries to sign into skype
- crash

After that, restarting pidgin and signing into skype works fine.  Sounds like skype is not starting fast enough to me.

**Comment by Toqozz** [comment]
Sigh... I cannot get the issue to reproduce for gdp.

I only switched to using pidgin-light instead.

**Comment by EionRobb** [comment]
Is that using the old Skype plugin or the newer sjypeweb plugin (which doesn't need Skype running).?

**Comment by EionRobb** [comment]
Oh yeah, that definitely sounds like the old plugin. Try the new one and see how you get on :)

**Comment by Toqozz** [comment]
Seems good, thank you.
