### ISSUE TITLE
Skype hangs after short period of time

### ISSUE THREAD

**Issue by Squire136** [EionRobb/skype4pidgin#341]
On Windows 10, start Pidgin 2.10.11, Skype 7.8.0.102 with addon:
Skype
	Author: Eion Robb <eion@robbmob.com>
	Version: 2.0
	Website: http://eion.robbmob.com/
	ID String: prpl-bigbrownchunx-skype
	Loadable: Yes
	Loaded: Yes

Lock the desktop without logging out of Windows, return some time later, log into Windows, open Skype, try to interact with it in any way, it displays "Not Responding" and you have to terminate it forcefully and restart it.

**Comment by EionRobb** [comment]
Want to try with the newer skypeweb plugin instead (that doesn't need Skype running)

**Comment by Squire136** [comment]
I have an MS Live account (live:username) so the HTTP plugin doesn't appear to work right now.

**Comment by EionRobb** [comment]
As long as you login with an email address that should be fine

**Comment by Squire136** [comment]
Thanks, that worked (after I figured out I had to log into login.live.com manually to get past a security check they were doing).


I appreciate the quick response and assistance.

**Comment by EionRobb** [comment]
Nice one :)
