### ISSUE TITLE
Pidgin 2.10.11 has segfaulted and attempted to dump a core file.

### ISSUE THREAD

**Issue by grinapo** [EionRobb/skype4pidgin#342]
Yeah, I know, not very descriptive title but I cannot connect it to anything: from time to time pidgin crashes and last messages are always shyte ones. Erm. I mean skype, of course. ;-)

(20:43:23) skype: Sending: '#9 NAME Pidgin'
(20:43:23) skype: Received: #9 OK
(20:43:23) skype: Sending: '#10 PROTOCOL 7'
(20:43:23) skype: Received: #10 PROTOCOL 7
(20:43:23) skype: Sending: 'SET SILENT_MODE ON'
(20:43:23) skype: Sending: 'MINIMIZE'
(20:43:23) skype: Sending: 'SET USERSTATUS AWAY'
(20:43:23) skype: Sending: 'SET PROFILE MOOD_TEXT I'm not here right now'
(20:43:23) skype: Sending: 'CREATE APPLICATION libpurple_typing'
(20:43:23) skype: Received: CONNSTATUS ONLINE
(20:43:23) skype: Received: USERSTATUS AWAY
(20:43:23) skype: Received: CURRENTUSERHANDLE grinapo
(20:43:23) skype: Received: ERROR 18 SET: invalid WHAT
(20:43:23) skype: Sending: '#11 GET SKYPEVERSION'
(20:43:23) skype: Received: USERSTATUS AWAY
(20:43:23) skype: Received: OK
(20:43:23) skype: Received: PROFILE MOOD_TEXT I'm not here right now
(20:43:23) skype: Received: CREATE APPLICATION libpurple_typing
Pidgin 2.10.11 has segfaulted and attempted to dump a core file.
This is a bug in the software and has happened through

[I'll start an instance under gdb and see what happens, this no-stack-trace is not very useful. :-(]

**Comment by EionRobb** [comment]
Don't suppose you'd care to try the newer skypeweb plugin that doesn't connect to a running skype to work?

**Comment by EionRobb** [comment]
I'll assume that things are working ok with the SkypeWeb plugin instead? :)
