### ISSUE TITLE
Impossible to download the Windows builds

### ISSUE THREAD

**Issue by Hexalyse** [EionRobb/skype4pidgin#344]
The server hosting the Windows .dll (http://eion.robbmob.com/libskypeweb-debug.dll) and .exe installer returns a "time out" error.

**Comment by EionRobb** [comment]
Apologies, power went out, ups failed. I'm currently in hospital but when I'm out I'll get the server back up and running again. 

Might be time for me to do a github release, right? :)

**Comment by Hexalyse** [comment]
Ok, no problem ! Take care.

And yes, a github release would be a great idea, I searched for one, but was sad to see none :stuck_out_tongue:

**Comment by EionRobb** [comment]
Should be back up and running now. Let me know if you're still having issues :)
