### ISSUE TITLE
libjson-glib-1.0.dll and https://github.com/jgeboski/purple-facebook

### ISSUE THREAD

**Issue by Kvasi** [EionRobb/skype4pidgin#345]
The version of libjson-glib-1.0.dll in the installer is not compatible with the facebook addon. However the libjson-glib-1.0.dll in the facebook addon is compatible with skypeweb.

**Comment by EionRobb** [comment]
Yep, that sounds about right. The Facebook plugin used version 0.14.0 of json-glib whereas the Skype plugin only needs 0.8.0, which is what is included.

**Comment by alexolog** [comment]
There are other plugins that require, and often supply, libjson-glib-1.0.dll which leads to incompatibilities.  For example, F-List.

I think it would be better for the main package to include the latest version (at the time of the release)

**Comment by EionRobb** [comment]
@alexolog I believe I've updated json-glib in the skype plugin as of version 1.2

**Comment by alexolog** [comment]
I meant that it should be a part of the core pidgin

**Comment by EionRobb** [comment]
Oh, well it is part of core Pidgin as of Pidgin 3.0
