### ISSUE TITLE
Skypeweb doesn't correctly handle messages sent from canonical Skype client

### ISSUE THREAD

**Issue by redyoshi49q** [EionRobb/skype4pidgin#348]
The following behavior was seen from a version of the plugin that was downloaded on August 23, but I haven't seen any bug reports on this since then.

My username is on my own contact list from Skypeweb's perspective (the canonical Skype client doesn't have me listed in my own contacts list).  If I use the canonical Skype client to chat with another user while Skypeweb isn't connected and later connect with Skypeweb, messages that the other user sent to me will appear as having been sent from that person (as expected), but messages that I sent them will appear as if I had instead sent them to myself (in a separate chat window).  For instance, if I send message to Bob on the canonical Skype client, Skypeweb displays those messages as if I had sent them to myself.

My guess is that messages that the logged in user sent from another client are being associated with the sender's conversation rather than the conversation of the party other than that of the logged in user.

**Comment by EionRobb** [comment]
The plugin should be handling that, yeah. Are you able to get a debug log when that happens? I'm wondering if Skype doesn't send through the conversation retails any more, or in wondering if it's something to do with it no relapsing which username is yours? Do you log in to Skype with an email address or a Skype username?

**Comment by redyoshi49q** [comment]
I log in with a Skype username on both clients.

I've created a debug log (filtered for the string "skype"), which is viewable [here](https://gist.github.com/redyoshi49q/bf7befdeaf5c1b609ab6).  I did the following things while recording:
* Log out of Skypeweb
* Send a message to a contact
* Log back in

**Comment by EionRobb** [comment]
Can you give a hint as to what the body of the message was that you sent appeared to be sent to yourself? :)   (just having trouble looking for the needle in the haystack there)

**Comment by EionRobb** [comment]
Ah found it.  "don't mind me" at (16:48:49)

**Comment by redyoshi49q** [comment]
The "don't mind me" message was the message I sent for the purposes of this bug report.  My apologies for not quoting the message here (which, in retrospect, would have been the smart thing to do).

It seems that Skypeweb re-requests a **ton** of data that it has already read on a previous login (which is why I'm guessing there's so much data in that transcript, even though the time span between logging out and logging back in again is only a handful of minutes).  I don't know whether this is expected behavior (i.e., an established aspect of the Skype protocol) or not.

Would it help you to also have a debug log of a message that I send through Pidgin, or would that information not be relevant to your process of diagnosis?

**Comment by EionRobb** [comment]
The debug is looking pretty normal.  We do a check in https://github.com/EionRobb/skype4pidgin/blob/master/skypeweb/skypeweb_messages.c#L335 to make sure the message isn't from ourselves, so I'm a little bit at a loss as to why you're receiving your own message like that.  I'll keep digging....

**Comment by redyoshi49q** [comment]
It looks like the if block you linked to is not returning true, even when it should be.  Are `sa->username` and `from` being compared in the same format?  It might be comparing "redyoshi49q" (`sa->username`) with "8:redyoshi49q" (the data at the end of the `from` data field in the debug log's relevant blip).

**Comment by EionRobb** [comment]
Want to give a try with that latest commit?  I've heard from another user that it's making things a lot better :)

**Comment by redyoshi49q** [comment]
Indeed, the bug I described has been fixed as of the referencing commit.  Apparently, my hypothesis as to what the issue was is wrong, and moreover, I'm still trying to figure out exactly what the bug was after having looked at the diff.

Thanks for fixing it, though.

**Comment by EionRobb** [comment]
There's potential that the username you've logged in with doesn't match the exact format of what the server thinks you've got.  If there's any uppercase letters in your username or if you login with one user and it's merged in with another then it'll be getting confused.

The previous commits to that one also made sure things happened in the correct order to ensure we had the server-side username fetched before we try to do any offline message processing and buddy list fetching, etc :)

Glad to hear it's working for you now.  Thanks for posting feedback :)
