### ISSUE TITLE
Skype users don't see animated smilies

### ISSUE THREAD

**Issue by Ghabry** [EionRobb/skype4pidgin#350]
When I use skype4pidgin (the new skypeweb version) and send Smilies like ":D", "(rofl)" or "(headbang)" the user of a real skype client (skypeweb in the webbrowser e.g.) sees only the texts representing the smilies instead of the replaced, animated smilies.

Only a minor issue but would nice to get it resolved :)

**Comment by vitalyster** [comment]
same here

**Comment by Ghabry** [comment]
By looking at skypeweb it seems to send links and smilies in the following way:

Links: You send "www.github.com", it sends "<a href
=\"http://www.github.com\">www.github.com</a>"

Smilies: You send ":D (headbang)", it sends "<ss type=\"laugh\">:D</ss> <ss type=\"headbang\">(headbang)</ss>"

**Comment by EionRobb** [comment]
Not quite sure what to do here since different Skype UI's will display these in different ways, and trying to do it without a big lookup table would be ideal (especially since the smilies can change).  Hmm...

**Comment by Ghabry** [comment]
We are lucky. Skype fixed this in the meanwhile for us :+1:
