### ISSUE TITLE
Tell the user that a file was sent

### ISSUE THREAD

**Issue by rafzi** [EionRobb/skype4pidgin#355]
In the official web client it tells the user:

>Receiving files over P2P network is not supported on Skype for Web

This is very useful, to tell the other person he should send it over a different channel. Without this notification it sometimes leads to confusing interaction and lost information.

**Comment by EionRobb** [comment]
Good idea :)

**Comment by EionRobb** [comment]
I think I've fixed this in https://github.com/EionRobb/skype4pidgin/commit/416fee02b3d785acd3c70f98c0733338c85330ed
