### ISSUE TITLE
No message when someone trys to add you?

### ISSUE THREAD

**Issue by TomTheDragon** [EionRobb/skype4pidgin#361]
You normally can enter a message for the other buddy, if you going to add him to your buddylist, so that he know who you are or why you want to add him.
I just noticed that i cant see this kind of massage on Pidgin and its kind of strange if someone adds you and you dont get any kind of information about him.
I was just wondering if this is a limit of the plugin or Skypeweb itself.

**Comment by TomTheDragon** [comment]
I actually never did take a closer look to that massage.. does it also show a custom massage if someone types one in?

**Comment by EionRobb** [comment]
Yeah, it does :)
