### ISSUE TITLE
Add source archive

### ISSUE THREAD

**Issue by xvitaly** [EionRobb/skype4pidgin#363]
Add source archive to releases. It can be downloaded as https://github.com/EionRobb/skype4pidgin/archive/v1.0.tar.gz. Save it as skype4pidgin-1.0.tar.gz and upload into releases.

**Comment by EionRobb** [comment]
Ah, the 1.0 release is at
https://github.com/EionRobb/skype4pidgin/releases
That old releases folder was a workaround for Google code not providing any download space, and needs to be cleared out.

**Comment by xvitaly** [comment]
Download this https://github.com/EionRobb/skype4pidgin/archive/v1.0.tar.gz and then upload it with name skype4pidgin-1.0.tar.gz into release v1.0.

**Comment by EionRobb** [comment]
That's for the old skype4pidgin plugin not the newer skypeweb plugin

**Comment by xvitaly** [comment]
It contains all contents of GitHub repository (on tag v1.0) including new skypeweb plugin in skypeweb directory.

**Comment by EionRobb** [comment]
Oic, yeah you're right, I got confused with the steam plugin that has a similar but different setup. 

I'm confused though, you're saying there's already a tarball and you want a tarball?

**Comment by xvitaly** [comment]
> I'm confused though, you're saying there's already a tarball and you want a tarball?

We need tarball with name skype4pidgin-1.0.tar.gz. :-)
