### ISSUE TITLE
Unsent messages

### ISSUE THREAD

**Issue by kaptoxic** [EionRobb/skype4pidgin#366]
This issue was bugging me for a longer period of time. Sometimes (i.e. usually) when I initiate a conversation from pidgin, the recipient does not get my messages. Afterwards, if I look at the actual Skype conversation there is a warning next to the message saying ```Not delivered yet```.
Once I write something in the same conversation in Skype, the following messages from pidgin start to get through.
This was happening to me with both Skype and "D-bus" alternatives.

**Comment by EionRobb** [comment]
Is this with the old skype4pidgin plugin or the newer skypeweb plugin (which doesn't need skype running)?

**Comment by kaptoxic** [comment]
I believe it is the old one then (I installed this package [AUR package](https://aur.archlinux.org/packages/skype4pidgin-git)). Should I use skypeweb plugin? (I was not aware of it; cool, so the new one does not even need skype running.)

**Comment by EionRobb** [comment]
Glad you found the new plugin :)  Please reopen if it's still happening.
