### ISSUE TITLE
Buddys List

### ISSUE THREAD

**Issue by SouKisto** [EionRobb/skype4pidgin#367]
How can i change my Idle buddy list to be like Online for example:

![2015-12-09_3-57-58](https://cloud.githubusercontent.com/assets/16037472/11674393/328f2006-9e29-11e5-852d-5161826690f0.png)

I want to make my Idle buddys like online just with a orange icon for example.
I'm also trying to Hide offline buddys and show only online and idle but can't do that. if anyone knows that please reply.

**Comment by EionRobb** [comment]
To hide offline buddies, try:
Buddies->Show->Offline buddies

To change how idle buddies look, you'll need to set a new status icon theme in Pidgin, the plugin has no control over how to display those type of users
