### ISSUE TITLE
skypeweb archlinux install instructions

### ISSUE THREAD

**Issue by arnottcr** [EionRobb/skype4pidgin#369]
I have made an aur package for a simplified archlinux install; are you willing to add this to your README's building section for skypeweb: https://aur.archlinux.org/packages/purple-skypeweb

**Comment by EionRobb** [comment]
Sure, send through a PR for 'how to install' or something and i'll consider it! :)

**Comment by arnottcr** [comment]
yeah, no problem I will get on it; you mind if I leave this issue open till I submit my pull?

**Comment by EionRobb** [comment]
can do :)

**Comment by ceribik** [comment]
Note that there already is an AUR package for this: https://aur.archlinux.org/packages/purple-skypeweb-git

**Comment by arnottcr** [comment]
Yes, I actually used that package as a template; mine is built against the v1.0 release, as *-git packages are not intended for regular use: https://wiki.archlinux.org/index.php/Arch_User_Repository#What_is_the_difference_between_foo_and_foo-git_packages.3F


On 16 December 2015 07:55:49 UTC, ceribik <notifications@github.com> wrote:
>Note that there already is an AUR package for this:
>https://aur.archlinux.org/packages/purple-skypeweb-git
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/EionRobb/skype4pidgin/issues/369#issuecomment-165026058

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by EionRobb** [comment]
Any updates on this? :)

**Comment by arnottcr** [comment]
should be done; I am embarrassed at how long I forgot about this issue compared with how little time it took. let me know if you would like me to change any formatting.
