### ISSUE TITLE
Login error: Failed getting Skype Token

### ISSUE THREAD

**Issue by AlmightyFrog** [EionRobb/skype4pidgin#373]
As of Ticket #264 was closed and per request as problem still exists here a new Ticket.
I can't login to my (years old, not @outlook one) Skype account:
> <root> skypeweb - Logging in: Connecting
> <root> skypeweb - Logging in: Authenticating
> <root> skypeweb - Login error: Failed getting Skype Token
> <root> skypeweb - Logging in: Signing off..

Running on Linux:
>  dpkg -s skypeweb
> Version: 0.1.0
> Depends: libc6 (>= 2.14), libglib2.0-0 (>= 2.24.0), libjson-glib-1.0-0 (>= 0.12.0), libpurple0 (>= 1:2.6.0), libpurple0 (>= 2.10.11), libglib2.0-0 (>= 2.31.8), libjson-glib-1.0-0 (>= 0.14.2)

>  dpkg -s bitlbee-libpurple
> Version: 3.2.1+otr4-1ubuntu0.2
> Depends: libc6 (>= 2.14), libgcrypt11 (>= 1.4.5), libglib2.0-0 (>= 2.24.0), libgnutls26 (>= 2.12.17-0), libpurple0 (>= 1:2.6.0), debianutils (>= 1.16), bitlbee-common (= 3.2.1+otr4-1ubuntu0.2)

**Comment by EionRobb** [comment]
Can you try with 1.0 of the skypeweb plugin?

**Comment by AlmightyFrog** [comment]
Don't exactly know how to update to 1.0 ov skypeweb but problem got solved by updating bitlbee-libpurple to newest version 3.4.1+20151216+master+120-gd11ccbf-git
So ticket can be closed, please excuse interruption @EionRobb.
