### ISSUE TITLE
More skypeweb crash

### ISSUE THREAD

**Issue by manavortex** [EionRobb/skype4pidgin#380]
DEBUG account: Connecting to account a@b.de.
DEBUG connection: Connecting. gc = 0x7fa14ddad1a0
DEBUG util: requesting to fetch a URL
DEBUG dnsquery: Performing DNS lookup for login.skype.com
DEBUG dns: Wait for DNS child 3529 failed: No child processes
DEBUG dns: Created new DNS child 8702, there are now 1 children.
DEBUG dns: Successfully sent DNS request to child 8702
DEBUG dns: Got response for 'login.skype.com'
DEBUG dnsquery: IP resolved for login.skype.com
DEBUG proxy: Attempting connection to 91.190.218.34
DEBUG proxy: Connecting to login.skype.com:443 with no proxy
DEBUG proxy: Connection in progress
DEBUG proxy: Connecting to login.skype.com:443.
DEBUG proxy: Connected to login.skype.com:443.
DEBUG nss: SSL version 3.3 using 256-bit AES with 160-bit SHA1 MAC
Server Auth: 2048-bit RSA, Key Exchange: 2048-bit RSA, Compression: NULL
Cipher Suite Name: TLS_RSA_WITH_AES_256_CBC_SHA
DEBUG nss: subject=CN=login.skype.com,O=Skype,L=Dublin,C=IE issuer=CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US
DEBUG nss: subject=CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US issuer=CN=Baltimore CyberTrust Root,OU=CyberTrust,O=Baltimore,C=IE
DEBUG nss: subject=CN=Baltimore CyberTrust Root,OU=CyberTrust,O=Baltimore,C=IE issuer=CN=Baltimore CyberTrust Root,OU=CyberTrust,O=Baltimore,C=IE
DEBUG certificate/x509/tls_cached: Starting verify for login.skype.com
DEBUG certificate/x509/tls_cached: Checking for cached cert...
DEBUG certificate/x509/tls_cached: ...Found cached cert
DEBUG nss/x509: Loading certificate from /var/lib/bitlbee//purple/manavortex/certificates/x509/tls_peers/login.skype.com
DEBUG certificate/x509/tls_cached: Peer cert matched cached
DEBUG nss/x509: Exporting certificate to /var/lib/bitlbee//purple/manavortex/certificates/x509/tls_peers/login.skype.com
DEBUG util: Writing file /var/lib/bitlbee//purple/manavortex/certificates/x509/tls_peers/login.skype.com
DEBUG nss: Trusting CN=login.skype.com,O=Skype,L=Dublin,C=IE
DEBUG certificate: Successfully verified certificate for login.skype.com
DEBUG util: request constructed
DEBUG util: Response headers: 'HTTP/1.1 302 Found
Server: nginx
Date: Fri, 01 Jan 2016 15:03:44 GMT
Content-Type: text/html
Content-Length: 0
Connection: keep-alive
Set-Cookie: SC=CC=:CCY=:LC=en:LIM=:TM=1451660624:TS=1451660624:TZ=:VAT=:VER=; expires=Sat, 31-Dec-2016 15:03:44 GMT; Max-Age=31536000; path=/; domain=.skype.com
X-Stratus-Processing-Time: 0.0222
X-Skype-Request-Id: 4c4c40bf
X-Stratus-Request-Id: 4c4c40bf
Pragma: no-cache
Cache-Control: no-store, no-cache, must-revalidate
Expires: Thu, 01 Jan 1970 00:00:01 +0000
P3P: CP="CAO PSA OUR"
Location: https://login.live.com/login.srf?wa=wsignin1.0&rpsnv=12&ct=1451660624&rver=6.6.6577.0&wp=MBI_SSL&wreply=https:%2F%2Flw.skype.com%2Flogin%2Foauth%2Fproxy%3Fclient_id%3D578134%26redirect_uri%3Dhttps%253A%252F%252Fweb.skype.com%26site_name%3Dlw.skype.com&lc=1033&id=293290&mkt=en
X-Stratus-Config-Namespace:
X-Content-Type-Options: nosniff
X-Processing-Time: 0.027
Strict-Transport-Security: max-age=31536000; includeSubDomains

'
DEBUG util: Redirecting to  https://login.live.com/login.srf?wa=wsignin1.0&rpsnv=12&ct=1451660624&rver=6.6.6577.0&wp=MBI_SSL&wreply=https:%2F%2Flw.skype.com%2Flogin%2Foauth%2Fproxy%3Fclient_id%3D578134%26redirect_uri%3Dhttps%253A%252F%252Fweb.skype.com%26site_name%3Dlw.skype.com&lc=1033&id=293290&mkt=en
DEBUG dnsquery: Performing DNS lookup for login.live.com
DEBUG dns: Successfully sent DNS request to child 8702
DEBUG dns: Got response for 'login.live.com'
DEBUG dnsquery: IP resolved for login.live.com
DEBUG proxy: Attempting connection to 131.253.61.82
DEBUG proxy: Connecting to login.live.com:443 with no proxy
DEBUG proxy: Connection in progress
DEBUG proxy: Connecting to login.live.com:443.
DEBUG proxy: Connected to login.live.com:443.
DEBUG nss: SSL version 3.3 using 256-bit AES with 160-bit SHA1 MAC
Server Auth: 2048-bit RSA, Key Exchange: 521-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
DEBUG nss: subject=CN=gateway.login.live.com,OU=Passport,O=Microsoft Corporation,STREET=1 Microsoft Way,L=Redmond,ST=Washington,postalCode=98052,C=US,serialNumber=600413485,businessCategory=Private Organization,incorporationState=Washington,incorporationCountry=US issuer=CN=Symantec Class 3 EV SSL CA - G3,OU=Symantec Trust Network,O=Symantec Corporation,C=US
DEBUG nss: subject=CN=Symantec Class 3 EV SSL CA - G3,OU=Symantec Trust Network,O=Symantec Corporation,C=US issuer=CN=VeriSign Class 3 Public Primary Certification Authority - G5,OU="(c) 2006 VeriSign, Inc. - For authorized use only",OU=VeriSign Trust Network,O="VeriSign, Inc.",C=US
DEBUG nss: subject=CN=VeriSign Class 3 Public Primary Certification Authority - G5,OU="(c) 2006 VeriSign, Inc. - For authorized use only",OU=VeriSign Trust Network,O="VeriSign, Inc.",C=US issuer=CN=VeriSign Class 3 Public Primary Certification Authority - G5,OU="(c) 2006 VeriSign, Inc. - For authorized use only",OU=VeriSign Trust Network,O="VeriSign, Inc.",C=US
DEBUG certificate/x509/tls_cached: Starting verify for login.live.com
DEBUG certificate/x509/tls_cached: Checking for cached cert...
DEBUG certificate/x509/tls_cached: ...Found cached cert
DEBUG nss/x509: Loading certificate from /var/lib/bitlbee//purple/manavortex/certificates/x509/tls_peers/login.live.com
DEBUG certificate/x509/tls_cached: Peer cert matched cached
DEBUG nss/x509: Exporting certificate to /var/lib/bitlbee//purple/manavortex/certificates/x509/tls_peers/login.live.com
DEBUG util: Writing file /var/lib/bitlbee//purple/manavortex/certificates/x509/tls_peers/login.live.com
DEBUG nss: Trusting CN=gateway.login.live.com,OU=Passport,O=Microsoft Corporation,STREET=1 Microsoft Way,L=Redmond,ST=Washington,postalCode=98052,C=US,serialNumber=600413485,businessCategory=Private Organization,incorporationState=Washington,incorporationCountry=US
DEBUG certificate: Successfully verified certificate for login.live.com
DEBUG util: request constructed
DEBUG util: Response headers: 'HTTP/1.1 200 OK
Cache-Control: max-age=0
Content-Length: 9518
Content-Type: text/html; charset=utf-8
Expires: Fri, 01 Jan 2016 15:02:44 GMT
Server: Microsoft-IIS/8.5
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
X-XSS-Protection: 0
X-Content-Type-Options: nosniff
Set-Cookie: MSPRequ=lt=1451660624&co=1&id=293290; secure= ;path=/;HTTPOnly=;version=1
Set-Cookie: MSPOK=$uuid-bc061dc0-7ef6-46b5-ad9b-daa0d380cbae; domain=login.live.com;secure= ;path=/;HTTPOnly= ;version=1
X-Frame-Options: deny
X-Content-Type-Options: nosniff
Date: Fri, 01 Jan 2016 15:03:44 GMT
Connection: close

'
DEBUG util: parsed 9518
DEBUG util: requesting to fetch a URL
DEBUG dnsquery: Performing DNS lookup for login.live.com
DEBUG dns: Successfully sent DNS request to child 8702
DEBUG dns: Got response for 'login.live.com'
DEBUG dnsquery: IP resolved for login.live.com
DEBUG proxy: Attempting connection to 131.253.61.82
DEBUG proxy: Connecting to login.live.com:443 with no proxy
DEBUG proxy: Connection in progress
DEBUG proxy: Connecting to login.live.com:443.
DEBUG proxy: Connected to login.live.com:443.
DEBUG nss: SSL version 3.3 using 256-bit AES with 160-bit SHA1 MAC
Server Auth: 2048-bit RSA, Key Exchange: 521-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
DEBUG nss: subject=CN=gateway.login.live.com,OU=Passport,O=Microsoft Corporation,STREET=1 Microsoft Way,L=Redmond,ST=Washington,postalCode=98052,C=US,serialNumber=600413485,businessCategory=Private Organization,incorporationState=Washington,incorporationCountry=US issuer=CN=Symantec Class 3 EV SSL CA - G3,OU=Symantec Trust Network,O=Symantec Corporation,C=US
DEBUG nss: subject=CN=Symantec Class 3 EV SSL CA - G3,OU=Symantec Trust Network,O=Symantec Corporation,C=US issuer=CN=VeriSign Class 3 Public Primary Certification Authority - G5,OU="(c) 2006 VeriSign, Inc. - For authorized use only",OU=VeriSign Trust Network,O="VeriSign, Inc.",C=US
DEBUG nss: subject=CN=VeriSign Class 3 Public Primary Certification Authority - G5,OU="(c) 2006 VeriSign, Inc. - For authorized use only",OU=VeriSign Trust Network,O="VeriSign, Inc.",C=US issuer=CN=VeriSign Class 3 Public Primary Certification Authority - G5,OU="(c) 2006 VeriSign, Inc. - For authorized use only",OU=VeriSign Trust Network,O="VeriSign, Inc.",C=US
DEBUG certificate/x509/tls_cached: Starting verify for login.live.com
DEBUG certificate/x509/tls_cached: Checking for cached cert...
DEBUG certificate/x509/tls_cached: ...Found cached cert
DEBUG nss/x509: Loading certificate from /var/lib/bitlbee//purple/manavortex/certificates/x509/tls_peers/login.live.com
DEBUG certificate/x509/tls_cached: Peer cert matched cached
DEBUG nss/x509: Exporting certificate to /var/lib/bitlbee//purple/manavortex/certificates/x509/tls_peers/login.live.com
DEBUG util: Writing file /var/lib/bitlbee//purple/manavortex/certificates/x509/tls_peers/login.live.com
DEBUG nss: Trusting CN=gateway.login.live.com,OU=Passport,O=Microsoft Corporation,STREET=1 Microsoft Way,L=Redmond,ST=Washington,postalCode=98052,C=US,serialNumber=600413485,businessCategory=Private Organization,incorporationState=Washington,incorporationCountry=US
DEBUG certificate: Successfully verified certificate for login.live.com
DEBUG util: request constructed
DEBUG util: Response headers: 'HTTP/1.1 200 OK
Cache-Control: max-age=0
Content-Length: 9225
Content-Type: text/html; charset=utf-8
Expires: Fri, 01 Jan 2016 15:02:45 GMT
Server: Microsoft-IIS/8.5
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
X-XSS-Protection: 0
X-Content-Type-Options: nosniff
Set-Cookie: MSPOK= ; expires=Thu, 30-Oct-1980 16:00:00 GMT;domain=login.live.com;path=/;HTTPOnly= ;version=1
Set-Cookie: MSPOK=$uuid-bc061dc0-7ef6-46b5-ad9b-daa0d380cbae$uuid-008778e6-7d07-4420-a3b9-370cb7c47b89; domain=login.live.com;secure= ;path=/;HTTPOnly= ;version=1
X-Frame-Options: deny
X-Content-Type-Options: nosniff
Date: Fri, 01 Jan 2016 15:03:44 GMT
Connection: close

'
DEBUG util: parsed 9225

*\* (process:28519): CRITICAL *_: skypeweb_string_get_chunk: assertion 'chunk_start' failed
DEBUG connection: Connection error on 0x7fa14ddad1a0 (reason: 2 description: Failed getting Magic T value)
DEBUG account: Disconnecting account a@b.de (0x7fa14db26e60)
DEBUG connection: Disconnecting connection 0x7fa14ddad1a0
DEBUG skypeweb: getting url /logout
DEBUG skypeweb: sending headers:
GET /logout HTTP/1.0
Host: login.skype.com
Connection: close
Accept: */_
Cookie:
Accept-Encoding: gzip
Accept-Language: en-GB.UTF-8, en-GB, en.UTF-8, en, C

Please let me know what you need for debugging this further. :)

**Comment by EionRobb** [comment]
That's not a crash, it just can't login :) 
Can you double check you password and try logging into web.skype.com with your browser?

**Comment by manavortex** [comment]
Hi, 
I triple-checked all of these. :)

**Comment by EionRobb** [comment]
And it logged in via your browser without problem?

**Comment by EionRobb** [comment]
Oh, you're using bitlbee?  Are you logging in to the account with a browser on the same machine where you run bitlbee, because you might be tripping a captcha or something from running it on a different IP

**Comment by manavortex** [comment]
Yes, I've been using bitlbee, and I've SSH-tunneled my browser to that machine to log in from web browser, so it'd be the same IP. It's a headless Ubuntu Vserver, so I've been sort of struggling to get a browser working. :D

**Comment by EionRobb** [comment]
Sorry that it's taken so long to respond to this.  If it's still a problem, can you reopen this issue
