### ISSUE TITLE
group conversations missing

### ISSUE THREAD

**Issue by veritas1980** [EionRobb/skype4pidgin#383]
I was in a couple group conversations on skype, but they don't show in pidgin.

**Comment by EionRobb** [comment]
I should really make an FAQ section, yeah?

The old P2P group chats (i.e. chats created from more than 2 years ago) don't work with this plugin, but it does work with the newer cloud-backed Threads.  You can use the /fork command in the old client to recreate the group chat as a thread.

See https://github.com/EionRobb/skype4pidgin/issues/298 for more info.

**Comment by veritas1980** [comment]
I am already in existing rooms with many people that show on my phone, but do not show in my pidgin for windows. Can I make this work with my latest version pidgin and plugin?

**Comment by EionRobb** [comment]
Try using the /fork command.

**Comment by veritas1980** [comment]
I am not entirely sure where I would input such a command, please forgive my neophyte status.

**Comment by EionRobb** [comment]
http://community.skype.com/t5/Skype-for-Web-Beta/Legacy-group-chat-support-on-Skype-for-Web-Beta/m-p/3828350/highlight/true#M47 has the info about it

Run /fork in a client that can see the legacy chats and it will recreate it as a thread for new Skype things (including the plugin) to see it

**Comment by veritas1980** [comment]
didn't seem to help.

**Comment by EionRobb** [comment]
Do they show up in Tools->Room List (don't forget to pick the Skype account then press the Get List button at the bottom)

**Comment by veritas1980** [comment]
Its all lines of Hash, I can't tell which it is.

**Comment by EionRobb** [comment]
Try using the 'topic' column to work out which one it is, otherwise, just add them all to your buddy list and see

**Comment by veritas1980** [comment]
that helped, but the one I split off isnt there that I can see
