### ISSUE TITLE
Linux version missing

### ISSUE THREAD

**Issue by EasyAs123** [EionRobb/skype4pidgin#384]
In the latest 1.1 release there was no .so file included for linux users. I don't know if this was intentional or not but unfortunately it means linux users have to use the old 1.0 version unless they're in an environment where they can compile it themselves.

Anyway, thank you very much for your hard work.

**Comment by xvitaly** [comment]
@EasyAs123 Build it from source code.

**Comment by EionRobb** [comment]
@EasyAs123 that .so caused more confusion than it solved, since it was just a 32-bit only .so :)
These days, you should be able to grab the package from your distro's repo or as a last resort, compile it yourself.
