### ISSUE TITLE
Failed to find Pidgin installation (windows 7) Version 1.1

### ISSUE THREAD

**Issue by dignityinside** [EionRobb/skype4pidgin#387]
Can't install on Windows 7. 

"Failed to find Pidgin installation".

Pidgin is installed in: "C:\Users<username>\AppData\Roaming\Microsoft\Windows\Pidgin" (default install path).

**Comment by xvitaly** [comment]
> \AppData\Roaming\Microsoft\Windows\Pidgin" (default install path).

Default install path is %PROGRAMFILES%\Pidgin\ or %PROGRAMFILES(x86)%\Pidgin\.

**Comment by dignityinside** [comment]
Sorry, but no. pidgin-2.10.12 install by default to: "C:\Users\<username>\AppData\Roaming\Microsoft\Windows\Pidgin" and not to %PROGRAMFILES%\Pidgin\ (x86-32) or %PROGRAMFILES(x86)%\Pidgin\ (x86_64). Maybe you add a funtion, to select the path, where pidgin are installed, when your plugin can't find this one.

**Comment by EionRobb** [comment]
You've installed pidgin into the user folder instead of system wide. You can install pidgin system wide by right clicking on the pidgin installer and choosing to "Run as Administrator"

I'll see if its possible at all to pick up on a user install of Pidgin in the registry

**Comment by nurps** [comment]
What if I don't want it system wide, fix your installer.
