### ISSUE TITLE
File transfer not working

### ISSUE THREAD

**Issue by d3str0y3r** [EionRobb/skype4pidgin#393]
I tried to send a file from the official Skype client to Pidgin (with skypeweb) without luck.

Logfile: http://pastebin.com/aaVzDB5M

Pidgin v2.10.12
Plugin v1.1
Windows 10 x64
Skype client v7.18.85.103

**Comment by EionRobb** [comment]
Unfortunately the plugin can't receive P2P files like that, only files uploaded via the skypeweb service
