### ISSUE TITLE
"Known as" spam in chat window and logs

### ISSUE THREAD

**Issue by xvitaly** [EionRobb/skype4pidgin#394]
Is it possible to permanently disable "known as" spam in chat window and chat logs?

```
(18:09:56) $LOGIN now known as $USERNAME.
(18:10:00) $LOGIN now known as $USERNAME.
(18:10:04) $LOGIN now known as $USERNAME.
(18:10:08) $LOGIN now known as $USERNAME.
(18:10:15) $LOGIN now known as $USERNAME.
(18:10:22) $LOGIN now known as $USERNAME.
(18:10:26) $LOGIN now known as $USERNAME.
(18:10:32) $LOGIN now known as $USERNAME.
```

$LOGIN - Skype login and $USERNAME - nickname.

**Comment by sjpengelly** [comment]
There is a Pidgin plugin that provides this functionality, which can be found here:

https://github.com/EionRobb/pidgin-ignore-nickchange

**Comment by xvitaly** [comment]
> There is a Pidgin plugin that provides this functionality, which can be found here:

**Comment by EionRobb** [comment]
Yep this is definitely possible to do, I've done this in other prpls too.  Just need to check if the alias is actually different before re-setting it.

**Comment by sjpengelly** [comment]
>It hides name changes in multi-user conferences, not chats
In the configuration, you are able to set the minimum number of users in the group chat for which the filtering will activate, and 1 is an acceptable value. It also filters notifications from single users you have not spoken to within the last X minutes (also configurable).

**Comment by EionRobb** [comment]
@sjpengelly nah, that plugin only works with chat messages not IM messages (although adding IM support to it could be quite handy).  The SkypeWeb plugin needs to be updated to ignore the alias update if it's the same alias

**Comment by xvitaly** [comment]
> The SkypeWeb plugin needs to be updated to ignore the alias update if
it's the same alias

It would be great.

**Comment by TETYYS** [comment]
Still occurs

**Comment by alex3kov** [comment]
@EionRobb 
> The SkypeWeb plugin needs to be updated to ignore the alias update if it's the same alias
That would be awesome!

**Comment by EionRobb** [comment]
Would someone be able to test with the commit b2862d2 and see if this is resolved?

**Comment by xvitaly** [comment]
> Would someone be able to test with the commit b2862d2 and see if this is resolved?
