### ISSUE TITLE
skypeweb: groupchat topics

### ISSUE THREAD

**Issue by rigid** [EionRobb/skype4pidgin#399]
Is it possible to show the topics of groupchats as MUC description?
I'm using prpl-skypeweb with spectrum2 and currently, it's hard to differ between groupchats :)

**Comment by EionRobb** [comment]
The topic already shows as the topic, if you type /topic in Pidgin you'll see it more clearly.  Not sure how this translates in spectrum2

**Comment by rigid** [comment]
it seems the topic should also added as MUC description. When listing the conferences with DISCO, both "jid" and "description" contain the jid.
i'm not sure what it takes to do that in libpurple.

**Comment by EionRobb** [comment]
I don't really understand how that works either. Is this a change that needs to be made to spectrum2?

**Comment by shookees** [comment]
![Groupchat topic](http://i.imgur.com/cB6eYC5.png)

I find it hard to distinguish between hashes and `/topic` does not return anything (using Pidgin 2.10.9 with plugin version 1.1)

**Comment by baskervald** [comment]
It shows when you're going through the list of rooms if you mouse over the title.

![example](https://cloud.githubusercontent.com/assets/8798637/12623760/a0e89e50-c4f9-11e5-9e51-1de713311894.png)

`/topic` also doesn't return anything for me, though (pidgin 2.10.12-1, purple-skypeweb-git 20160120.1.1.11.gb352617-1 [although I don't know how to interpret that -- it's just what pacman tells me])

**Comment by rigid** [comment]
@baskervald Is there another column next to "Name" if you scroll right? I'm seeing "Description" there and it's also showing the name, while with XMPP chats, the topic is shown there.

**Comment by shookees** [comment]
Hm, interesting. Eventually, one of the group chats started started showing the topic, but only in the description area, while other are still cryptic. On the other hand, the topics can be seen via the method @baskervald described. I would expect to see the cryptic chatroom hash in additional information, how is it that it's the main thing shown, is that some purple API based limitation?

**Comment by rigid** [comment]
@shookees I agree that it would make more sense the other way round in this case. But that's only because skype channel names are cryptic. With other protocols, they are quite descriptive.
The problem is that the method @baskervald described is only available in Pidgin, other libpurple users don't seem to be able to get the actual topic.

**Comment by rigid** [comment]
fixed. Seemingly, it was a spectrum issue.
