### ISSUE TITLE
No connection over Spectrum 2.0.1

### ISSUE THREAD

**Issue by TomTheDragon** [EionRobb/skype4pidgin#400]
A new version of Spectrum2 was released some weeks ago, after a long time and i wanted to go it a try again, since this new one is based on the current version of libpurple.
But it dont seem to work sine i only get a "Failed getting Skype Token" message on my jabber client.

Here is a log from the server side (only the last lines since there is a lot of html code in the log file):

22602: 2016-01-30 01:58:15,879 INFO  libpurple: connection:Connection error on 0x26bec70 (reason: 2 description: Failed getting Skype Token)
22602: 2016-01-30 01:58:15,879 INFO  libpurple: account:Disconnecting account tomthedragon87@hotmail.de (0x26bb590)
22602: 2016-01-30 01:58:15,879 INFO  libpurple: connection:Disconnecting connection 0x26bec70
22602: 2016-01-30 01:58:15,879 ERROR backend: GLib g_source_remove: assertion 'tag > 0' failed
22602: 2016-01-30 01:58:15,879 ERROR backend: GLib g_source_remove: assertion 'tag > 0' failed
22602: 2016-01-30 01:58:15,879 ERROR backend: GLib g_source_remove: assertion 'tag > 0' failed
22602: 2016-01-30 01:58:15,879 INFO  libpurple: skypeweb:getting url /logout
22602: 2016-01-30 01:58:15,879 INFO  libpurple: skypeweb:sending headers:
GET /logout HTTP/1.0
Host: login.skype.com
Connection: close
Accept: */*
Cookie: 
Accept-Encoding: gzip
Accept-Language: en-US.UTF-8, en-US, en.UTF-8, en, C

22602: 2016-01-30 01:58:15,879 INFO  libpurple: dnsquery:Performing DNS lookup for login.skype.com
22602: 2016-01-30 01:58:15,879 INFO  libpurple: skypeweb:destroying 0 waiting connections
22602: 2016-01-30 01:58:15,879 INFO  libpurple: skypeweb:destroying 1 incomplete connections
22602: 2016-01-30 01:58:15,879 INFO  libpurple: connection:Destroying connection 0x26bec70
22602: 2016-01-30 01:58:15,922 ERROR backend: g_log purple_account_disconnect: assertion '!purple_account_is_disconnected(account)' failed
22602: 2016-01-30 01:58:15,922 INFO  libpurple: account:Destroying account 0x26bb590
22602: 2016-01-30 01:58:18,323 INFO  backend: Exiting...

**Comment by azul027** [comment]
I can confirm I am getting this on Manjaro

**Comment by Ghabry** [comment]
A new spectrum2 version? wow.

I'm still running on an old version and it works. So this is probably a spectrum bug?

**Comment by black-roland** [comment]
> I'm still running on an old version and it works. So this is probably a spectrum bug?

I use purple-skypeweb 1.1 with spectrum 2.0.1 — works well.

Only MUCs does not work — can't join conference :(

**Comment by TomTheDragon** [comment]
> So this is probably a spectrum bug? <

**Comment by black-roland** [comment]
> How did you get it to run?

It just works. I use Fedora 22, [this purple-skypeweb build](https://copr.fedorainfracloud.org/coprs/xvitaly/purple-skypeweb/), latest spectrum (rpm [builded with this script](https://github.com/hanzz/spectrum2/blob/master/packaging/fedora/build_rpm.sh)) and [prosody 0.10](https://copr.fedorainfracloud.org/coprs/robert/prosody-0.10/).

Spectrum config is simple `/etc/spectrum2/transports/skypeweb.cfg`:
```
[service]
frontend=xmpp
user=spectrum
group=spectrum
jid = skype.***.***
password = ***
server = 127.0.0.1
port = 5347
backend_host = 127.0.0.1
users_per_backend=5
backend=/usr/bin/spectrum2_libpurple_backend
protocol=prpl-skypeweb

[identity]
name=Spectrum Skype Transport
type=skype

[logging]
config = /etc/spectrum2/logging.cfg
backend_config = /etc/spectrum2/backend-logging.cfg

[database]
type = pqxx
database = spectrum2_skypeweb
user = spectrum2_skypeweb
password = ***
[registration]
enable_public_registration=1
```

**Comment by black-roland** [comment]
What the type of Internet connection do you have? It is server or home ISP? Do you use proxy servers?

**Comment by TomTheDragon** [comment]
I do have pretty much the same settings and i dont think this can be a problem because i use many protocols (7 different libpurple plugins) which i set up in the same way and all the others to work. I also think i would not get this kind of error if it would be a problems with the config, because its the same kind of error i also got on my Pidgin on "really early" versions of the plugin from time to time.
I remember getting it to work on the older version of Spectrum2, if i copied the SSL certificates from Pidgin over to Spectrum2 but this only did last for few days or so and did not always work.
So i think it must be a problem of the plugin

**Comment by TomTheDragon** [comment]
I did some other tests today and it seems to work at least with normal skype names but my main account is a MSN one.
I also did some tests on my laptop which runs LinuxMint 17 (x64) and i have the exact same problem with pidgin over there and only with MSN accounts.

So i assume there must be a problem with the combination of a Debian based linux distro and a MSN account.

**Comment by TomTheDragon** [comment]
I am still not sure why i get this error but i solved the problem in a different way.

I just found a repository which has prebuild Ubuntu "and" Debian packets for the plugin, which seems to run without any problems on my Debian 8 server.
repo --> http://www.tataranovich.com/cms/repository
package name --> pidgin-skypeweb

**Comment by dequis** [comment]
>but i solved the problem

Closing then
