### ISSUE TITLE
Any known issue with skypeweb and otr plugin

### ISSUE THREAD

**Issue by dietmarw** [EionRobb/skype4pidgin#412]
Hi,
I was wondering if there is a known issue with skypeweb and the OTR plugin. I had OTR working fine with the "old" skype4pidgin plugin but after I switched over to the skypeweb plugin I can't seem to get any OTR authentication and communication going.

**Comment by EionRobb** [comment]
Nope, it's working fine for me :)

Is it just that it's not automatically starting, but manually starting works allright?  If so, it could be that the server is stripping the trailing whitespace that OTR uses to auto-start an OTR conversation

**Comment by dietmarw** [comment]
Damn, on my side it doesn't come much further than "Attempting to start a private conversation with ..." And having the native Linux skype app running I can see that I get first some gobbledegook from the parther followed by Pidgin answering with: 
```
?OTRv23?
foobar has requested an Off-the-Record private conversation.  However, you do not have a plugin to support that.
```

**Comment by EionRobb** [comment]
Sorry for taking so long to respond to this, but I've just tested OTR with the skypeweb plugin and it seems ok
