### ISSUE TITLE
skypeweb: spec file is broken

### ISSUE THREAD

**Issue by vitalyster** [EionRobb/skype4pidgin#413]
1) wrong source url
2) "fg: no job control", google say spec have some undefined macro (I'm using fc19)
cast @xvitaly :)

**Comment by vitalyster** [comment]
working before at a468e21

**Comment by xvitaly** [comment]
@vitalyster Fedora 19 is too old and already reached it's EOL. We support build only under Fedora 21+.

SPEC for fedora upstream is located in this repository: https://github.com/xvitaly/purple-skypeweb/. Try build from this repo. If it will fail, upload full rpmbuild build log.

**Comment by dequis** [comment]
I got emails about fedora 22 getting EOL'd today. So fedora 19 is really really EOL'd.

Closing this thing with my newly acquired ticket nuking powers.

(BTW, all this time I thought you two were the same person. Stuff like, "hey, vitaly from spectrum sure is active in these bug trackers lately". Only realized the difference after seeing this ticket.)

**Comment by xvitaly** [comment]
@dequis Package purple-skypeweb is already in Fedora's upstream, so SPEC file is no longer needed in this repository.
