### ISSUE TITLE
skypeweb: Deleted buddies show up on Pidgin buddy list

### ISSUE THREAD

**Issue by tsdmgz** [EionRobb/skype4pidgin#416]
Due to a falling out with someone, I have deleted someone from my contact list. However, she still shows up online in Pidgin. Official Skype for Linux (4.3.0.37) does not have her in the list, neither does Skype for Web.

On initial occurrence, I deleted her. When I log in again, said (unwanted) contact is back. I have output from Pidgin's debug log and I'd like to upload but it looks like it has too much identifying info.

**Comment by xvitaly** [comment]
Yes, I can confirm this, but I think that it is libpurple's global problem because XMPP protocol has this bug too.

**Comment by tsdmgz** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Even if the contact was deleted well before adding a skypeweb account in Pidgin?
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJW0H26AAoJEFwU9ymJ941mo/gQAJqqiMP9pKJYi/+dwNr3FoOz
ZGkd6q3OYXjv6UX1Zw4G+APmf2BB2m4/0RCAEj2nr49z6wolLKtrJHYA5TaVAoEm
JQFXSGIm5uNbjbfYIj/b5q4DHTXijVdaQFbqQK3WlhyJSHUoJY7plxoVMeepAzya
0nRu07qYkgGmaRjjAOQu1/myBFImw+O9w70J0XNxwlGTwUAjMtvM/wpcsUQQHQX/
CGMAI71AYVhJCE8kyf6G5b0cpKdRcXsjXvmkwIl+J77JBEFuyAGTP5fwD12tNEvV
W8wHYrricBqZKABpt98HE5mJ8vqFasVdhl5kF7Ks6n7I/pSeBnyD5btdHziE60sk
fSUXX/IcugDI2y/ZEarBH99oHruY8BjohmChVgFS2xScvkBqd5WYkIXJcfyQpGbb
fa+9hFadvUrBoZ6Hn5A6Abr4PQXm5xiLUnoErxlTkNIVw6QNnvrura+F/dLsPLV6
jli4uZh4YYTqWhNrkHmbFMVNIkCeWhbzNd1x2x9NDhca3goM3Hq9UIEgAJ3J6CGX
o5z4/qV3Q6ur846KGrS41IsJFtCHqthbC6JNRKsK58bIJcrLy0DeFeCGszx8JEGr
E75U8UhE25Y2LykcXJEV0geR1zFcNV3NtHtZa8hwdltI1Ue6l8wlE5Zpd1llRn+L
QzSYD42zPkOqBbcRqT4u
=oXpX
-----END PGP SIGNATURE-----

**Comment by xvitaly** [comment]
> Even if the contact was deleted well before adding a skypeweb account in Pidgin?

This bug with other protocols can be reproduced with fresh Pidgin installation even without purple-skypeweb being installed.

**Comment by tsdmgz** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Ah, well, umm...I don't know how to comment on this further :S
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJW0ICbAAoJEFwU9ymJ941mSf0QAL9d4Bba1W36+LAbjn/sR975
Rt0U/sToGH6vpQwZxxDZjeSZ6BXT8/hGlKTXE1qZAbaBmQvHvW2dwkGymY5uQi0J
Blw4J82KQtRKVzHNdAJY2bdPE+mvonUWEF/X+PDyZWjYZSZXd5y/6QuPn4J48YEt
wBnF5D1RgzsYUkukiB3LLg6fAXnwly0chYmgfLoq52KX92VmLUYRYq8S1sJOyq/l
hM1tkhk7asjwUo+DDycxxk5cjhPf1EO732xJ/8O0A51kyE0oX5hl/kseBx6NkKNL
oQAFZyUyfMiW/BJfusHSghghtyaXfmxclvQRzAqLOA6qzaVtXdKqf1UgB9m7FvBp
EhRhhJ4bo/e1BRFuwjH11l5R31xxcBdw8mZNscWnlNfpR0V2SUibCc4gtJuRcCxP
ZiigSg4syWbyVBMwpV7vZXscI/OVVtW/RKA2qPWWT0LYqjiyocPdxEaVOExe0Lo1
aLNA23MXEVUCNhPIc8ArO8HNf8021IVejewkH8dG5nXBe3wK89fmRYtmn4dL1f3c
+SkyYA9f5nriRaW9kyj0NOxA73nebRlebMhFJSb4jip7INAsTh+vCVG+wm++ZCaT
p4Gfkk9PH4O1dsxE9bo+v1MUiCD+OBIRMgcQfAaS8jP79gQMEQ/4J4jXKI4Va52a
CkmMJfBY4E5LJpGbOfCt
=wpbn
-----END PGP SIGNATURE-----

**Comment by EionRobb** [comment]
I don't care what other prpls do :) if a buddy has been deleted then I don't think it should show up on your buddy list. I know of an issue where blocked users will show up as offline users but the deleted ones is a new thing to me. 

@tsdmgz do the deleted buddies show as online on the buddy list or just offline?

**Comment by tsdmgz** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Online and even goes idle. Unfortunately, I can't ask her to go offline to test and see if her entry goes offline too.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJW0MpYAAoJEFwU9ymJ941mgKsQAIZeVYvGuiZnBSrNBgxCKyoA
60zV2+Xgxwr6st71vpoWHGsyIUciD/us0LWPAQoTYbuF6dBuIjhhH3qWTEAct4K6
60Bwc2g0Iq0Y8TpvPV/N0WVtMFO3siB2oWgR6pgkCxoQvVVGbBne7h7YMUyUZ239
zs9YiUJI7fBFEnLVtYAFWHMZtnvRlyr7ZaWfchqDUU792co7JKZSJoti1bT6TLdS
AxxR8iRCa4xMTHAhGn6G/1EXn243c6pgRYEx/RM2t7r4lGGrU4LIv34FE/Vfvlhf
HYxrUR5SaAk+qTWPnuUjzpgEIuZ8QCZCo/9BIpIAcCgCGnF/xhCED3UELJq1+4lA
I0nDdC11qCmRUcW4MU+s6hD5FKl+rWgjuPciFhNfwCN7ySg0gW5rFhc85inY33od
iTAFHF4jS4bNR2oGdgcgY6/61kfbklsSAQiulf14exiPyOmPzeTJ64o4CEC7ZDCa
xcOzWGaEfDU06exQJAbfGyF8w1L95NCM/9yM7NEyE3ACsyOpAEAUjdPgNqt1o9Eu
TlK5HopeuD8HTO76LgvEn4GdiLC8ey5WGHSVc6+tIRclOQE1m97cCIDYcZ5lSdzR
+jLwUd1ZvtlWEesko3sSr1fJBLBZxOhkNQ2F6XXCHKb3sx38NiolfVskD1WE21Wx
KYV0B7TwWdxTeesq8GqQ
=FuIY
-----END PGP SIGNATURE-----

**Comment by tsdmgz** [comment]
Just an update: said buddy is now gone from my list. Renamed blist.xml to blist.xml.old and have Pidgin make a new one. Looks like it's all okay now.

Thanks for your time!

**Comment by grzegorz-janoszka** [comment]
hi, I have tried to edit the xml with removing the accounts and it didn't work - the deleted contacts are still there.
