### ISSUE TITLE
Error message spam on Spectrum

### ISSUE THREAD

**Issue by TomTheDragon** [EionRobb/skype4pidgin#418]
I do run a little skype jabber transport for some friends and i noticed that every time Skypeweb is trying to get infos about a buddy, a error message pops up into my ssh console. Its normally not that big of a problem but now since i have more users which are using the transport all the time, the console gets regularly flooded with error messages.

Its always this one:
(process:11480): Json-CRITICAL **: json_object_get_string_member: assertion 'node != NULL' failed

I am not sure if this is a problem on the Skypeweb plugin or on Spectrum but is there a way to turn this off?

**Comment by dequis** [comment]
This one was handled by f23913d1287ab212aa2c3cd32eda64555a49281b
