### ISSUE TITLE
Linux mint 17.3 x64 Cinnamon

### ISSUE THREAD

**Issue by iTpain** [EionRobb/skype4pidgin#419]
Hi there i can't finish install it on my system is shows this error

`cmake ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
CMake Error: your CXX compiler: "CMAKE_CXX_COMPILER-NOTFOUND" was not found.   Please set CMAKE_CXX_COMPILER to a valid compiler path or name.
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for module 'glib-2.0'
--   found glib-2.0, version 2.40.2
-- checking for module 'json-glib-1.0'
--   found json-glib-1.0, version 0.16.2
-- checking for module 'purple'
--   found purple, version 2.10.9
-- Configuring incomplete, errors occurred!
See also "/home/inj3ct0r/skype4pidgin/skypeweb/build/skype4pidgin/skypeweb/build/CMakeFiles/CMakeOutput.log".
See also "/home/inj3ct0r/skype4pidgin/skypeweb/build/skype4pidgin/skypeweb/build/CMakeFiles/CMakeError.log".
`

**Comment by iTpain** [comment]
Well i found a work around before the bellow command

`cmake ..`

you need to use this command

`sudo apt-get install build-essential checkinstall`

**Comment by dequis** [comment]
Looks like this one was solved already.
