### ISSUE TITLE
Can't join a Skype group chat

### ISSUE THREAD

**Issue by guest73** [EionRobb/skype4pidgin#422]
When I select from Pidgin Buddies->Join a Chat and type a name of the group Chat from Skype then just a new chat window is opened, so I am not able to join an existing Skype chat. Also I can't  find anywhere in any list Skype's group chats I am participating in.
My software:
Linux Mint Rosa XFCE edition 64bit
skype-ubuntu-precise_4.3.0.37-1_i386
Pidgin 2.10.9
skype4linux 20130613+svn660+dfsg-1 installed from Mint's repository

My initial idea was maybe it was due to I have an old version of skype4linux installed thus I tried to install from git source but got this error
```
i686-pc-linux-gnu-gcc -I/usr/include/libpurple -DPURPLE_PLUGINS -DENABLE_NLS -Wall -pthread `pkg-config --cflags glib-2.0` -I/usr/include -I. -g -march=athlon-xp -pipe libskype.c -o libskype.so -shared -fPIC -DPIC
/bin/sh: 1: i686-pc-linux-gnu-gcc: not found
make: *** [libskype.so] Error 127
```
I do not have so strong knowledge about this stuff so dunno how to fix this problem.
Also I've been told that skype4linux is an old lib and skypeweb is a new one. Should I install skypeweb then? I mean I am fine with running a Skype instance and have skype4linux just communicate to it. I am afraid that skypeweb just has some limitations, like not allowing video call or something else.

So how can I deal with this little problem and is it possible to participate in group chats from Skype with the help of this plugin at all?

**Comment by EionRobb** [comment]
Try, Tools->Room List... it should show the group threads you're in and you can join them from there.

Looks like you're still trying to compile the old plugin though, try skypeweb instead of skype4pidgin, if your repo has it, otherwise the instructions at https://github.com/EionRobb/skype4pidgin/tree/master/skypeweb#compiling should help.

**Comment by EionRobb** [comment]
I've created a new wiki about this to hopefully help answer any questions about group chats:
https://github.com/EionRobb/skype4pidgin/wiki/Working-with-Group-Chats

**Comment by guest73** [comment]
As I understood the old skype4pidgin does not work with Thread chats and the new one does not have Video call support(At least I searched everywhere how to enable it but all items in Media menu were grayed) which is needed. So I think I will stick with stock Skype for now. Thanks for help anyway.
