### ISSUE TITLE
Failed getting Skype token

### ISSUE THREAD

**Issue by LaP0573** [EionRobb/skype4pidgin#428]
Just installed skype4pidgin on my dedicated server. I use it together with Weechat and Bitlbee. I have the same setup on my Mac and it works fine. However, on my dedicated server (Debian) I get this error when trying to connect :

```
skypeweb - Logging in: Connecting
skypeweb - Logging in: Authenticating
skypeweb - Login error: Failed getting Skype Token
skypeweb - Logging in: Signing off..
```

My account is an old account so no live or outlook or anything like that. The setup of the account is fine, same as the one I have in local. I've got the latest version of your plugin, as well as libpurple-dev 2.10.11-1.

**Comment by xvitaly** [comment]
Login on https://web.skype.com/ from server's IP address and enter CAPTCHA.

**Comment by LaP0573** [comment]
That seems likely to be the issue indeed ! However, how can I do that ? I mean, I've searched and haven't found any command-line based browser that could allow me to log onto web.skype.com (because of javascript) and I'm not even sure it would work for a captcha anyway.

I tried using my server as a proxy for my computer (checked the IP, it was the server's one) but http://web.skype.com did not ask for a captcha.

**Comment by xvitaly** [comment]
> However, how can I do that ?

SSH tunnel, VPN.

**Comment by LaP0573** [comment]
That's what I did though. I did that :

`ssh -C2qTnN -D 9090 me@my-server-ip`

Then changed in my OSX preferences to activate a proxy through localhost:9090. As I said, I checked and google did indeed recognize me as my server's IP when I did that, but no captcha on skype web. Did I miss something ?

**Comment by spyjo** [comment]
@EionRobb one suggestion, would it be possible to download the captcha image if there is one ?
it's a first step for solving

**Comment by LaP0573** [comment]
I'm investigating the issue a bit more. I've installed a X server on my VPS and tried to access http://web.skype.com (by faking my useragent since iceweasel is rejected by default), and it works fine without the use of a captcha. I've also tried Pidgin in this visual mode and it managed to connect to skype as well, so the issue stems with Bitlbee it seems, although it works fine on my Mac. Any idea @EionRobb ?

**Comment by LaP0573** [comment]
Oh well, I "solved" the issue by fully reinstalling everything related to this (so bitlbee, libpurple, weechat, pidgin, etc). No idea where the issue came from, maybe something wasn't properly set up (although I double checked everything), maybe I got an unfortunately glitch. In any case, it now works so I'm closing this issue, I'll assume the problem came from my end and not from the plugin itself. :)
