### ISSUE TITLE
Token expired after 24h then disconnected

### ISSUE THREAD

**Issue by spyjo** [EionRobb/skype4pidgin#433]
Hello,

I let my Skype account connected during 1 day, and after 24h, the account was disconnected, here are the errors in debug logs:

skypeweb: getting url /v1/users/ME/endpoints/SELF/subscriptions/0/poll
skypeweb: post_or_get_ssl_connect_cb
skypeweb: Got response: HTTP/1.1 403 The provided registration token is expired, and no authentication ticket was provided.
skypeweb: No data in response
util: requesting to fetch a URL
util: request constructed
util: Response headers: 'HTTP/1.1 401 The provided 'skypetoken' ticket failed authentication.
util: parsed 0
connection: Connection error on 0x8363e0 (reason: 0 description: Failed getting Registration Token)

and then it disconnected.

Is the 24h token renew actually handled by skypeweb ?

Thanks

**Comment by spyjo** [comment]
I tried an other time to let the skype connected for more than 24h, just to be sure if it was not a temporary bug, and again I had the token expired 24h later and got disconnected.

May be there should be some internal "cron" that renew the token at about 23h after the last connection or last token renew ?

**Comment by 3ruce** [comment]
Agreed.... some way to stay always connected would be great....

**Comment by EionRobb** [comment]
I think the latest commit helps with this, but feedback would be appreciated

**Comment by 3ruce** [comment]
ok, I've just got it running via this ppa ppa:nilarimogard/webupd8

I've had to re-enter the password once or twice but I'll let you know how it goes...

**Comment by EionRobb** [comment]
I don't think that ppa will have that change, you may have to compile it yourself

**Comment by EionRobb** [comment]
Apologies, looks like the webupd8 ppa should have that change :)

**Comment by 3ruce** [comment]
ok - cool....

**Comment by 3ruce** [comment]
Hmmm, I'm still getting frequent connection losses... I am on mobile broadband though???

**Comment by EionRobb** [comment]
This issue isn't about frequent connection losses, it's about the account being auto disconnected every 24 hours

**Comment by 3ruce** [comment]
Ahhh... is there another issue on connection losses? Or do you want me to open a new one?

**Comment by EionRobb** [comment]
@3ruce sure, create a new issue with a debug log and lets see

**Comment by 3ruce** [comment]
How can I get the debug log? Is there a link I can follow that explains how to do it?

**Comment by EionRobb** [comment]
v1.2.1 has fixes to help with this :)

Please open a new issue if anyone is still having trouble with this.
