### ISSUE TITLE
Separate previous conversations with <hr> line

### ISSUE THREAD

**Issue by Monsterovich** [EionRobb/skype4pidgin#437]
![pidgin2](https://cloud.githubusercontent.com/assets/3750982/15709240/54c46678-280c-11e6-84e4-438fe872f3e9.png)

On my screenshot you can see that two last messages are same, but I selected the previous conversation.

**Comment by xvitaly** [comment]
Yes, I can confirm that. This happens after SkypeWeb disconnect/reconnect.

**Comment by rafzi** [comment]
related/duplicate: https://github.com/EionRobb/skype4pidgin/issues/372
