### ISSUE TITLE
Suddenly getting "Failed getting Skype Token" for MSN/LIVE log-in, but skypename works.

### ISSUE THREAD

**Issue by gordon-fish** [EionRobb/skype4pidgin#441]
Since about late Saturday evening or so, I can no longer connect using my MSN/LIVE email login, as it fails pretty quickly with "Failed getting Skype Token", though if I use the skypename that it is associated with, it appears to log in just fine.

I have built the latest git from this morning, and also tried the latest from the releases page, both giving me the same result as when I saw yesterday (I was using git-built libskypeweb.dll from a couple weeks ago when I first noticed the problem, which had worked fine until yesterday,

Debug log for connection attempt from this morning (2016/6/6 PDT): http://paste.debian.net/hidden/9b07d9fd/ while using libskypeweb.dll built from a8feb9a94b017668b535bda32a1482fb5677e50d.

(Edit: copied the wrong commit string.)

**Comment by gordon-fish** [comment]
Also, I have tried logging into manually to https://web.skype.com/en/ with my LIVE/MSN email and that works just fine (the web skype interface loads up just fine.) I never get any captcha or anything though.

**Comment by gordon-fish** [comment]
Here is a debug log with libskypeweb-debug.dll built from the same git clone (a8feb9a94b017668b535bda32a1482fb5677e50d): http://paste.debian.net/hidden/6fcebd08/

(Note: This git commit I gave in the first post was incorrect, I used a8feb9a94b017668b535bda32a1482fb5677e50d for that as well.)

**Comment by ndias** [comment]
Same problem here, using the latest code from git can connect with a skype account can't connect with an old MSN account that works with the skype client.
The error is the same ... Failed getting Skype Token

**Comment by edtsz** [comment]
hello guy, 
I'm having the same problem since last week.. using the [latest code](https://github.com/EionRobb/skype4pidgin/commit/72f0b003252d0c827e9fa5dcb31005ef4a51b036) from git.
I tried by email (live account) and by username (live:<something>) and no results

**Comment by edtsz** [comment]
@xvitaly I'm on using it and I get no captcha

**Comment by gordon-fish** [comment]
@xvitaly Just like edtsz, I also have not been presented with any captcha each time I tried logging via the web using live account (or skypename for that matter) no matter how many times I've tried. Instead, it just logs right in after enter the password.

**Comment by szr8** [comment]
I'm also getting the same error now and also not getting any capture when I try the the browser/web log-in directly.

**Comment by szr8** [comment]
Also, I use a couple of old MSN-only accounts (that aren't associated with any skypename, thus using this as a sort of MSN/Live plugin) so I hope that this is something that can fixed. I'd like to help in any way I can (I can submit debug logs and try test builds and such.)

**Comment by EionRobb** [comment]
Please send through your debug logs!  Annoyingly, I can't replicate the problem here, Live logins work fine for me :(

To grab one, open the Help->Debug Window, then try login to Skypeweb before saving the debug log output.

If you could also mention what version of libpurple/Pidgin you're running with, and perhaps what distro, it might help narrow down the problem.

**Comment by gordon-fish** [comment]
Pidgin 2.10.12 release on Windows. Also tested with Finch on Linux built from 2.10.12 sources and also getting the same exact "Failed getting Skype Token" error there too.

**Comment by szr8** [comment]
I'm using Pidgin 2.10.12 on Windows as well.

**Comment by xvitaly** [comment]
@gordon-fish @szr8 Try new Windows build: http://eion.robbmob.com/libskypeweb-debug.dll

**Comment by szr8** [comment]
@xvitaly I still get the same error using that, same as with 72f0b003252d0c827e9fa5dcb31005ef4a51b036

**Comment by szr8** [comment]
Here's my debug log https://gist.github.com/szr8/597432de3ec86c0fa555ae1abc88bf87 using the http://eion.robbmob.com/libskypeweb-debug.dll available at the time of this writing.

**Comment by gordon-fish** [comment]
Using http://eion.robbmob.com/libskypeweb-debug.dll I'm seeing the same thing as @szr8 in my debug log.

**Comment by xvitaly** [comment]
Yes, error:
```
There is a problem signing in with Microsoft account. Please try again or sign in with Skype details instead.
```

**Comment by szr8** [comment]
@xvitaly Yeah I see that in my debug log, though logging in via https://web.skype.com works fine.

**Comment by Woodzrul** [comment]
@EionRobb Please see attached debug log when trying to sign into Skype (HTTP) via Pidgin using just my Skype username.

Running Pidgin 2.11.0 along with latest Skype Purple installer. Do let me know if you require any further information.

[purple-debug.zip](https://github.com/EionRobb/skype4pidgin/files/325497/purple-debug.zip)

**Comment by dequis** [comment]
@Woodzrul that was fixed in 72f0b003252d0c827e9fa5dcb31005ef4a51b036 and is not related to this ticket. Get the latest revision from http://eion.robbmob.com/libskypeweb-debug.dll

**Comment by Woodzrul** [comment]
@dequis I apologise.

**Comment by ndias** [comment]
My log ... Fedora 23 (x86_64), pidgin-2.10.12-1.fc23.x86_64 and skypeweb 72f0b00 compiled by myself

[purple-debug.txt](https://github.com/EionRobb/skype4pidgin/files/325637/purple-debug.txt)

**Comment by xvitaly** [comment]
@ndias You got the same problem as @szr8. Login via Microsoft Account is broken. Can you try to login via Skype Account instead?

**Comment by ndias** [comment]
@xvitaly I can connect using a skype acoount, no problem, only fails when I use an old Microsoft Account, using the same plugin.

**Comment by szr8** [comment]
@xvitaly It's not just Microsoft accounts, but also Live/MSN accounts (either stand-alone or associated with a skype account), which are not the same thing as a MS account (an account created in/for Windows 8+/Windows Phone.) I think they use slightly different url paths when logging in last I recall.

**Comment by rafzi** [comment]
I'm getting this error after upgrading to pidgin 2.11.0 on Windows. I'm using the current skypeweb 1.1 release.

debug log: https://up1.ca/#TReF5bfjrzi6FBK_c6GJUA

**Comment by xvitaly** [comment]
> I'm using the current skypeweb 1.1 release.

Too outdated. Upgrade to 72f0b003252d0c827e9fa5dcb31005ef4a51b036 revision: http://eion.robbmob.com/libskypeweb-debug.dll

**Comment by rafzi** [comment]
@xvitaly Do you mean with regards to the new pidgin release? I was logging in just fine before the update.

**Comment by xvitaly** [comment]
> Do you mean with regards to the new pidgin release?

Yes. Under Pidgin 2.11.0 you needs 72f0b00 revision of purple-skypeweb or higher.

**Comment by rafzi** [comment]
@xvitaly thanks that resolved the issue for me

**Comment by gordon-fish** [comment]
Here is one more debug log: https://gist.github.com/gordon-fish/fee9869b1694ff02ace5fafebd37d54c

pidgin-2.11.0 Win32, running with PURPLE_UNSAFE_DEBUG=1
skypeweb-git.be125c6ff258d83b27cf2310957b2fe95990b8cf

**Comment by xvitaly** [comment]
@gordon-fish Use this: http://eion.robbmob.com/libskypeweb-debug.dll

**Comment by advcomp2019** [comment]
@xvitaly I am using the newest build of skypeweb and my MSN/Live account will not connect. So I tried my Skype account, and it works just fine. My MSN/Live account works fine on https://web.skype.com/. By the way, these are two different accounts that is very old.

**Comment by PF4Public** [comment]
For me it looks like it first connects to `login.skype.com`, which redirects to `Location: https://login.live.com/login.srf?wa=wsignin1.0&...`, which in turn redirects to `Location: https://login.skype.com/login?client_id=578134&redirect_uri=https%3A%2F%2Fweb.skype.com&error=microsoft_oauth_failed`. So I suppose something broke in handling Microsoft OAuth, since I can login successfully via browser, not being asked for captcha.

**Comment by edtsz** [comment]
@xvitaly I got the same as @PF4Public and my debug log is the same that @gordon-fish  ....  looking the log file I got the same kind redirection.. but via browser is working fine..
I have my MS account (me@hotmail.com) linked to a skype (migration from old MSN)
It was working fine until Jun 13th..
 - Pidgin 2.10.12-3.fc24
 - Fedora 24 (but the problem starts on Fedora 23, I updated yesterday)
 - skypeweb latest commit

I hope we could help to fix it ASAP :)

**Comment by EionRobb** [comment]
Hi all, just a brief follow-up since @gordon-fish is harassing me ;)

I've been desperately trying to get this to work and, thanks to all the debug logs people have sent me and some additional packet captures, know what it's supposed to do.

Unfortunately I must missing a tiny piece of the puzzle because all my attempts thus far have been unsuccessful - admittedly I've only had time for a couple of go's at this - I just need to throw more time at it.

Apologies to all getting this issue.  It's my number one priority at the moment and you definitely haven't been forgotten about.

**Comment by PF4Public** [comment]
Any help needed -- just ask! We are ready to help!

**Comment by nkrepo** [comment]
Issue affects also Skypename in pidgin 2.11 , update the tittle if possible.
In Pidgin 2.10 Skypename works fine.

**Comment by dequis** [comment]
@nkrepo that's a different issue, use http://eion.robbmob.com/libskypeweb-debug.dll (or build the latest revision if linux)

**Comment by nkrepo** [comment]
@dequis I tested the latest http://eion.robbmob.com/libskypeweb-debug.dll with Pidgin 2.11 in Windows 10. I got the same error "Failed getting Registration Token" with Skypename.

**Comment by advcomp2019** [comment]
@nkrepo make sure you do not have libskypeweb.dll with libskypeweb-debug.dll in the folder. It might be loading the one and not the other.

**Comment by nkrepo** [comment]
@dequis , I have already deleted the libskypeweb.dll. I also used the libjson provided at https://github.com/EionRobb/skype4pidgin/raw/master/skypeweb/libjson-glib-1.0.dll.

**Comment by nkrepo** [comment]
@dequis. I have already deleted the libskypeweb.dll and used the libjson provided from skypeweb project at https://github.com/EionRobb/skype4pidgin/raw/master/skypeweb/libjson-glib-1.0.dll with no luck.
Is the libjson build provided by the skypeweb project incompatible with the libjson provided by the purple-facebook project at https://github.com/dequis/purple-facebook/releases/download/downloads/libjson-glib-1.0.dll ?
When I use the libjson from skypeweb , purple-facebook plugin does not load unfortunately :(.

**Comment by advcomp2019** [comment]
@nkrepo I use the the libjson from Facebook myself. Not sure why it is not loading for you. I have it working here but for my Live accounts.

**Comment by nkrepo** [comment]
@advcomp2019 
With libjson from purple-facebook both skypweb and purple-facebook and worked fine in Pidgin 2.10.

**Comment by dequis** [comment]
@nkrepo please open a new ticket, this ticket is about live logins and the error message "Failed getting Skype Token". Your issue is unrelated and there's a bunch of people here subscribed to get notifications about the other issue.

**Comment by EionRobb** [comment]
Sorry everyone, couldn't get Live logins sorted quickly enough so v1.2 of the plugin that I've just released doesn't have any Live login fixes (before anyone asks).

I'm definitely not forgetting you guys, I'm still trying to get Live logins working.

**Comment by EionRobb** [comment]
Might have fixed this in https://github.com/EionRobb/skype4pidgin/commit/2b42d110708837d757b09ebc71e9e7053f259458 ?  If some other people could give it a try, that would be great.
I've got a precompiled dll at http://eion.robbmob.com/libskypeweb-debug.dll if you want to give that a try

**Comment by advcomp2019** [comment]
@EionRobb I just compiled a version for Windows myself. It is working right. I even tested messages between the Skype client and Pidgin. All looks good for now for me.

**Comment by edtsz** [comment]
@EionRobb  it is working very well with this fix.. :D :+1: :+1: :+1: :+1: 
Great job ..

I just compiled for:
Fedora 24 x86_64
Pidgin 2.11.0-1

**Comment by intrepidIbex** [comment]
Yes, it's working again. Thank you!

**Comment by gordon-fish** [comment]
It is working perfectly for me. I've tested with a a skypename-associated MSN account, an old legacy MSN account, and a more recent MS account (that I use in Win 8/10 VMs) and all seem to work. Well done, thanks!

**Comment by JanBessai** [comment]
I had the same issue with 1.2.
Compiled and tested the latest version from git cabcc1befee74ed6d4bbdc1cb2bcd4263c837c0c on Gentoo amd64. Both pidgin-2.10.12-r2 and pidgin-2.11.0 work.

**Comment by EionRobb** [comment]
Hi all,  Finally made a v1.2.1 release that contains this fix.  Everyone can start using that now instead :)

Thanks for your patience!
