### ISSUE TITLE
Pidgin version 2.11.0 lost protocol icon of skype4pidgin

### ISSUE THREAD

**Issue by PF4Public** [EionRobb/skype4pidgin#446]
(13:53:26) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file C:\Program Files\Pidgin\pixmaps\pidgin\protocols\16\skype.png: «C:\Program Files\Pidgin\pixmaps\pidgin\protocols\16\skype.png»: No such file or directory
At least on Windows.

**Comment by EionRobb** [comment]
Unfortunately the Windows uninstaller of Pidgin will delete all protocol icons if you use it to upgrade.  You'll need to apply the images to the Program Files\Pidgin\pixmaps\protocols\* folders manually.
