### ISSUE TITLE
no longer able to connect with pidgin 2.11

### ISSUE THREAD

**Issue by xogium** [EionRobb/skype4pidgin#449]
Hi,
I'm running archlinux with the latest pidgin version, 2.11.0. I just noticed this was no longer working, this is not only happening on windows. 'failed to get registration token' every time I try to activate my account. This account was previously linked to a microsoft account, though I was trying to connect with skype username and not my microsoft account directly. So in case it would start to work again, I unlinked it, and yet, it's not working, I still get that error. I can provide debug logs if needed.
Thanks :)

**Comment by advcomp2019** [comment]
Sounds like you might need to build a newer version or wait for it get updated on arch's sources. You most likely have #445 or it could be but most likely not #441.

**Comment by xvitaly** [comment]
@xogium Ask your distro's maintainer to build rev. 72f0b003252d0c827e9fa5dcb31005ef4a51b036 or build it from sources manually.

**Comment by radenling** [comment]
The purple-skypeweb-git AUR package works if you don't want to build it manually.

**Comment by xogium** [comment]
Hi,
thanks to everyone :) that's exactly what I did, building it from source, since I saw the message about the AUR package too late :dancer: Well I guess I should close this, then.

**Comment by alex3kov** [comment]
Do you plan to release a stable version with a fix? Seems like a good enough reason, with functionality completely broken and all :)

**Comment by xogium** [comment]
Hi,
I just warned the maintainer of the community package for arch a few minutes ago :)

**Comment by EionRobb** [comment]
@alex3kov I'm trying to get the Live logins fixed first, before releasing a new version
