### ISSUE TITLE
Got a mail that my account was closed

### ISSUE THREAD

**Issue by Thaodan** [EionRobb/skype4pidgin#450]
Cause I did things that are not allowed.
I changed my password before cause I needed to change it cause skype thought there were suspicious acctivies on my account.
I distribute the plugin on openrepos too and some had the same issue.

![screenshot_20160628_000131](https://cloud.githubusercontent.com/assets/1747359/16397248/8a1302a0-3cc3-11e6-8919-e5d9d566d2d1.png)

**Comment by xvitaly** [comment]
Microsoft may close your account for lots of reasons: spam, credit card fraud, attack via reports and so on.

**Comment by dequis** [comment]
Not much we can do about this, closing.
