### ISSUE TITLE
"Failed getting registration token" since yesterday

### ISSUE THREAD

**Issue by Ghabry** [EionRobb/skype4pidgin#451]
Hi since last night I can't connect with the plugin anymore. I use the package from the Arch Linux repo (which is Version 1.1).
I use KDE telepathy to login through libpurple via "telepathy-haze" but it also fails in Pidgin so I assume it is unrelated to the chat application I use.

I always get this error when logging in now. 2 days ago it worked flawless. I don't have an outlook account, use my normal Skype username.

Is anybody else experiencing this issue? Usually when getting this skypeweb is just under maintanance or broken, but currently it works flawless in the browser :/

**Comment by D4rk4** [comment]
Yes, same trouble...

**Comment by xvitaly** [comment]
> I use the package from the Arch Linux repo (which is Version 1.1).

This version is too outdated. Upgrade to revision 72f0b003252d0c827e9fa5dcb31005ef4a51b036.

**Comment by D4rk4** [comment]
@xvitaly не поможет, такая-же ошибка с версией вытащенной сегодня из гита.

**Comment by xvitaly** [comment]
@D4rk4 Try to use Skype Account instead of MSN/Microsoft. Microsoft/MSN/Outlook accounts support are now broken.

**Comment by Ghabry** [comment]
Updating to Git version fixed my connection issue, thx :)
