### ISSUE TITLE
Failed getting Skype token

### ISSUE THREAD

**Issue by demolitions** [EionRobb/skype4pidgin#452]
Already seen #441 and #451, tried compiling git HEAD version, but still have the same problem.

I'm using the skype login, not the MSN one.
I'm on Arch Linux 64bit, and this issue is present on both my workstations, with both my skype accounts.

Attaching log for one of the accounts.
[purple-debug.log.txt](https://github.com/EionRobb/skype4pidgin/files/340868/purple-debug.log.txt)

**Comment by EionRobb** [comment]
The debug log is saying you have an incorrect username or password

**Comment by demolitions** [comment]
Sorry, attached the wrong log.
This is one using the correct password.
[purple-debug.log.txt](https://github.com/EionRobb/skype4pidgin/files/340917/purple-debug.log.txt)

**Comment by demolitions** [comment]
Clicked the wrong button, I need my coffee this morning.

**Comment by EionRobb** [comment]
That one's not showing as having the "2.11 fixes" from the latest git head :)

**Comment by demolitions** [comment]
Ok, that is actually weird.
I'm searching now how to clean up pidgin's directory to install a freshly compiled version.

Hope to actually close this as soon as I manage to get the git HEAD properly installed.
How do I check from the logs if the correct version is installed?

**Comment by demolitions** [comment]
Ok, I can close this for real this time.
Re-compiling HEAD version worked this time.
Don't know what I did wrong this morning, but now it works.

Thanks very much for your help.

**Comment by EionRobb** [comment]
Yay :) 
Glad you got it working :)
