### ISSUE TITLE
Changing mood/message in skypeweb (new functionality)

### ISSUE THREAD

**Issue by spyjo** [EionRobb/skype4pidgin#453]
Hello,

Skype Web has just added a new functionality: changing the mood/message

https://community.skype.com/t5/Skype-for-Web-Beta/How-Do-I-Change-My-Mood-Message-In-Skype-for-Web/m-p/4426293/highlight/true#M3383
"Just click your profile picture in the top left, then click the little pencil icon next to Change activity message."

That would be great to add this in the plugin :)

Thanks

**Comment by EionRobb** [comment]
Yay! It finally happened :) 

Thanks for letting me know, I'll look into this

**Comment by EionRobb** [comment]
Its a POST request to `https://api.skype.com/users/self/profile/partial` with the body content of `{"payload":{"mood":"new message goes here"}}`

**Comment by kiravi** [comment]
Do we have a new Windows build

Ravi

- sent from outlook mobile




On Sat, Jul 2, 2016 at 3:33 AM -0500, "Eion Robb" <notifications@github.com> wrote:












Its a POST request to https://api.skype.com/users/self/profile/partial with the body content of {"payload":{"mood":"new message goes here"}}

**Comment by EionRobb** [comment]
@kiravi no, the change to the code hasn't been made yet (but if someone else wants to do it and put through a PR I won't complain ;) )

**Comment by EionRobb** [comment]
https://github.com/EionRobb/skype4pidgin/commit/b2c3457d1a90421b1ca82812915c37022721bb29
