### ISSUE TITLE
Please tag #72f0b00

### ISSUE THREAD

**Issue by enodata** [EionRobb/skype4pidgin#454]
72f0b003252d0c827e9fa5dcb31005ef4a51b036 fixes a serious issue (#449, it is impossible to connect unless updated to this rev), could you please tag it so maintainers can update downstream packages. :thumbsup:

**Comment by xvitaly** [comment]
> so maintainers can update downstream packages

Maintainers should use Git-builds for this plugin.

**Comment by EionRobb** [comment]
I'm planning on tagging a 1.2 version after I get the Live logins fixed.

**Comment by EionRobb** [comment]
https://github.com/EionRobb/skype4pidgin/releases/tag/v1.2
