### ISSUE TITLE
install error overwrite original file

### ISSUE THREAD

**Issue by peekaa** [EionRobb/skype4pidgin#455]
Hi, when doing last command of install in debian (sid), I got:
> root@linuxbox:~/skype4pidgin/skypeweb/build# dpkg -i skypeweb-1.1.0-Linux.deb
> (Reading database ... 174404 files and directories currently installed.)
> Preparing to unpack skypeweb-1.1.0-Linux.deb ...
> Unpacking skypeweb (1.1.0) ...
> dpkg: error processing archive skypeweb-1.1.0-Linux.deb (--install):
>  trying to overwrite '/usr/share/pixmaps/pidgin/protocols/16/skype.png', which is also in package pidgin-skype 20140930+svn665+dfsg-1
> Errors were encountered while processing:
>  skypeweb-1.1.0-Linux.deb

Thank you for help.

**Comment by peekaa** [comment]
its this: ` dpkg -i --force-overwrite skypeweb-1.1.0-Linux.deb `. You might like to update install instructions for debian. Thanks! :-)

**Comment by xvitaly** [comment]
@peekaa You have two different packages of this plugin installed: pidgin-skype and skypeweb. Remove both of them, then install new version.

**Comment by peekaa** [comment]
done, thank you.
