### ISSUE TITLE
Search friends url

### ISSUE THREAD

**Issue by spyjo** [EionRobb/skype4pidgin#458]
Hi,

In the skypeweb source code I see the url to search friends is /search/users/any , but in skypeweb I see this one:

https://skypegraph.skype.com/search/v1.1/namesearch/swx/?requestid=XXX&searchstring=YYY&locale=fr-fr

I suppose they have updated it and should be updated it in the plugin :)

Thanks

**Comment by spyjo** [comment]
In fact after looking a bit more, the current search url (api.skype.com/search/users/any) returns a 404 error. That's why I always have "Your search for the user "xxxx" returned no results", I did not understand why at first.
So the search url definitely need an update :)
The json returned for the results seems also a bit different that the current implementation.

**Comment by EionRobb** [comment]
Hmm... Haven't seen a "skypegraph" url before.  Interesting :)

Thanks for bringing this to my attention.  I'll have a go at throwing this in.

**Comment by EionRobb** [comment]
https://github.com/EionRobb/skype4pidgin/commit/5084a3e946cf890aa330cbaae4025591e0711e35 should do the trick

**Comment by spyjo** [comment]
Thanks I will try your patch tomorrow :)

**Comment by hotice** [comment]
It still doesn't work for me using the latest git. It looks like the search URL returns a 403 error. This is the output:

```
(13:24:23) dnsquery: Performing DNS lookup for skypegraph.skype.com
(13:24:23) dns: Successfully sent DNS request to child 30975
(13:24:23) dns: Got response for 'skypegraph.skype.com'
(13:24:23) dnsquery: IP resolved for skypegraph.skype.com
(13:24:23) proxy: Attempting connection to 23.101.135.34
(13:24:23) proxy: Connecting to skypegraph.skype.com:443 with no proxy
(13:24:23) proxy: Connection in progress
(13:24:23) proxy: Connecting to skypegraph.skype.com:443.
(13:24:23) proxy: Connected to skypegraph.skype.com:443.
(13:24:23) nss: SSL version 3.3 using 128-bit AES with 256-bit SHA256 MAC
Server Auth: 2048-bit RSA, Key Exchange: 256-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
(13:24:23) nss: subject=CN=skypegraph.skype.com issuer=CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US
(13:24:23) nss: subject=CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US issuer=CN=Baltimore CyberTrust Root,OU=CyberTrust,O=Baltimore,C=IE
(13:24:23) nss: partial certificate chain
(13:24:23) certificate/x509/tls_cached: Starting verify for skypegraph.skype.com
(13:24:23) certificate/x509/tls_cached: Checking for cached cert...
(13:24:23) certificate/x509/tls_cached: ...Found cached cert
(13:24:23) nss/x509: Loading certificate from /home/andrei/.purple/certificates/x509/tls_peers/skypegraph.skype.com
(13:24:23) certificate/x509/tls_cached: Peer cert matched cached
(13:24:23) nss/x509: Exporting certificate to /home/andrei/.purple/certificates/x509/tls_peers/skypegraph.skype.com
(13:24:23) util: Writing file /home/andrei/.purple/certificates/x509/tls_peers/skypegraph.skype.com
(13:24:23) nss: Trusting CN=skypegraph.skype.com
(13:24:23) certificate: Successfully verified certificate for skypegraph.skype.com
(13:24:23) skypeweb: post_or_get_ssl_connect_cb
dns[30924]: nobody needs me... =(
(13:24:23) skypeweb: Got response: HTTP/1.1 403 Forbidden
Keep-Alive: true
Content-Length: 0
Server: Microsoft-HTTPAPI/2.0
Date: Fri, 15 Jul 2016 10:24:22 GMT
Connection: close
```

**Comment by spyjo** [comment]
@EionRobb I think it doesn't work because the skype token is missing in the headers, and requestid (not requestId) should be a bit more populated (skype.com-VERSION_NUMBER-ran-dom-st-ri-ngs)

**Comment by EionRobb** [comment]
Whoops, I forgot to commit the bit with the skype token for the skypegraph server!
