### ISSUE TITLE
Skype avatars not fetched automatically

### ISSUE THREAD

**Issue by xvitaly** [EionRobb/skype4pidgin#459]
After last changes in SkypeWeb buddy avatars and status messages are not automatically fetched. Pidgin shows default avatar and empty status message for all online contacts, but if you click RMB on buddy and open Information window normal avatar and status text will be downloaded.

Before:
![skav](https://cloud.githubusercontent.com/assets/966711/16878054/d2a16180-4acc-11e6-9999-2fa76bba94d1.png)

After:
![e545](https://cloud.githubusercontent.com/assets/966711/16878125/29afb882-4acd-11e6-87ee-1ada89b1ddc3.png)

**Comment by EionRobb** [comment]
Hopefully resolved in https://github.com/EionRobb/skype4pidgin/releases/tag/1.3
