### ISSUE TITLE
skypeweb: skype account suspended

### ISSUE THREAD

**Issue by walidsa3d** [EionRobb/skype4pidgin#462]
My skype account got suspended shortly after I started using skypeweb, I had to change my password to get it back.

**Comment by dequis** [comment]
Did you use it to connect from a remote location, such as a VPS, or with something like bitlbee or spectrum?

**Comment by walidsa3d** [comment]
Not, I used it in Pidgin on my machine running Linux Mint.

**Comment by maxtros** [comment]
i'm using skypeweb plugin since 2016 and never had a problem like this, for me it works awesome

**Comment by CkNoSFeRaTU** [comment]
It just happened to me. I'm using skypeweb through spectrum2.
Today I had been blocked with continuous "Failed getting Skype Token" messages on login attempts.
Then I had tried to login with web.skype.com and was greeted with message like "for security reasons you must change your password". After changing the password all is back to normal.

Looks like frequent authorization attempts to skype servers triggers security check on their side as I'm updating ejabberd today and the were numerous server restarts.

**Comment by xvitaly** [comment]
Too many skypeweb users from same IP -> addidtional security checks.

**Comment by dequis** [comment]
Not much we can do about this, closing.
