### ISSUE TITLE
timestamps get processed for emoticons

### ISSUE THREAD

**Issue by alexolog** [EionRobb/skype4pidgin#463]
The emoticon substitution applies to timestamps as well

![issue](https://cloud.githubusercontent.com/assets/2112513/17037520/5cfc5268-4f5f-11e6-9b2e-c7a7c0221d8e.png)

**Comment by EionRobb** [comment]
Unfortunately the plugin doesn't have any control over that :(
https://developer.pidgin.im/ticket/3633 is the Pidgin bug about that

**Comment by LurkerHub** [comment]
That ticket is 8 years old.
