### ISSUE TITLE
Skypeweb v1.2.1: "Failed getting Skype Token" because of a missing dependency? [LinuxMint 17.3 x64]

### ISSUE THREAD

**Issue by TomTheDragon** [EionRobb/skype4pidgin#467]
I have the problem that the Skypeweb plugin dont want to connect on only one of my computers and this only happens to live accounts.
I use the same OS (LinuxMint 17.3 x64) on 3 different computers (one of them is a VM) but this "Failed getting Skype Token" error only occurs at one of them. I build the plugin myself and it seems to run fine on my other systems.
I also tryed precompiled packages and different versions of the plugin but i get always the same error.

So i was thinking that maybe there must be a dependency missing or so, could that be a possibility?

**Comment by xvitaly** [comment]
@TomTheDragon Upload full debug log.

**Comment by TomTheDragon** [comment]
(19:52:48) g_log: skypeweb_string_get_chunk: assertion 'chunk_start' failed
(19:52:48) skypeweb: login response was HTTP/1.1 404 Not Found
Server: nginx
Date: Sat, 13 Aug 2016 17:52:47 GMT
Content-Type: text/html; ver=1.0; charset=utf-8;
Connection: close
Set-Cookie: SC=CC=:CCY=:LC=en:LIM=:TM=1471110767:TS=1471110767:TZ=:VAT=:VER=; expires=Sun, 13-Aug-2017 17:52:47 GMT; Max-Age=31536000; path=/; domain=.skype.com
X-Stratus-Processing-Time: 0.0150
X-Skype-Request-Id: 3dbf70ef
X-Stratus-Request-Id: 3dbf70ef
Pragma: no-cache
Cache-Control: no-store, no-cache, must-revalidate
Expires: Thu, 01 Jan 1970 00:00:01 +0000
P3P: CP="CAO PSA OUR"
X-Frame-Options: SAMEORIGIN
X-Stratus-Config-Namespace: 
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000; includeSubDomains

<!DOCTYPE html><html class="noTabletState ltr " lang="en" dir="ltr"><head><meta charset="utf-8"/><meta content="text/html; charset=utf-8" http-equiv="content-type"/><meta content="IE=edge" http-equiv="X-UA-Compatible"/><title>Page not found</title><meta content="width=device-width, initial-scale=1" name="viewport"/><style type="text/css">@-webkit-viewport{width:device-width;} @-moz-viewport{width:device-width;} @-ms-viewport{width:device-width;} @-o-viewport{width:device-width;} @viewport{width:device-width;}</style><script type="text/javascript">/*<![CDATA[*/    (function() {
        if ("-ms-user-select" in document.documentElement.style && navigator.userAgent.match(/IEMobile\/10\.0/)) {
            var msViewportStyle = document.createElement("style");
            msViewportStyle.appendChild(
                document.createTextNode("@-ms-viewport{width:auto!important}")
            );
            document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
        }
    })(); 
    /*]]>*/</script><link rel="icon" type="image/vnd.microsoft.icon" href="https://apps.skypeassets.com/static/2.1.0/skype.login/images/icons/favicon.ico"/><link rel="shortcut icon" href="https://apps.skypeassets.com/static/2.1.0/skype.login/images/icons/favicon.ico"/><link rel="apple-touch-icon" href="https://apps.skypeassets.com/static/2.1.0/skype.login/images/logos/skype_webclip.png"/><link rel="stylesheet" type="text/css" media="screen" href="https://apps.skypeassets.com/static/2.1.0/skype.login/css/reset.css;fonts.css;responsiveness.css;buttons.css;navigation.css"/><link rel="stylesheet" type="text/css" media="screen" href="https://apps.skypeassets.com/static/2.1.0/skype.login/css/base.css;layout.css;emoticons.css"/><script src="https://apps.skypeassets.com/static/2.1.0/skype.login/js/jquery.js;skype.js;language.js"></script><meta content="noindex,nofollow" name="robots"/></head><body><div class="pageWrap"><div class="skypeLogo"><span class="skypeLogoImage"></span></div><header class="pageTitle"><div class="subContent"><h1>Page not found</h1></div></header><div class="fancyContainer" id="container" role="main"><div class="contentBlock"><div class="loginContainer"><div class="cell"><div class="emoticonWrapper emoWrapErrorPage"><div class="emoticon center emo-160 itwasntme" data-align="center" data-emoticon-name="itwasntme" data-mode="animated" data-size="160"></div></div><div class="mobileCenter"><p class="semibold" tabindex="0">We're sorry - The page you were looking for could not be found.</p><p tabindex="0">You can try the following:</p><ul class="discs"><li><a href="https://go.skype.com/myaccount">Access your account</a></li><li><a href="https://go.skype.com/download">Download Skype</a></li><li><a href="https://go.skype.com/products">See our products page</a></li><li><a href="https://go.skype.com/home">Go to Skype.com homepage</a></li></ul></div></div></div></div></div><footer class="footer"><div class="footer_app"><form class="language-selector" method="get" action="https://login.skype.com/login"><span class="language-selector_selected" id="selectedLanguage">English</span><div><select class="language-selector_picker" name="setlang" id="languageSelector" title="Language" aria-label="Language"><option value="en" lang="en" label="English" selected="selected">English</option><option value="ar" lang="ar" label="عربي">عربي</option><option value="bg" lang="bg" label="Български">Български</option><option value="cs" lang="cs" label="Česky">Česky</option><option value="da" lang="da" label="Dansk">Dansk</option><option value="de" lang="de" label="Deutsch">Deutsch</option><option value="el" lang="el" label="Ελληνικά">Ελληνικά</option><option value="es" lang="es" label="Español">Español</option><option value="et" lang="et" label="Eesti">Eesti</option><option value="fi" lang="fi" label="Suomi">Suomi</option><option value="fr" lang="fr" label="Français">Français</option><option value="he" lang="he" label="עברית">עברית</option><option value="hi" lang="hi" label="हिन्दी">हिन्दी</option><option value="hu" lang="hu" label="Magyar">Magyar</option><option value="id" lang="id" label="Bahasa Indonesia">Bahasa Indonesia</option><option value="it" lang="it" label="Italiano">Italiano</option><option value="ja" lang="ja" label="日本語">日本語</option><option value="ko" lang="ko" label="한국어">한국어</option><option value="nl" lang="nl" label="Nederlands">Nederlands</option><option value="no" lang="no" label="Norsk">Norsk</option><option value="pl" lang="pl" label="Polski">Polski</option><option value="pt-PT" lang="pt-PT" label="Português">Português</option><option value="pt-BR" lang="pt-BR" label="Português (Brasileiro)">Português (Brasileiro)</option><option value="ro" lang="ro" label="Română">Română</option><option value="ru" lang="ru" label="Русский">Русский</option><option value="sv" lang="sv" label="Svenska">Svenska</option><option value="tr" lang="tr" label="Türkçe">Türkçe</option><option value="uk" lang="uk" label="Українська">Українська</option><option value="zh-Hans" lang="zh-Hans" label="中文（简体)">中文（简体)</option><option value="zh-Hant" lang="zh-Hant" label="中文 (繁體)">中文 (繁體)</option></select></div></form></div><div class="footer_legal"><a class="footer_link" target="_blank" href="https://go.skype.com/tou">Terms of use</a><div class="footer_separator">·</div><a class="footer_link" href="https://go.skype.com/privacy">Privacy and cookie policy</a><div class="footer_separator">·</div><span id="copyright">© 2016 Skype and/or Microsoft.</span></div></footer><script type="text/javascript">            SKYPE.namespace("emoticons");
            SKYPE.emoticons.path = "https://apps.skypeassets.com/static/2.1.0/skype.login/images/emoticons";
        </script><script src="https://apps.skypeassets.com/static/2.1.0/skype.login/js/hotfix.js;emoticons.js"></script><script type="text/javascript">var varSegmentation = 0;
var varClickTracking = 0;
var varCustomerTracking = 1;
var varAutoFirePV = 0;
var Route = "16160";
var Ctrl = null;
var _wedcs_vars = {};
/*<![CDATA[*/
document.write("<script type='text/javascript' src='" + (window.location.protocol) + "//i.s-microsoft.com/wedcs/ms.js'" + "><\/script>");
/*]]>*/
function _wedcs_customevent(trackingProps) {
    if (typeof window.MscomCustomEvent !== 'function') {
        return;
    }

    if (typeof trackingProps === "string") {
        if (!_wedcs_vars.hasOwnProperty(trackingProps)) {
            return;
        }
        trackingProps = _wedcs_vars[trackingProps];
    }

    if (!trackingProps.hasOwnProperty('ms.rwd')) {
        /*<![CDATA[*/
        var responsive = 'desktop';
        if (typeof(Portal) !== 'undefined' && typeof(Portal.Detection) !== 'undefined') {
            responsive = Portal.Detection.getDeviceType();
        }
        /*]]>*/
        trackingProps['ms.rwd'] = responsive;
    }

    var args = [];
    for (var prop in trackingProps) {
        if (trackingProps.hasOwnProperty(prop)) {
            args.push(prop);
            args.push(trackingProps[prop]);
        }
    }
    MscomCustomEvent.apply(window, args);
}
function _wedcs_add_action(name, event) {
    if (event.providerId === 'composite') {
        for (var item in event.items) {
            _wedcs_add_action(name, event.items[item]);
        }
    } else if (event.providerId === 'wedcs') {
        _wedcs_vars[name] = event.params;
    }
}
</script><noscript><img src="http://c.microsoft.com/trans_pixel.aspx" width="1" height="1" alt=""/></noscript> <script type="text/javascript">_wedcs_vars['_load'] = {"ms.pagetype" : "404", "ms.env" : "prod", "ms.skypepn" : "skypeloginweb/error/not-found", "ms.lang" : "en", "ms.prod" : "Skype", "wcs.cot" : "0"};</script><script type="text/javascript">_wedcs_customevent('_load');</script><script type="text/javascript">/*<![CDATA[*/function _skype_track_action(actionId) {
    if (typeof s !== 'undefined' && typeof window[actionId] !== 'undefined') {
        s.trackAction(window[actionId]);
    }
    if (typeof _wedcs_customevent !== 'undefined') {
        _wedcs_customevent(actionId);
    }
}
function _skype_add_action(name, event) {
    if (typeof _omniture_add_action != 'undefined') {
        _omniture_add_action(name, event);
    }
    if (typeof _wedcs_add_action != 'undefined') {
        _wedcs_add_action(name, event);
    }
}
/*]]>*/</script></div></body></html>
(19:52:48) skypeweb: getting url /logout
(19:52:48) skypeweb: sending headers:
GET /logout HTTP/1.0
Host: login.skype.com
Connection: close
Accept: */*
Cookie: 
Accept-Encoding: gzip
Accept-Language: de-DE.UTF-8, de-DE, de.UTF-8, de, C


(19:52:48) skypeweb: destroying 0 waiting connections
(19:52:48) skypeweb: destroying 1 incomplete connections

**Comment by EionRobb** [comment]
Unfortunately that's not quite enough of the debug log to know what's going on but it could be from not having 1.2.1 of the plugin installed e.g. if you have two copies of the plugin accidentally, one old one new. 

Can you look in Help->Plugin Info (from the buddy list) to confirm what version of the plugin you have installed?

**Comment by dequis** [comment]
@TomTheDragon poke

**Comment by TomTheDragon** [comment]
Oh yeah sorry i totally forget to answer >.-.>

Yeah Pidgin was using an much older version from one of the multiple packages i had installed and did not know about.. but it was working fine after removing all the older packages.

**Comment by dequis** [comment]
Neat!
