### ISSUE TITLE
HTML entities in status message on buddy list

### ISSUE THREAD

**Issue by snackiz** [EionRobb/skype4pidgin#471]
When I set a status message containing special characters, I see the html entity for it in the buddy list, but if I hover over the contact, the message is shown as intended in the popup. See image.
![skypeweb-status-htmlentities](https://cloud.githubusercontent.com/assets/12606941/18345595/71b1f8e2-75bc-11e6-8615-1412a9fd73c8.png)

**Comment by snackiz** [comment]
This is also true for smilies, showing up in the buddy list as <ss type="smile">:-)</ss> and in the popup as :-)

**Comment by EionRobb** [comment]
I think I've fixed this now in one of the latest commits, if you're able to try?

**Comment by EionRobb** [comment]
https://github.com/EionRobb/skype4pidgin/releases/tag/1.3 includes a fix for this
