### ISSUE TITLE
New to Pidgin - Failed getting Registration Token

### ISSUE THREAD

**Issue by Brancliff** [EionRobb/skype4pidgin#475]
I've never used Pidgin before, just picked it up today. I downloaded the skype .exe installer at http://eion.robbmob.com/ and it worked smoothly.

However, when I enter my skype login on the account info on the account window, I get an error message on the main pidgin window. It says:

[username] disabled
Failed getting Registration Token

What does this mean and how can I fix it?

**Comment by EionRobb** [comment]
Can you get a debug log as you connect?

To do this, open the Help->Debug Window (from the buddy list) then try to reconnect to the account, then copy-paste the output of the debug window here.

Just to check off a few things, you're using Pidgin 2.11.0, and you can login to https://web.skype.com/ from your browser without trouble?

**Comment by Brancliff** [comment]
(13:55:48) util: Writing file prefs.xml to directory C:\Users\Brancliff-LT\AppData\Roaming\.purple
(13:55:48) util: Writing file C:\Users\Brancliff-LT\AppData\Roaming\.purple\prefs.xml
(13:55:51) account: Connecting to account boometh.
(13:55:51) connection: Connecting. gc = 03D1C970
(13:55:51) util: requesting to fetch a URL
(13:55:51) dnsquery: Performing DNS lookup for login.skype.com
(13:55:51) dnsquery: IP resolved for login.skype.com
(13:55:51) proxy: Attempting connection to 91.190.216.77
(13:55:51) proxy: Connecting to login.skype.com:443 with no proxy
(13:55:51) proxy: Connection in progress
(13:55:51) proxy: Connecting to login.skype.com:443.
(13:55:51) proxy: Connected to login.skype.com:443.
(13:55:52) nss: SSL version 3.3 using 256-bit AES with 160-bit SHA1 MAC
Server Auth: 2048-bit RSA, Key Exchange: 2048-bit RSA, Compression: NULL
Cipher Suite Name: TLS_RSA_WITH_AES_256_CBC_SHA
(13:55:52) nss: subject=CN=login.skype.com,O=Skype,L=Dublin,C=IE issuer=CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US
(13:55:52) nss: subject=CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US issuer=CN=Baltimore CyberTrust Root,OU=CyberTrust,O=Baltimore,C=IE
(13:55:52) nss: partial certificate chain
(13:55:52) certificate/x509/tls_cached: Starting verify for login.skype.com
(13:55:52) certificate/x509/tls_cached: Checking for cached cert...
(13:55:52) certificate/x509/tls_cached: ...Found cached cert
(13:55:52) nss/x509: Loading certificate from C:\Users\Brancliff-LT\AppData\Roaming\.purple\certificates\x509\tls_peers\login.skype.com
(13:55:52) certificate/x509/tls_cached: Peer cert matched cached
(13:55:52) nss/x509: Exporting certificate to C:\Users\Brancliff-LT\AppData\Roaming\.purple\certificates\x509\tls_peers\login.skype.com
(13:55:52) util: Writing file C:\Users\Brancliff-LT\AppData\Roaming\.purple\certificates\x509\tls_peers\login.skype.com
(13:55:52) nss: Trusting CN=login.skype.com,O=Skype,L=Dublin,C=IE
(13:55:52) certificate: Successfully verified certificate for login.skype.com
(13:55:52) util: request constructed
(13:55:52) util: Response headers: 'HTTP/1.1 200 OK

Server: nginx

Date: Thu, 22 Sep 2016 20:55:50 GMT

Content-Type: text/html; ver=1.0; charset=utf-8;

Connection: close

Set-Cookie: ecs-passwordRecovery=57e4455681e7d; expires=Sat, 22-Oct-2016 20:55:50 GMT; Max-Age=2592000; path=/

Set-Cookie: SC=CC=:CCY=:LC=en:LIM=:TM=1474577750:TS=1474577750:TZ=:VAT=:VER=; expires=Fri, 22-Sep-2017 20:55:50 GMT; Max-Age=31536000; path=/; domain=.skype.com

Set-Cookie: frmrgtpe=3-1; path=/; domain=.skype.com

X-Stratus-Processing-Time: 0.0754

X-Skype-Request-Id: 543fb496

X-Stratus-Request-Id: 543fb496

P3P: CP="CAO PSA OUR"

Pragma: no-cache

Cache-Control: no-store, no-cache, must-revalidate

Expires: Thu, 01 Jan 1970 00:00:01 +0000

X-Skype-Ecs: passwordRecovery=passwordRecovery

X-Frame-Options: DENY

X-Stratus-Config-Namespace: 

X-Content-Type-Options: nosniff

X-Processing-Time: 0.088

Strict-Transport-Security: max-age=31536000; includeSubDomains



'
(13:55:52) util: requesting to fetch a URL
(13:55:52) dnsquery: Performing DNS lookup for login.skype.com
(13:55:52) dnsquery: IP resolved for login.skype.com
(13:55:52) proxy: Attempting connection to 91.190.216.77
(13:55:52) proxy: Connecting to login.skype.com:443 with no proxy
(13:55:52) proxy: Connection in progress
(13:55:52) proxy: Connecting to login.skype.com:443.
(13:55:52) proxy: Connected to login.skype.com:443.
(13:55:53) nss: SSL version 3.3 using 256-bit AES with 160-bit SHA1 MAC
Server Auth: 2048-bit RSA, Key Exchange: 2048-bit RSA, Compression: NULL
Cipher Suite Name: TLS_RSA_WITH_AES_256_CBC_SHA
(13:55:53) nss: subject=CN=login.skype.com,O=Skype,L=Dublin,C=IE issuer=CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US
(13:55:53) nss: partial certificate chain
(13:55:53) certificate/x509/tls_cached: Starting verify for login.skype.com
(13:55:53) certificate/x509/tls_cached: Checking for cached cert...
(13:55:53) certificate/x509/tls_cached: ...Found cached cert
(13:55:53) nss/x509: Loading certificate from C:\Users\Brancliff-LT\AppData\Roaming\.purple\certificates\x509\tls_peers\login.skype.com
(13:55:53) certificate/x509/tls_cached: Peer cert matched cached
(13:55:53) nss/x509: Exporting certificate to C:\Users\Brancliff-LT\AppData\Roaming\.purple\certificates\x509\tls_peers\login.skype.com
(13:55:53) util: Writing file C:\Users\Brancliff-LT\AppData\Roaming\.purple\certificates\x509\tls_peers\login.skype.com
(13:55:53) nss: Trusting CN=login.skype.com,O=Skype,L=Dublin,C=IE
(13:55:53) certificate: Successfully verified certificate for login.skype.com
(13:55:53) util: request constructed
(13:55:53) util: Response headers: 'HTTP/1.1 200 OK

Server: nginx

Date: Thu, 22 Sep 2016 20:55:51 GMT

Content-Type: text/html; ver=1.0; charset=utf-8;

Content-Length: 3886

Connection: keep-alive

Set-Cookie: ecs-passwordRecovery=57e445578544d; expires=Sat, 22-Oct-2016 20:55:51 GMT; Max-Age=2592000; path=/

Set-Cookie: SC=CC=:CCY=:LC=en:LIM=:TM=1474577751:TS=1474577751:TZ=:VAT=:VER=; expires=Fri, 22-Sep-2017 20:55:51 GMT; Max-Age=31536000; path=/; domain=.skype.com

Set-Cookie: frmrgtpe=3-1; path=/; domain=.skype.com

Set-Cookie: login-vi=7d9c400bfe51ee97c36bfd7ddc3e4a44; path=/

Set-Cookie: kmsi=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/

Set-Cookie: login-vi=699bc05ae70621fddd4869997710a3b4; path=/

Set-Cookie: login-bt=578134; expires=Fri, 23-Sep-2016 20:56:51 GMT; Max-Age=86460; path=/; secure; HttpOnly

Set-Cookie: refresh-token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjIifQ.eyJpYXQiOjE0NzQ1Nzc3NTEsImV4cCI6MTQ3NzE2OTc1MSwic2t5cGVpZCI6ImJvb21ldGgiLCJzY3AiOjEsImNzaSI6IjEiLCJjaWQiOiI3ZjFmMmQ5NDE5ZWE0MGI2IiwiYWF0IjoxNDc0NTc3NzUxfQ.VWLVNYm1dgAugEGnCMgMyazzem2cMRkBgyqJz1OPttUVaHuaOjF8238zHqaCdhCAReJzV54kmJS5HGmMZBLsCqqf2vPhJTu6sPfUsvW2c8om_JTB9I55uwrlnPe8x9GtdaMmBALw4C8FIe06mY5dEQWcUMs0sumvLqgYHN3YiuKdxjmHOOObuf3ORFtmQGl1gyyBs35iROiHe5-7; path=/; secure; HttpOnly

Set-Cookie: skplet=1477169751; path=/; domain=.skype.com

Set-Cookie: lastLogin=SK; expires=Tue, 21-Mar-2017 20:55:51 GMT; Max-Age=15552000; path=/

X-Stratus-Processing-Time: 0.0836

X-Skype-Request-Id: ffde9b17

X-Stratus-Request-Id: ffde9b17

P3P: CP="CAO PSA OUR"

Pragma: no-cache

Cache-Control: no-store, no-cache, must-revalidate

Expires: Thu, 01 Jan 1970 00:00:01 +0000

X-Frame-Options: DENY

X-Stratus-Config-Namespace: 

X-Content-Type-Options: nosniff

X-Processing-Time: 0.091

Strict-Transport-Security: max-age=31536000; includeSubDomains



'
(13:55:53) util: parsed 3886
(13:55:53) util: requesting to fetch a URL
(13:55:53) dnsquery: Performing DNS lookup for client-s.gateway.messenger.live.com
(13:55:53) dnsquery: IP resolved for client-s.gateway.messenger.live.com
(13:55:53) proxy: Attempting connection to 65.52.108.76
(13:55:53) proxy: Connecting to client-s.gateway.messenger.live.com:443 with no proxy
(13:55:53) proxy: Connection in progress
(13:55:53) proxy: Connecting to client-s.gateway.messenger.live.com:443.
(13:55:53) proxy: Connected to client-s.gateway.messenger.live.com:443.
(13:55:53) nss: SSL version 3.3 using 128-bit AES with 256-bit SHA256 MAC
Server Auth: 2048-bit RSA, Key Exchange: 256-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
(13:55:53) nss: subject=CN=apis.skype.com issuer=CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US
(13:55:53) nss: subject=CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US issuer=CN=Baltimore CyberTrust Root,OU=CyberTrust,O=Baltimore,C=IE
(13:55:53) nss: partial certificate chain
(13:55:53) certificate/x509/tls_cached: Starting verify for client-s.gateway.messenger.live.com
(13:55:53) certificate/x509/tls_cached: Checking for cached cert...
(13:55:53) certificate/x509/tls_cached: ...Found cached cert
(13:55:53) nss/x509: Loading certificate from C:\Users\Brancliff-LT\AppData\Roaming\.purple\certificates\x509\tls_peers\client-s.gateway.messenger.live.com
(13:55:54) certificate/x509/tls_cached: Peer cert matched cached
(13:55:54) nss/x509: Exporting certificate to C:\Users\Brancliff-LT\AppData\Roaming\.purple\certificates\x509\tls_peers\client-s.gateway.messenger.live.com
(13:55:54) util: Writing file C:\Users\Brancliff-LT\AppData\Roaming\.purple\certificates\x509\tls_peers\client-s.gateway.messenger.live.com
(13:55:54) nss: Trusting CN=apis.skype.com
(13:55:54) certificate: Successfully verified certificate for client-s.gateway.messenger.live.com
(13:55:54) util: request constructed
(13:55:54) util: Response headers: 'HTTP/1.1 201 Created

Cache-Control: no-store, must-revalidate, no-cache

Keep-Alive: true

Pragma: no-cache

Content-Length: 2

Content-Type: application/json; charset=utf-8

Location: https://bn2-client-s.gateway.messenger.live.com/v1/users/ME/endpoints/%7B240071b8-e553-4c24-9e62-ccb4034f5b84%7D

X-Content-Type-Options: nosniff

Set-RegistrationToken: registrationToken=U2lnbmF0dXJlOjI6Mjg6QVFRQUFBQjVIakxGZU1wNDZsSnoza1NteHhFZTtWZXJzaW9uOjY6MToxO0lzc3VlVGltZTo0OjE5OjUyNDc3ODc3NjM5NTA1NTU2OTc7RXAuSWRUeXBlOjc6MToxO0VwLklkOjI6Mzc6Y2lkLSg5MTYwMDkwMjgxMjA4MDcwMzI2KUBvdXRsb29rLmNvbTtFcC5FcGlkOjU6MzY6MjQwMDcxYjgtZTU1My00YzI0LTllNjItY2NiNDAzNGY1Yjg0O0VwLkxvZ2luVGltZTo3OjE6MDtFcC5BdXRoVGltZTo0OjE5OjUyNDc3ODc3NjM5NTAzOTk0NTI7RXAuQXV0aFR5cGU6NzoyOjE1O0VwLkV4cFRpbWU6NDoxODo2MzYxMDI2MDk1MTAwMDAwMDA7VXNyLk5ldE1hc2s6MTE6MTozO1Vzci5YZnJDbnQ6NjoxOjA7VXNyLlJkcmN0RmxnOjI6MDo7VXNyLkV4cElkOjk6MTowO1Vzci5FeHBJZExhc3RMb2c6NDoxOjA7VXNlci5BdGhDdHh0OjI6Mjc2OkNsTnJlWEJsVkc5clpXNGxZMmxrTFNnNU1UWXdNRGt3TWpneE1qQTRNRGN3TXpJMktVQnZkWFJzYjI5ckxtTnZiUUVEVldsakZERXZNUzh3TURBeElERXlPakF3T2pBd0lFRk5ERTV2ZEZOd1pXTnBabWxsWkxaQTZobVVMUjkvQUFBQUFBQUFRQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQWRpYjI5dFpYUm9BQUFBQUFBQUFBQUFCMDV2VTJOdmNtVUFBQUFBQkFBQUFBQUFBQUFBQUFBQXRrRHFHWlF0SDM4QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFFSFltOXZiV1YwYUFBQUFBQUFBQUFBQUE9PTs=; expires=1474664152; endpointId={240071b8-e553-4c24-9e62-ccb4034f5b84}

ContextId: tcid=6710536398919549586,server=BN3SCH030022458

Date: Thu, 22 Sep 2016 20:55:52 GMT

Connection: close



'
(13:55:54) util: Redirecting to  https://bn2-client-s.gateway.messenger.live.com/v1/users/ME/endpoints/%7B240071b8-e553-4c24-9e62-ccb4034f5b84%7D
(13:55:54) g_log: skypeweb_string_get_chunk: assertion `haystack && start && end' failed
(13:55:54) g_log: skypeweb_string_get_chunk: assertion `haystack && start && end' failed
(13:55:54) g_log: skypeweb_string_get_chunk: assertion `haystack && start && end' failed
(13:55:54) g_log: skypeweb_string_get_chunk: assertion `haystack && start && end' failed
(13:55:54) connection: Connection error on 03D1C970 (reason: 2 description: Failed getting Registration Token)
(13:55:54) account: Disconnecting account boometh (020DAAE0)
(13:55:54) connection: Disconnecting connection 03D1C970
(13:55:54) GLib: g_source_remove: assertion `tag > 0' failed
(13:55:54) GLib: g_source_remove: assertion `tag > 0' failed
(13:55:54) GLib: g_source_remove: assertion `tag > 0' failed
(13:55:54) skypeweb: getting url /logout
(13:55:54) skypeweb: sending headers:
GET /logout HTTP/1.0

Host: login.skype.com

Connection: close

Accept: */*

Cookie: ecs-passwordRecovery=57e445578544d;frmrgtpe=3-1;skplet=1477169751;login-vi=699bc05ae70621fddd4869997710a3b4;login-bt=578134;lastLogin=SK;kmsi=deleted;SC=CC=:CCY=:LC=en:LIM=:TM=1474577751:TS=1474577751:TZ=:VAT=:VER=;refresh-token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjIifQ.eyJpYXQiOjE0NzQ1Nzc3NTEsImV4cCI6MTQ3NzE2OTc1MSwic2t5cGVpZCI6ImJvb21ldGgiLCJzY3AiOjEsImNzaSI6IjEiLCJjaWQiOiI3ZjFmMmQ5NDE5ZWE0MGI2IiwiYWF0IjoxNDc0NTc3NzUxfQ.VWLVNYm1dgAugEGnCMgMyazzem2cMRkBgyqJz1OPttUVaHuaOjF8238zHqaCdhCAReJzV54kmJS5HGmMZBLsCqqf2vPhJTu6sPfUsvW2c8om_JTB9I55uwrlnPe8x9GtdaMmBALw4C8FIe06mY5dEQWcUMs0sumvLqgYHN3YiuKdxjmHOOObuf3ORFtmQGl1gyyBs35iROiHe5-7;

Accept-Encoding: gzip

Accept-Language: en, C




(13:55:54) dnsquery: Performing DNS lookup for login.skype.com
(13:55:54) skypeweb: destroying 0 waiting connections
(13:55:54) skypeweb: destroying 1 incomplete connections
(13:55:54) connection: Destroying connection 03D1C970
(13:55:57) util: Writing file accounts.xml to directory C:\Users\Brancliff-LT\AppData\Roaming\.purple
(13:55:57) util: Writing file C:\Users\Brancliff-LT\AppData\Roaming\.purple\accounts.xml

I'm using the newest version of Pidgin from he website (as I just downloaded it yesterday) and Skype web works fine.

**Comment by EionRobb** [comment]
Can you try again with v1.2.1 from https://github.com/EionRobb/skype4pidgin/releases/tag/1.2.1

**Comment by Brancliff** [comment]
It works now, thanks!

Is there any way I can hide users on the list, or only show certain ones?

**Comment by EionRobb** [comment]
You could move buddies into a different group and just collapse that group.

Glad to hear it's going alright.
