### ISSUE TITLE
Can't connect with account live/microsoft  

### ISSUE THREAD

**Issue by ndias** [EionRobb/skype4pidgin#478]
In the logs I get this ...

(13:58:17) g_log: skypeweb_string_get_chunk: assertion 'chunk_start' failed
(13:58:17) connection: Connection error on 0x55927cbec400 (reason: 2 description: Failed getting Magic T value)

Using Fedora 24, with pidgin-2.11.0-1.fc24.x86_64 and the lastest skype4pidgin (master) compiled by me.

**Comment by xvitaly** [comment]
> Using Fedora 24, with pidgin-2.11.0-1.fc24.x86_64 and the lastest skype4pidgin (master) compiled by me.

Under Fedora you can use purple-skypeweb package from Fedora's repository. Upload full debug log.

**Comment by ndias** [comment]
I was using the package from Fedora, but I had the same problem, and even the skype account had some problems, that's the reason I compile the master version.

So can we try to debug the problem with the version I compiled? 

log attached

**Comment by ndias** [comment]
And now the log ... 
[skypeweb.txt](https://github.com/EionRobb/skype4pidgin/files/516250/skypeweb.txt)

**Comment by xvitaly** [comment]
> I was using the package from Fedora, but I had the same problem, and even the skype account had some problems, that's the reason I compile the master version.

Version in Fedora is the same as in Git (except support of notifications plugin).

> So can we try to debug the problem with the version I compiled? 

Yes, of cource.

> And now the log ... 

2FA enabled on your Microsoft Account?

**Comment by ndias** [comment]
Ok, sorry about the noise, it seems I need to login in my mail account and then the login works :(
