### ISSUE TITLE
Unable to transfer files [v1.2.2]

### ISSUE THREAD

**Issue by maxtros** [EionRobb/skype4pidgin#484]
Hi eion... using the lasted plugin 1.2.2 (and older too) its impossible to transfer files, in all cases you get this error:

Error al leer de nus1-api.asm.skype.com: la respuesta es demasiado larga (el límite es 69 bytes)

On english its like... Reading error from nus1-api.asm.skype.com: the answer its too long (the limit its 69 bytes)

Thanks 4 all your work

**Comment by EionRobb** [comment]
See #423
