### ISSUE TITLE
"Failed getting Skype Token" again

### ISSUE THREAD

**Issue by cypa** [EionRobb/skype4pidgin#485]
Ubuntu 14.04, libskypeweb 1.2.1 and 1.2.2 behaves same, chromium and firefox login to http://web.skype.com like a charm, but honestly I've not found any TOS and security question on account pages
debug log attached - I see complaints there about no javascript in the browser
[debug.txt](https://github.com/EionRobb/skype4pidgin/files/534405/debug.txt)

**Comment by Linkandzelda** [comment]
This should be fixed with the latest release a couple of days ago, at least it fixed my issue which was the same as yours, related to a changed account login flow or something

**Comment by dequis** [comment]
The "no javascript" thing just appears in every page, ignore that. But the page itself (if you copy it, save it as an html file, and open it in a browser) is a normal login form with no errors.

From irc, cypa said it's a skype username based account.

@Linkandzelda That latest release is 1.2.2, which cypa is using.

**Comment by EionRobb** [comment]
@cypa can you look in (from the buddy list) Help->Plugin Information and scroll down to "Skype (HTTP)" (about half way down) and double check the version?  From the debug log it looks like you're still trying to use the old login in 1.2.1

**Comment by Rydian** [comment]
Had this issue as well today, checked that and it said 1.1, despite having run the installer today to update.  So I went into the plugins directory and found both the normal and -debug DLLs existing.  I manually deleted both, ran the latest installer again, and all is good.

**Comment by cypa** [comment]
@EionRobb somthing strange there is 
```
Skype (HTTP)
	Author: Eion Robb <eionrobb@gmail.com>
	Version: 1.1
	Website: http://github.com/EionRobb/skype4pidgin
	ID String: prpl-skypeweb
	Loadable: Yes
	Loaded: Yes
```

**Comment by cypa** [comment]
btw all skype libs are newly compiled 1.2.2
```
find /usr/lib/ -name *skype* -exec ls -l {} \;
-rwxr-xr-x 1 root root 237287 Oct 17 22:35 /usr/lib/purple-2/libskypenet.so
-rw-r--r-- 1 root root 185337 Oct 17 22:35 /usr/lib/purple-2/libskype.so
-rw-r--r-- 1 root root 108113 Oct 17 22:35 /usr/lib/purple-2/libskype.c
-rw-r--r-- 1 root root 173012 Oct 17 22:35 /usr/lib/purple-2/libskype_dbus.so
-rw-r--r-- 1 root root 338396 Oct 17 22:41 /usr/lib/purple-2/libskypeweb.so
```

**Comment by EionRobb** [comment]
@cypa Open the debug log (Help->Debug Window) then leave that open and open the plugins list (Tools->Plugins) then close the plugins list, and copy-paste the output of the debug window... that should show where all the copies of skypeweb are being loaded from - there could also be one hiding in ~/.purple/plugins or /usr/lib/pidgin/

**Comment by cypa** [comment]
@EionRobb my mystake due to cmd line autocompletion cause 1.1 and 1.2.2 src directories are in the same dir
```
$ ls -dl skype4pidgin*
drwxrwxr-x 10 cypa cypa 4096 окт.  17 22:34 skype4pidgin
drwxrwxr-x  9 cypa cypa 4096 окт.  16 04:40 skype4pidgin-1.2.2
```
recompiled and logged in OK now ... thanks
