### ISSUE TITLE
Reconnect not working after the latest fix from a few days ago

### ISSUE THREAD

**Issue by Linkandzelda** [EionRobb/skype4pidgin#486]
A few days ago there was a fix posted for the "Failed Getting Skype Token" error on login, I believe related to the Microsoft account login flow. Up until a few days ago and before this fix was released things were working fine. I'd get random "token" errors which were happening daily but I considered them normal, and after I would get an automatic reconnect.

It seems that after this new token fix it does not want to reconnect automatically.

**Comment by dequis** [comment]
What error does it throw when it fails to reconnect?

**Comment by Linkandzelda** [comment]
I don't have any debug logs currently but based on the output it seems to disconnect and throw back into "authentication".

> [17:08:36]  <root>	skypeweb - Authenticating
> [17:08:37]  <root>	skypeweb - Error: Failed getting Skype Token
> [17:08:37]  <root>	skypeweb - Signing off..

Compared to how it used to behave last week before the fix was released:

> [2016-10-07T16:02:08+0100] <root> skypeweb - Error: Failed getting Registration Token
> [2016-10-07T16:02:08+0100] <root> skypeweb - Signing off..
> [2016-10-07T16:02:08+0100] <root> skypeweb - Reconnecting in 5 seconds..
> [2016-10-07T16:02:13+0100] <root> skypeweb - Logging in: Connecting
> [2016-10-07T16:02:14+0100] <root> skypeweb - Logging in: Authenticating
> [2016-10-07T16:02:16+0100] <root> skypeweb - Logging in: Logged in

It's hard to pinpoint since it disconnects at random

**Comment by EionRobb** [comment]
Do you have the account marked as saving the password?  I'm not sure how bitlbee-purple enables that setting, but @dequis might know :)

**Comment by dequis** [comment]
Yeah it's possible it's always false in bitlbee

**Comment by Linkandzelda** [comment]
I'm not sure honestly, first that I've heard, since bitlbee always saves passwords, or at least it doesn't ever ask for a password after adding my accounts to it. Whether that is the same I don't know.

**Comment by EionRobb** [comment]
Ugh, probably shouldn't have done https://github.com/EionRobb/skype4pidgin/commit/a000b9e1317b807301050358fd6d33b36cdd7556 then.... going to end up affecting all bitlbee users

**Comment by dequis** [comment]
Is there any downside other than going through a longer auth path every time? (and, well, higher likelihood of hitting stupid error with stupid reconnect behavior?)

**Comment by kendoori** [comment]
Am running into similar issues. Am running Pidgin 2.10.9 on Linux Mint 17.3 64-bit. This was previously working. I've attached the debug log.
[purple-debug.txt](https://github.com/EionRobb/skype4pidgin/files/537639/purple-debug.txt)

**Comment by dequis** [comment]
@kendoori can you look in (from the buddy list) Help->Plugin Information and scroll down to "Skype (HTTP)" (about half way down) and double check the version? You need 1.2.2

**Comment by kendoori** [comment]
@dequis Thanks I recompiled and all is good again.

**Comment by Linkandzelda** [comment]
I undid the changes done in that remember password commit, though I still have the problem. Maybe it's something to do with the new login flow instead?

**Comment by maxtros** [comment]
I have to admit...at least on pidgin..lastest debug versions its working great...i had only a few disconnects and almost all reconnects okay.

**Comment by markspiller** [comment]
Having a perhaps related problem - downloaded the windows pidgin-skypeweb installer, and installed, but I'm still getting Skype (HTTP) 1.0 in the plugin list.  Have gone through looking for any old libskype* files, but no luck...  And getting a "Failed getting Skype Token" error when I try to log in.  Any thoughts?  Thanks for any input!

**Comment by EionRobb** [comment]
@markspiller nope, your issue is different, please start a new issue (but it sounds like you still have an old libskypeweb somewhere)

**Comment by maxtros** [comment]
I never had this problem again using the lastest debug dll.

**Comment by intika** [comment]
This could may be help... have a look 
https://github.com/EionRobb/skype4pidgin/issues/474#issuecomment-263105854
