### ISSUE TITLE
1.2.2 windows binary doesn't show up in available protocols

### ISSUE THREAD

**Issue by aubade** [EionRobb/skype4pidgin#487]
It seems like the new binary release for windows isn't working; Both with the installer and manually dropping the .DLL into Program Files/Pidgin/Plugins, it doesn't even show up in available protocols and my previously added skype account is listed as an unknown protocol.

**Comment by EionRobb** [comment]
Unfortunately I found just after releasing 1.2.2 that I built the dll against a newer version of Pidgin, so the dll's there will only work with Pidgin 2.10.12 or newer (eg, the latest is currently Pidgin 2.11.0)

You can either update Pidgin or download a new copy of the dll from the nightly build server at https://eion.robbmob.com/libskypeweb.dll or https://eion.robbmob.com/pidgin-skypeweb-installer.exe

**Comment by aubade** [comment]
That woked much better; thank you!

**Comment by EionRobb** [comment]
:)
