### ISSUE TITLE
New Linux User With Dumb Question

### ISSUE THREAD

**Issue by WithThisHerring** [EionRobb/skype4pidgin#488]
I'm sure this will be an easy answer for someone, but Googling hasn't found it for me.  Thank you for your patience. 

I installed version 1.1 a few months ago, shortly after switching from Windows to Linux Mint 17.3 (which doesn't have this lovely program in its software manager).  I used the terminal compile instructions back then:
`git clone git://github.com/EionRobb/skype4pidgin.git`
`cd skype4pidgin/skypeweb`
`make`
`sudo make install`

Now I've finally gotten the Skype token error, so I want to update to the current version.  As I didn't install via the software manager, what do I need to do about version 1.1 before installing version 1.2.2?  Can I just follow the same steps and the new version will just overwrite the old version? Super-clear terminal entries or "go to folder X, delete Y, then go to folder Z, delete A and B" would be much appreciated.

Per advice of another page on the internet, I tried:
`cd skype4pidgin/skypeweb`
`sudo make uninstall`
but got
`make: *** No rule to make target 'uninstall'.  Stop.`

**Comment by xvitaly** [comment]
Thats why you should **never** use make install on package based distributions!

**Comment by WithThisHerring** [comment]
I followed the compile directions that are featured for the current Skypeweb plugin [here](https://github.com/EionRobb/skype4pidgin/tree/master/skypeweb) and on [Eion Robb's website](http://eion.robbmob.com/).  What should I have done differently?
How do I "remove all installed via `make install` files, build package and install it"?
I have very little experience in Linux.

**Comment by EionRobb** [comment]
There's currently no `make uninstall` rule, but PR's welcome :)

I guess the key here is to be consistent... if you're going to use `make install` keep using it, and conversely if you're going to use the package manager keep using it :)

**Comment by EionRobb** [comment]
@WithThisHerring to answer your original question of "Can I just follow the same steps and the new version will just overwrite the old version?" the answer is yes.

**Comment by xvitaly** [comment]
>  What should I have done differently?

Every file and directory on package-based distributions must be installed via package manager. Using `make install` ruins whole system and creates untracked files. It will cause you lots of problems on updates/upgrades.

> How do I "remove all installed via make install files

Just remove listed files via file manager or console rm as root.

> build package and install it"

https://github.com/EionRobb/skype4pidgin/tree/master/skypeweb#building-deb-package-for-debianubuntumint

**Comment by EionRobb** [comment]
@xvitaly I would have to respectfully disagree.  Your system is up to you to control, and if your package manager doesn't provide packages for software that you want/need/use then being reliant on a 3rd party to make packages certainly violates the 'desert island' principle of Free software

**Comment by EionRobb** [comment]
This issue has gotten a bit off-topic :)

@WithThisHerring if you're still getting stuck with upgrading, please feel free to re-open

**Comment by xvitaly** [comment]
> Your system is up to you to control, and if your package manager doesn't provide packages for software that you want/need/use then being reliant on a 3rd party to make packages certainly violates the 'desert island' principle of Free software

Then you can use `sudo checkinstall` instead of `sudo make install`. It will create and install package. :-)

**Comment by WithThisHerring** [comment]
EionRobb, I'm not sure how to re-open this.
In the terminal, I entered:
`git clone git://github.com/EionRobb/skype4pidgin.git`
Result:
`fatal: destination path 'skype4pidgin' already exists and is not an empty directory.`
Help?

(xvitaly, I don't have the background to understand some of your comments.  I'm on Skype (via Pidgin, of course) as QuasiAlert, if I can ask you more questions there?  I would like to learn.)

**Comment by xvitaly** [comment]
>  Help?

You don't need to clone repository again. Just follow all other steps.

**Comment by xvitaly** [comment]
Also for Ubuntu and Mint you can enable 3rd party ppa https://launchpad.net/~nilarimogard/+archive/ubuntu/webupd8/ and install purple-skypeweb package from it.

**Comment by WithThisHerring** [comment]
I enter:
```
cd skype4pidgin/skypeweb
make
```
Result:
`make: Nothing to be done for 'all'.`
I enter:
`sudo make install`
Result:
```
mkdir -m 0755 -p /usr/lib/purple-2
install -m 0644 libskypeweb.so /usr/lib/purple-2/libskypeweb.so
mkdir -m 0755 -p /usr/share/pixmaps/pidgin/protocols/16
install -m 0644 icons/16/skype.png /usr/share/pixmaps/pidgin/protocols/16/skype.png
install -m 0644 icons/16/skypeout.png /usr/share/pixmaps/pidgin/protocols/16/skypeout.png
mkdir -m 0755 -p /usr/share/pixmaps/pidgin/protocols/22
install -m 0644 icons/22/skype.png /usr/share/pixmaps/pidgin/protocols/22/skype.png
install -m 0644 icons/22/skypeout.png /usr/share/pixmaps/pidgin/protocols/22/skypeout.png
mkdir -m 0755 -p /usr/share/pixmaps/pidgin/protocols/48
install -m 0644 icons/48/skype.png /usr/share/pixmaps/pidgin/protocols/48/skype.png
install -m 0644 icons/48/skypeout.png /usr/share/pixmaps/pidgin/protocols/48/skypeout.png
mkdir -m 0755 -p /usr/share/pixmaps/pidgin/emotes/skype
install -m 0644 theme /usr/share/pixmaps/pidgin/emotes/skype/theme
```
Then I go into Pidgin, Help -> Pidgin Plugin Information
It says I'm still on version 1.1 for Skype (HTTP).
> Skype (HTTP)
> 	Author: Eion Robb <eionrobb@gmail.com>
> 	Version: 1.1
> 	Website: http://github.com/EionRobb/skype4pidgin
> 	ID String: prpl-skypeweb
> 	Loadable: Yes
> 	Loaded: Yes
  
What am I doing incorrectly?

If I were to add the PPA instead, what would I need to do to clean up the existing version 1.1 first?

I'm sorry for being such a pain.  :(

**Comment by xvitaly** [comment]
> What am I doing incorrectly?

Try:
```
cd skype4pidgin/skypeweb
make clean
make
sudo make install
```

> If I were to add the PPA instead, what would I need to do to clean up the existing version 1.1 first?

Yes.

**Comment by WithThisHerring** [comment]
Tried:
```
cd skype4pidgin/skypeweb
make clean
```
Got:
```
rm -f libskypeweb.so
```
Tried:
```
make
```
Got:
```
cc -Wall -I. -fPIC -O2 -g -pipe skypeweb_connection.c skypeweb_contacts.c skypeweb_login.c skypeweb_messages.c skypeweb_util.c libskypeweb.c  -o libskypeweb.so -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/json-glib-1.0 -I/usr/include/libpurple   -ljson-glib-1.0 -lgio-2.0 -lgobject-2.0 -lpurple -lglib-2.0 -lz   -shared
skypeweb_contacts.c: In function ‘skypeweb_xfer_send_write’:
skypeweb_contacts.c:500:19: warning: unused variable ‘sa’ [-Wunused-variable]
  SkypeWebAccount *sa = swft->sa;
                   ^
skypeweb_contacts.c: In function ‘skypeweb_got_object_for_file’:
skypeweb_contacts.c:690:9: warning: unused variable ‘id’ [-Wunused-variable]
  gchar *id;
         ^
skypeweb_login.c: In function ‘skypeweb_login_got_t’:
skypeweb_login.c:164:12: warning: unused variable ‘mspok_cookie’ [-Wunused-variable]
     gchar *mspok_cookie = skypeweb_string_get_chunk(url_text, len, "Set-Cookie: MSPOK=", "; domain=");
            ^
skypeweb_login.c:163:12: warning: unused variable ‘ppauth_cookie’ [-Wunused-variable]
     gchar *ppauth_cookie = skypeweb_string_get_chunk(url_text, len, "Set-Cookie: PPAuth=", ";");
            ^
skypeweb_login.c:162:12: warning: unused variable ‘SLK’ [-Wunused-variable]
     gchar *SLK = skypeweb_string_get_chunk(url_text, len, ",aB:'", "',");
            ^
skypeweb_login.c:161:12: warning: unused variable ‘PPFT’ [-Wunused-variable]
     gchar *PPFT = skypeweb_string_get_chunk(url_text, len, ",sFT:'", "',");
            ^
skypeweb_messages.c: In function ‘process_message_resource’:
skypeweb_messages.c:202:5: warning: null argument where non-null required (argument 1) [-Wnonnull]
     skypeemoteoffset = atoi(json_object_get_string_member(resource, "skypeemoteoffset"));
     ^
skypeweb_messages.c:310:26: warning: unused variable ‘imconv’ [-Wunused-variable]
    PurpleIMConversation *imconv;
                          ^
skypeweb_messages.c:340:5: warning: null argument where non-null required (argument 1) [-Wnonnull]
     skypeemoteoffset = atoi(json_object_get_string_member(resource, "skypeemoteoffset"));
     ^
skypeweb_messages.c:391:26: warning: unused variable ‘imconv’ [-Wunused-variable]
    PurpleIMConversation *imconv;
                          ^
```
Tried:
```
sudo make install
```
Got:
```
mkdir -m 0755 -p /usr/lib/purple-2
install -m 0644 libskypeweb.so /usr/lib/purple-2/libskypeweb.so
mkdir -m 0755 -p /usr/share/pixmaps/pidgin/protocols/16
install -m 0644 icons/16/skype.png /usr/share/pixmaps/pidgin/protocols/16/skype.png
install -m 0644 icons/16/skypeout.png /usr/share/pixmaps/pidgin/protocols/16/skypeout.png
mkdir -m 0755 -p /usr/share/pixmaps/pidgin/protocols/22
install -m 0644 icons/22/skype.png /usr/share/pixmaps/pidgin/protocols/22/skype.png
install -m 0644 icons/22/skypeout.png /usr/share/pixmaps/pidgin/protocols/22/skypeout.png
mkdir -m 0755 -p /usr/share/pixmaps/pidgin/protocols/48
install -m 0644 icons/48/skype.png /usr/share/pixmaps/pidgin/protocols/48/skype.png
install -m 0644 icons/48/skypeout.png /usr/share/pixmaps/pidgin/protocols/48/skypeout.png
mkdir -m 0755 -p /usr/share/pixmaps/pidgin/emotes/skype
install -m 0644 theme /usr/share/pixmaps/pidgin/emotes/skype/theme
```

Opening Pidgin shows I'm still on Skypeweb version 1.1...
What am I missing?



  

> >   If I were to add the PPA instead, what would I need to do to clean up the existing version 1.1 first?
> 
> Yes.

How?

**Comment by xvitaly** [comment]
>  What am I missing?

Try `git pull` after `cd skype4pidgin/skypeweb`.

**Comment by WithThisHerring** [comment]
Success!  Oh, thank you thank you thank you for all your help and patience!
