### ISSUE TITLE
[1.2.2] Failed getting Skype Token

### ISSUE THREAD

**Issue by pipebomb** [EionRobb/skype4pidgin#490]
Windows 7 64 bit
Pidgin 2.11.0
plugin version 1.2.2

Tried reinstalling both pidgin and skype4web and still getting the same error. Desktob skype and Web skype work.
I changed y skype password a couple of days ago, could it had some effect on this issue?"

**Comment by Sirrobinn** [comment]
Same issue. It worked fine 2 days ago. No password changes. 
Official skypeweb works fine. My guess is this problem occurs for everyone :s.

**Comment by XDjackieXD** [comment]
I updated to the latest version (compiled from git right now) and it is working again (had the same problem before)

**Comment by pipebomb** [comment]
Fixed!

Pidgin was still using 1.1 for some odd reason (checked it in About -> plugin information), and when it started using 1.2.2 skype worked again!

Thanks to people in #pidgin

**Comment by axxapy** [comment]
does not work for me (1.2.2)
It gives me "Failed getting Magic T value" error

**Comment by dequis** [comment]
@axxapy your issue is unrelated, please open a new ticket

The original issue here is fixed, closing.
