### ISSUE TITLE
Failed getting magic T value

### ISSUE THREAD

**Issue by CP1832** [EionRobb/skype4pidgin#492]
Hi guys:

I've installed Pidgin web 1.2.2 under Pidgin 2.11.0 and I keep getting failed getting magic T value. I double checked the password and logged in using the standard skype app without issues. Could you please check what could be wrong? Attached is my debug log in case it's needed.
[debug.txt](https://github.com/EionRobb/skype4pidgin/files/562765/debug.txt)

**Comment by EionRobb** [comment]
Just to double-check some things,  can you try logging into https://web.skype.com/ in a new Incognito web browser window (sometimes you might just need to accept a popup), and also check that you don't use two-factor authentication (as the plugin doesn't support that right now)

**Comment by CP1832** [comment]
Indeed the web interface just wanted me to fill out my name and surname. Once I did that I could log in without issues. Thanks EionRobb.
