### ISSUE TITLE
[SkypeWeb 1.2.2] "Barely logging in"

### ISSUE THREAD

**Issue by Metalhead33** [EionRobb/skype4pidgin#495]
Let me explain my problem:
When ever my SkypeWeb plugin for Pidgin logs in... it shows everyone as offline. And moments later, the plugin kicks me out, saying that "Server closed connection" or something similar. Then it takes forever to try to login, giving me either and error message, or "barely logging in" again.
I also get the error message "Failed getting Skype token" sometimes.

SkypeWeb also has the problem of showing every one of my contacts as offline, even though on other platforms, they swear they are online in Skype.

In Outlook - they have a kind of Skype too - everything connects just fine.

Information about my Pidgin build:

> Pidgin 2.11.0 (libpurple 2.11.0)
f02ebb71b5e32cc4af521e7f89c34dedff8d09ae

> Build információk
>   Arguments to ./configure:   '--prefix=/usr' '--build=x86_64-pc-linux-gnu' '--host=x86_64-pc-linux-gnu' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--datadir=/usr/share' '--sysconfdir=/etc' '--localstatedir=/var/lib' '--disable-dependency-tracking' '--disable-silent-rules' '--docdir=/usr/share/doc/pidgin-2.11.0' '--htmldir=/usr/share/doc/pidgin-2.11.0/html' '--libdir=/usr/lib64' '--enable-consoleui' '--enable-gtkui' '--enable-sm' '--enable-nls' '--enable-screensaver' '--disable-cap' '--disable-gevolution' '--enable-gtkspell' '--enable-perl' '--disable-tk' '--disable-tcl' '--disable-debug' '--enable-dbus' '--disable-meanwhile' '--enable-gstreamer' '--with-gstreamer=1.0' '--enable-farstream' '--enable-vv' '--disable-cyrus-sasl' '--disable-doxygen' '--disable-nm' '--disable-avahi' '--disable-idn' '--with-system-ssl-certs=/etc/ssl/certs/' '--with-dynamic-prpls=irc,jabber,oscar,yahoo,simple,msn,myspace' '--disable-mono' '--x-includes=/usr/include/X11' '--enable-gnutls=no' '--enable-nss=yes' '--with-python=/usr/bin/python2.7' 'build_alias=x86_64-pc-linux-gnu' 'host_alias=x86_64-pc-linux-gnu' 'CFLAGS=-O2 -pipe -mtune=native' 'LDFLAGS=-Wl,-O1 -Wl,--as-needed' 'CPPFLAGS=' 'PKG_CONFIG_PATH=/var/tmp/portage/net-im/pidgin-2.11.0/temp/python2.7/pkgconfig'
>   Print debugging messages: No
>   Plugins: Enabled
>   SSL: SSL support is present.
> 
>   Library Support
>     Cyrus SASL: Disabled
>     D-Bus: Enabled
>     Evolution Addressbook: Disabled
>     Gadu-Gadu library (libgadu): Internal
>     GtkSpell: Enabled
>     GnuTLS: Disabled
>     GStreamer: Enabled
>     Mono: Disabled
>     NetworkManager: Disabled
>     Network Security Services (NSS): Enabled
>     Perl: Enabled
>     Tcl: Disabled
>     Tk: Disabled
>     UTF-8 DNS (IDN): Disabled
>     Voice and Video: Enabled
>     X Session Management: Enabled
>     XScreenSaver: Enabled
>     Zephyr library (libzephyr): Internal
>     Zephyr uses Kerberos: No

Additionally, some of the logs:

> (20:14:39) nss: subject=CN=apis.skype.com issuer=CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US
> (20:14:39) nss: Trusting CN=apis.skype.com
> (20:14:39) skypeweb: post_or_get_ssl_connect_cb
> (20:14:40) nss: subject=CN=apis.skype.com issuer=CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US
> (20:14:40) nss: Trusting CN=apis.skype.com
> (20:14:40) skypeweb: post_or_get_ssl_connect_cb
> (20:14:41) skypeweb: fatal connection error
> (20:14:41) skypeweb: getting url /logout
> (20:14:41) skypeweb: sending headers:
> Host: login.skype.com
> (20:14:41) dnsquery: Performing DNS lookup for login.skype.com
> (20:14:41) skypeweb: destroying 0 waiting connections
> (20:14:41) skypeweb: destroying 1 incomplete connections

> (20:17:44) dnsquery: Performing DNS lookup for api.skype.com
> (20:17:44) dns: Got response for 'api.skype.com'
> (20:17:44) dnsquery: IP resolved for api.skype.com
> (20:17:44) proxy: Connecting to api.skype.com:443 with no proxy
> (20:17:44) proxy: Connecting to api.skype.com:443.
> (20:17:44) proxy: Connected to api.skype.com:443.
> (20:17:44) nss: subject=CN=api.skype.com issuer=CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US
> (20:17:44) certificate/x509/tls_cached: Starting verify for api.skype.com
> (20:17:44) nss/x509: Loading certificate from /home/metalhead33/.purple/certificates/x509/tls_peers/api.skype.com
> (20:17:44) nss/x509: Exporting certificate to /home/metalhead33/.purple/certificates/x509/tls_peers/api.skype.com
> (20:17:44) util: Writing file /home/metalhead33/.purple/certificates/x509/tls_peers/api.skype.com
> (20:17:44) nss: Trusting CN=api.skype.com
> (20:17:44) certificate: Successfully verified certificate for api.skype.com
> (20:17:44) skypeweb: post_or_get_ssl_connect_cb
> (20:17:45) skypeweb: Got response: HTTP/1.1 200 OK
> Access-Control-Allow-Origin: https://web.skype.com
> (20:17:45) skypeweb: executing callback for /users/self/profile
> (20:17:47) nss: subject=CN=apis.skype.com issuer=CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US
> (20:17:47) nss: Trusting CN=apis.skype.com
> (20:17:47) g_log: skypeweb_string_get_chunk: assertion 'haystack && start && end' failed
> (20:17:47) g_log: skypeweb_string_get_chunk: assertion 'haystack && start && end' failed
> (20:17:47) g_log: skypeweb_string_get_chunk: assertion 'haystack && start && end' failed
> (20:17:47) g_log: skypeweb_string_get_chunk: assertion 'haystack && start && end' failed
> (20:17:47) dnsquery: Performing DNS lookup for login.skype.com
> (20:17:47) dns: Got response for 'login.skype.com'
> (20:17:47) dnsquery: IP resolved for login.skype.com
> (20:17:47) proxy: Connecting to login.skype.com:443 with no proxy
> (20:17:48) proxy: Connecting to login.skype.com:443.
> (20:17:48) proxy: Connected to login.skype.com:443.
> (20:17:48) nss: subject=CN=login.skype.com,O=Skype,L=Dublin,C=IE issuer=CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US
> (20:17:48) certificate/x509/tls_cached: Starting verify for login.skype.com
> (20:17:48) nss/x509: Loading certificate from /home/metalhead33/.purple/certificates/x509/tls_peers/login.skype.com
> (20:17:48) nss/x509: Exporting certificate to /home/metalhead33/.purple/certificates/x509/tls_peers/login.skype.com
> (20:17:48) util: Writing file /home/metalhead33/.purple/certificates/x509/tls_peers/login.skype.com
> (20:17:48) nss: Trusting CN=login.skype.com,O=Skype,L=Dublin,C=IE
> (20:17:48) certificate: Successfully verified certificate for login.skype.com

> (20:17:03) dnsquery: Performing DNS lookup for client-s.gateway.messenger.live.com
> (20:17:03) dns: Got response for 'client-s.gateway.messenger.live.com'
> (20:17:03) dnsquery: IP resolved for client-s.gateway.messenger.live.com
> (20:17:03) proxy: Connecting to client-s.gateway.messenger.live.com:443 with no proxy
> (20:17:06) proxy: Connecting to client-s.gateway.messenger.live.com:443.
> (20:17:06) proxy: Connected to client-s.gateway.messenger.live.com:443.
> (20:17:07) certificate/x509/tls_cached: Starting verify for client-s.gateway.messenger.live.com
> (20:17:07) nss/x509: Loading certificate from /home/metalhead33/.purple/certificates/x509/tls_peers/client-s.gateway.messenger.live.com
> (20:17:07) nss/x509: Exporting certificate to /home/metalhead33/.purple/certificates/x509/tls_peers/client-s.gateway.messenger.live.com
> (20:17:07) util: Writing file /home/metalhead33/.purple/certificates/x509/tls_peers/client-s.gateway.messenger.live.com
> (20:17:07) certificate: Successfully verified certificate for client-s.gateway.messenger.live.com
> Location: https://co4-client-s.gateway.messenger.live.com/v1/users/ME/endpoints/%7Be2192873-6c1d-4f70-90fd-38db2bc89765%7D
> (20:17:09) util: Redirecting to  https://co4-client-s.gateway.messenger.live.com/v1/users/ME/endpoints/%7Be2192873-6c1d-4f70-90fd-38db2bc89765%7D
> (20:17:09) skypeweb: Messages host has changed to co4-client-s.gateway.messenger.live.com
> (20:17:09) dnsquery: Performing DNS lookup for co4-client-s.gateway.messenger.live.com
> (20:17:09) dns: Got response for 'co4-client-s.gateway.messenger.live.com'
> (20:17:09) dnsquery: IP resolved for co4-client-s.gateway.messenger.live.com
> (20:17:09) proxy: Connecting to co4-client-s.gateway.messenger.live.com:443 with no proxy
> (20:17:09) proxy: Connecting to co4-client-s.gateway.messenger.live.com:443.
> (20:17:09) proxy: Connected to co4-client-s.gateway.messenger.live.com:443.
> (20:17:12) certificate/x509/tls_cached: Starting verify for co4-client-s.gateway.messenger.live.com
> (20:17:12) nss/x509: Loading certificate from /home/metalhead33/.purple/certificates/x509/tls_peers/co4-client-s.gateway.messenger.live.com
> (20:17:12) nss/x509: Exporting certificate to /home/metalhead33/.purple/certificates/x509/tls_peers/co4-client-s.gateway.messenger.live.com
> (20:17:12) util: Writing file /home/metalhead33/.purple/certificates/x509/tls_peers/co4-client-s.gateway.messenger.live.com
> (20:17:12) certificate: Successfully verified certificate for co4-client-s.gateway.messenger.live.com
> (20:17:13) dnsquery: Performing DNS lookup for co4-client-s.gateway.messenger.live.com
> (20:17:13) dns: Got response for 'co4-client-s.gateway.messenger.live.com'
> (20:17:13) dnsquery: IP resolved for co4-client-s.gateway.messenger.live.com
> (20:17:13) proxy: Connecting to co4-client-s.gateway.messenger.live.com:443 with no proxy
> (20:17:13) proxy: Connecting to co4-client-s.gateway.messenger.live.com:443.
> (20:17:13) proxy: Connected to co4-client-s.gateway.messenger.live.com:443.
> (20:17:14) certificate/x509/tls_cached: Starting verify for co4-client-s.gateway.messenger.live.com
> (20:17:14) nss/x509: Loading certificate from /home/metalhead33/.purple/certificates/x509/tls_peers/co4-client-s.gateway.messenger.live.com
> (20:17:14) nss/x509: Exporting certificate to /home/metalhead33/.purple/certificates/x509/tls_peers/co4-client-s.gateway.messenger.live.com
> (20:17:14) util: Writing file /home/metalhead33/.purple/certificates/x509/tls_peers/co4-client-s.gateway.messenger.live.com
> (20:17:14) certificate: Successfully verified certificate for co4-client-s.gateway.messenger.live.com
> (20:17:16) dnsquery: Performing DNS lookup for co4-client-s.gateway.messenger.live.com
> (20:17:16) dns: Got response for 'co4-client-s.gateway.messenger.live.com'
> (20:17:16) dnsquery: IP resolved for co4-client-s.gateway.messenger.live.com
> (20:17:16) proxy: Connecting to co4-client-s.gateway.messenger.live.com:443 with no proxy
> (20:17:17) proxy: Connecting to co4-client-s.gateway.messenger.live.com:443.
> (20:17:17) proxy: Connected to co4-client-s.gateway.messenger.live.com:443.
> (20:17:19) certificate/x509/tls_cached: Starting verify for co4-client-s.gateway.messenger.live.com
> (20:17:19) nss/x509: Loading certificate from /home/metalhead33/.purple/certificates/x509/tls_peers/co4-client-s.gateway.messenger.live.com
> (20:17:19) nss/x509: Exporting certificate to /home/metalhead33/.purple/certificates/x509/tls_peers/co4-client-s.gateway.messenger.live.com
> (20:17:19) util: Writing file /home/metalhead33/.purple/certificates/x509/tls_peers/co4-client-s.gateway.messenger.live.com
> (20:17:19) certificate: Successfully verified certificate for co4-client-s.gateway.messenger.live.com
> (20:17:20) dnsquery: Performing DNS lookup for co4-client-s.gateway.messenger.live.com
> (20:17:20) dns: Got response for 'co4-client-s.gateway.messenger.live.com'
> (20:17:20) dnsquery: IP resolved for co4-client-s.gateway.messenger.live.com
> (20:17:20) proxy: Connecting to co4-client-s.gateway.messenger.live.com:443 with no proxy
> (20:17:21) proxy: Connecting to co4-client-s.gateway.messenger.live.com:443.
> (20:17:21) proxy: Connected to co4-client-s.gateway.messenger.live.com:443.
> (20:17:21) certificate/x509/tls_cached: Starting verify for co4-client-s.gateway.messenger.live.com
> (20:17:21) nss/x509: Loading certificate from /home/metalhead33/.purple/certificates/x509/tls_peers/co4-client-s.gateway.messenger.live.com
> (20:17:21) nss/x509: Exporting certificate to /home/metalhead33/.purple/certificates/x509/tls_peers/co4-client-s.gateway.messenger.live.com
> (20:17:21) util: Writing file /home/metalhead33/.purple/certificates/x509/tls_peers/co4-client-s.gateway.messenger.live.com
> (20:17:21) certificate: Successfully verified certificate for co4-client-s.gateway.messenger.live.com
> (20:17:23) dnsquery: Performing DNS lookup for co4-client-s.gateway.messenger.live.com
> (20:17:23) dns: Got response for 'co4-client-s.gateway.messenger.live.com'
> (20:17:23) dnsquery: IP resolved for co4-client-s.gateway.messenger.live.com
> (20:17:23) proxy: Connecting to co4-client-s.gateway.messenger.live.com:443 with no proxy
> (20:17:23) proxy: Connecting to co4-client-s.gateway.messenger.live.com:443.
> (20:17:23) proxy: Connected to co4-client-s.gateway.messenger.live.com:443.
> (20:17:23) certificate/x509/tls_cached: Starting verify for co4-client-s.gateway.messenger.live.com
> (20:17:23) nss/x509: Loading certificate from /home/metalhead33/.purple/certificates/x509/tls_peers/co4-client-s.gateway.messenger.live.com
> (20:17:23) nss/x509: Exporting certificate to /home/metalhead33/.purple/certificates/x509/tls_peers/co4-client-s.gateway.messenger.live.com
> (20:17:23) util: Writing file /home/metalhead33/.purple/certificates/x509/tls_peers/co4-client-s.gateway.messenger.live.com
> (20:17:23) certificate: Successfully verified certificate for co4-client-s.gateway.messenger.live.com
> Location: https://co4-client-s.gateway.messenger.live.com/v1/users/ME/endpoints/%7B5c7c998c-9832-4f65-a34c-d0182222d454%7D
> (20:17:27) util: Redirecting to  https://co4-client-s.gateway.messenger.live.com/v1/users/ME/endpoints/%7B5c7c998c-9832-4f65-a34c-d0182222d454%7D
> Host: co4-client-s.gateway.messenger.live.com
> (20:17:27) dnsquery: Performing DNS lookup for co4-client-s.gateway.messenger.live.com
> (20:17:27) dns: Got response for 'co4-client-s.gateway.messenger.live.com'
> (20:17:27) dnsquery: IP resolved for co4-client-s.gateway.messenger.live.com
> (20:17:27) proxy: Connecting to co4-client-s.gateway.messenger.live.com:443 with no proxy
> (20:17:27) proxy: Connecting to co4-client-s.gateway.messenger.live.com:443.
> (20:17:27) proxy: Connected to co4-client-s.gateway.messenger.live.com:443.
> (20:17:28) certificate/x509/tls_cached: Starting verify for co4-client-s.gateway.messenger.live.com
> (20:17:28) nss/x509: Loading certificate from /home/metalhead33/.purple/certificates/x509/tls_peers/co4-client-s.gateway.messenger.live.com
> (20:17:28) nss/x509: Exporting certificate to /home/metalhead33/.purple/certificates/x509/tls_peers/co4-client-s.gateway.messenger.live.com
> (20:17:28) util: Writing file /home/metalhead33/.purple/certificates/x509/tls_peers/co4-client-s.gateway.messenger.live.com
> (20:17:28) certificate: Successfully verified certificate for co4-client-s.gateway.messenger.live.com
> (20:17:28) dnsquery: Performing DNS lookup for co4-client-s.gateway.messenger.live.com
> (20:17:28) dns: Got response for 'co4-client-s.gateway.messenger.live.com'
> (20:17:28) dnsquery: IP resolved for co4-client-s.gateway.messenger.live.com
> (20:17:28) proxy: Connecting to co4-client-s.gateway.messenger.live.com:443 with no proxy
> (20:17:29) proxy: Connecting to co4-client-s.gateway.messenger.live.com:443.
> (20:17:29) proxy: Connected to co4-client-s.gateway.messenger.live.com:443.
> (20:17:30) certificate/x509/tls_cached: Starting verify for co4-client-s.gateway.messenger.live.com
> (20:17:30) nss/x509: Loading certificate from /home/metalhead33/.purple/certificates/x509/tls_peers/co4-client-s.gateway.messenger.live.com
> (20:17:30) nss/x509: Exporting certificate to /home/metalhead33/.purple/certificates/x509/tls_peers/co4-client-s.gateway.messenger.live.com
> (20:17:30) util: Writing file /home/metalhead33/.purple/certificates/x509/tls_peers/co4-client-s.gateway.messenger.live.com
> (20:17:30) certificate: Successfully verified certificate for co4-client-s.gateway.messenger.live.com
> (20:17:30) dnsquery: Performing DNS lookup for co4-client-s.gateway.messenger.live.com
> (20:17:30) dns: Got response for 'co4-client-s.gateway.messenger.live.com'
> (20:17:30) dnsquery: IP resolved for co4-client-s.gateway.messenger.live.com
> (20:17:30) proxy: Connecting to co4-client-s.gateway.messenger.live.com:443 with no proxy
> (20:17:30) proxy: Connecting to co4-client-s.gateway.messenger.live.com:443.
> (20:17:30) proxy: Connected to co4-client-s.gateway.messenger.live.com:443.
> (20:17:31) certificate/x509/tls_cached: Starting verify for co4-client-s.gateway.messenger.live.com
> (20:17:31) nss/x509: Loading certificate from /home/metalhead33/.purple/certificates/x509/tls_peers/co4-client-s.gateway.messenger.live.com
> (20:17:31) nss/x509: Exporting certificate to /home/metalhead33/.purple/certificates/x509/tls_peers/co4-client-s.gateway.messenger.live.com
> (20:17:31) util: Writing file /home/metalhead33/.purple/certificates/x509/tls_peers/co4-client-s.gateway.messenger.live.com
> (20:17:31) certificate: Successfully verified certificate for co4-client-s.gateway.messenger.live.com
> (20:17:45) dnsquery: Performing DNS lookup for client-s.gateway.messenger.live.com
> (20:17:45) dns: Got response for 'client-s.gateway.messenger.live.com'
> (20:17:45) dnsquery: IP resolved for client-s.gateway.messenger.live.com
> (20:17:45) proxy: Connecting to client-s.gateway.messenger.live.com:443 with no proxy
> (20:17:46) proxy: Connecting to client-s.gateway.messenger.live.com:443.
> (20:17:46) proxy: Connected to client-s.gateway.messenger.live.com:443.
> (20:17:47) certificate/x509/tls_cached: Starting verify for client-s.gateway.messenger.live.com
> (20:17:47) nss/x509: Loading certificate from /home/metalhead33/.purple/certificates/x509/tls_peers/client-s.gateway.messenger.live.com
> (20:17:47) nss/x509: Exporting certificate to /home/metalhead33/.purple/certificates/x509/tls_peers/client-s.gateway.messenger.live.com
> (20:17:47) util: Writing file /home/metalhead33/.purple/certificates/x509/tls_peers/client-s.gateway.messenger.live.com
> (20:17:47) certificate: Successfully verified certificate for client-s.gateway.messenger.live.com

**Comment by snackiz** [comment]
I have the same problem, since today or yesterday. Debian Jessie and latest version of skypeweb from git

**Comment by Metalhead33** [comment]
Now it also says "Failed getting MSPRequ cookie"

**Comment by EionRobb** [comment]
There was a bit of server error and lag over the past few days, but it appears to have gone away now.

Are things logging in alright now?

**Comment by Metalhead33** [comment]
Yep, log-in is working fine now. Looks like it can be closed now.
