### ISSUE TITLE
Messages containing URLs frequently do not send

### ISSUE THREAD

**Issue by abmorris** [EionRobb/skype4pidgin#500]
I don't know if it's some sort of spam protection, but it's annoying to have to log in to web.skype.com just to check if my message has gone through.

At the moment I don't have faith that this is a reliable method of communication.

**Comment by EionRobb** [comment]
Do you have examples of messages that don't send? What errors are shown in the debug log (Help->Debug Window) when you do send them? Do those same messages send if you send them through the website? How can we repeat this to be able to try fix it?

**Comment by abmorris** [comment]
An example that repeatedly fails is any message containing `http://www.youtube.com/watch?v=`
[log.txt](https://github.com/EionRobb/skype4pidgin/files/649777/log.txt)

**Comment by EionRobb** [comment]
It looks like the server is rejecting messages that have one url in the href and a different url in the content with a response of
```
{
	"errorCode": 284,
	"message": "Failure due to: BlockedContent."
}
```

I should be able to check the server response and display the error message, but as a workaround in the meantime, don't change the content of the urls that you're sending :)

**Comment by gordon-fish** [comment]
@EionRobb Could you please elaborate on this? How can one enter two separate URLs from pidgin? I thought that one just enters a url into the chat and that's it. Not sure what I'm missing here.

**Comment by EionRobb** [comment]
![image](https://cloud.githubusercontent.com/assets/1063865/21163679/5b7da3bc-c1f9-11e6-952b-2bdd73f2f317.png)
The 'add url' box lets you specify a different 'URL' to the 'Description', eg in @abmorris 's example you could specify `https://www.youtube.com/watch?v=spQIj-26aC0` for the url but `http://www.youtube.com/watch?v=` for the description

**Comment by dequis** [comment]
You can also get that result accidentally by pasting an url and backspacing. It gets linkified as soon as you paste so what you're editing is the text, not the link. Pidgin "bug" that has been around for years.

**Comment by gordon-fish** [comment]
@EionRobb @dequis Thank you very much for the explanations and insight. Much appreciated.

**Comment by EionRobb** [comment]
@abmorris can you try with the latest commit to see if the error messages are ok?

**Comment by abmorris** [comment]
Hi, yes, the error messages work perfectly. (Sorry for the delay, I thought I had already responded).

I suppose the rest of the problem is server-side. 

Thanks for implementing this.
