### ISSUE TITLE
[v1.2.2/Debian] "Failed getting Magic T value" only at Spectrum

### ISSUE THREAD

**Issue by TomTheDragon** [EionRobb/skype4pidgin#507]
I did some tests here and there to use Skype over an XMPP transport, on my phone.
It did work really well all the time and i also start using the plugin on Finch to bridge some chats together with a special script.

I wanted to give the Skype transport a go again last week but it suddenly cant connect any longer, i am always getting an "Failed getting Magic T value" error.
The strange thing is that Finch dont seems to have any problems with it
I also tried different builds and some of the never dev builds but it dont changed anything.

Btw i never had to accept any TOS to use skypeweb on this machine, i could not do it anyway since its an server without any gui.

**Comment by dequis** [comment]
>i could not do it anyway since its an server without any gui.

You can create a tunnel to your server's connection using [ssh -D][1]

Does finch run in the same host as spectrum?

[1]: https://help.ubuntu.com/community/SSH/OpenSSH/PortForwarding#Dynamic_Port_Forwarding

**Comment by TomTheDragon** [comment]
Thx dequis, i didn't know that you can tunnel over SSH out of the box.
It seems to work again after logging into the web version of Skype over the tunnel and i dont even had to accept any new TOS.

Yes they do.

**Comment by dequis** [comment]
Huh, weird. Well, we can consider this fixed, i guess.
