### ISSUE TITLE
Does skype4pidgin supports '\alertsoff' in any way?

### ISSUE THREAD

**Issue by ipeacocks** [EionRobb/skype4pidgin#508]
Some skype groups of mine are annoying but I need to be there. Does skype4pidgin supports '\alertsoff' in any way?

Thank you for attention.

**Comment by EionRobb** [comment]
What does "/alertsoff" do?

**Comment by dequis** [comment]
Disables notifications from a chat

**Comment by EionRobb** [comment]
In Pidgin, you can change the Options->Enable Sounds on a per-conversation basis. Does that do what you're after, @ipeacocks ?
