### ISSUE TITLE
skype with bitlbee

### ISSUE THREAD

**Issue by realies** [EionRobb/skype4pidgin#512]
Following this guide for using [Bitlbee with Skype](https://wiki.bitlbee.org/HowtoSkypeWeb), I am successfully running Skypeweb with Bitlbee. I've noticed that running [Bitlbee in debug mode](https://wiki.bitlbee.org/Debugging) produces the following output when connecting to the Skype service:

>** (process:15047): CRITICAL **: skypeweb_set_mood_message: assertion 'mood' failed

It runs fine but thought it might be worth reporting.

**Comment by dequis** [comment]
Harmless, ignore.

**Comment by robert-scheck** [comment]
I'm seeing the following multiple times per second…flooding the irssi status window:

> ** (process:16190): CRITICAL **: skypeweb_set_mood_message: assertion `mood' failed
> ** (process:16190): CRITICAL **: skypeweb_string_get_chunk: assertion `chunk_start' failed

**Comment by EionRobb** [comment]
One of the commits over the past couple of days should have gotten rid of the "skypeweb_set_mood_message" assersion
