### ISSUE TITLE
SkypeWeb SkypeTokenRevoked

### ISSUE THREAD

**Issue by paguan** [EionRobb/skype4pidgin#513]
Hey,

This issue doesn't really apply to skype4pidgin. My code is running in JAVA based on the Skype4J library which is also based on SkypeWeb. The thing is that Skype4J is no longer maintained and the issues that I'm having could also apply to this implementation.

In any case if you think this does not apply feel free to discard this message, but some help will be much appreciated as somehow we need to support the unnoficial SkypeWeb community.

The application I'm working on is some kind of backup system for Skype. The user just need to provide username and password and the system will actively monitor their messages while backing them up.

That been said the problem that I'm facing is that at random periods I'm forbidden to connect to the POLL URL (https://client-s.gateway.messenger.live.com/v1/users/ME/endpoints/SELF/subscriptions/0/poll) with a 403 http error. Similarly to your skypeweb_messages module, whenever an error on the POLL URL happens I try to renegociate the token by calling the URL "https://client-s.gateway.messenger.live.com/v1/users/ME/endpoints/" and when doing so is when I get this error:

> ErrorCode: 401 Message: The provided 'skypetoken' ticket failed authentication. SkypeTokenRevoked

The thing is that whenever I get this error my client account is suspended at Skype, and he has to go through some two-step authentication process to get that account working again.

I wonder if you guys have ever expirienced something similar on your implementation and if so some feedback will be really appreciated :)

Ups, forgot to mention that the tokens that were revoked were correctly retrieved 30 minutes before the error and their expiration time supposed to last 23 hours more.

Thanks

**Comment by EionRobb** [comment]
Hope you managed to get this working by now.  The poll url can be on different server's though, you need to follow the Location: redirect to get to the correct server address, generally the client-s.gateway.messenger.live.com one is just the starting point.

**Comment by paguan** [comment]
Thanks for your response @EionRobb. 
Yes I'm doing those redirections and from my side everything seems to be working fine. But still, at random periods -10-15 days- some accounts get suspended at Skype.
Have you ever suffered suspensions? I think this is all related to some IP blacklisting at Skype. If I proxy my connection through other IP this does not seem to happen, only when I use the one I initially used during my tests is when I get accounts suspended.
So my goal now is to understand how and why Skype bans IPs.

Thanks for your reply!

**Comment by EionRobb** [comment]
The login does appear to be IP based in terms of black/white listing.  Bitlbee and spectrum2 users are particularly affected by this when they use servers in a different IP area to connect to skypeweb, generally they have to proxy through that IP to auth before they can let the skypeweb plugin auth.
