### ISSUE TITLE
Copy pasting messages results in tiny font in official skype client

### ISSUE THREAD

**Issue by powertomato** [EionRobb/skype4pidgin#515]
If I copy and paste a message within pidgin to a skype contact, the font at the skype side gets really small:
https://i.imgur.com/jSu6I17.png

Copy-pasting any other formated text results in size beeing discarded.

**Comment by EionRobb** [comment]
Yeah, this is really annoying.  I'm signalling to libpurple that the protocol doesn't support font sizes, but that setting is ignored when copy-pasting.  The workaround at the moment is to use the "Reset Formatting" button or using the "Paste as Plain Text" right-click option

**Comment by typoworx-de** [comment]
I also have this problem using Ubuntu/Linux. But my chat partners even complain about really small message font-size even if I write them without copy&paste! Sounds like the same problem.

**Comment by EionRobb** [comment]
Hopefully fixed by that commit :)
