### ISSUE TITLE
JSON error when used with Spectrum2.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [EionRobb/skype4pidgin#517]
purple-skypeweb  throwing this JSON error:

(process:27674): Json-CRITICAL **: json_node_get_array: assertion 'JSON_NODE_TYPE (node) == JSON_NODE_ARRAY' failed

(process:27674): Json-CRITICAL **: json_array_get_length: assertion 'array != NULL' failed

(process:27674): Json-CRITICAL **: json_node_get_array: assertion 'JSON_NODE_TYPE (node) == JSON_NODE_ARRAY' failed

(process:27674): Json-CRITICAL **: json_array_get_length: assertion 'array != NULL' failed
^

**Comment by EionRobb** [comment]
They're just harmless no-op's, not as 'critical' as the logging makes them out to be

**Comment by Zombie-Ryushu** [comment]
Can they be silenced to make them not fill up my logs?
