### ISSUE TITLE
New version of Skype??

### ISSUE THREAD

**Issue by saleslogistix** [EionRobb/skype4pidgin#519]
Just received an email from MSFT that says:
"The time has come. From March 1, you may no longer be able to sign into the version of Skype on your computer. To keep talking with your family and friends, please update to the latest version. It only takes a few minutes and all your contacts and conversations will be right there when you sign in."
As the version of Skype I have is the latest thing from Redmond, is it possible that this message was triggered by using the Skype(HTTP) protocol?  I certainly hope that MSFT isn't retiring that protocol support.

Any info??

**Comment by xvitaly** [comment]
> Any info??

https://blogs.skype.com/news/2017/02/03/the-skype-you-love-is-getting-better-download-it-for-free-today/

**Comment by dequis** [comment]
Yeah this is most likely irrelevant to skypeweb. But interesting either way.

That link:

>Because we want to provide our users with the best possible Skype experience, necessary changes must be made along the way. So, beginning March 1, users running older versions of Skype for Windows desktop (7.16 and below) [...]

Skype windows 7.17 changelog:

>Users who are signed in to their Windows 10 machine with a Microsoft account can now sign into Skype with that account in just one click. When you launch Skype, you'll see a new screen showing your Microsoft account. Click on this to sign in. If you want to sign in with a different account, simply select 'Other Account' and continue as normal. This is rolling out gradually so if you don't see it, don't worry - it's coming!

So it was something about integrating skype usernames with live logins, maybe?

**Comment by saleslogistix** [comment]
And of course...I'm running Skype 7.28, well beyond the cutoff that would have triggered this email from MSFT.  It's that famous Redmond software quality...
While there IS a brand new UI for Skype available on Win10, I'm at Win7 and I'm at the most current release.
So...I'm guessing this is in the file-and-forget category...
We'll see.

**Comment by dequis** [comment]
Anyway nothing to do here, closing
