### ISSUE TITLE
Show who is typing in the group chat

### ISSUE THREAD

**Issue by bodqhrohro** [EionRobb/skype4pidgin#520]
Now only generic "buddy is typing" is displayed and this message remains in the chatlog after the typing was finished.

**Comment by Monsterovich** [comment]
I doesn't even see that someome is typing. :P But for private chat it works fine.

**Comment by tpenguinltg** [comment]
I'm on e774405 and I see buddy names, but the message still continues to be displayed when they stop typing. The message also disappears when I send a message, even if the other person is still typing.
It all works as expected in private chats.

**Comment by EionRobb** [comment]
Try using the plugin from https://github.com/EionRobb/pidgin-groupchat-typing-notifications instead, which does disappearing typing notifications in a similar way to one-on-one IM's

**Comment by tpenguinltg** [comment]
@EionRobb I'm not sure who that's directed to, but I completely forgot I had that plugin and had it enabled. It seems, then, that I've described the behaviour with that plugin enabled.

**Comment by bodqhrohro** [comment]
@EionRobb that plugin is not working for me in Skype chats, neither just after enabling, nor after restarting Pidgin; the 'buddy typing...' messages still keep in the chatlog.

**Comment by EionRobb** [comment]
@bodqhrohro you'll need to disable the 'Show Typing status as system message in chat window' advanced setting in Skype to be able to use the group typing plugin.

**Comment by bodqhrohro** [comment]
The plugin started working a some time after starting even without disabling that option. Nevertheless, the pidgin-skypeweb's builtin behavior is not needed now.
