### ISSUE TITLE
Sent messages not shown in group chat

### ISSUE THREAD

**Issue by snackiz** [EionRobb/skype4pidgin#522]
After a keeping a group chat open a while, probably multiple hours, my sent messages are not shown in the chat window.
They get sent and I can see the messages in other clients.
Restarting pidgin makes the sent messages visible. In the conversation logs there are two sessions, one without the sent messages and one with them, with a date from when I restarted the client.

Debug logs from two different occations attached.

[skypeweb-cannotseeownmessages2.txt](https://github.com/EionRobb/skype4pidgin/files/769330/skypeweb-cannotseeownmessages2.txt)
[pidgin-cannotseeownmessages.txt](https://github.com/EionRobb/skype4pidgin/files/769331/pidgin-cannotseeownmessages.txt)

**Comment by EionRobb** [comment]
Hmm... nothing unusual is showing in the logs you've attached.

If you send a message from a different client to that group chat, does it show up in Pidgin or is it just messages you send from Pidgin that aren't displaying?

**Comment by snackiz** [comment]
When I reach this state, messages from pidgin don't show in pidgin, but they do show on the official skype client in my mobile. Messages from skype on my mobile show in pidgin tho.

**Comment by snackiz** [comment]
Also note that this does not affect one-on-one conversations, only group chats.

**Comment by snackiz** [comment]
While this problem appeared frequently before, after updating and a long time of testing, I believe this is no longer a problem.

**Comment by EionRobb** [comment]
Yay, thanks for coming back to provide feedback.  Hopefully it was the robust changes added in v1.4 that helped
