### ISSUE TITLE
Missing away, NA contacts

### ISSUE THREAD

**Issue by drJeckyll** [EionRobb/skype4pidgin#531]
Commit ec057ab63f34e626918d6c2e86ce0a7b616006c1 make users which are away or NA (probably others which are not online) disappear from contact list.
With commit I see only users which are online.

**Comment by EionRobb** [comment]
Can you get a debug log of someone disappearing when they go away/not-available?  There should be an error message about unknown status types, or something

**Comment by drJeckyll** [comment]
From debug window:
(08:09:41) g_log: skypeweb_set_mood_message: assertion 'mood' failed
(08:09:42) g_log: purple_status_is_online: assertion 'status != NULL' failed
(08:09:42) g_log: purple_status_is_online: assertion 'status != NULL' failed
(08:09:42) g_log: purple_status_is_online: assertion 'status != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) g_log: blist_node_aliased_cb: assertion 'gc != NULL' failed
(08:09:43) GLib: g_source_remove: assertion 'tag > 0' failed
(08:09:44) g_log: purple_status_is_online: assertion 'status != NULL' failed
(08:09:44) g_log: purple_status_is_online: assertion 'status != NULL' failed
(08:09:44) g_log: purple_status_is_online: assertion 'status != NULL' failed
(08:09:44) g_log: purple_status_is_online: assertion 'status != NULL' failed
(08:09:44) g_log: purple_status_is_online: assertion 'status != NULL' failed
(08:09:46) g_log: purple_status_is_online: assertion 'status != NULL' failed
(08:09:46) g_log: purple_status_is_online: assertion 'status != NULL' failed
(08:09:48) g_log: purple_status_is_online: assertion 'status != NULL' failed
(08:09:48) g_log: purple_status_is_online: assertion 'status != NULL' failed
(08:09:50) g_log: purple_status_is_online: assertion 'status != NULL' failed
(08:09:50) g_log: purple_status_is_online: assertion 'status != NULL' failed
(08:09:50) g_log: purple_status_is_online: assertion 'status != NULL' failed
(08:09:50) g_log: purple_status_is_online: assertion 'status != NULL' failed
(08:09:50) g_log: purple_status_is_online: assertion 'status != NULL' failed
(08:09:50) g_log: purple_status_is_online: assertion 'status != NULL' failed
(08:09:52) g_log: purple_status_is_online: assertion 'status != NULL' failed

**Comment by EionRobb** [comment]
And at what time did the buddy go 'away'?

**Comment by drJeckyll** [comment]
May be I was not clear in my first post. Users don't appear in list when I enable account. This is log when I enable account. In my list I can see only online users. 
Without commit there is no such errors when I enable account and I can see user which are away, NA, DND ... not just online users.

**Comment by EionRobb** [comment]
Can you try with that commit and see if it helps?

**Comment by drJeckyll** [comment]
It's better. Now users are shown, but icons are wrong ... 

This is list with old icons: http://images.f-e-n.net/3/4ce31caedabd0f8522807fad3cf75b75.png
As you can see there are away and NA status icons.

Now they look like this: http://images.f-e-n.net/3/e31f13660e2e66a5570df657501868b6.png
I think away become invisible, and NA become away ...

**Comment by EionRobb** [comment]
That's the intended effect of https://github.com/EionRobb/skype4pidgin/commit/ec057ab63f34e626918d6c2e86ce0a7b616006c1
