### ISSUE TITLE
Skype with Spectrum 2

### ISSUE THREAD

**Issue by Zombie-Ryushu** [EionRobb/skype4pidgin#532]
Using SkypeWeb with Spectrum 2 results in these error repeatedly in the console and logs:

(process:21406): Json-CRITICAL **: json_array_get_length: assertion 'array != NULL' failed

(process:21406): Json-CRITICAL **: json_node_get_array: assertion 'JSON_NODE_TYPE (node) == JSON_NODE_ARRAY' failed

(process:21406): Json-CRITICAL **: json_array_get_length: assertion 'array != NULL' failed

(process:21406): Json-CRITICAL **: json_node_get_array: assertion 'JSON_NODE_TYPE (node) == JSON_NODE_ARRAY' failed

(process:21406): Json-CRITICAL **: json_array_get_length: assertion 'array != NULL' failed

(process:21406): Json-CRITICAL **: json_node_get_array: assertion 'JSON_NODE_TYPE (node) == JSON_NODE_ARRAY' failed

(process:21406): Json-CRITICAL **: json_array_get_length: assertion 'array != NULL' failed
Almost continuously.

Recompiled for Pidgin 2.12.0

**Comment by EionRobb** [comment]
A bit dodgy, but that commit should do the trick
