### ISSUE TITLE
No avatars

### ISSUE THREAD

**Issue by xvitaly** [EionRobb/skype4pidgin#534]
No avatars after latest commits. Pidgin show default Skype avatar for all users in message dialogues. Tested on 49cd9cf95714605fedc63cf357cb3addd6d342b2.
![rt9](https://cloud.githubusercontent.com/assets/966711/24357942/d31a5526-1318-11e7-950a-ab832a73badd.png)

Also there are no avatars in User Information windows too.

**Comment by xvitaly** [comment]
More test results:
 * start Pidgin with purple-skypeweb plugin -> can see avatars in message dialogues;
 * RMB on buddy - User Information -> no avatar for this contact.

**Comment by EionRobb** [comment]
So, just to confirm, the avatar only goes away after opening the "Get Info" screen for the buddy?

**Comment by xvitaly** [comment]
> So, just to confirm, the avatar only goes away after opening the "Get Info" screen for the buddy?

Yes.

**Comment by EionRobb** [comment]
I tried playing around with fixing it, but instead just got rid of the code to get an updated avatar, it doesn't seem to ever work.  Can you test fc3d6f3 to confirm?

**Comment by xvitaly** [comment]
> Can you test fc3d6f3 to confirm?

Tested [build](https://koji.fedoraproject.org/koji/taskinfo?taskID=18662331). Now works fine. Thanks.

**Comment by EionRobb** [comment]
Released in https://github.com/EionRobb/skype4pidgin/releases/tag/1.3
