### ISSUE TITLE
Cannot chat with or see Skype for Business accounts

### ISSUE THREAD

**Issue by BoFiS** [EionRobb/skype4pidgin#536]
My friend uses Lync, or Skype for Business, and while I can see his account and chat with him in the Skype app, it does not work in Pidgin.  In fact, when I send him messages in Skype proper I get those same messages sent back to me in Pidgin, as though they are messages from me to me :-\

**Comment by EionRobb** [comment]
Hmm... we've been working through this in Issue #470.  What version of the skypeweb plugin are you using?

**Comment by BoFiS** [comment]
Hi, I'm using v1.2.2 is there a beta or other version that maybe addresses this?  Should I close this and add comments in the other issue thread?

**Comment by EionRobb** [comment]
Ah, yes, it won't be available until v1.3 which is due out later this week.

In the meantime, you can compile from source yourself, or use one of the pre-built nightly dll's from https://eion.robbmob.com/libskypeweb-debug.dll (making sure you remove all other libskypeweb dll/so's from your plugins folder if you use either of those two options)

**Comment by BoFiS** [comment]
Thank you, that pre-built nightly DLL solves the issue and now I can see status of, and chat with Skype for Business accounts using my personal Skype account!

**Comment by EionRobb** [comment]
Glad to hear it :)

Thanks for reporting back with the update :)
