### ISSUE TITLE
Incoming file transfer can't close file after complete transfer

### ISSUE THREAD

**Issue by LynxChaus** [EionRobb/skype4pidgin#537]
Missing call to purple_xfer_end() after completing file transfer - lead to broken files and leak file descriptors.

```diff --git a/skypeweb/skypeweb_contacts.c b/skypeweb/skypeweb_contacts.c
index 60bd437..f067915 100644
--- a/skypeweb/skypeweb_contacts.c
+++ b/skypeweb/skypeweb_contacts.c
@@ -376,6 +376,7 @@ skypeweb_got_file(PurpleUtilFetchUrlData *url_data, gpointer user_data, const gc
        
        //cleanup
        skypeweb_free_xfer(xfer);
+       purple_xfer_end(xfer);
 }
 
 static void
```

And purple_xfer_set_bytes_sent() after purple_xfer_write_file() not need, purple_xfer_write_file() update sizes internally.

**Comment by EionRobb** [comment]
Could you send through those two changes as a PR?

**Comment by EionRobb** [comment]
Whoops, I stuffed up that commit - that should have been tagged as being created by you, @LynxChaus 
I'll see if I can fix

**Comment by EionRobb** [comment]
This ended up sneaking its way into https://github.com/EionRobb/skype4pidgin/releases/tag/1.3

**Comment by ildar** [comment]
This is the major issue, should be released asap.

**Comment by dequis** [comment]
@ildar the ticket is closed as fixed and the last comment says that this is included in a release that happened months ago

**Comment by ildar** [comment]
Indeed. Sorry for the noise.
