### ISSUE TITLE
Results check of virustotal. Why .dll and .exe have not quite good indicators?

### ISSUE THREAD

**Issue by smolskimo** [EionRobb/skype4pidgin#539]
hello. i would like to ask you small question about your this plugin. It works great, thank you so much for your work, but

I use earlier skypeweb for Miranda ng, but it does not have offline checking of messages. If you write to offline, then the messages do not reach.
You solved this problem and it's great
But I checked the installation file and some .dll on the viruses, and for some reason the results did not good

For example 
pidgin-skypeweb-installer.exe
https://virustotal.com/ru/file/543be04291a93c0e7e308a1189d504c8b1b2304c1f2e60842c9ef95ba6e81035/analysis/

or .dll
(libskypeweb-debug.dll)
https://virustotal.com/ru/file/b848c578fe1578d565fd45bf46ddd3139505329aeb14107c1781e2826049baa7/analysis/

or libskypeweb.dll.dbg
https://virustotal.com/ru/file/69295979db59a9f1c728e2c86b8c804ea1ffe4e24db470498e24469290d441fe/analysis/

Could you explain why this is so? I checked and earlier versions on virustotal, not only new, and the results are actually the same everywhere, ie they did not change. The names are not related to downloading from other places or unpacking, or third-party advertising in the program, so I can not understand - where does it come from?

**Comment by dequis** [comment]
http://www.techsupportalert.com/content/what-false-positive-antivirus-detection.htm

But only three false positives (out of 61) in three antiviruses that no one uses seems like a pretty good score if you ask me.

**Comment by smolskimo** [comment]
I understand you, but even a single response to the malicious code already causes some suspicion.
Yes, it often occurs even in the most innocuous programs, but there are no level titles
Win32.Trojan.WisdomEyes.16070401.9500.9886
and so on
I'm not a developer, but I understand a little about cryptography and how to crypting out files, cleaning the stub or redirecting the code, and so on, you probably understand what the speech is about. You can actually any file with any malicious code, but the signatures will be shown only by several antiviruses

**Comment by smolskimo** [comment]
Is it possible to write to them about these, as you write, perhaps false responses, so that antivirus companies recheck the file?

**Comment by dequis** [comment]
Each antivirus product has its own procedures to submit false positives. I googled "baidu antivirus false positive" and got http://antivirus.baidu.com/en/submit-file.php. Have fun

**Comment by EionRobb** [comment]
Unfortunately not much we can do about false positives.  Probably the best way of guaranteeing that you're not downloading any viruses is to compile the plugin yourself.
