### ISSUE TITLE
Pidgin Crashes after receiving text file

### ISSUE THREAD

**Issue by logixtreeCode** [EionRobb/skype4pidgin#540]
Hello, 
Everything is working unless we receive a file. 

After receiving a file over skype, a window pop to accept or decline. Then after accept a window popup to choose directory. After than a window with only close sign shows. Few seconds after pidgin crashes. 

System Details : 
Pidgin 2.12.0 (libpurple 2.12.0)
skypeweb-1.3.0
Xubuntu Desktop 17.04 

I have also generated a debug.log from pidgin. Just curious to know if it's okay to share it here.

Regards,
Team LogixTree

**Comment by EionRobb** [comment]
A backtrace would be even better, if you can use https://developer.pidgin.im/wiki/GetABacktrace we can start with that - a debug log may not be needed.

**Comment by EionRobb** [comment]
Will reopen once we get a backtrace :)
