### ISSUE TITLE
(SkypeWeb) Can't receive messages except on plugin restart

### ISSUE THREAD

**Issue by Penaz91** [EionRobb/skype4pidgin#541]
I started noticing that the Skypeweb plugin doesn't receive messages automatically, but I need to reload the plugin for it to do so.
In the debug window there are some 404 errors when I reload the plugin or use it.
I added a log with all what happens when I reload the plugin and how it behaves for a good 5 minutes (buddy names removed for obvious reasons).
Thank you for this plugin, it really made things much easier for me and I'd love to have this working again.
[debug.zip](https://github.com/EionRobb/skype4pidgin/files/924623/debug.zip)

**Comment by EionRobb** [comment]
What version of the plugin are you using?  1.3.0 or a pull from git?

**Comment by Junker** [comment]
i confirm it too. last 2 days have this problem, cannot receive messages. i'm using last dev version.

**Comment by Penaz91** [comment]
I use the latest pull from git too

**Comment by EionRobb** [comment]
Looks like there's still some kinks to work out from the purple3 compatability code (issue #538).  If everyone could try the latest commit to see if that helps, that would be appreciated :)

**Comment by Penaz91** [comment]
Seems to be working for now, I just installed the new Git version, I will keep you updated. Thank you a lot. :+1:

**Comment by Junker** [comment]
confirm, it works now

**Comment by Penaz91** [comment]
I have been using the plugin for a solid 6 hours without running into any issue (I even got an episode where #386 didn't present itself, with an image successfully showing, I'm so happy xD).
I'll mark this as closed and solved.

**Comment by EionRobb** [comment]
Yay! Glad to get it solved. :) 

Thanks everyone for the feedback and apologies for breaking it so badly
