### ISSUE TITLE
Can't connect / active plugin. Failed getting PPFT value.

### ISSUE THREAD

**Issue by MartinX3** [EionRobb/skype4pidgin#546]
Linux Mint 18.1 (Ubuntu 16.04)
purple-skypeweb 1.4.0+git20170502-1\~webupd8\~xenial0

Tested with both
Pidgin 2.10.12-0ubuntu5.2
Pidgin 2.12.0-1ubuntu1~16.04.york0

Tested with old skype credentials and with the microsoft account credentials

Error message, while trying to activate the account:
> Failed getting PPFT value

**Comment by EionRobb** [comment]
Can you get a debug log out of Pidgin? Did you follow the steps in the flowchart? Have you logged into web.skype.com through your browser?

**Comment by MartinX3** [comment]
web.skype.com
I thought it isn't the use of 2-factor, because there is no magic number error
Is it still not supported?

**Comment by EionRobb** [comment]
No two-factor authentication isn't supported yet

**Comment by MartinX3** [comment]
Thank you for the information :)

Is there a ROADMAP, which shows me, when it will be implemented?
