### ISSUE TITLE
SKype for Business?

### ISSUE THREAD

**Issue by bpmcdowell** [EionRobb/skype4pidgin#547]
Wondering if the skype4pidgin is intended to work with Skype for Business? Just got pushed over into the new platform today and I'm getting the "Failed getting Magic T value" error. I'd love to follow the troubleshooting flowchart but when I try the web.skype.com or login.live.com links I'm told my for business Skype login "That Microsoft account doesn't exist. Enter a different account or get a new one." Well, the account works fine in the Skype for Business app. I did login at those sites with my "regular" Microsoft account and it works find, but did not change the error in Pidgin.

Your patience and reply appreciated in advance!

**Comment by dequis** [comment]
https://sourceforge.net/projects/sipe/

**Comment by bpmcdowell** [comment]
Found what appears to be a Windows installer and applied that with Pidgin turned off, started Pidgin and still get the Magic T error. Don't see anywhere to configure the plugin. Do I need to remove skype4pidgin first?

**Comment by dequis** [comment]
That is a different plugin, not related to this one. The magic T error is from this plugin. Remove the account you added for this plugin and add one for the other plugin (which probably calls itself something like office communicator).

**Comment by bpmcdowell** [comment]
Thank you, thank you, thank you! That was the nudge I needed. Did get an error about "You have been rejected by the server: https://portal.microsoftonline.com/download/lync.aspx" but the very comprehensive FAQ had a solution for that.

Many thanks again!!!

**Comment by dequis** [comment]
Neat. If you have any other issues with that plugin, use their help forum at sourceforge:

https://sourceforge.net/p/sipe/discussion/688534/
