### ISSUE TITLE
Will it work after July 1?

### ISSUE THREAD

**Issue by bmomjian** [EionRobb/skype4pidgin#549]
Skype/MS has announced they are terminating support for Skype 4.3 (Linux) clients on July 1.  Will this plugin continue working after that date?

**Comment by EionRobb** [comment]
There's no reason at this stage to expect it to not work after the 1st of July since we use the same protocol as what the current web.skype.com and mobile clients use

**Comment by EionRobb** [comment]
Might just leave this open until after the 1st of July :)

**Comment by EionRobb** [comment]
First of July been and gone and the world didn't explode.  I call that a success :)
