### ISSUE TITLE
Download link in README.md

### ISSUE THREAD

**Issue by bmomjian** [EionRobb/skype4pidgin#550]
The README.md file at:

   https://github.com/EionRobb/skype4pidgin/blob/master/skypeweb/README.md

says:

   Download latest releases from here

but "here" points to:

   https://github.com/EionRobb/skype4pidgin/releases

Is skypeweb the name of the fork of skype4pidgin, but it still uses the skype4pidgin name?

**Comment by EionRobb** [comment]
Nope, that's correct.  I was naughty and used one repo for several plugins, but there's only a single "releases" section per repo
