### ISSUE TITLE
Failure due to: ServiceProxy_Timeout.

### ISSUE THREAD

**Issue by o1o1o1o1o1** [EionRobb/skype4pidgin#551]
Since yesterday i sometimes get the message "Failure due to: ServiceProxy_Timeout." and my contacs dont get my messages. When i open Skype in the browser my previously sended messages dont appear there.
Im using Windows 10 and Solus (Linux) and get the error on both versions.

**Comment by EionRobb** [comment]
That's a new one.  Does your Pidgin connect via a Proxy?

Are you able to get a debug log from Help->Debug Window as it happens next?

**Comment by o1o1o1o1o1** [comment]
I dont use any Proxy
The error appears at 12:09:33

`(12:08:47) http: Performing new request 07CAA960 to db5-client-s.gateway.messenger.live.com.
(12:08:51) http: Performing new request 07CAA4C8 to db5-client-s.gateway.messenger.live.com.
(12:08:57) http: Performing new request 07CA98F8 to db5-client-s.gateway.messenger.live.com.
(12:09:03) jabber: Sending (ssl) (misaki-chan@xmppnet.de/0de19e6c-440d-436c-b78b-362ebcb84ef0): <iq type='get' id='purple5c8d3f09'><ping xmlns='urn:xmpp:ping'/></iq>
(12:09:03) jabber: Recv (ssl)(104): <iq id='purple5c8d3f09' type='result' to='misaki-chan@xmppnet.de/0de19e6c-440d-436c-b78b-362ebcb84ef0'/>
(12:09:03) http: Performing new request 07CA97A8 to db5-client-s.gateway.messenger.live.com.
(12:09:03) dnsquery: Performing DNS lookup for db5-client-s.gateway.messenger.live.com
(12:09:03) dnsquery: IP resolved for db5-client-s.gateway.messenger.live.com
(12:09:03) proxy: Attempting connection to 40.77.226.194
(12:09:03) proxy: Connecting to db5-client-s.gateway.messenger.live.com:443 with no proxy
(12:09:03) proxy: Connection in progress
(12:09:03) proxy: Connecting to db5-client-s.gateway.messenger.live.com:443.
(12:09:03) proxy: Connected to db5-client-s.gateway.messenger.live.com:443.
(12:09:03) nss: SSL version 3.3 using 128-bit AES with 256-bit SHA256 MAC
Server Auth: 2048-bit RSA, Key Exchange: 256-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
(12:09:03) nss: subject=CN=apis.skype.com issuer=CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US
(12:09:03) nss: subject=CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US issuer=CN=Baltimore CyberTrust Root,OU=CyberTrust,O=Baltimore,C=IE
(12:09:03) nss: partial certificate chain
(12:09:03) certificate/x509/tls_cached: Starting verify for db5-client-s.gateway.messenger.live.com
(12:09:03) certificate/x509/tls_cached: Checking for cached cert...
(12:09:03) certificate/x509/tls_cached: ...Found cached cert
(12:09:03) nss/x509: Loading certificate from C:\Users\lol\AppData\Roaming\.purple\certificates\x509\tls_peers\db5-client-s.gateway.messenger.live.com
(12:09:03) certificate/x509/tls_cached: Peer cert matched cached
(12:09:03) nss/x509: Exporting certificate to C:\Users\lol\AppData\Roaming\.purple\certificates\x509\tls_peers\db5-client-s.gateway.messenger.live.com
(12:09:03) util: Writing file C:\Users\lol\AppData\Roaming\.purple\certificates\x509\tls_peers\db5-client-s.gateway.messenger.live.com
(12:09:03) nss: Trusting CN=apis.skype.com
(12:09:03) certificate: Successfully verified certificate for db5-client-s.gateway.messenger.live.com
(12:09:06) purple-splitter: splitter plugin invoked
(12:09:06) http: Performing new request 07CA9A48 to db5-client-s.gateway.messenger.live.com.
(12:09:06) http: Performing new request 07CA9E38 to db5-client-s.gateway.messenger.live.com.
(12:09:06) dnsquery: Performing DNS lookup for db5-client-s.gateway.messenger.live.com
(12:09:06) dnsquery: IP resolved for db5-client-s.gateway.messenger.live.com
(12:09:06) proxy: Attempting connection to 40.77.226.194
(12:09:06) proxy: Connecting to db5-client-s.gateway.messenger.live.com:443 with no proxy
(12:09:06) proxy: Connection in progress
(12:09:06) proxy: Connecting to db5-client-s.gateway.messenger.live.com:443.
(12:09:06) proxy: Connected to db5-client-s.gateway.messenger.live.com:443.
(12:09:06) nss: SSL version 3.3 using 128-bit AES with 256-bit SHA256 MAC
Server Auth: 2048-bit RSA, Key Exchange: 256-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
(12:09:06) nss: subject=CN=apis.skype.com issuer=CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US
(12:09:06) nss: subject=CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US issuer=CN=Baltimore CyberTrust Root,OU=CyberTrust,O=Baltimore,C=IE
(12:09:06) nss: partial certificate chain
(12:09:06) certificate/x509/tls_cached: Starting verify for db5-client-s.gateway.messenger.live.com
(12:09:06) certificate/x509/tls_cached: Checking for cached cert...
(12:09:06) certificate/x509/tls_cached: ...Found cached cert
(12:09:06) nss/x509: Loading certificate from C:\Users\lol\AppData\Roaming\.purple\certificates\x509\tls_peers\db5-client-s.gateway.messenger.live.com
(12:09:06) certificate/x509/tls_cached: Peer cert matched cached
(12:09:06) nss/x509: Exporting certificate to C:\Users\lol\AppData\Roaming\.purple\certificates\x509\tls_peers\db5-client-s.gateway.messenger.live.com
(12:09:06) util: Writing file C:\Users\lol\AppData\Roaming\.purple\certificates\x509\tls_peers\db5-client-s.gateway.messenger.live.com
(12:09:06) nss: Trusting CN=apis.skype.com
(12:09:06) certificate: Successfully verified certificate for db5-client-s.gateway.messenger.live.com
(12:09:12) http: Request 07CAA4C8 performed without success.
(12:09:19) http: Request 07CA98F8 performed without success.
(12:09:24) http: Request 07CA97A8 performed without success.
(12:09:26) http: Request 07CAA960 performed successfully.
(12:09:26) skypeweb: executing callback for https://db5-client-s.gateway.messenger.live.com/v1/users/ME/endpoints/SELF/subscriptions/0/poll
(12:09:27) http: Request 07CA9A48 performed without success.
(12:09:28) http: Performing new request 07CAA420 to db5-client-s.gateway.messenger.live.com.
(12:09:33) http: Performing new request 07CA9EE0 to contacts.skype.com.
(12:09:33) http: Request 07CAA420 performed successfully.
(12:09:33) skypeweb: executing callback for https://db5-client-s.gateway.messenger.live.com/v1/users/ME/endpoints/SELF/subscriptions/0/poll
(12:09:33) http: Request 07CA9E38 performed without success.
(12:09:33) skypeweb: executing callback for https://db5-client-s.gateway.messenger.live.com/v1/users/ME/conversations/8%3Aa-tour89/messages
(12:09:33) g_log: purple_conversation_get_chat_data: assertion `conv != NULL' failed
(12:09:33) http: Request 07CA9EE0 performed successfully.
(12:09:33) skypeweb: executing callback for https://contacts.skype.com/contacts/v2/users/SELF/invites
(12:09:34) http: Performing new request 07CA9508 to db5-client-s.gateway.messenger.live.com.`

**Comment by EionRobb** [comment]
I'm not seeing a "Failure due to: ServiceProxy_Timeout" error in the log there.  Was this log captured when you got that specific error?

**Comment by o1o1o1o1o1** [comment]
Yes but the error appears only in the message window

**Comment by EionRobb** [comment]
Does disconnecting and reconnecting to the account in Pidgin help?

**Comment by o1o1o1o1o1** [comment]
No because i get the error yesterday too and since then i restartet Pidgin at least 2-3 times
It appears randomly and goes away after some minutes

**Comment by o1o1o1o1o1** [comment]
I was going back to the old Version 1.3 for a while and the error never happens and it works like back then

**Comment by o1o1o1o1o1** [comment]
I blocked some IPs from Microsoft servers in my router to stop windows 10 from spying me and sometimes skype need one of them and this is why i got the randomly appear errors.
Sorry for making this stupid bugreport
