### ISSUE TITLE
Sending lots of whitespace on first messages

### ISSUE THREAD

**Issue by boris-petrov** [EionRobb/skype4pidgin#555]
Sending anything after I've started Pidgin always sends a lot of whitespace in the end of the message. This stops after the person the chat is with answers - after that all messages are sent fine. This is not a new issue - it has been so from day one of the `skypeweb` version of the plugin. Please tell me if you need anything from me to debug this. :)

**Comment by EionRobb** [comment]
Do you use the OTR plugin? This is normally caused by that plugin trying to auto start an OTR session

**Comment by boris-petrov** [comment]
I have it installed however I've never used it with Skype. Normally I should manually initiate an OTR session, why would it try automatically?

**Comment by EionRobb** [comment]
If you have it set to try to auto start an OTR session in the settings it will try to auto start using the whitespace

**Comment by boris-petrov** [comment]
I see, thanks for that, I'll try and will reopen if the issue is still there. Thanks!

**Comment by EionRobb** [comment]
Whoops sorry, didn't mean to accidentally close this - please feel free to reopen if there's still issues after disabling the "Automatically initiate private messaging" setting for your Skype account
