### ISSUE TITLE
Upcoming skype changes

### ISSUE THREAD

**Issue by alexolog** [EionRobb/skype4pidgin#565]
Got this emailed to my account:

> Dear Customer,
> 
> We’ve noticed that you are, or previously were, using an older version of Skype for Windows 7.‍17-7.‍30. This is a reminder to please update Skype for Windows as your version will be permanently retired, and after Septe‍mber 4, 20‍17 you will be unable to sign‑in.
> 
> Recently updated? Great, you can ignore this email.
> Thank you,
> 
> Skype 

Does this affect the plugin in any way?

**Comment by EionRobb** [comment]
Hopefully not, didn't seem to affect us when they last sent out an email as such
