### ISSUE TITLE
Binary embedded images do no appear in Spectrum 2.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [EionRobb/skype4pidgin#569]
Binary embedded images do no appear in Spectrum 2. When someone sends an image to an XMPP Client running Pidgin via a Spectrum 2 Gateway, Said image does not appear while running the SkypeWeb Plugin Directly does.

**Comment by dequis** [comment]
That's a problem with spectrum2. I'm pretty sure they have config entries to enable this.
