### ISSUE TITLE
Is possible whatsapp4pidgin?

### ISSUE THREAD

**Issue by usernatilds** [EionRobb/skype4pidgin#571]
Very good plugin skype4pidgin based web, but the same creators can made a similar plugin whatsapp using whatsappweb?

This is a suggestion, if possible made.

**Comment by EionRobb** [comment]
Sorry, off-topic for this plugin

**Comment by usernatilds** [comment]
Okay, but can you answer if in the future you want to do something for whatsapp?

**Comment by lmfardin** [comment]
Once there was a plugin for WhatsApp on Pidgin, but it's no longer working.Last time I tried to use it, my number got banned from WhatsApp. Apparently, they have some sort of control to prevent third party applications to emulate it.
    Em sexta-feira, 6 de outubro de 2017 06:00:29 BRT, usernatilds <notifications@github.com> escreveu:  
 
 
Okay, but can you answer if in the future you want to do something for whatsapp?
