### ISSUE TITLE
Does it still work ? (20 dec)

### ISSUE THREAD

**Issue by linuxenko** [EionRobb/skype4pidgin#579]
Something went wrong with `skypeweb` last hour, I've lost connections of all of my skype accounts I work with via `bitlbee + skypeweb`.

If someone has the same problem please gave me know. Even if it works just fine, cannot figure out where the problem is ...

Thank you

**Comment by EionRobb** [comment]
Still working here.  Can you get a debug log out of bitlbee to see what the issue is?

https://wiki.bitlbee.org/Debugging

Also, what version of bitlbee and skypeweb?

**Comment by linuxenko** [comment]
Almost all accounts come back online now, but there is a couple with following message: 

```
 Login error: Failed getting PPFT value
```

Looks like M$ is very angry today ))))

**Comment by EionRobb** [comment]
Can you build the plugin from git and use the 'Use alternative login method' setting?

Also, what version of bitlbee and skypeweb?

**Comment by linuxenko** [comment]
It started working without any efforts from me. I don't know how to explain it.. 
Anyways, thank you @EionRobb  for the support !

**Comment by EionRobb** [comment]
Alrighty :)
