### ISSUE TITLE
Enable timeout configuration

### ISSUE THREAD

**Issue by robross0606** [EionRobb/skype4pidgin#580]
Over slow connections, the plugin times out too fast when trying to connect.  The regular Skype for Business application negotiates a connection without problem because it has a longer timeout.

**Comment by EionRobb** [comment]
How slow a connection? What should the allowed timeout be?

**Comment by robross0606** [comment]
Sorry, this was posted to the wrong project.  I mean to do it against Skype for Business (SIPE).  Apologies.

**Comment by EionRobb** [comment]
All good :)
