### ISSUE TITLE
Alpine json-glib dependency

### ISSUE THREAD

**Issue by realies** [EionRobb/skype4pidgin#588]
Working on a minimal Docker image for BitlBee with plugins. It seems that everything works fine when `skype4pidgin` is compiled with [`json-glib-dev`](https://pkgs.alpinelinux.org/package/v3.7/main/x86/json-glib-dev) and having [`json-glib`](https://pkgs.alpinelinux.org/package/v3.7/main/x86/json-glib) missing. Can you please confirm that having only [`json-glib-dev`](https://pkgs.alpinelinux.org/package/v3.7/main/x86/json-glib-dev) is sufficient?

**Comment by EionRobb** [comment]
That json-glib-dev package on its own would let it compile, not run, but the json-glib package looks like it's a dependency of json-glib-dev anyway?

**Comment by realies** [comment]
Did not spot the `origin` field, thanks for the clarification. Assuming it's a good idea having both listed in the dependencies.

**Comment by realies** [comment]
Can confirm that `skype4pidgin` still works when `json-glib-dev` is removed and `json-glib` is present after compilation.
