### ISSUE TITLE
Rooms list lacks a member count

### ISSUE THREAD

**Issue by bodqhrohro** [EionRobb/skype4pidgin#589]
F.e., for IRC channels the following column is displayed:
![2018-02-13-155109_827x396_scrot](https://user-images.githubusercontent.com/2134486/36153530-3c3ccec8-10d7-11e8-9640-b9db0cfdecf9.png)
But there is no such column for Skype group chats. Can it be easily added or it would lead to expensive requests for every chat separately?

**Comment by xavery** [comment]
You're in luck : the number of members is present in the messages supplied by the server. PR #598 solves this .

**Comment by bodqhrohro** [comment]
Great, it works, thank you. However, not for every chat; some of them, mostly old ones, don't have a counter.

**Comment by monsta** [comment]
You can close this as https://github.com/EionRobb/skype4pidgin/pull/598 has been merged.

**Comment by bodqhrohro** [comment]
> You can close this as #598 has been merged.

Okay, I made some debugging and now see that old chats just lack the `threadProperties.membercount` attribute for some reason. So this is probably everything that could be done.

**Comment by xavery** [comment]
Yes, I reached the same conclusion while writing this patch : the server just doesn't return the data for some of the chats. Maybe it would be possible to work around this by asking each room for all the members and then returning the count, but I haven't investigated it further.
