### ISSUE TITLE
No way to retrieve group chat history 

### ISSUE THREAD

**Issue by jeenuv** [EionRobb/skype4pidgin#592]
As subject, I don't see a way to access or resume a group chat that I was participating. The main window only shows Skype contacts, but no group chats.

**Comment by EionRobb** [comment]
Tools->Room List

I've been thinking about automatically adding group chats to the buddy list like the Hangouts plugin does, but that can dredge up a lot of old useless group chats with no good way to get rid of them without them appearing at the next account connection

**Comment by jeenuv** [comment]
Ah, I missed that - thanks. As you mentioned, in there I can see chats before time!

I'll close this issue now.
