### ISSUE TITLE
Strange message was sent to last two person I have conversation with

### ISSUE THREAD

**Issue by KryDos** [EionRobb/skype4pidgin#602]
Hello. 

Today I have noticed that two latest persons I had conversation with yesterday evening got message form me today morning (probably when I've open up my laptop).

The message looks to me as base64 encoded something:

```
?OTR:AAMC9rZH2wAAAAAAAADE2eU10ItIRdpe7Pn4mPyI18HE5ut6fIyBXa+Etg3d/PTVOdkD63pLTreP4S6CTuoLOz5F6Qbhqi3oRwCccWt+y+b4gza9sBQzOSWbOn/7gHzKWTtZs2txJsulDWMpvMfn1xONx3ckcb6mECSWWgOm67AXPrATpFa945IhWN/ZMepM+i76mP4jiILgklWoS5ez7EYPTy97eXaMgv9eLnspJW8sw21wgG3ndZQWFyCp3BKNsYLAdCeRJ2LkFmo6wxwJrVlDUwAAACDOMdtbRBBYRmAfv8OggWtbSbft9Bw6IBTbUqiKTjdylw==.
```

I hope there is nothing private in this string. Both persons got different strings. 

I use BitlBee and Weechat. Please let me know what do you think it is.

**Comment by EionRobb** [comment]
That's the OTR plugin sending an encrypted message

**Comment by KryDos** [comment]
@EionRobb I was trying to understand more about OTR and recompiled my Bitlbee with disabled OTR option. But I still not really understand, why skype plugin (or bitlbee) is sending this encrypted message without me knowing and asking. I don't want it to be send to anyone. 

Is it appropriate to keep asking about it here?

**Comment by EionRobb** [comment]
Nope, that's just how OTR works.
