### ISSUE TITLE
Debian 64bit, cmake error - glib2.0 not found

### ISSUE THREAD

**Issue by bep11** [EionRobb/skype4pidgin#605]
Hello,
I built skype4pidgin without problems on a 32bit machine.
However, I needed it on a 64bit notebook and here built failed with a "glib-2.0 not found" error. There is no libglib2.0 for 64bit machines but a libglib2.0.0 package.
What do I have to change to build the 64bit package?
Thanks

**Comment by dequis** [comment]
Install libglib2.0-dev

**Comment by bep11** [comment]
Thank you very much! That worked.
I have a more general question. Does the plugin depend either the full (Linux) skype package? I did install the Linux skype package but wonder if this is really necessary.
Thanks

**Comment by ildar** [comment]
It doesn't. It uses webpage of browser version of Skype.

**Comment by bep11** [comment]
Hi Ildar,
great; thanks for the info.
