### ISSUE TITLE
Any new builds after 1.4 to be released?

### ISSUE THREAD

**Issue by kiravi** [EionRobb/skype4pidgin#611]
Eion,

It has been a long time since last build 1.4.  Looks like more commits after that.

Any plans for a new build?

Ravi

**Comment by EionRobb** [comment]
Whoops, yes.  I just forgot :)

**Comment by dequis** [comment]
God dammit eion

**Comment by EionRobb** [comment]
https://github.com/EionRobb/skype4pidgin/releases/tag/1.5

🎉

**Comment by kiravi** [comment]
Thanks Eion!!

**Comment by kiravi** [comment]
Another update after 1.5? July has seen more commits?
