### ISSUE TITLE
[skypeweb] libpurple-3 support broken

### ISSUE THREAD

**Issue by jderehag** [EionRobb/skype4pidgin#614]
Seems like the libpurple-3 support is broken (has it ever worked?).

_$> git checkout 1.4 # which should have worked_
_$>make_
cc -fPIC -O2 -g -pipe -shared -o libskypeweb3.so libskypeweb.c skypeweb_connection.c skypeweb_contacts.c skypeweb_login.c skypeweb_messages.c skypeweb_util.c   `pkg-config purple-3 glib-2.0 json-glib-1.0 zlib --libs --cflags`   -g -ggdb

skypeweb_util.c:21:32: fatal error: ciphers/sha256hash.h: No such file or directory
 #include "ciphers/sha256hash.h"

_$>find . -name "sha256hash.h"_
./purple2compat/ciphers/sha256hash.h

**So apparently its in the purple2compat dir, (which is not in the include path for purple3, see CC line above).**

**When switching to 1.5 we get additional errors:**
_$>git checkout 1.5_
_$>make clean; make_
rm -f libskypeweb3.so
cc -fPIC -O2 -g -pipe -shared -o libskypeweb3.so libskypeweb.c skypeweb_connection.c skypeweb_contacts.c skypeweb_login.c skypeweb_messages.c skypeweb_util.c   `pkg-config purple-3 glib-2.0 json-glib-1.0 zlib --libs --cflags`   -g -ggdb

skypeweb_login.c: In function ‘skypeweb_skyper_hash’:
skypeweb_login.c:392:9: warning: implicit declaration of function ‘purple_base64_encode’ [-Wimplicit-function-declaration]
  return purple_base64_encode(hashed, len);
         ^
skypeweb_login.c:392:9: warning: return makes pointer from integer without a cast [-Wint-conversion]
skypeweb_util.c:21:32: fatal error: ciphers/sha256hash.h: No such file or directory
 #include "ciphers/sha256hash.h"
                                ^
compilation terminated.
Makefile:92: recipe for target 'libskypeweb3.so' failed
make: *** [libskypeweb3.so] Error 1

So now we have an additional warning for purple_base64_encode, which it seems was removed from libpurple in revision 38894 (havent figured out exactly why they removed it).
But I suspect you should use glib base64 encode directly.

**Comment by jderehag** [comment]
I suspect alot of that code can actually be removed from the purple2compat layer altogether?
Those functions should be available in glib either way, so switching should work for both purple2 & 3?

**Comment by EionRobb** [comment]
Can you give https://github.com/EionRobb/skype4pidgin/commit/d192665b8ff362c956cf7ab801730c9f736559c4 a try?

**Comment by jderehag** [comment]
Worked like a charm, thanks!

**Comment by EionRobb** [comment]
@jderehag That looks like it might be a different issue?  Can you open a new issue on github and get a backtrace with debug symbols?
