### ISSUE TITLE
"Failed getting Registration Token" leads to assertion failure in BitlBee

### ISSUE THREAD

**Issue by robert-scheck** [EionRobb/skype4pidgin#619]
With 2290013 I'm seeing the following warning in BitlBee:

```
[00:09:41] -!- (process:8880): Json-CRITICAL **: json_node_get_object: assertion `node != NULL' failed
[00:09:41] -!- ** (process:8880): CRITICAL **: skypeweb_string_get_chunk: assertion `haystack && start' failed
[00:09:41] <@root> skypeweb - Error: Failed getting Registration Token
[00:09:41] <@root> skypeweb - Signing off..
```

Maybe there's a way for the future to avoid the assertion failure?

**Comment by EionRobb** [comment]
https://github.com/EionRobb/skype4pidgin/tree/master/skypeweb#issues

**Comment by robert-scheck** [comment]
@EionRobb, the "Failed getting Registration Token" shows up here about once a day and a reconnect works normally. I just would like to get rid of the assertion failures using this issue (do they really need to be thrown?).

**Comment by EionRobb** [comment]
Switching to the alternate auth will skip the Registration Token method entirely.  The assert is necessary to assert that the login succeeded

**Comment by dequis** [comment]
If you're using systemd socket units you'll want something like this https://github.com/bitlbee/bitlbee/commit/bdf9214217579534c9ea6e906ddecaba136e2916

If using (x)inetd i think you can't do much about it

**Comment by sdfg2** [comment]
@EionRobb how would I enable the alt-login method for spectrum?

**Comment by Thaodan** [comment]
Just tested this, this issue no longer happens.

**Comment by Thaodan** [comment]
> @EionRobb how would I enable the alt-login method for spectrum?

@sdfg2: Did you try [Spectrum2/Setting libpurple plugins configurations](https://spectrum.im/documentation/backends/libpurple.html "Some libpurple protocol plugins allow setting configuration variables. Spectrum 2 passes every variable set in purple section to libpurple library. If you need to set such options, you can do it for example like this in your configuration file.") ?
