### ISSUE TITLE
Login error: Internal Server Error (code 50000)

### ISSUE THREAD

**Issue by undeference** [EionRobb/skype4pidgin#620]
I went away from my computer and came back to find that Pidgin had crashed (apparently from steam_post_or_get_readdata_cb from libsteam.so). When I restarted Pidgin, I had "Login error: Internal Server Error (code 50000)" from Skype. This only happens with Pidgin: I can login fine on the website (even with private browsing) and with skypeforlinux.

I am using purple-skypeweb-1.5-3.20180720git2290013.fc28.x86_64 on Fedora 28

**Comment by EionRobb** [comment]
Looks like a temporary server failure.  I had the same problem, but reconnected and its all working again.  Are you able to double check?

(And can you also post the backtrace of the steam plugin on the steam github issue tracker)

**Comment by undeference** [comment]
Ok, that is interesting. I kept trying to reconnect earlier and getting the same problem. Now it works.
