### ISSUE TITLE
Eroror build

### ISSUE THREAD

**Issue by CheckB** [EionRobb/skype4pidgin#624]
OS: Ubuntu 18.04
GCC: 7.3

> make install
> cc -fPIC -O2 -g -pipe -march=westmere -shared -o libskypeweb.so libskypeweb.c skypeweb_connection.c skypeweb_contacts.c skypeweb_login.c skypeweb_messages.c skypeweb_util.c purple2compat/http.c purple2compat/purple-socket.c   `pkg-config purple glib-2.0 json-glib-1.0 zlib --libs --cflags`   -Ipurple2compat -g -ggdb
> Package json-glib-1.0 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `json-glib-1.0.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'json-glib-1.0' found
> In file included from libskypeweb.c:19:0:
> libskypeweb.h:29:10: fatal error: glib.h: No such file or directory
>  #include <glib.h>
>           ^~~~~~~~

Ok.
apt -y install libglib2.0-dev 

pkg-config --cflags --libs glib-2.0

> -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -lglib-2.0

I reassemble and the problem remains the same.

How to fix?

**Comment by dequis** [comment]
>Requires devel headers/libs for libpurple and libjson-glib [libglib2.0-dev, libjson-glib-dev and libpurple-dev]

You also need libjson-glib-dev and libpurple-dev

**Comment by Thaodan** [comment]
Can this be closed out of inactivity?
