### ISSUE TITLE
Cannot login to skype

### ISSUE THREAD

**Issue by YFL** [EionRobb/skype4pidgin#629]
So I've followed the instructions on how to compile this plugin and installed it with dpkg. First I was using pidigin installed with apt (Ubuntu 18.04.1 LTS), then I removed pidgin* with apt and compiled it from src (form sourceforge). I always get the Failed getting PPFT, please try logging in via browser first message. First I thought the problem comes from my skype account not being merged with my microsoft account so I merged them (and I felt real physical pain while doing it), didn't help. So I've created a brand new email and a microsoft account (in the official skype app) still no progress. I even installed empathy and it's skype plugin and it cannot connect to any of my accounts either. (Yep and logging in via browser incognito/non-incognito didn't help). I've tried to use an account which I know is working on ANOTHER MACHINE, and I couldn't use it on mine.
`pidgin --version
Pidgin 2.13.0 (libpurple 2.13.0)`

Here is my pidgin debug info:
(11:32:54) prefs: Reading /home/yofuckinlo/.purple/prefs.xml
(11:32:54) prefs: Finished reading /home/yofuckinlo/.purple/prefs.xml
(11:32:54) prefs: purple_prefs_get_path: Unknown pref /pidgin/browsers/command
(11:32:54) dbus: okkk
(11:32:54) plugins: probing /usr/local/lib/pidgin/gestures.so
(11:32:54) plugins: probing /usr/local/lib/pidgin/ticker.so
(11:32:54) plugins: probing /usr/local/lib/pidgin/gtkbuddynote.so
(11:32:54) plugins: probing /usr/local/lib/pidgin/timestamp_format.so
(11:32:54) plugins: probing /usr/local/lib/pidgin/spellchk.so
(11:32:54) plugins: probing /usr/local/lib/pidgin/relnot.so
(11:32:54) plugins: probing /usr/local/lib/pidgin/xmppdisco.so
(11:32:54) plugins: probing /usr/local/lib/pidgin/extplacement.so
(11:32:54) plugins: probing /usr/local/lib/pidgin/themeedit.so
(11:32:54) plugins: probing /usr/local/lib/pidgin/timestamp.so
(11:32:54) plugins: probing /usr/local/lib/pidgin/convcolors.so
(11:32:54) plugins: probing /usr/local/lib/pidgin/transparency.so
(11:32:54) plugins: probing /usr/local/lib/pidgin/markerline.so
(11:32:54) plugins: probing /usr/local/lib/pidgin/xmppconsole.so
(11:32:54) plugins: probing /usr/local/lib/pidgin/iconaway.so
(11:32:54) plugins: probing /usr/local/lib/pidgin/notify.so
(11:32:54) plugins: probing /usr/local/lib/pidgin/pidginrc.so
(11:32:54) plugins: probing /usr/local/lib/pidgin/sendbutton.so
(11:32:54) plugins: probing /usr/local/lib/pidgin/musicmessaging.so
(11:32:54) plugins: probing /usr/local/lib/pidgin/vvconfig.so
(11:32:54) plugins: probing /usr/local/lib/pidgin/history.so
(11:32:54) plugins: probing /usr/local/lib/purple-2/joinpart.so
(11:32:54) plugins: probing /usr/local/lib/purple-2/libgg.so
(11:32:54) plugins: probing /usr/local/lib/purple-2/libsametime.so
(11:32:54) plugins: /usr/local/lib/purple-2/libsametime.so has a prefs_info, but is a prpl. This is no longer supported.
(11:32:54) plugins: probing /usr/local/lib/purple-2/tcl.so
(11:32:54) plugins: probing /usr/local/lib/purple-2/ssl.so
(11:32:54) plugins: probing /usr/local/lib/purple-2/idle.so
(11:32:54) plugins: probing /usr/local/lib/purple-2/libsimple.so
(11:32:54) plugins: probing /usr/local/lib/purple-2/autoaccept.so
(11:32:54) plugins: probing /usr/local/lib/purple-2/perl.so
(11:32:54) plugins: probing /usr/local/lib/purple-2/libnovell.so
(11:32:54) plugins: probing /usr/local/lib/purple-2/offlinemsg.so
(11:32:54) plugins: probing /usr/local/lib/purple-2/libskypeweb.so
(11:32:54) plugins: probing /usr/local/lib/purple-2/liboscar.so
(11:32:54) plugins: /usr/local/lib/purple-2/liboscar.so is not usable because the 'purple_init_plugin' symbol could not be found.  Does the plugin call the PURPLE_INIT_PLUGIN() macro?
(11:32:54) plugins: probing /usr/local/lib/purple-2/ssl-nss.so
(11:32:54) plugins: probing /usr/local/lib/purple-2/psychic.so
(11:32:54) plugins: probing /usr/local/lib/purple-2/statenotify.so
(11:32:54) plugins: probing /usr/local/lib/purple-2/libicq.so
(11:32:54) plugins: probing /usr/local/lib/purple-2/libbonjour.so
(11:32:54) plugins: probing /usr/local/lib/purple-2/newline.so
(11:32:54) plugins: probing /usr/local/lib/purple-2/log_reader.so
(11:32:54) plugins: probing /usr/local/lib/purple-2/nss-prefs.so
(11:32:54) plugins: probing /usr/local/lib/purple-2/libaim.so
(11:32:54) plugins: probing /usr/local/lib/purple-2/libjabber.so
(11:32:54) plugins: /usr/local/lib/purple-2/libjabber.so is not usable because the 'purple_init_plugin' symbol could not be found.  Does the plugin call the PURPLE_INIT_PLUGIN() macro?
(11:32:54) plugins: probing /usr/local/lib/purple-2/libxmpp.so
(11:32:54) plugins: probing /usr/local/lib/purple-2/libirc.so
(11:32:54) plugins: probing /usr/local/lib/purple-2/ssl-gnutls.so
(11:32:54) plugins: probing /usr/local/lib/purple-2/buddynote.so
(11:32:54) plugins: probing /usr/local/lib/purple-2/dbus-example.so
(11:32:54) plugins: probing /usr/local/lib/purple-2/libzephyr.so
(11:32:54) gg: Loading Gadu-Gadu protocol plugin with libgadu 1.12.1...
(11:32:54) util: Reading file xmpp-caps.xml from directory /home/yofuckinlo/.purple
(11:32:54) util: File /home/yofuckinlo/.purple/xmpp-caps.xml does not exist (this is not necessarily an error)
(11:32:54) jabber: creating hash tables for data objects
(11:32:54) prefs: /purple/status/scores/offline changed, scheduling save.
(11:32:54) prefs: /purple/status/scores/available changed, scheduling save.
(11:32:54) prefs: /purple/status/scores/invisible changed, scheduling save.
(11:32:54) prefs: /purple/status/scores/away changed, scheduling save.
(11:32:54) prefs: /purple/status/scores/extended_away changed, scheduling save.
(11:32:54) prefs: /purple/status/scores/idle changed, scheduling save.
(11:32:54) prefs: /purple/status/scores/offline_msg changed, scheduling save.
(11:32:54) util: Reading file accounts.xml from directory /home/yofuckinlo/.purple
(11:32:54) util: Reading file status.xml from directory /home/yofuckinlo/.purple
(11:32:54) certificate: CertificateVerifier x509, singleuse requested but not found.
(11:32:54) certificate: CertificateVerifier singleuse registered
(11:32:54) certificate: CertificatePool x509, ca requested but not found.
(11:32:54) certificate: CertificateScheme x509 requested but not found.
(11:32:54) certificate/x509/ca: Lazy init failed because an X.509 Scheme is not yet registered. Maybe it will be better later.
(11:32:54) certificate/x509/ca: Init failed, probably because a dependency is not yet registered. It has been deferred to later.
(11:32:54) certificate: CertificatePool ca registered
(11:32:54) certificate: CertificatePool x509, tls_peers requested but not found.
(11:32:54) certificate: CertificatePool tls_peers registered
(11:32:54) certificate: CertificateVerifier x509, tls_cached requested but not found.
(11:32:54) certificate: CertificateVerifier tls_cached registered
(11:32:54) prefs: /purple/logging/format changed, scheduling save.
(11:32:54) prefs: /purple/logging/format changed, scheduling save.
(11:32:54) prefs: /purple/proxy/type changed, scheduling save.
(11:32:54) prefs: /purple/proxy/host changed, scheduling save.
(11:32:54) prefs: /purple/proxy/port changed, scheduling save.
(11:32:54) prefs: /purple/proxy/username changed, scheduling save.
(11:32:54) prefs: /purple/proxy/password changed, scheduling save.
(11:32:54) nss: Cipher - TLS_AES_128_GCM_SHA256: Enabled
(11:32:54) nss: Cipher - TLS_CHACHA20_POLY1305_SHA256: Enabled
(11:32:54) nss: Cipher - TLS_AES_256_GCM_SHA384: Enabled
(11:32:54) nss: Cipher - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256: Enabled
(11:32:54) nss: Cipher - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256: Enabled
(11:32:54) nss: Cipher - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256: Enabled
(11:32:54) nss: Cipher - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256: Enabled
(11:32:54) nss: Cipher - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384: Disabled
(11:32:54) nss: Cipher - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384: Disabled
(11:32:54) nss: Cipher - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA: Enabled
(11:32:54) nss: Cipher - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA: Enabled
(11:32:54) nss: Cipher - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA: Enabled
(11:32:54) nss: Cipher - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256: Enabled
(11:32:54) nss: Cipher - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256: Enabled
(11:32:54) nss: Cipher - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA: Enabled
(11:32:54) nss: Cipher - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384: Disabled
(11:32:54) nss: Cipher - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384: Disabled
(11:32:54) nss: Cipher - TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA: Disabled
(11:32:54) nss: Cipher - TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA: Disabled
(11:32:54) nss: Cipher - TLS_ECDHE_ECDSA_WITH_RC4_128_SHA: Disabled
(11:32:54) nss: Cipher - TLS_ECDHE_RSA_WITH_RC4_128_SHA: Disabled
(11:32:54) nss: Cipher - TLS_DHE_RSA_WITH_AES_128_GCM_SHA256: Enabled
(11:32:54) nss: Cipher - TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256: Enabled
(11:32:54) nss: Cipher - TLS_DHE_DSS_WITH_AES_128_GCM_SHA256: Disabled
(11:32:54) nss: Cipher - TLS_DHE_RSA_WITH_AES_256_GCM_SHA384: Disabled
(11:32:54) nss: Cipher - TLS_DHE_DSS_WITH_AES_256_GCM_SHA384: Disabled
(11:32:54) nss: Cipher - TLS_DHE_RSA_WITH_AES_128_CBC_SHA: Enabled
(11:32:54) nss: Cipher - TLS_DHE_DSS_WITH_AES_128_CBC_SHA: Enabled
(11:32:54) nss: Cipher - TLS_DHE_RSA_WITH_AES_128_CBC_SHA256: Enabled
(11:32:54) nss: Cipher - TLS_DHE_DSS_WITH_AES_128_CBC_SHA256: Disabled
(11:32:54) nss: Cipher - TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA: Disabled
(11:32:54) nss: Cipher - TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA: Disabled
(11:32:54) nss: Cipher - TLS_DHE_RSA_WITH_AES_256_CBC_SHA: Enabled
(11:32:54) nss: Cipher - TLS_DHE_DSS_WITH_AES_256_CBC_SHA: Enabled
(11:32:54) nss: Cipher - TLS_DHE_RSA_WITH_AES_256_CBC_SHA256: Enabled
(11:32:54) nss: Cipher - TLS_DHE_DSS_WITH_AES_256_CBC_SHA256: Disabled
(11:32:54) nss: Cipher - TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA: Disabled
(11:32:54) nss: Cipher - TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA: Disabled
(11:32:54) nss: Cipher - TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA: Enabled
(11:32:54) nss: Cipher - TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA: Enabled
(11:32:54) nss: Cipher - TLS_DHE_DSS_WITH_RC4_128_SHA: Disabled
(11:32:54) nss: Cipher - TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA: Disabled
(11:32:54) nss: Cipher - TLS_ECDH_RSA_WITH_AES_128_CBC_SHA: Disabled
(11:32:54) nss: Cipher - TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA: Disabled
(11:32:54) nss: Cipher - TLS_ECDH_RSA_WITH_AES_256_CBC_SHA: Disabled
(11:32:54) nss: Cipher - TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA: Disabled
(11:32:54) nss: Cipher - TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA: Disabled
(11:32:54) nss: Cipher - TLS_ECDH_ECDSA_WITH_RC4_128_SHA: Disabled
(11:32:54) nss: Cipher - TLS_ECDH_RSA_WITH_RC4_128_SHA: Disabled
(11:32:54) nss: Cipher - TLS_RSA_WITH_AES_128_GCM_SHA256: Enabled
(11:32:54) nss: Cipher - TLS_RSA_WITH_AES_256_GCM_SHA384: Disabled
(11:32:54) nss: Cipher - TLS_RSA_WITH_AES_128_CBC_SHA: Enabled
(11:32:54) nss: Cipher - TLS_RSA_WITH_AES_128_CBC_SHA256: Enabled
(11:32:54) nss: Cipher - TLS_RSA_WITH_CAMELLIA_128_CBC_SHA: Disabled
(11:32:54) nss: Cipher - TLS_RSA_WITH_AES_256_CBC_SHA: Enabled
(11:32:54) nss: Cipher - TLS_RSA_WITH_AES_256_CBC_SHA256: Enabled
(11:32:54) nss: Cipher - TLS_RSA_WITH_CAMELLIA_256_CBC_SHA: Disabled
(11:32:54) nss: Cipher - TLS_RSA_WITH_SEED_CBC_SHA: Disabled
(11:32:54) nss: Cipher - TLS_RSA_WITH_3DES_EDE_CBC_SHA: Enabled
(11:32:54) nss: Cipher - TLS_RSA_WITH_RC4_128_SHA: Enabled
(11:32:54) nss: Cipher - TLS_RSA_WITH_RC4_128_MD5: Enabled
(11:32:54) nss: Cipher - TLS_DHE_RSA_WITH_DES_CBC_SHA: Disabled
(11:32:54) nss: Cipher - TLS_DHE_DSS_WITH_DES_CBC_SHA: Disabled
(11:32:54) nss: Cipher - TLS_RSA_WITH_DES_CBC_SHA: Disabled
(11:32:54) nss: Cipher - TLS_ECDHE_ECDSA_WITH_NULL_SHA: Disabled
(11:32:54) nss: Cipher - TLS_ECDHE_RSA_WITH_NULL_SHA: Disabled
(11:32:54) nss: Cipher - TLS_ECDH_RSA_WITH_NULL_SHA: Disabled
(11:32:54) nss: Cipher - TLS_ECDH_ECDSA_WITH_NULL_SHA: Disabled
(11:32:54) nss: Cipher - TLS_RSA_WITH_NULL_SHA: Disabled
(11:32:54) nss: Cipher - TLS_RSA_WITH_NULL_SHA256: Disabled
(11:32:54) nss: Cipher - TLS_RSA_WITH_NULL_MD5: Disabled
(11:32:54) nss: TLS supported versions: 0x0301 through 0x0304
(11:32:54) nss: TLS versions allowed by default: 0x0301 through 0x0303
(11:32:54) certificate: CertificateScheme x509 requested but not found.
(11:32:54) certificate: CertificateScheme x509 registered
(11:32:54) util: Reading file smileys.xml from directory /home/yofuckinlo/.purple
(11:32:54) util: File /home/yofuckinlo/.purple/smileys.xml does not exist (this is not necessarily an error)
(11:32:54) stun: using server 
(11:32:54) sound: Initializing sound output drivers.
(11:32:54) prefs: /pidgin/conversations/placement changed, scheduling save.
(11:32:54) prefs: purple_prefs_get_bool: Unknown pref /pidgin/docklet/x11/embedded
(11:32:54) gtkmedia: Registering media element types
(11:32:54) util: Reading file blist.xml from directory /home/yofuckinlo/.purple
(11:32:54) plugins: probing /usr/lib/purple-2/pidgin-libnotify.so
(11:32:54) plugins: Unable to find saved plugin /usr/lib/purple-2/pidgin-libnotify.so
(11:32:54) plugins: Loading saved plugin /usr/local/lib/pidgin/notify.so
(11:32:54) plugins: Loading saved plugin /usr/local/lib/purple-2/ssl-nss.so
(11:32:54) plugins: Loading saved plugin /usr/local/lib/purple-2/ssl.so
(11:32:54) plugins: probing /usr/lib/pidgin/unity.so
(11:32:54) plugins: Unable to find saved plugin /usr/lib/pidgin/unity.so
(11:32:54) pounce: Error reading pounces: Failed to open file “/home/yofuckinlo/.purple/pounces.xml”: No such file or directory
(11:32:54) Session Management: ICE initialized.
(11:32:54) Session Management: Connecting with no previous ID
(11:32:54) Session Management: Handling new ICE connection... 
(11:32:54) done.
(11:32:54) Session Management: Connected to manager (gnome-session) with client ID 10254d27d4adeb635154806677425043100000017430081
(11:32:54) Session Management: Using pidgin as command
(11:32:54) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file /usr/local/share/pixmaps/pidgin/protocols/16/skype.png: Failed to open file '/usr/local/share/pixmaps/pidgin/protocols/16/skype.png': No such file or directory
(11:32:54) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file : Failed to open file '': No such file or directory
(11:32:54) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file /usr/local/share/pixmaps/pidgin/protocols/22/skype.png: Failed to open file '/usr/local/share/pixmaps/pidgin/protocols/22/skype.png': No such file or directory
(11:32:54) util: requesting to fetch a URL
(11:32:54) dnsquery: Performing DNS lookup for 192.168.0.1
(11:32:54) Session Management: Received first save_yourself
(11:32:54) Session Management: Received save_complete
(11:32:54) dnsquery: IP resolved for 192.168.0.1
(11:32:54) proxy: Attempting connection to 192.168.0.1
(11:32:54) proxy: Connecting to 192.168.0.1:49652 with no proxy
(11:32:54) proxy: Connection in progress
(11:32:54) proxy: Connecting to 192.168.0.1:49652.
(11:32:54) proxy: Connected to 192.168.0.1:49652.
(11:32:54) util: request constructed
(11:32:54) util: Response headers: 'HTTP/1.1 200 OK
CONTENT-LENGTH: 2712
CONTENT-TYPE: text/xml
DATE: Mon, 21 Jan 2019 11:32:54 GMT
LAST-MODIFIED: Thu, 01 Jan 1970 00:00:30 GMT
SERVER: Linux/3.10.53-HULK2, UPnP/1.0, Portable SDK for UPnP devices/1.6.18
CONNECTION: close

'
(11:32:54) util: parsed 2712
(11:32:54) util: requesting to fetch a URL
(11:32:54) dnsquery: Performing DNS lookup for 192.168.0.1
(11:32:54) dnsquery: Performing DNS lookup for 192.168.0.1
(11:32:54) dnsquery: IP resolved for 192.168.0.1
(11:32:54) proxy: Attempting connection to 192.168.0.1
(11:32:54) proxy: Connecting to 192.168.0.1:49652 with no proxy
(11:32:54) proxy: Connection in progress
(11:32:54) dnsquery: IP resolved for 192.168.0.1
(11:32:54) proxy: Attempting connection to 192.168.0.1
(11:32:54) proxy: Connecting to 192.168.0.1:49652 with no proxy
(11:32:54) proxy: Connection in progress
(11:32:54) proxy: Connecting to 192.168.0.1:49652.
(11:32:54) proxy: Connected to 192.168.0.1:49652.
(11:32:54) util: request constructed
(11:32:54) proxy: Connecting to 192.168.0.1:49652.
(11:32:54) proxy: Connected to 192.168.0.1:49652.
(11:32:54) upnp: Local IP: 192.168.0.2
(11:32:54) util: Response headers: 'HTTP/1.1 200 OK
CONTENT-LENGTH: 342
CONTENT-TYPE: text/xml; charset="utf-8"
DATE: Mon, 21 Jan 2019 11:32:54 GMT
EXT:
SERVER: Linux/3.10.53-HULK2, UPnP/1.0, Portable SDK for UPnP devices/1.6.18
X-User-Agent: UPnP/1.0 DLNADOC/1.50
CONNECTION: close

'
(11:32:54) util: parsed 342
(11:32:54) upnp: NAT Returned IP: 95.102.255.26
(11:32:57) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file /usr/local/share/pixmaps/pidgin/protocols/16/skype.png: Failed to open file '/usr/local/share/pixmaps/pidgin/protocols/16/skype.png': No such file or directory
(11:32:57) account: Connecting to account f3ti.star.
(11:32:57) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file /usr/local/share/pixmaps/pidgin/protocols/16/skype.png: Failed to open file '/usr/local/share/pixmaps/pidgin/protocols/16/skype.png': No such file or directory
(11:32:57) GLib-GObject: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
(11:32:59) util: Writing file prefs.xml to directory /home/yofuckinlo/.purple
(11:32:59) util: Writing file /home/yofuckinlo/.purple/prefs.xml
(11:32:59) util: Writing file accounts.xml to directory /home/yofuckinlo/.purple
(11:32:59) util: Writing file /home/yofuckinlo/.purple/accounts.xml
(11:33:02) connection: Connecting. gc = 0x55633e423f20
(11:33:02) http: Performing new request 0x55633e45d680 to login.skype.com.
(11:33:02) signals: Signal data for chat-conversation-typing not found!
(11:33:02) dnsquery: Performing DNS lookup for login.skype.com
(11:33:02) dns: Created new DNS child 6390, there are now 1 children.
(11:33:02) dns: Successfully sent DNS request to child 6390
(11:33:02) dns: Got response for 'login.skype.com'
(11:33:02) dnsquery: IP resolved for login.skype.com
(11:33:02) proxy: Attempting connection to 52.138.209.16
(11:33:02) proxy: Connecting to login.skype.com:443 with no proxy
(11:33:02) proxy: Connection in progress
(11:33:02) proxy: Connecting to login.skype.com:443.
(11:33:02) proxy: Connected to login.skype.com:443.
(11:33:02) nss: SSL version 3.3 using 128-bit AES with 256-bit SHA256 MAC
Server Auth: 2048-bit RSA, Key Exchange: 256-bit ECDHE, Compression: NULL
Cipher Suite Name: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
(11:33:02) nss: subject=CN=login.skype.com,O=Skype,L=Dublin,C=IE issuer=CN=Microsoft IT TLS CA 5,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US
(11:33:02) nss: subject=CN=Microsoft IT TLS CA 5,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US issuer=CN=Baltimore CyberTrust Root,OU=CyberTrust,O=Baltimore,C=IE
(11:33:02) nss: subject=CN=Baltimore CyberTrust Root,OU=CyberTrust,O=Baltimore,C=IE issuer=CN=Baltimore CyberTrust Root,OU=CyberTrust,O=Baltimore,C=IE
(11:33:02) certificate/x509/tls_cached: Starting verify for login.skype.com
(11:33:02) certificate/x509/tls_cached: Checking for cached cert...
(11:33:02) certificate/x509/tls_cached: ...Found cached cert
(11:33:02) nss/x509: Loading certificate from /home/yofuckinlo/.purple/certificates/x509/tls_peers/login.skype.com
(11:33:02) certificate/x509/tls_cached: Peer cert matched cached
(11:33:02) nss/x509: Exporting certificate to /home/yofuckinlo/.purple/certificates/x509/tls_peers/login.skype.com
(11:33:02) util: Writing file /home/yofuckinlo/.purple/certificates/x509/tls_peers/login.skype.com
(11:33:02) nss: Trusting CN=login.skype.com,O=Skype,L=Dublin,C=IE
(11:33:02) certificate: Successfully verified certificate for login.skype.com
(11:33:02) dnsquery: Performing DNS lookup for login.live.com
(11:33:02) dns: Successfully sent DNS request to child 6390
(11:33:02) dns: Got response for 'login.live.com'
(11:33:02) dnsquery: IP resolved for login.live.com
(11:33:02) proxy: Attempting connection to 2a01:111:2010:8::ff19
(11:33:02) proxy: Connecting to login.live.com:443 with no proxy
(11:33:02) proxy: Connection in progress
(11:33:07) util: Writing file accounts.xml to directory /home/yofuckinlo/.purple
(11:33:07) util: Writing file /home/yofuckinlo/.purple/accounts.xml
(11:33:32) http: Timeout reached for request 0x55633e45d680
(11:33:32) http: Request 0x55633e45d680 performed without success.
(11:33:32) g_log: skypeweb_string_get_chunk: assertion 'chunk_start' failed
(11:33:32) connection: Connection error on 0x55633e423f20 (reason: 2 description: Failed getting PPFT value, please try logging in via browser first)
(11:33:32) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file /usr/local/share/pixmaps/pidgin/protocols/16/skype.png: Failed to open file '/usr/local/share/pixmaps/pidgin/protocols/16/skype.png': No such file or directory
(11:33:32) account: Disconnecting account f3ti.star (0x55633d91c0e0)
(11:33:32) connection: Disconnecting connection 0x55633e423f20
(11:33:32) GLib: g_source_remove: assertion 'tag > 0' failed
(11:33:32) GLib: g_source_remove: assertion 'tag > 0' failed
(11:33:32) GLib: g_source_remove: assertion 'tag > 0' failed
(11:33:32) http: Performing new request 0x55633e468850 to login.skype.com.
(11:33:32) skypeweb: destroying incomplete connections
(11:33:32) http: Request 0x55633e468850 performed without success.
(11:33:32) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file /usr/local/share/pixmaps/pidgin/protocols/16/skype.png: Failed to open file '/usr/local/share/pixmaps/pidgin/protocols/16/skype.png': No such file or directory
(11:33:32) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file /usr/local/share/pixmaps/pidgin/protocols/22/skype.png: Failed to open file '/usr/local/share/pixmaps/pidgin/protocols/22/skype.png': No such file or directory
(11:33:32) connection: Destroying connection 0x55633e423f20
(11:33:35) certificate: CertificateVerifier tls_cached unregistered
(11:33:35) certificate: CertificateVerifier singleuse unregistered
(11:33:35) certificate: CertificatePool tls_peers unregistered
(11:33:35) certificate: CertificatePool ca unregistered
(11:33:35) main: Unloading normal plugins
(11:33:35) plugins: Unloading plugin Message Notification
(11:33:35) plugins: Unloading plugin SSL
(11:33:35) plugins: Unloading plugin NSS
(11:33:35) certificate: CertificateScheme x509 unregistered
(11:33:35) blist: Destroying
(11:33:35) accels: accel changed, scheduling save.
(11:33:35) accels: accel changed, scheduling save.
(11:33:35) accels: accel changed, scheduling save.
(11:33:35) accels: accel changed, scheduling save.
(11:33:35) accels: accel changed, scheduling save.
(11:33:35) accels: accel changed, scheduling save.
(11:33:35) accels: accel changed, scheduling save.
(11:33:35) accels: accel changed, scheduling save.
(11:33:35) accels: accel changed, scheduling save.
(11:33:35) accels: accel changed, scheduling save.
(11:33:35) accels: accel changed, scheduling save.
(11:33:35) accels: accel changed, scheduling save.
(11:33:35) accels: accel changed, scheduling save.
(11:33:35) util: Writing file accounts.xml to directory /home/yofuckinlo/.purple
(11:33:35) util: Writing file /home/yofuckinlo/.purple/accounts.xml
(11:33:35) account: Destroying account 0x55633d91c0e0
(11:33:35) main: Unloading all plugins
(11:33:35) plugins: Unloading plugin Gadu-Gadu
(11:33:35) plugins: Unloading plugin Sametime
(11:33:35) plugins: Unloading plugin Tcl Plugin Loader
(11:33:35) plugins: Unloading plugin SIMPLE
(11:33:35) plugins: Unloading plugin Perl Plugin Loader
(11:33:35) plugins: Unloading plugin GroupWise
(11:33:35) plugins: Unloading plugin Skype (HTTP)
(11:33:35) plugins: Unloading plugin ICQ
(11:33:35) plugins: Unloading plugin Bonjour
(11:33:35) plugins: Unloading plugin AIM
(11:33:35) plugins: Unloading plugin XMPP
(11:33:35) jabber: destroying hash tables for data objects
(11:33:35) plugins: Unloading plugin IRC
(11:33:35) plugins: Unloading plugin Zephyr
(11:33:35) Session Management: Handling closed ICE connection... 
(11:33:35) done.
(11:33:35) Session Management: Connection closed.

**Comment by EionRobb** [comment]
Have you followed the flowchart at https://github.com/EionRobb/skype4pidgin/tree/master/skypeweb#issues ?

**Comment by YFL** [comment]
Yes, as I mentioned, logging in via browser didn't help and what I didn't mention I'm not using 2 factor auth.

**Comment by dequis** [comment]
The flowchart should get you to alt login, but it doesn't look like you're there.

**Comment by YFL** [comment]
@dequis Nope. The Alt login comes when the other error occurs or if I use 2 factor auth, which is not the case (if I understand the chart correctly and I'm pretty sure I do 'cause it's not that complicated). In my case I should just check my credentials, and I've done that too. I've tried lots of things, because I was able to set it up on another windows machine with absolutely no problems at all, so I thought I was missing something.

**Comment by YFL** [comment]
Now I've tried it again and it works. Please clarify what have I missed in the flowchart :laughing:

**Comment by dequis** [comment]
>Please clarify what have I missed in the flowchart

"Failed getting Registration Token, Failed getting Skype Token (or any other)" - yours is "(or any other)".

The 2 factor authentication stuff is only relevant if your error is "Failed getting magic T value".

In general, even if alt login fails, we're interested in the error messages from that end, as they tend to be more informative.

**Comment by YFL** [comment]
Oh now I understand. I thought the "any other" meant "any other token" and the magic T value remained in the chart from an older version and it really meant the PPFT value. Now it's clear. Thank you. I'll close the issue. Thank you for the good work :smile:
