### ISSUE TITLE
Custom Chaticons

### ISSUE THREAD

**Issue by Vampire** [EionRobb/skype4pidgin#633]
In Skype you can have a custom icon for a chat.
Would be nice if this custom icon could also be shown in Pidgin like the profile image instead of the Skype logo.

**Comment by EionRobb** [comment]
Unfortunately the libpurple api doesn't give us a way of providing this to the UI from a protocol plugin :(

**Comment by Vampire** [comment]
So you can only specify one icon for all chats? Because the Skype-Icon is shown as chat icon.

**Comment by EionRobb** [comment]
Ah, the protocol icon is slightly different.  You can show or hide that in conversations with Buddies->Show->Protocol Icons (or there's a plugin to enable them too) - but these can only be set to icons that ship with Pidgin.

In Pidgin, you can right-click a chat in the buddy list and choose "Set Custom Icon" that will set the chat icon, but this is a pidgin-only feature, not part of libpurple
