### ISSUE TITLE
Support for this version of Skype for Web is coming to an end. A new preview version is available now for Microsoft Edge and Google Chrome with HD video calling, call recording and much more...

### ISSUE THREAD

**Issue by neil969** [EionRobb/skype4pidgin#636]
Not really an issue, just wondering how this upcoming change will affect this project? 
"Support for this version of Skype for Web is coming to an end. A new preview version is available now for Microsoft Edge and Google Chrome with HD video calling, call recording and much more. Try it out" 
I have removed Skype from my phone due to the forced "upgrade" and now they are trying to force users of Skype for web to MUCH less secure browsers ( think WHY they don't support FF - Prob because it doesn't "leak" data as badly)  -  I only use Pidgin for Skye text now, and is this the death-knell for Skype for me?

**Comment by metasonic** [comment]
Ola,
Looking over the calls made in the new web app it looks like the biggest change is switching from long polling to websockets, the message structure appears to be similar. I sort of started working on this for one of the java libraries, but time is short so didn't manage to make much progress. Would gladly share any progress i make once I has at least a decent shape.

**Comment by neil969** [comment]
So now the web.skype just says "Browser not supported" to Firefox so if you get a "token error" How can you fix it?

**Comment by Varstahl** [comment]
Plugin's officially dead as of two days ago.

**Comment by szr8** [comment]
On 3/8/2019 1:32 AM, neil969 wrote:
>
> So now the web.skype just says "Browser not supported" to Firefox so 
> if you get a "token error" How can you fix it?
>

I've found that logging in via just https://www.skype.com (rather than 
https://web.skype.com) is enough to clear that sort of error.

**Comment by EionRobb** [comment]
@Varstahl not sure what you're talking about

Using the "alternative auth" setting in the Advanced tab should resolve most login problems

**Comment by neil969** [comment]
> 
> 
> @Varstahl not sure what you're talking about
> 
> Using the "alternative auth" setting in the Advanced tab should resolve most login problems
@ Varstahl  had me worried there for a minute!!! 

@EionRobb In my install  (Windoze10) I don't HAVE the "alternative auth" setting in advanced tab There is one "blank" checkbox though.. I have seen the mentioned before and I made sure I had the most recent version of the plugin. (Note that I have NOT had the "login issue" since the Skype web support was dropped though!)  

![image](https://user-images.githubusercontent.com/22851918/55189336-8c758600-5195-11e9-864e-723cd0bdccc8.png)

**Comment by Varstahl** [comment]
> Using the "alternative auth" setting in the Advanced tab should resolve most login problems

Doesn't work with or without alternative auth:

```
Login error: Invalid value "Varstahl" for username param "username" (code 40002)
```

As I said, was working up to a couple days ago, now no login method works anymore.

**Comment by EionRobb** [comment]
@Varstahl use all-lowercase characters to login, or you might need to use an email address instead

@neil969 It's not available in the download from the releases section but from the nightly builds at https://eion.robbmob.com/libskypeweb.dll instead

**Comment by neil969** [comment]
> @neil969 It's not available in the download from the releases section but from the nightly builds at https://eion.robbmob.com/libskypeweb.dll instead

Well There you go ;)  That made it work  - Thanks heaps @EionRobb a great useful project!  - I will leave it unchecked unless I have a problem..

**Comment by Varstahl** [comment]
> @Varstahl had me worried there for a minute!!!

@neil969: oh, believe me, I was worried too :P

> @Varstahl use all-lowercase characters to login, or you might need to use an email address instead

I already tried both upper and lower with no effect, but it seems like using the e-Mail address did the trick, thanks for the tip. Apparently it stopped accepting usernames as of a few days ago.

Now if I could stop Pidgin from crashing when sending files through Skype, I'd be golden :D

**Comment by dequis** [comment]
I think it's safe to say that this was not really an issue, or if the last issue with alt login was related to this in any way, it's fixed already, so i'm closing this.
