### ISSUE TITLE
Login error: No handler found for resource (code 40499)

### ISSUE THREAD

**Issue by xss** [EionRobb/skype4pidgin#639]
Connection via skypeweb plugin doesn't work for me anymore. Pidgin shows the error ...

> Login error: No handler found for resource (code 40499)

... and disables the account.

Two days ago, I could still use skypeweb plugin normally, and I think even earlier today. I also just updated skypeweb, but that didn't solve the issue, neither did logging into Skype via web browser or the SkypeForLinux application.

Any hints on this?

**Comment by dequis** [comment]
Fun. Is this with or without alt login enabled? What do you get when toggling that setting?

**Comment by xss** [comment]
This is with alt login enabled – I didn't change that setting recently.
Without alt login, I get the horrid Magic T value message.

**Comment by xenos1984** [comment]
Same error here. I could login 12 hours ago, and stayed logged in until 30 minutes ago. Went to a different computer just now and could not login.

**Comment by xenos1984** [comment]
...and this morning it seems to work again. Maybe a temporary problem?

**Comment by xss** [comment]
Indeed, now it seems to work again, as if nothing ever happened. o.O

I bet they're having great fun over there at Microsoft, changing small things and waiting who notices...

**Comment by egslava** [comment]
Now I've just got the same problem. Though 2 days before everything okay. I dunno how to login.

**Comment by xss** [comment]
Yep, for me it's back, as well.

So, again, any hints on this? How may I help with debugging?

**Comment by accipiter** [comment]
I've just got the same error. I've disabled alt login and now it works.

**Comment by egslava** [comment]
@accipiter I'm sorry, how do you use non-alt login? Do you have any link to a manual?

**Comment by xss** [comment]
For me disabling alt login doesn't help, as before, I then get the dreaded Magic T value error.

@egslava With pidgin contact list window having focus, press Ctrl+A to open account settings, select your Skype (HTTP) account and click "Modify...". Then, in the tab "Advanced", check or uncheck "Use alternative login method".

When unchecked, you might get the Magic T value error, as well. According to the README [here](https://github.com/EionRobb/skype4pidgin/tree/master/skypeweb), in this case you should rather activate that setting.

**Comment by egslava** [comment]
@xss thanks for the reply :) Yeah, I have Magic T value error, probably, because I don't know any way to point the plugin my credentials. It's said, that I need to go to browser's (which one) incognito mode and, there, log in into Skype web. Firefox isn't supported by Skype Web, so I use Chromium. But, anyways, I can't (and couldn't) log in.

**Comment by xss** [comment]
Yep, I think for some cases when we get the Magic T value error, it really helps logging in via a browser, because some new EULA or data retention policy or whatever from Skype/Microsoft must be accepted first before we are able to continue to use the service (after all, using the "real" Skype client or logging in via a browser, such updates would pop up automatically). IIRC, that's why the Magic T value error at one point got this additional hint. However, apparently, there are more of those Magic T cases, where logging in via browser doesn't change a thing, and this hint can be rather misleading.

**Comment by brianjmurrell** [comment]
Disabling alt login, resulted in Magic T errors.  Logging in via incognito session in chrome and processing the (secure your account or somesuch nonsense) popup dialog with a "skip" allowed me to log in with this plugin without alt login again.

**Comment by bmomjian** [comment]
Interesting.  I got the error with Alt-Login on and off.  I logged in to Skype on Chromium and after that Pidgin login worked.  It did ask me if my security info was correct, so maybe it just needed to check that.

**Comment by chainria** [comment]
Same here. Alt-Login seems broken all the time now. But logging in on Skype.com (web.skype.com did not help!) worked. It asked me about the Security Information as well. Might very well be that that's the problem. So, Alt-Mode off now for me, two out of two accounts working again.

**Comment by alexolog** [comment]
Disabled alt-login.  Logged in from chrome.  This solved the problem.
Re-enabling alt-login, brings the problem back, so I keep it disabled.

**Comment by 667bdrm** [comment]
Not helped with alt login and without alt login. Also I have found that now web.skype.com blocking requests from Gecko engine (Firefox, Tor Browser, etc), curl. In browser it has been fixed by substituting Chromium User-Agent header to requests. Didn't found user agent refereneces in source code, maybe should try this workaround.

**Comment by xss** [comment]
No luck here, as well: After disabling alt login, for the very first connection attempt, I received the following error:

`Failed getting PPFT value, please try logging in via browser first`

For any later attempt in this constellation, the error switched back to the Magic T value one.

Logging in via browser didn't change a thing, no security question or whatever pops up that needs to be confirmed. It's the same for web.skype.com (using Chromium or manipulating user-agent in Firefox) and skype.com directly.

With or without alt login enabled, I am unable to connect to Skype via Pidgin. Doesn't matter, either, whether I try to login via Skype username or the associated email address.

alt login enabled: Login error: No handler found for resource (code 40499)
alt login disabled: Failed getting Magic T value, please try logging in via browser first

**Comment by brianjmurrell** [comment]
@xss:
> Logging in via browser didn't change a thing, no security question or whatever pops up that needs to be confirmed.

Did you use an incognito session so that any existing cookies in your non-incognito session are not used?

**Comment by xss** [comment]
@brianjmurrell Yes, for web.skype.com I did. Anyway, my browser removes the few cookies I accept, as well as LocalStorage, right away after closing the tab. So old session data would be very unlikely and should not be relevant here.

**Comment by philfry** [comment]
Same here, no handler with alt login, Magic T without alt login. Tried with different browsers in incognito mode, didn't help. The only thing microsoft/skype is asking me for is my billing information which I don't want to fill in.

**Comment by bolera** [comment]
In my case the code 40499 error appeared after a crash of Windows. The crash seems to have happened in the middle of the Skype sign-in. Maybe data is corrupted. I can sign-in to web.skype.com and secure.skype.com, but this didn't help. I switched to the non-alt login. That works, but I would prefer the new method, of course. Once I switch back to alt login I get the same 40499 error. What can I do to clean it up without removing the account from Pidgin? Is there a temporary directory that holds session data?

**Comment by dequis** [comment]
> Same here, no handler with alt login, Magic T without alt login. Tried with different browsers in incognito mode, didn't help. The only thing microsoft/skype is asking me for is my billing information which I don't want to fill in.

If it does that on every web.skype.com login, then you won't be able to get in. Try to get rid of it.

> In my case the code 40499 error appeared after a crash of Windows. The crash seems to have happened in the middle of the Skype sign-in. Maybe data is corrupted. I can sign-in to web.skype.com and secure.skype.com, but this didn't help. I switched to the non-alt login. That works, but I would prefer the new method, of course. Once I switch back to alt login I get the same 40499 error. What can I do to clean it up without removing the account from Pidgin? Is there a temporary directory that holds session data?

No, this has nothing to do with your local data, it's the server.

**Comment by philfry** [comment]
> If it does that on every web.skype.com login, then you won't be able to get in. Try to get rid of it.

entered some fake address data and skype stopped asking for it. Reset all, logged in in incognito. Still getting the handler-thingy, though :\

**Comment by dequis** [comment]
Getting rid of pages that appear after the web login fixes the non-alt login. Alt login is not affected by it.

There's no known fix for alt login at the moment, for all we know microsoft might have killed it.

**Comment by philfry** [comment]
There are no nag screens left but still getting the Magic T w/o alt login. But that's probably offtopic, because this issue addresses the alt login.

**Comment by raztus** [comment]
I, too, tried to disable alt login and used an incognito window to login to skype.com and web.skype.com.

My Microsoft account is setup with two-factor-auth--will this prevent altogether me from signing in without alt login?

**Comment by egslava** [comment]
Just in case: I can log in with disabled alt-login method. But I don't use 2-factor authentication!

**Comment by dequis** [comment]
Yeah 2fa will stop non-alt-login from working, too.

**Comment by bolera** [comment]
As I said: for me it started happening immediately after a crash of the system and reboot. 2 days ago. (Others reported it already 7 days ago where it was still working fine for me.) Changing to non-alt login works. Without a need to log into web.skype.com in any form. But alt-login doesn't work at all now and none of the suggested methods makes it wortk again. No 2FA. My question is: is this now a general problem = nobody can login with alt method? Then it's clearly not associated with the crash. But if it's working for many but not for some, then it rather looks like a client-side thing.

**Comment by xenos1984** [comment]
For me neither method works. For me alt login still worked on May 6th, but after that it stopped working and I get the "Login error: No handler found for resource (code 40499)".

Without alt login, I get the Magic T error. Browser login does not work at all.

**Comment by chainria** [comment]
I really guess they just nuked whatever gateway/endpoint was used for Alt-Login (did not look at the code)

**Comment by xss** [comment]
> @philfry @xss do you both have 2FA set up on your Microsoft account?

I don't, no. Simple login via username (or one of the email addresses skype forced to add at some point) and password.

**Comment by philfry** [comment]
@raztus yes, using 2FA here.

**Comment by himselfv** [comment]
Alt-login fails with the same error as everyone here. Switching to normal login and logging in once via web UI worked for me for now.

**Comment by edsonv** [comment]
I have read all the comments here and I can confirm that when I deactivate the 2FA method and uncheking the alt-login method, I do not get errors

**Comment by powerman** [comment]
Same thing here, thank you guys for the hint!
Disabled alt login, logged in at skype.com in a clean browser (no 2FA), and now pidgin works.

**Comment by xss** [comment]
For those lucky fellas of you where non-alt login works with 2FA disabled: Do you use your skype name or the email address to log in to skype with Pidgin?

I'm really not in the mood to first enable 2FA only to later disable it, just to see if that works. My phone number is none of Microsoft's business.

**Comment by powerman** [comment]
@xss I'm using username to login, not email. And I never enabled 2FA on this account before.

**Comment by 667bdrm** [comment]
After some time of using web skype in opera's "vpn" window and switching off alt login in Pidgin with tor socks proxy, the plugin has been started working again.

**Comment by xss** [comment]
Unfortunately, no luck here. I've been using web.skype.com in private or VPN windows of various browsers and within the Skype desktop client for a while now, but it didn't help in re-activating the pidgin plugin. The result remains the same:

non-alt login: Failed getting Magic T value
alt login: Login error: No handler found for resource (code 40499)
Independent on whether I use my Skype login name or my email address.

Anything else one can try now? Any chance for a fix to once again use Skype with pidgin?

**Comment by gmsotavio** [comment]
Same issue here

> Login error: No handler found for resource (code 40499)

**Comment by dequis** [comment]
Some misc notes here.

The "no handler" error is the output of https://api.skype.com/login/skypetoken using username and the skyper password hash. The full response is a json that doesn't have anything more than what the error message shows.

That method is only used if alt login is enabled and the username isn't a microsoft account (email).

When not using that method (either changed in the code, or switched to an email address), the SOAP reply is a rather unhelpful `<S:Fault><faultcode>wsse:FailedAuthentication</faultcode><faultstring>Authentication Failure</faultstring></S:Fault>` but for every attempt https://account.live.com/Activity claims it was a successful login

Non-alt login fails because it gets an html page with "Verify your identity"

**Comment by dequis** [comment]
Oh, derp. I also got an email saying "You need an app password" after those SOAP "successful" logins.

Adding an app password gets it past the SOAP part, but then feeding that token to https://api.skype.com/rps/skypetoken fails with an error that has the same text as the other endpoint. I guess that makes sense.

I think it's good news that the SOAP part still works, and i've known for a while that it can work for plain skype usernames.

Now we need to figure out some way to turn that into a skype token, I guess.

**Comment by dequis** [comment]
#640 has a fix.

Windows users, wait for eion.

**Comment by EionRobb** [comment]
[libskypeweb.zip](https://github.com/EionRobb/skype4pidgin/files/3195592/libskypeweb.zip)
Wrap your laughing gear around this

**Comment by xenos1984** [comment]
Works for me, thanks! :)

**Comment by xss** [comment]
I can confirm that dequis' commit fixes it for me, as well. Thank you very much!! :)

**Comment by raztus** [comment]
Confirming that alt-login with an application password (2FA enabled) works for me on Windows 10. Thank you!

**Comment by alexolog** [comment]
Doesn't work for me.
I get "Login error: Bad username or password (Profile accrual is required)"

Non-alt login works

**Comment by dequis** [comment]
@alexolog that's a very different error, not the same as this issue.

I got that once for an account where I had to  finish linking my skype username to a microsoft account, but it could be anything. Logging in to https://login.live.com/ may help

I guess it might be related as the skyper hash login method is now gone so everything needs to go through the microsoft account login. Maybe your password only exists in that specific poorly encrypted form and it can't use it? Who knows.

**Comment by alexolog** [comment]
I am currently logged in into the Microsoft account, as well as skype, with the same username/password.
The non-alt method works.
The alt method used to work until the "No handler found for resource" issue started, but doesn't work now with the new DLL.  I have not changed my password since.

The debug window (on level "all") does not provide any useful information other than the error code.

**Comment by dequis** [comment]
Please open a new issue

**Comment by alexolog** [comment]
Opened #643

**Comment by bolera** [comment]
Thank you very much, Robb. I replaced with the new libskypeweb.dll and relaunched with old settings (= no alt-login). Works. Then I changed to alt-login and relaunched again. It still works. So I can confirm that at the moment both methods work with this dll. I don't and didn't have 2FA.

**Comment by bjmi** [comment]
> [libskypeweb.zip](https://github.com/EionRobb/skype4pidgin/files/3195592/libskypeweb.zip)
> Wrap your laughing gear around this

What about a new release that contains these changes?

**Comment by grzegorz-janoszka** [comment]
+1 - when can we expect new release containing all the latest addition to this plugin?
