### ISSUE TITLE
Failed getting Magic T value, please try logging in via browser first

### ISSUE THREAD

**Issue by antonbutanaev** [EionRobb/skype4pidgin#645]
Hi!,

Everything worked for years, but now I get Failed getting Magic T value, please try logging in via browser first. Logging via browser doesn't help anymore. I use build 1.5.r23.5d29285

**Comment by dequis** [comment]
https://github.com/EionRobb/skype4pidgin/tree/master/skypeweb#issues

**Comment by antonbutanaev** [comment]
Logging via browser in incognito mode helped. Thanks a lot!
