### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by solomani** [EionRobb/skype4pidgin#646]
Installed it and it didn't work so before I start troubleshooting it just wan to confirm it should work.  Thanks.

**Comment by EionRobb** [comment]
Yup, sure does. :)
https://github.com/EionRobb/skype4pidgin/tree/master/skypeweb#issues

**Comment by solomani** [comment]
Thank you - let the troubleshooting begin :)

**Comment by solomani** [comment]
So the error I am getting is "Login error: No handler found for resource (code 40499)"  ?

**Comment by dequis** [comment]
@solomani get the latest git

**Comment by solomani** [comment]
Using 1.5 and the installer.  Gives me the error: Error getting BinarySecurityToken
