### ISSUE TITLE
facebook keeps disconnecting

### ISSUE THREAD

**Issue by RodMyers** [EionRobb/skype4pidgin#652]
libpurple-facebook-0.9.5.9ff9acf9fa14_1 

facebook keeps disconnecting with the error message;

the action attempted was deemed abusive or is otherwise disallowed.

This is with me, the user, not doing anything other letting pidgin run

**Comment by alexolog** [comment]
Wrong plugin :)

**Comment by RodMyers** [comment]
damn, gotta love olde age
