### ISSUE TITLE
Feature request: See conversation history in chat window.

### ISSUE THREAD

**Issue by D33M0N** [EionRobb/skype4pidgin#654]
1. When there is logging enabled. I would like option to see the old previously logged conversation in the chat window when I open one.

2. Even better when it would be possible to get the actual full conversation history from Skype server? I mean the part chatted on different devices earlier.

**Comment by EionRobb** [comment]
Try using the 'History' plugin (in Pidgin, Tools->Plugins) for the first one

The second one is a bigger issue and affects all the protocol plugins, not just Skype.  Needs some fundamental changes in libpurple to handle it, and don't want to give the wrong idea about leaving the issue open that there might be an easy fix, so closing this
