### ISSUE TITLE
Getting "failed to get magic-T" error even when logged in via browser

### ISSUE THREAD

**Issue by alexolog** [EionRobb/skype4pidgin#656]
After multiple reconnection attempts, it will randomly succeed but it can take several minutes of trying.

**Comment by dlmarquis** [comment]
I am having the same problem. This week I started having to log in via browser every time I changed IP address; now I can't get in even when logged in via browser.

**Comment by Zombie-Ryushu** [comment]
This behavior just started today.

**Comment by alexolog** [comment]
Now I cannot connect at all.

Please take a look at it.
I use a different Skype account in Pidgin so I rely on it for communications.

**Comment by neil969** [comment]
This has just started to happen to me too today ..  Looks like Skype have changed something.. I can also say that when I try to login using Firefox but changing the user agent to Chrome ( which used to work to allow a log in to fix the Magic T issue) Skype gives an error and wont log in. It will log in on (de-googled) Chromium browser though, but I still get the issue in Pidgin. I imagine that this is related and Web.Skype may be using some new form of browser check?

**Comment by alexolog** [comment]
Hmmm, I can login with FF without problems

**Comment by neil969** [comment]
> 
> 
> Hmmm, I can login with FF without problems

It normally says "Unsupported Browser" if you try FF .. It has been doing that for years !

**Comment by alexolog** [comment]
Sorry, I fake the user agent to Edge 44 on the skype.com domain

**Comment by alexolog** [comment]
Miranda-NG has the same problem, according to their forum.
Microsoft did something.

**Comment by zevelorgani** [comment]
> Miranda-NG has the same problem, according to their forum.
> Microsoft did something.

Actually, they say it works fine on their end.

**Comment by DeRiderConsultingServices** [comment]
Experiencing same issue. Attaching log files. Nothing overtly identifying 

(19:12:29) http: Request 02306870 performed successfully.
(19:12:29) g_log: skypeweb_string_get_chunk: assertion `chunk_start' failed
(19:12:29) g_log: skypeweb_string_get_chunk: assertion `chunk_start' failed
(19:12:29) g_log: skypeweb_string_get_chunk: assertion `chunk_start' failed
(19:12:29) connection: Connection error on 0390AC48 (reason: 2 description: Failed getting Magic T value, please try logging in via browser first)

**Comment by alexolog** [comment]
I looked at the Miranda-NG source and they are passing three cookies to `https://login.live.com/ppsecure/post.srf`: `MSPRequ`, `MSPOK`, and `CkTst`, while Pidgin only passes `CkTst`

Could that be the problem?

**Comment by DeRiderConsultingServices** [comment]
That could definitely be a source. Definitely worthy of testing if one has both the knowledge, the time and the ability to build the skype plugin from the source.

**Comment by boris-petrov** [comment]
@alexolog - if Miranda has the same problem then probably these cookies don't matter (that much). Would you mind linking to their issue here?

**Comment by neil969** [comment]
> 
> 
> @alexolog - if Miranda has the same problem then probably these cookies don't matter (that much). Would you mind linking to their issue here?

I have had a dig through the issues at Miranda, (forum & Github) but I can't see that they have a an issue with NOT connecting ( amybe an issue with "remaining* connected) with web.skype , so maybe the issue is the two extra cookies?

**Comment by SullyvanCrow** [comment]
Same problem here, using "Alternative login method" Failed too

**Comment by EionRobb** [comment]
Using alternate auth with the latest version of the plugin is always preferred, but I'm looking into the "pretend to be a web browser" method too 

It looks like it's hitting the "do you want to store these details / stay logged in" screen and getting stuck. There should be one more screen to pretend to click through for the old login method to work

**Comment by SullyvanCrow** [comment]
updating pidgin to the latest version and the plugin from 1.5 to 1.6 seems to solve the login problem (with alternative auth method)

**Comment by neil969** [comment]
>
> Using alternate auth with the latest version of the plugin is always preferred, but I'm looking into the "pretend to be a web browser" method too
> 
I have never managed to get anything but an error when I check " Alternative login method" - currently that error is "Login error: No handler found for resource (code 40499)"  
So currently it is either that error or the "magic T" error  ... At least it is now consistent :)

**Comment by ZaxonXP** [comment]
> updating pidgin to the latest version and the plugin from 1.5 to 1.6 seems to solve the login problem (with alternative auth method)

This did not work for me. It says:
```
Login error: Bad username or password (Profile accrual is required)
```

**Comment by SullyvanCrow** [comment]
> 
> 
> > updating pidgin to the latest version and the plugin from 1.5 to 1.6 seems to solve the login problem (with alternative auth method)
> 
> This did not work for me. It says:
> 
> ```
> Login error: Bad username or password (Profile accrual is required)
> ```
Is the loging ok on the web version of Skype ?

**Comment by ZaxonXP** [comment]
> Is the loging ok on the web version of Skype ?

No, it is not. That is why I tried the alternative, but it also did not work for me.

**Comment by SullyvanCrow** [comment]
> 
> 
> > Is the loging ok on the web version of Skype ?
> 
> No, it is not. That is why I tried the alternative, but it also did not work for me.

are you sure of your login/password ?

**Comment by neil969** [comment]
OK I can confirm that the the 1.6 fixed the "Login error: No handler found for resource (code 40499)" when using the alt login method, and I am back connected to Skype again...
I REALLY thought I had the most recent version so sorry about that @EionRobb - I think I may have had a beta version  from like January .
so "*BEFORE DOING ANYTHING ELSE* Grab the latest DLL  (1.6) from here https://github.com/EionRobb/skype4pidgin/releases & drop it into the plugins directory and restart pidgin with "Alternative login" check as on!   :)

**Comment by PF4Public** [comment]
1.6 does not work for me

1.5 alt login: "Login error: No handler found for resource (code 40499)"
1.6 alt login: "Login error: Bad username or password (Profile accrual is required)"

1.5 non-alt login: "Failed getting Magic T value, please try logging in via browser first"
1.6 non-alt login: "Failed getting Magic T value, please try logging in via browser first"

**Comment by ZaxonXP** [comment]
@PF4Public : I have the same situation as you.
@SullyvanCrow : Yes, I put my login/pass correctly (tried few times).

**Comment by SullyvanCrow** [comment]
@ZaxonXP with the last pidgin version (2.14.1) ?

**Comment by konto-andrzeja** [comment]
I also have `Login error: Bad username or password (Profile accrual is required)` error when trying alt method with 1.6 plugin version and 2.14.1 Pidgin version. Can log in using web just fine, so login and password are correct. Tried to verify recent activities as suggested [here](https://github.com/EionRobb/skype4pidgin/issues/643#issuecomment-516954066), but it didn't help.

**Comment by SullyvanCrow** [comment]
try to change your ip.. (through VPN, or rebooting your modem/box)

**Comment by EionRobb** [comment]
This issue might start to get a bit noisy, but I don't want to lock down comments just yet in case someone has something helpful 👍 

Basically, the web-based login is currently broken and you need to use the "use alternative login method" in the Advanced settings

If you don't have that setting then you need to update to 1.6 of the plugin from https://github.com/EionRobb/skype4pidgin/releases

"Code 40499" means you have v1.5 of the plugin and you need to update to v1.6 of the plugin from https://github.com/EionRobb/skype4pidgin/releases
"Profile accrual is required" is something to do with not linking a Skype account to a Microsoft account.  Please wait for the plugin to get an update, or try link your Skype account to a MS account.

This will need a code change to fix, so any suggestions of "use another browser" or "restart your computer" will be removed :)

Please only comment in this issue if you have a code suggestion.  If things get too noisy I'll lock the thread down.

**Comment by alexolog** [comment]
> "Profile accrual is required" is something to do with not linking a Skype account to a Microsoft account. Please wait for the plugin to get an update, or try link your Skype account to a MS account.

I am getting "Profile accrual is required".  I can login to a Microsoft account with my Skype credentials, so I assume they are linked.  How do I verify?

**Comment by ZaxonXP** [comment]
> I am getting "Profile accrual is required". I can login to a Microsoft account with my Skype credentials, so I assume they are linked. How do I verify?

Log in to Pidgin Skype plugin using your MS account and use `alternative login method`. 

It worked for me however that account has no contacts, so it is not ideal solution (I would have to import the contacts and assure the persons that this accounts belongs to me). So waiting for the fix.

**Comment by alexolog** [comment]
I do not have separate Microsoft and Skype accounts for the username I use in Pidgin.  I use the exact same credentials for `web.skype.com` and `account.microsoft.com`, and logging in into one automatically logs me in into the other.
And I still get the Profile accrual is required" error using the alternative method.

**Comment by Zombie-Ryushu** [comment]
The Alternate login method can work for Spectrum 2:
in your skype.cfg file add:

[purple]
alt-login = 1

**Comment by georgehazan** [comment]
@EionRobb you can find the solution here
https://github.com/miranda-ng/miranda-ng/commit/f672145138af24d238bc763001f5625da9525d88

Patch is simple

**Comment by EionRobb** [comment]
For those unable to use the 'Use alternative login method' setting, can you try with the above commit 6d6abba?

Windows dll 
[libskypeweb.zip](https://github.com/EionRobb/skype4pidgin/files/5116768/libskypeweb.zip)

Thanks to @georgehazan for pointers about the opid :+1:

**Comment by ZaxonXP** [comment]
@EionRobb I just recompilled the plugin with the commit changes you posted. I can confirm that it is working. :+1: 
Good job! :)

**Comment by uzpis** [comment]
@EionRobb  Unfortunately, windows dll still pops up (Profile accural is required)

**Comment by EionRobb** [comment]
Thanks for the feedback @uzpis  - will need to update the login flowchart to say 'use an email address' for the alt login flow

I'll wait 24 hours for more feedback on the commit, and then hopefully push out a 1.7 version tomorrow :)

**Comment by vrobolab** [comment]
Simply recompiling the plugin does not help, I had to create an Outlook account to login.

open https://login.live.com -> "Discover Microsoft services" -> "All Microsoft" -> "Software" -> "Outlook" -> "Sign in" and it will ask for your email address "You need to specify an email address to continue". I clicked "Or get a new Outlook email from us" and registered a new Outlook account.

Then I successfully logged in using an alternative method and Outlook email address instead of Skype account name.

But there are two more problems now - I have no chat history from the old Skype account, but it is not a big problem. The big one - I do not receive new messages (they do not sync?). 

If I login with the browser to https://web.skype.com there are several new messages in different chats, and no such messages in Pidgin.

**Comment by vrobolab** [comment]
read "open https://login.live.com" as "log in to https://login.live.com using your Skype account"

**Comment by kosilin** [comment]
Good day!

I've solved this problem for me just now. After I've logged in (from PC where my Pidgin installed) into MS live account (not skype!) I was trying to see my activities. At this point MS had required me to confirm my e-mail address. Since my e-mail has been confirmed I'm able to login into Skype account with skypeweb using alternative login.

May be this recipe will be usefull for someone....

Best regards,
Alexey

**Comment by brianjmurrell** [comment]
@EionRobb 
> Using alternate auth with the latest version of the plugin is always preferred, but I'm looking into the "pretend to be a web browser" method too

Except that doesn't work using [1.6](https://github.com/EionRobb/skype4pidgin/releases/tag/1.6): `Login error: Bad username or password (Profile accrual is required)`

**Comment by kosilin** [comment]
> @EionRobb
> 
> > Using alternate auth with the latest version of the plugin is always preferred, but I'm looking into the "pretend to be a web browser" method too
> 
> Except that doesn't work using [1.6](https://github.com/EionRobb/skype4pidgin/releases/tag/1.6): `Login error: Bad username or password (Profile accrual is required)`

Please try to confirm your e-mail from the PC where the skypweb is working on (please see my post a little bit earlier) before using alternative skype login.

Alexey

**Comment by PF4Public** [comment]
>Windows dll
>libskypeweb.zip

Immediately after: "Failed getting PPFT value, please try logging in via browser first"
After logging in via browser: "Failed getting Magic T value, please try logging in via browser first"

**Comment by brianjmurrell** [comment]
I added an e-mail address to the MS account that I use for skype and reconfigured Pidgin to use that instead of my skype name and now login is still failing with: `Login error: Bad username or password (Profile accrual is required)`

**Comment by vrobolab** [comment]
Try logging out from web.skype.com, if it does not help - try registering an Outlook account and logging in with it.

**Comment by kosilin** [comment]
> I added an e-mail address to the MS account that I use for skype and reconfigured Pidgin to use that instead of my skype name and now login is still failing with: `Login error: Bad username or password (Profile accrual is required)`

I use skype name nevertheless. And that's working for me.

**Comment by brianjmurrell** [comment]
I have an outlook account yet trying to log in to skype with my e-mail address is still giving: `Login error: Bad username or password (Profile accrual is required)`

**Comment by dazzzl** [comment]
The commit works! Thanks!

**Comment by DeRiderConsultingServices** [comment]
> Immediately after: "Failed getting PPFT value, please try logging in via browser first"
>After logging in via browser: "Failed getting Magic T value, please try logging in via browser first"

I experienced this behavior with the update also.

**Comment by vrobolab** [comment]
> The big one - I do not receive new messages (they do not sync?).

> If I login with the browser to https://web.skype.com there are several new messages in different chats, and no such messages in Pidgin.


Update: I send and receive messages without problems, i.e. if I send in browser then the same message appears in Pidgin, and replies received do appear in Pidgin too. So no issues with syncing messages after logging in with the browser. But those several messages I was talking above have never appeared in Pidgin.

So make sure to log in with the browser first, to see any new messages that came while you was offline in Pidgin.

**Comment by kosilin** [comment]
> > Immediately after: "Failed getting PPFT value, please try logging in via browser first"
> > After logging in via browser: "Failed getting Magic T value, please try logging in via browser first"
> 
> I experienced this behavior with the update also.

You probably should switch on "alternative login method" in Skypeweb plugin settings.

Best regards,
Alexey

**Comment by DeRiderConsultingServices** [comment]
> > > Immediately after: "Failed getting PPFT value, please try logging in via browser first"
> > > After logging in via browser: "Failed getting Magic T value, please try logging in via browser first"
> > 
> > 
> > I experienced this behavior with the update also.
> 
> You should probably switch on "alternative login method" flag in Skypeweb plugin settings.
> 
> Best regards,
> Alexey

That produces the Profile acrual error. And the account is already linked to a MS account because they forced us to do create this Skype account when they migrated everybody over from MSN to skype.

**Comment by kosilin** [comment]
> That produces the Profile acrual error. And the account is already linked to a MS account because they forced us to do create this Skype account when they migrated everybody over from MSN to skype.

Yeah. This was producing the error for me too. since I  did some magic with my mslive account. Please see [this](https://github.com/EionRobb/skype4pidgin/issues/656#issuecomment-679067738) and try to do something like this.

Best regards,
Alexey

**Comment by alexolog** [comment]
If that solves the issue, it should be added to the FAQ.

**Comment by bodqhrohro** [comment]
Works now with my plain old Skype account, thanks!

**Comment by zod6** [comment]
17e03bb and no luck here with old skype account.
Alt login method: "Login error: Bad username or password (Profile accrual is required)"
Without alt. login method: "Failed getting Magic T value, please try logging in via browser first"

When I consistently press the login button tens or hundreds of time, it finally goes online. But same behavior with old version (compiled 26.08.2019 from git).

Also tried Miranda-NG, mentioned before, and it works. After first connect it fetched contact list (and groupchat names were correct!), but everybody were offline. After second connect everything worked as expected.

**Comment by zod6** [comment]
Sry, my mistake. Git pull failed because of my changes and I didn't notice this.
With new version everything is fine!

**Comment by EionRobb** [comment]
Thanks everyone for the testing and feedback.

I've pushed out a new release at https://github.com/EionRobb/skype4pidgin/releases/tag/1.7 - hopefully should start trickling out to distros at some point :)

**Comment by ohhai** [comment]
Just to share: got it working on Fedora Linux with these versions (no 1.7 update):
  pidgin-2.13.0-18.fc32.x86_64
  pidgin-skypeweb-1.6-1.fc32.noarch

With following steps:
* Login from https://login.live.com
* Accept updated terms of service
* Set "don't log out"
* Go to payment setting: https://account.microsoft.com/billing/payments?c.state=add&fref=home.banner.payment-instruments
* Get new Outlook address

Enabled alt login method and now it works.

**Comment by heeplr** [comment]
Can confirm it works without outlook address. Just associating any e-mail address with the account was enough.

**Comment by ZaxonXP** [comment]
Today ver 1.6 does not work again. I tried the version 1.7 and it is working correctly.

**Comment by alexolog** [comment]
Maybe make that step conditional?

**Comment by bodqhrohro** [comment]
> Maybe make that step conditional?

[Done.](https://github.com/EionRobb/skype4pidgin/pull/665)

[New .deb package.](https://github.com/bodqhrohro/skype4pidgin/releases/download/v1.7.1-alpha2/skypeweb-1.7.0-Linux.deb)

**Comment by H0w4rd** [comment]
And it's back again.
`Failed getting Magic T value, please try logging in via browser first`
Suggested action won't help.
Any solution for 2021? :-)

**Comment by dreamlayers** [comment]
Now, October 14th 2024, with the latest version, I am only able to log in if I am logged in via the browser. If I log out via the browser, then I get "failed to get magic-T" in Pidgin. Fortunately, it still works if I close the browser tab without logging out. I don't think this was needed before.
