### ISSUE TITLE
(12:44:09) connection: Connection error on 0x564994a7db20 (reason: 0 description: <data>:1:12: Parse error: unexpected identifier `taNewMessage', expected value)

### ISSUE THREAD

**Issue by brianjmurrell** [EionRobb/skype4pidgin#670]
As of the last day or two, I have started getting random disconnects with:

```
(12:44:09) connection: Connection error on 0x564994a7db20 (reason: 0 description: <data>:1:12: Parse error: unexpected identifier `taNewMessage', expected value)
```

Usually the account reconnects, but then I get spammed with the most recent messages in all of my chats.  This reconnect-message-spam is not new -- this has happened for a long time, but this issue above exacerbates the problem due to it's frequent and random disconnections due to that error.

**Comment by EionRobb** [comment]
Is that definitely happening with the skype account and not Facebook?

**Comment by mvandemar** [comment]
I am getting it with Facebook. Just updated a thread about it here:

https://github.com/dequis/purple-facebook/issues/496

**Comment by EionRobb** [comment]
Yup, definitely FB and not Skype :)
