### ISSUE TITLE
missing icon for protocol

### ISSUE THREAD

**Issue by hethhhhh** [EionRobb/skype4pidgin#686]
Hey there! This is a very simple problem, skype protocol doesn't have an icon so it's hard to say if a contact is a skype contact or some other protocol, and it gets confusing with other protocols that doesn't have icons. 
Can you please add it? Thanks!

**Comment by EionRobb** [comment]
hi again, same deal as https://github.com/EionRobb/purple-hangouts/issues/238
There's icons at https://github.com/EionRobb/skype4pidgin/tree/master/skypeweb/icons :)

**Comment by hethhhhh** [comment]
great, thanks!
