### ISSUE TITLE
Edited message not updated in Pidgin

### ISSUE THREAD

**Issue by GoogleCodeExporter** [EionRobb/skype4pidgin#72]
```
What steps will reproduce the problem?
1. Send a message from skype (first account) to another account configured in 
Pidgin
- message received
2. Edit last message in skype (first account)
- message does not updated in Pidgin

What is the expected output? What do you see instead?
Expected: edited message updated
Actual: old version of message displayed

What version of the plugin are you using? On what operating system?
Skype 4, Pidgin 2.6.1, libskype.dll (Last update 24 July 2009), Win Vista
```

Original issue reported on code.google.com by `z3...@ya.ru` on 26 Aug 2009 at 10:34

**Comment by CapsAdmin** [comment]
When you edit a message it will be sent as a new message and when you remove an old message you'll send a new blank message.

I haven't looked that much into this but I'm not finding anything in libpurple that allows you to edit and remove old messages. I guess it's possible for skype4pidgin to handle but it would probably be hacky. It would be best if libpurple had proper support for this. The ability to edit and remove messages is kinda new in instant messaging I guess.

**Comment by EionRobb** [comment]
@CapsAdmin history in libpurple is "immutable" and cannot be changed.  A UI plugin specific to Pidgin might be able to accomplish this, but not the protocol plugin, which has to work across multiple UI's
